### ISSUE TITLE
Substitute not loading all data for weapons(?)

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1020]
UPDATE: Go read my bottom comments, this is a weird bug.

This is pretty complex and weird so I'll explain what I was doing and let you smart coders figure out what needs to be done.

I have a missile, let's call it Rockeye 2. It has a white engine glow, trail and explosion.

Rockeye 2 has 5 substitute entries listed within it. Rockeye 2 Red, Blue, Green, Yellow and Orange. These are all just copies of Rockeye 2 just with the engine glow, trail and explosion swapped around. The goal is to have very colorful missiles and explosions.

When I fire Rockeye 2, **_only_** the original white versions has an engine glow. When the others fire, they just have the trail.

If I equip and fire the actual Rockeye 2 Red, no engine glow appears. If I equip and fire the Rockeye 2 Orange (last on the substitute list), the engine glows begin to appear for everyone (even if I go back to the original substituting Rockeye 2). (?)

If comment out the substitute entries and try again, the engine glow appears for everyone. _(??)_

If I go to debug, the engine glows appear. _**(???)**_

And when I went to go make a test mod for coder debugging without any special assets, the engine glows began to appear. **_(????????)_**

After a lot of hair pulling, I had discovered that the problem was only occurring with ships that had a non-retail species definition. So it worked with "Terran" and "Vasudan" (in my test cases) but not my special "Heroes" species (for my actual mod).

My Heroes species def file had as an entry for ThrustAnims...
```
$ThrustAnims:
   +Normal: thruster01
   +Afterburn: thruster01a
```

And after replacing it with
```
   $ThrustAnims:
	+Pri_Normal: <none>
	+Pri_Afterburn: <none>
	+Sec_Normal: Thruster02-01
	+Sec_Afterburn: Thruster02-01a
	+Ter_Normal: Thruster03-01
	+Ter_Afterburn: Thruster03-01a
```

Then my problem suddenly went away.

So the tl;dr is missing ThrustAnim entries can cause odd weapon engine glow behavior. Because... reasons.

Thank you for listening to my tale.

**Comment by AxemP** [comment]
Scratch that, it's not working all of a sudden again... I just don't understand at all.

**Comment by AxemP** [comment]
Okay, so things start working when I have cheats enabled. Maybe substitute is actually not loading all the data required?

**Comment by AxemP** [comment]
Finally got a test case "working". Previously I was using cheats to bring up the weapons, but that fixes the problem. So here's a mod with the Myrmidon being able to equip the weapon in a test mission.

**Comment by DahBlount** [comment]
This is appears to be an issue with substitution weapons not being properly paged in unless a debug build is run (which automatically ensures Weapon::Info_Flags::Thruster is set for all weapons) or the weapons_page_in_cheats() function is called, which pages in every valid weapon. The fix to this is to either page in a weapons substitutes whenever a weapon is paged in, or mark a substitution weapons as used in a weapon that has substitutes is marked used.

**Comment by DahBlount** [comment]
Should be fixed in #1023

**Comment by asarium** [comment]
@AxemP Could you confirm that your issues has been fixed by the changed made by @DahBlount? The changes are present in the latest nightly.

**Comment by AxemP** [comment]
Ya, this is all fixed and good now. :)

**Comment by asarium** [comment]
Ok, thanks for testing it.
