### ISSUE TITLE
Some cutscenes are played incompletely since merging new cutscene player

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1028]
For example:
ST:R Introduction ends before it starts.
ST:R End Game is cut when Hades crashes into planet.
FSPort End Game is cut before monologue.
It looks like these cutscenes end when black frames (?) should be visible before next part of video.

**Comment by asarium** [comment]
Weird, I tested the cutscene player extensively with the 1080p endding cutscene of ST:R and I never had these issues.

**Comment by asarium** [comment]
I can reproduce this issue.

**Comment by asarium** [comment]
I fixed a few issues with playback timing that I found with the ST:R intro cutscene but for some reason FFmpeg continues throwing errors when I try to read the file. It's probably corrupted in some way but it still works if I ignore the error...
