### ISSUE TITLE
Allow to use movie files for other purposes

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1041]
Movie files are an ideal choice for CBanims since those are usually pretty long and could be compressed pretty well by the video codecs. They also typically don't use an alpha channel which is good since typical video codecs also don't support an alpha channel. The obvious choice for adding this functionality is the `generic_anim` system but that relies on bmpman which may cause issues since video files use the YUV encoding which is supported by the video player by directly using OpenGL textures.

A special bitmap type could be introduced that is capable of holding this YUV data. Combined with a special rendering material that encapsulates video rendering it could be used to properly integrate video files into the generic anim system without requiring major changes to the code base (at least I hope...).

**Comment by Goober5000** [comment]
I believe this is now complete.
