### ISSUE TITLE
Ballistic weapon gauge offset behavior is hardcoded, should be controlled by hud_gauges

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#1061]
Currently elements of the weapons gauges (the backgrounds and the header text) are automatically shifted by the engine to the left when ballistic primary weapons are in your ship's loadout. There are no options in hud_gauges.tbl to control this behavior, which means that if non-default assets (such as the 2_ graphics as used in Axem's hi-res HUD) are used for the weapons gauge, it will display incorrectly with ballistic primaries. Please add fields in hud_gauges.tbl to control the way the gauge is altered when ballistic primaries are loaded.

Examples:

Twist of Fate HUD with no ballistic primaries (correct): http://i.imgur.com/nPMFjjv.jpg
Twist of Fate HUD with ballistic primaries (incorrect): http://i.imgur.com/zy8vbE7.jpg

**Comment by MageKing17** [comment]
They're not hardcoded; follow "Header Offsets:" with "Alt Ballistic Offsets:".

**Comment by DahBlount** [comment]
Should this be closed since the functionality exists already?

**Comment by niffiwan** [comment]
I'd say no, need to add the relevant doco to the [wiki](http://www.hard-light.net/wiki/index.php/Hud_gauges.tbl)

**Comment by z64555** [comment]
The wiki has been updated to document the mentioned entries.
