### ISSUE TITLE
unable to configure with cmake 3.6.2

### ISSUE THREAD

**Issue by yoshi314** [scp-fs2open/fs2open.github.com#1064]
pwd

`/home/yoshi/src/games/fs2open/build`

`cmake -DFSO_FREESPACE_PATH=. ..`

```
CMake Error at CMakeLists.txt:7 (message):
  Binary and source directory can not be the same! Choose another build
  directory.

```

This happens regardless of choice of build directory.

**Comment by MageKing17** [comment]
Did you delete the CMake cache after the first failure? If not, it will just repeat that error regardless of what directory is used afterwards.

**Comment by asarium** [comment]
The reason for that behavior is that if CMake sees a CMakeCache.txt file in the specified path then it assumes that that should be the binary directory. Simply removing the old file and re-running `cmake` should work.

**Comment by yoshi314** [comment]
Hm, that might be the case. I'll be able to verify that in a few hours. I'll reopen in case of problems.
