### ISSUE TITLE
Backward Compatibility and Deprecation of VM_EXTERNAL_CAMERA_LOCKED in scripts

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#1066]
PR #1065 Addresses issue #965, however it does not deprecate VM_EXTERNAL_CAMERA_LOCKED that may be present in older scripts.

The new flag, VM_CAMERA_LOCKED, takes the same bit place of VM_EXTERNAL_CAMERA_LOCKED, but is not quite the same behavior.

The old behavior of VM_EXTERNAL_CAMERA_LOCKED is the same as the new behavior of VM_CAMERA_LOCKED when VM_EXTERNAL is also true.

**Comment by MageKing17** [comment]
Is it not possible to have both `VM_EXTERNAL_CAMERA_LOCKED` and `VM_CAMERA_LOCKED`, with the former becoming basically an alias for `VM_CAMERA_LOCKED && VM_EXTERNAL`?

**Comment by z64555** [comment]
That's what I was thinking for getting things backwards compatible, but the `VM_EXTERNAL_CAMERA_LOCKED` flag should still be marked as deprecated when running a debug build. It's not as flexible as having the camera lock state separate from the external view state.
