### ISSUE TITLE
Subtitle images without transparency get drawn incorrectly

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1074]
Quite a few mods (like Blue Planet) had subtitle images that were just white on black that rendered additively in 3.7.4 and before. Now on the recent nightlies, that black is rendered regardless. See images below and test mod.

This is the current behavior
![screen0827](https://cloud.githubusercontent.com/assets/6625164/20464425/03a6546c-af0d-11e6-9718-ee6e242aee67.jpg)

This is how it was in 3.7.4
![screen0689](https://cloud.githubusercontent.com/assets/6625164/20464430/0aac9fdc-af0d-11e6-8807-3b03bb3596ab.jpg)

Here's a test mod
[subimagetest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/602161/subimagetest.zip)

**Comment by AxemP** [comment]
This appears to be fixed now. :)

**Comment by AxemP** [comment]
Oops, my bad... One thing that seems to be broken with that new commit is apngs now get additive blending even if they have alpha channels.

**Comment by SamuelCho** [comment]
I'm gonna need a test case of this. Especially if this is done through a script cuz there might be a parameter that's not being set in scripting.

**Comment by AxemP** [comment]
[APNGTest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/672037/APNGTest.zip)

Here ye go. Playing around with the gr.CurrentOpacityType didn't appear to affect anything. I am having to set it to ALPHABLEND_NONE to make sure nothing renders additively for my visual novel script. You can uncomment the appropriate line,

**Comment by AxemP** [comment]
Okay, I tried that new change and it appears to work as intended... for animations anyway.

But one last related thing since this seems like its all related together. So I mentioned how I found I needed to start using ALPHABLEND_NONE because otherwise all my drawImage scripting stuff gets rendered additively, I didn't need to do that before PR #1104 and I thought that was just "the way it goes now". But now I find when I do that I can't affect the alpha of images done with gr.drawImage so... maybe not? :\ (I guess judging by the name, nothing has alpha?)

So here's an updated script file that tries to draw a normal image with a gradual alpha fade in with an apng animation doing the same thing. Just throw it in the mod folder from before, its just the script file.
[apng-sct.zip](https://github.com/scp-fs2open/fs2open.github.com/files/673188/apng-sct.zip)

(Sorry for being late with these findings, its just I'm only looking to see if one thing is fixed and then find those unintended side-effects later!)

**Comment by SamuelCho** [comment]
So, if an image doesn't have an alpha channel, it'll get blended additively if blending is requested. If no blending is requested, the game will use alpha blending regardless of if an alpha channel is present or not. But a behavior that I didn't carry over from the old opengl_setup_render_states function was to force the use of the user defined alpha value. I've updated my pull request with that missing behavior.

**Comment by SamuelCho** [comment]
https://github.com/scp-fs2open/fs2open.github.com/pull/1112

**Comment by AxemP** [comment]
It would appear that all my qualms are now resolved with that latest PR.

Thank you so much. :)

**Comment by SamuelCho** [comment]
Hooray!
