### ISSUE TITLE
LUA Enum's have no description in scripting.html

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#1077]
There's a provision for enum descriptions already, but it's commented out and none of the descriptions have been written.

To enable them:
- `flag_def_list` would require a member that is `char* desc;`
- **lua.cpp:15491** should be uncommented
- The descriptions for all of the enums in **scripting/api/enums.cpp** should be drafted, or an empty string "" used as a placeholder.

**Comment by Goober5000** [comment]
I'm going to say that we don't need enum descriptions.  The enum names themselves are self-explanatory.
