### ISSUE TITLE
Coverity 1298266 Missing break in switch

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#109]
In [code/graphics/gropengldraw.cpp:3183](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/graphics/gropengldraw.cpp#L3183), the switch ```case LT_CONE``` falls through to ```case LT_POINT```.  Is this intentional i.e. is a point light a subset of a cone light? My guess is yes, but I'd like a graphics coder to confirm that before I dismiss the warning.

**Comment by SamuelCho** [comment]
Yup, the missing break is intentional.

**Comment by niffiwan** [comment]
thanks!
