### ISSUE TITLE
$On Weapon Fired scripting hook not firing correctly for secondaries on last shot

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1091]
See attached mod for a simple script that displays the issue.

Basically the script will display on a list the last weapon fired (a Harpoon or a Rockeye). The mission gives the player 4 of each missile. If you fire all the missiles, the last shot for a bank won't fire correctly, it will try and fire the next bank's trigger instead. So you'll see something like...

1 Harpoon
2 Harpoon
3 Harpoon
4 Rockeye  (A Harpoon is actually fired)
5 Rockeye

[OnFiredBug.zip](https://github.com/scp-fs2open/fs2open.github.com/files/656138/OnFiredBug.zip)

**Comment by MageKing17** [comment]
Looks like the call into the scripting engine happens *after* the automatic bank-swap due to running out of ammo; simply swapping the two blocks of code should be sufficient to fix this issue.
