### ISSUE TITLE
Trying to play a message wav file in FRED crashes FRED

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1092]
Open FRED, make a new message, select any wav file at all and hit the play button. FRED will freeze and crash. It looks like this started happening with the ffmpeg commits. (Should also add this occurs for any ogg file as well)

Sept 30 nightly: no crash
Oct 3 nightly: crash

Debug log doesn't show any really useful info.

Here what it had about my audio setup
`Initializing OpenAL...
os_config_read_string(): section = "Sound", name = "PlaybackDevice", default value: "NULL"
os_config_read_string(): section = "Sound", name = "CaptureDevice", default value: "NULL"
  OpenAL Vendor     : OpenAL Community
  OpenAL Renderer   : OpenAL Soft
  OpenAL Version    : 1.1 ALSOFT 1.17.2

  Found extension "AL_EXT_float32".
  Found extension "ALC_EXT_EFX".
Enhanced sound is enabled.

  Sample rate: 48000 (44100)
  EFX enabled: NO
  Playback device: OpenAL Soft on Speakers (Realtek High Definition Audio)
  Capture device: Microphone (2- USB Audio CODEC 
... OpenAL successfully initialized!`

I'm running OpenALSoft, main game works fine without any issues.

**Comment by MageKing17** [comment]
Fairly easy to reproduce; looks like [this line](https://github.com/scp-fs2open/fs2open.github.com/blob/04dcb4cf606b6c9c5ea3adfbab37a2f6a3603216/code/libs/ffmpeg/FFmpegContext.cpp#L113) is throwing an exception, saying "Operation not permitted". No idea why this is only a problem in FRED.

**Comment by asarium** [comment]
I can reproduce this issue and I'll try to fix it soon.

**Comment by asarium** [comment]
I found the issue, fix submitted as #1094.
