### ISSUE TITLE
No Collisions and No Disabled Self Destruct Flags not saving when FRED saves

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1115]
Click those flags on in the ship editor, save in FRED and they won't be ticked when the mission reloads.

I tried ticking every flag and those were the only two that did that.

**Comment by asarium** [comment]
@AxemP Could you please confirm that the issue is not present in master anymore?

**Comment by AxemP** [comment]
Yeah its fixed now.
