### ISSUE TITLE
FringeSpace's Scripted Mainhall Breaks with Debug Window Changes

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#1157]
@asarium 's debug window broke FringeSpace's mainhall somehow. When loading the mainhall after committing the pilot selection, the screen goes black and cannot progress through. The cursor is still active, however, and FSO responds during debug sessions in MSVS.

c7f523ae461541d0a494bd7386d9ab9cc52034fa

**Comment by The-E** [comment]
I think this is a case where we really need a test case in order to properly fix this.

**Comment by asarium** [comment]
The original commit had a bug where the scripting code wasn't executed at all but that has since been fixed.

**Comment by z64555** [comment]
I could've sworn I had checked this already, but I might've been half asleep or something. Commit f376142d57a8516d35f59e7fc5af5930127e2003 has fixed the issue already.
