### ISSUE TITLE
Ship lab initial ship position regression

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1205]
As seen at the beginning of https://youtu.be/QbhOd6WM31g when you load the first model, you are staring at the tail-end of the ship.

I had thought this was a more recent regression, but when I went to confirm, I can see the behavior all the way back to 3.6.16.  In 3.6.14, when you first select a ship, Model Rotation was not disabled.  It seems that disabling that became a default behavior in 3.6.16.  Maybe this isn't the bug I initially suspected it was, but without that setting enabled by default, you are always staring at the tail of the ship, instead of a more appealing angle, such as first seen when you do enable model rotation.  Not sure why it seems model rotation was disabled by default, but it's annoyed me since then to be staring at thrusters when I open a ship up.  Wondering if there would be a quick way to set the initial camera angle, or if we should restore it defaulting to a rotating model.

**Comment by X3N0-Life-Form** [comment]
IIRC, shiplab model rotation was disabled by default because it was disliked by a number of modders, so restoring the old default would likely annoy a number of people.

**Comment by Goober5000** [comment]
There ought to be a way to set the initial angle of the ship without causing it to continuously rotate.

**Comment by TRBlount** [comment]
There is. Would we perhaps want a view similar to the default view you find standard across most 3D modeling apps?
Example: ![](http://puu.sh/tXgap/70648836aa.png)

**Comment by chief1983** [comment]
That is about exactly what it looks like when you first enabled model rotation, before it has started to spin.  That'd be perfect.

**Comment by TRBlount** [comment]
Alright, if that's the case the matrix for it should be somewhere in the code. I'll set about finding it and seeing the best way to apply it.

**Comment by TRBlount** [comment]
Is this a good default orientation?
![](http://puu.sh/tXuWX/90f578a6ff.png)

**Comment by chief1983** [comment]
That's great :)

**Comment by Goober5000** [comment]
Resolved by #1212.
