### ISSUE TITLE
Spam in fs2_open.log - A ship rotated too far. Offending vessel is ..., please investigate.

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1217]
Since #1208 fs2_open.log is spammed by messages: A ship rotated too far. Offending vessel is ..., please investigate. Message mentions every ship in mission except player's ship. I know message is useful but in Surrender, Belisarius! only after 30s I get 10k+ lines in log.
I created mission with only 2 ships, they do nothing and after 15s there is 2k+ lines of "A ship rotated too far. Offending vessel is Alpha 2, please investigate."

**Comment by chief1983** [comment]
Did we reverse the condition somehow?  This used to be a very rare assertion to hit, it should not suddenly be blowing up the logs.

**Comment by The-E** [comment]
Ooops, my bad. Fix incoming.

**Comment by tomimaki** [comment]
Thanks.
