### ISSUE TITLE
Make -get_flags disable warning abouts unrecognized command-line parameters.

### ISSUE THREAD

**Issue by MageKing17** [scp-fs2open/fs2open.github.com#1221]
```// DO THIS FIRST to avoid unrecognized flag warnings when just getting flag file```

The code doesn't actually do anything to stop warnings, because `os_validate_parms()` is called (more than once, if `-parse_cmdline_only` isn't present) well before `SetCmdlineParams()` (which contains the above comment) is.

**Comment by asarium** [comment]
The launcher should use `-parse_cmdline_only` to avoid the usage of other command line parameters but this could also be fixed in the FSO code by adding `-get_flags` to the checks in `has_cmdline_only_flag()`.
