### ISSUE TITLE
Issues with copying and renaming Mac .app bundles

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1228]
While working on #967, I thought I might have been able to solve a couple other issues that have annoyed me on the Mac, but since it was solved without those being fixed at the same time, I am opening another ticket.

First, when I make a build, and copy it from the bin folder into the Freespace2 folder, the icon changes from the FS2 icon into a generic App icon.  I can still run the build via wxLauncher or Finder (with #1227 applied).

Second, if I then rename it, so I can place another recently compiled build alongside it for instance, it becomes an unrecognized app and Finder refuses to run it.  wxLauncher can still run it though.

If one of these is solved without fixing the other the issue can be split again.

**Comment by chief1983** [comment]
I was looking at the binaries again with otool, seeing what significant differences might still exist that might give a hint.  I noticed some interesting differences near the end of the load commands still.  The left file was the otool -l output from a 3.7.4 based build, the right file was the output from a recent master build.  I believe that after enabling the APPLE_APP command we should be including CoreFoundation/CoreFoundation.h, but the Load Command for it is not present in the resulting binary yet.  Same with ApplicationServices, AppKit, and Foundation.framework.  I have a feeling some of these might be relevant to the issues in this ticket.

Also, the Frameworks load command has a trailing slash now, when it didn't before.  Not sure if that will affect anything or not.
```
 Load command 19
           cmd LC_LOAD_DYLIB
-      cmdsize 96
-         name /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (offset 24)
+      cmdsize 80
+         name @executable_path/../Frameworks/libswresample.2.dylib (offset 24)
    time stamp 2 Wed Dec 31 18:00:02 1969
-      current version 1349.0.0
-compatibility version 300.0.0
+      current version 2.1.100
+compatibility version 2.0.0
 Load command 20
           cmd LC_LOAD_DYLIB
-      cmdsize 56
-         name /usr/lib/libobjc.A.dylib (offset 24)
-   time stamp 2 Wed Dec 31 18:00:02 1969
-      current version 228.0.0
-compatibility version 1.0.0
-Load command 21
-          cmd LC_LOAD_DYLIB
       cmdsize 48
          name /usr/lib/libc++.1.dylib (offset 24)
    time stamp 2 Wed Dec 31 18:00:02 1969
       current version 307.4.0
 compatibility version 1.0.0
-Load command 22
+Load command 21
           cmd LC_LOAD_DYLIB
       cmdsize 56
          name /usr/lib/libSystem.B.dylib (offset 24)
    time stamp 2 Wed Dec 31 18:00:02 1969
       current version 1238.0.0
 compatibility version 1.0.0
-Load command 23
-          cmd LC_LOAD_DYLIB
-      cmdsize 88
-         name /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (offset 24)
-   time stamp 2 Wed Dec 31 18:00:02 1969
-      current version 1504.59.0
-compatibility version 45.0.0
-Load command 24
-          cmd LC_LOAD_DYLIB
-      cmdsize 112
-         name /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (offset 24)
-   time stamp 2 Wed Dec 31 18:00:02 1969
-      current version 48.0.0
-compatibility version 1.0.0
-Load command 25
-          cmd LC_LOAD_DYLIB
-      cmdsize 104
-         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
-   time stamp 2 Wed Dec 31 18:00:02 1969
-      current version 1348.15.0
-compatibility version 150.0.0
-Load command 26
+Load command 22
           cmd LC_RPATH
       cmdsize 40
-         path @loader_path/../Frameworks (offset 12)
-Load command 27
+         path @loader_path/../Frameworks/ (offset 12)
```

**Comment by chief1983** [comment]
http://docs.onemobilesdk.aol.com/ios-ad-sdk/adding-frameworks-xcode.html

Tried adding the frameworks to the Link phase as described, but it doesn't help with either issue here.

**Comment by jg18** [comment]
So the frameworks don't actually get added? As in the otool output doesn't change? Or the frameworks get added but the issues persist?

**Comment by chief1983** [comment]
Sorry, yeah, the latter.  They show up in the load commands now, but neither issue in the description is resolved.  So the cause seems unrelated to these frameworks being linked.  Not sure why we need to link to these frameworks then.  We even have an include for corefoundation.h that hasn't worked since the cmake merge and Mac builds seems mostly unaffected by that.

**Comment by asarium** [comment]
I'm pretty sure that we don't need the two includes of `corefoundation.h` and if that's true then we probably also don't need to link the framework that contains that header.

**Comment by ngld** [comment]
I just tested this with a recent nightly. The Info.plist file doesn't have an entry for [CFBundleExecutable](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-101909) which means that Finder is using the folder name to determine the executable's name.

From Apple's documentation:

> Important: You must include a valid CFBundleExecutable key in your bundle’s information property list file. macOS uses this key to locate the bundle’s executable or shared library in cases where the user renames the app or bundle directory.

I'm not sure about the icon problem. It works with the nightly I tested. You could check if the ```FS2_Open.icns``` file is in ```.app/Contents/Resources```.

**Comment by chief1983** [comment]
Ok, so I guess we need to find out how to define that correctly in the Info.plist, as it was in pre-CMake.

**Comment by ngld** [comment]
Looks like CMake is using ```freespace2/resources/mac/Info.plist``` which sets CFBundleExecutable to ```${PRODUCT_NAME}```. The relevant CMake file is ```freespace2/resources.cmake```.

Apparently none of the placeholders are resolved correctly since they are all replaced with empty strings in the final ```Info.plist```.
I think these keys need to be moved to the ```InfoPlist.strings.in``` file since that file seems to be preprocessed by CMake.

**Comment by chief1983** [comment]
Ah yeah, I didn't even think that first file was used now, can maybe be deleted.

**Comment by chief1983** [comment]
InfoPlist.strings.in is for a separate file in the bundle.  The Info.plist I think is merged with some other data by Xcode and placed in the final bundle.  But we aren't defining any of the variables used in our template Info.plist anywhere in the CMake code.  I think we can try to switch those to things that are actually defined to get the results we want, testing that now.

**Comment by chief1983** [comment]
Annnnnd I broke my build environment completely somehow.

**Comment by chief1983** [comment]
Well, now I have an Info.plist generated like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>16D32</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>FS2_Open 3.7.5</string>
	<key>CFBundleIconFile</key>
	<string>FS2_Open</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>FS2_Open</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>3.7.5</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>8C1002</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>16C58</string>
	<key>DTSDKName</key>
	<string>macosx10.12</string>
	<key>DTXcode</key>
	<string>0821</string>
	<key>DTXcodeBuild</key>
	<string>8C1002</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.games</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.9</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>SDL_FILESYSTEM_BASE_DIR_TYPE</key>
	<string>parent</string>
</dict>
</plist>
```
But now even _before_ I move it, or rename it, Finder complains that it is a broken app bundle.  So how did defining CFBundleExecutable, CFBundleVersion, and LSMinimumSystemVersion cause it to break even more?

**Comment by chief1983** [comment]
So I just realized that the CFBundle* entries are all _Core Foundation_ related, so maybe that is why we need CoreFoundation.framework linked into the bundle after all...

**Comment by ngld** [comment]
```CFBunldeExecutable``` is set to ```FS2_Open``` which means Finder is now looking for ```.app/Contents/MacOS/FS2_Open```. Does it exist?

**Comment by chief1983** [comment]
No, so that's probably my issue.  I need to find the variable that holds the name of the actual executable. I guess that makes sense.  Probably why wxLauncher works, it find the binary itself I'm guessing.

**Comment by asarium** [comment]
CMake has some special handling in place for the Info.plist which sets some default values. I'll look though the CMake code to determine which variables are available.

**Comment by chief1983** [comment]
I think I'm getting close, but if you find something else we can compare notes.

**Comment by chief1983** [comment]
Ok it looks like I want the OUTPUT_NAME property of the various targets, but not sure how to access that one inside the Info.plist template.  I got the bundle version and min system version defining correctly I think now.

**Comment by asarium** [comment]
That won't work because the value of that property depends on the configuration so you would need to use CMake generator expressions to get the correct value but that is a bit hard to do if you have no CMake experience. You could hard-code the value for now to test if that fixes the issue and if that's the case I can build a solution that will work for all configurations.

**Comment by chief1983** [comment]
Yeah, from what I can tell, we don't actually define the strings "fs2_open_", "fred2_open_", etc anywhere else usable in the codebase.  Could probably just SET() those to a global and use that in the target properties, and also allow it to be used in the Info.plist maybe?

**Comment by asarium** [comment]
It's defined in `freespace2/CMakeLists.txt:26` and `${FSO_BINARY_SUFFIX}` uses the value `$<$<CONFIG:Release>:>$<$<CONFIG:Debug>:-DEBUG>$<$<CONFIG:FastDebug>:-FASTDBG>` for specifying the configuration suffix using generator expressions.

**Comment by chief1983** [comment]
Sorry, that's what I mean, we set it as part of the OUTPUT_NAME, but if OUTPUT_NAME isn't usable that doesn't help anywhere else that needs it.  Sounds like you're saying it might still be usable with a more complicated syntax though, so maybe I can just look into that.  Don't mind trying to learn a little more CMake anyway.

**Comment by asarium** [comment]
I'm currently looking at the CMake code to determine which variables are available by default but I'll describe the other solution I had in mind.

CMake has a thing called "[generator expressions](https://cmake.org/cmake/help/v3.4/manual/cmake-generator-expressions.7.html)" which allows to reference values that are only available when the Makefiles/project files are actually being generated and not when the CMake code is initially executed. These expressions allow to access values such as the actual executable name for the current configuration which is not possible otherwise. Actually using these values requires two steps:

1. Use `configure_file` to replace any "normal" variables from an initial template.
2. Use `file(GENERATE ...)` to replace the generator expressions and produce the final file

I used the same technique when integrating AppImage (take a look at `cmake/appimage.cmake` for an example). I'm not sure if this solution would have worked since the plist file is a bit special but it would have been a start.

**Comment by chief1983** [comment]
After changing the icon one back to just a hardcoded FS2_Open, everything seems to work as expected.
