### ISSUE TITLE
Sun glare coming through objects

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1246]
I flew into the Lucifer's fighter chute for old time's sake on the Lucifer Dogfight - Ultra Heavy multiplayer mission while seeing if I could make anything glitch or crash.  I suddenly saw the sun glare (I think) coming through what should have been the solid interior of the fighter bay.  It was only visible at certain angles and only when I got close enough.  It was not coming through anywhere else I could see on the ship.  See the screenshots for clarification.  I don't know if this is a glitch on the model or the new rendering code.  It could be related to seeing thrusters through models.  This occurred on a build I made from latest master just a few hours earlier.

![screen0002](https://cloud.githubusercontent.com/assets/145825/23099978/b9f0cf9a-f639-11e6-901d-bc7e2e2c4097.png)
![screen0003](https://cloud.githubusercontent.com/assets/145825/23099976/b9f0301c-f639-11e6-8f27-6209054015c5.png)
![screen0001](https://cloud.githubusercontent.com/assets/145825/23099977/b9f077f2-f639-11e6-940d-d333fb6ba42f.png)

**Comment by chief1983** [comment]
This can be reproduced in 3.7.4, so my guess is it's some kind of pseudo-hole in the model.  Might not be anything to do here.

**Comment by MageKing17** [comment]
Might also be a relative of #1238.

**Comment by chief1983** [comment]
Probably only if that one also exists in 3.7.4.

**Comment by MageKing17** [comment]
It does.

**Comment by chief1983** [comment]
Ah, could be related then.  Thought that was introduced by more recent graphics updates.  Might be able to merge this report then.

**Comment by asarium** [comment]
Does this also happen with 3.7.2? IIRC, that was before the deferred lighting which changed a few things about how depth testing was handled.

**Comment by chief1983** [comment]
Yes,  just checked, the glare comes through that spot in 3.7.2 as well.  Seemed to have an even easier time of it, but maybe I just parked in the sweet spot.

**Comment by chief1983** [comment]
Unless I see another instance of this, I feel like chalking it up as a bug in the Lucifer that just happens to manifest in this one scenario (Sun located behind its fighterbay).  Unless there's a reason to leave it open.
