### ISSUE TITLE
Table texture replacement broken in the lab

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#1264]
Tabled texture replacement is currently not being reflected in the ship lab or the techroom.
The attached mod shows this; it replaces the Ulysses' base texture with the terran cockpit one.

[texreplacetest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/801429/texreplacetest.zip)

**Comment by MageKing17** [comment]
This isn't a regression, is it? I thought texture replacement has always required a ship object; am I wrong and there's some version of FSO where table-based texture replacement worked in the lab?

**Comment by The-E** [comment]
I thought it was a regression based on the discussion in IRC, but it really isn't.
