### ISSUE TITLE
coloured ambient light is missing

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#1279]
Or if not missing, it's too weak to see. I've got some images below.

My test mission had these settings:

https://gist.github.com/niffiwan/eb9f9b4c7be0e087c281c9980eee0331
$Ambient light level: 3342593
$Sun: SunWhite

I used SunWhite to make the issue obvious, using SunBlue as well tends to overwhelm the ambient effect.

3.7.4 ambient factor 128
![image](https://cloud.githubusercontent.com/assets/3313634/23578498/1e06cd8c-0124-11e7-93ce-7d4ed74e68dc.png)

3.7.4 ambient factor 200
![image](http://i.imgur.com/RhvQBs2.png)

10bbead ambient factor 128
![Imgur](http://i.imgur.com/87bdDhi.png)

10bbead ambient factor 200
![Imgur](http://i.imgur.com/dQgOLvX.png)

10bbead ambient factor 250
![Imgur](http://i.imgur.com/AcTWx72.png)

And some screens of what prompted me to investigate; I noticed in FotG that my ambient blue light was missing after I started using a recent build. The commit that changed the lighting was ee675a19b5b73b1ebfb271885903a41e608e24e0 /  #1135.

Mission light settings were:

$Ambient light level: 3342593
$Sun: SunBlue

around ac3faac0c51f2fd46da16cb61f1d1e85abb23070 ambient factor 125
![Imgur](http://i.imgur.com/XUdjPYF.png)

10bbead ambient factor 125
![Imgur](http://i.imgur.com/BpOGHQb.png)

Note that neither model has PBR compatible textures yet.

**Comment by niffiwan** [comment]
Just for fun; with 10bbead I tried setting ambient_factor to max (255), still no sign of blue.

![image](https://cloud.githubusercontent.com/assets/3313634/23578760/d07f98cc-0129-11e7-889d-29f85da3e69b.png)

**Comment by asarium** [comment]
I found the cause of this issue. The new ambient equation applies an absolute offset to the mission-specified values so if the user specifies anything other than 128, the mission specified value start to get overwritten by the user value. Example: If I specify an ambient factor of 50 the new equation returns something like -0.6 which then gets added to the ambient values. Since all those values are now below zero they get `CLAMP`d to 0.02 which means that the original blue ambient value is not preset anymore. Something similar happens to values above 128.

@SamuelCho If I use the code of `opengl_calculate_ambient_factor` from before ee675a19b5b73b1ebfb271885903a41e608e24e0 the ambient lighting looks more like how it looked before. What was the reason for the new equation?

**Comment by niffiwan** [comment]
ok, so if I make a massive increase to the blue slider in FRED for the missions ambient light I might be able to get the blue to return. I'll have to try that, but tomorrow, now I need sleep.

**Comment by SamuelCho** [comment]
Please try taking a screenshot without post processing turned on so I have a better idea of what's happening.

**Comment by SamuelCho** [comment]
You should also post screenshots of what that Star Wars mission looks like in 3.7.4. I don't want to change the ambient light behavior again and end up ping ponging us back to what got us into https://github.com/scp-fs2open/fs2open.github.com/issues/1135 in the first place.

**Comment by niffiwan** [comment]
yeah, I don't want to mess you around with ping-pong changes either! 

Here's 3.7.4 with ambient 125
![image](https://cloud.githubusercontent.com/assets/3313634/23584718/a9123d08-01b5-11e7-8272-0fcfc2fb06db.png)

And 10bbead with ambient 125 & no post processing
![image](https://cloud.githubusercontent.com/assets/3313634/23584719/b2de2888-01b5-11e7-8c1a-004bf8324366.png)

Based on that I think I've got my mission lighting settings messed up. However, the retail test case seems to indicate that we've got a change? I guess the question is "does it matter?" And from looking at the [preset lighting settings](http://www.hard-light.net/wiki/index.php/Sample_Lighting_Settings), none of them exceed 105, FotG is unreleased with 125 (needs updating for PbR/HDR anyway) and the default is 128. So we probably don't need to worry about ```-ambient_factor 200``` looking different to how it used to look.

I think I'm arguing myself into closing the issue \:D

**Comment by niffiwan** [comment]
I think I've got this back to looking almost the same as it was before;

Mission lighting:
R 51
G 51
B 137
Ambient Factor 120

![image](https://cloud.githubusercontent.com/assets/3313634/23586837/bd68561e-01e9-11e7-9992-ba994f6ad4c9.png)

I could probably play with the mission lighting a bit more so that I get the same result with ambient factor of 125. Or in short, happy to close this.
