### ISSUE TITLE
How to handle translated strings in SEXPs?

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1285]
[Mantis 3192](http://scp.indiegames.us/mantis/view.php?id=3192) reports an issue with how `grant-medal` doesn't work with translated medal names. As far as I can tell, this is caused by the inability of the SEXP system to translate the English medal name in the SEXP to the correct, translated version of the string.

How could this be fixed? I don't know enough about the SEXP system to fix this so maybe someone else has an idea.

**Comment by Goober5000** [comment]
This sounds like the same problem I encountered in [Mantis 2919](http://scp.indiegames.us/mantis/view.php?id=2919).  The `tech-add-intel` sexp didn't work with translated intel entry names, so the solution was to add `tech-add-intel-xstr`.

The same will have to be done for `grant-medal`, and indeed any sexp where the lookup key is a translated token.

**Comment by Goober5000** [comment]
This was fixed in #1736.
