### ISSUE TITLE
material::set_color discards alpha value when using a color struct parameter

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1289]
Here is the offending code: https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/graphics/material.cpp#L352

@SamuelCho I'm pretty sure that this is just an accidentally inverted condition but just to make sure that I don't break anything I wanted to clear that up first.

**Comment by MageKing17** [comment]
...Why do non-alpha colors use green as the alpha value instead of `1.0f`?

**Comment by asarium** [comment]
I didn't even notice that. I guess that reinforces the "bug" theory.
