### ISSUE TITLE
Improved Shield Shaders no longer working

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#1294]
Spoon reported this earlier today.
https://my.mixtape.moe/ifzqpj.webm
Looks like the new shield shaders aren't working for some reason, I checked the diff between current master and my up to date with master copy of of the WoD branch and found no changes to the shield shader related code.
Any suggestions?

**Comment by SamuelCho** [comment]
It kind of looks like shield detail level isn't set at 5?

**Comment by TRBlount** [comment]
Spoon says all those settings are maxed.

**Comment by SamuelCho** [comment]
I'll definitely need to get a log to see what's going on there.

**Comment by TRBlount** [comment]
Here's the log Spoon gave me: http://pastebin.com/K218Ligu
I honestly can't tell what's going on here. The builds spew that a shader failed to compile, but I can't find evidence of such in the debug log.

**Comment by TRBlount** [comment]
The behavior of this is unusual. The shield decals work just fine in JAD, but not in nuWoD. It also appears to work fine for me in other mods like BP or the MVPs, but those don't have capships with shields.

**Comment by SamuelCho** [comment]
There shouldn't really be anything affecting the new shield rendering code unless something is wrong with the shader or the pilot file has shield detail set to 4 or below but the options screen says otherwise. I guess you could always make a new pilot file, make sure shield detail settings are at 5, and test to see if shield decals work.

**Comment by TRBlount** [comment]
Yeah. Iirc, recent builds store everything in %APPDATA% on Windows so I'll do some exploring of the pilot files and see if something isnt getting properly set or something.

**Comment by asarium** [comment]
If you want to look at the actual pilot file, the JSON export option may help you. It should be much easier to analyze than a binary file.

**Comment by TRBlount** [comment]
Alright, thanks.

**Comment by TRBlount** [comment]
Well, you were right Swifty. It looks like the options menu isn't updating the shield hit effects variable. My WoD players all show it as 4, not 5.

**Comment by TRBlount** [comment]
So, based on what I'm looking at with the JSON dumps and the options screen, the pilot code is reading and writing the detail options as one less than they should be ie. 5 pips is being saved as 4, 4 pips as 3, 3 pips as 2, etc.

**Comment by SamuelCho** [comment]
Hmm, you might be right that it should be Detail.shield_effects < 4. I wonder how I got away with <= 4 for so long.

**Comment by TRBlount** [comment]
The code that sets the shield_effect var to 4 hasn't changed since the days of Volition, so I'd be inclined to say the logic should be modified to that.

**Comment by TRBlount** [comment]
Closed via #1304
