### ISSUE TITLE
Subsystem indicator not drawn correctly on cockpit displays

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1303]
This can be seen in the screenshot on the forums: http://www.hard-light.net/forums/index.php?topic=84459.msg1844339#msg1844339

It can be reproduced with the cockpit mod from the forums. Start a mission and target the subsystem of another ship. The targeting indicator will be drawn in the wrong location, some times they are visible at the bottom of the cockpit display.

**Comment by krevett62** [comment]
I'm not posting another issue for this but I noticed another bug with cockpits. The ballistic ammo shown in the HUD on top of the energy bar has dissapeared with the recent nightlies. You can see it in the last post of http://www.hard-light.net/forums/index.php?topic=93286

**Comment by niffiwan** [comment]
Can you please open a separate issue for the ballistic ammo bug; makes it easier to track/follow/fix. Thanks!

**Comment by wookieejedi** [comment]
Ah was going to make a new issue but one was already made for this target indicator bug. Also wanted to add that the target ship becomes very warped looking.

**Comment by Goober5000** [comment]
@wookieejedi can you post a link to it?

**Comment by wookieejedi** [comment]
Sure. Here's a comparison: 
![What it actually looks like](https://user-images.githubusercontent.com/14077810/70189351-15e43d00-16c1-11ea-8b09-8aba956731e1.png)
![What it should look like](https://user-images.githubusercontent.com/14077810/70189353-15e43d00-16c1-11ea-9434-931fb67c06eb.png)

**Comment by wookieejedi** [comment]
Think I found a fix, will submit a PR soon.

**Comment by wookieejedi** [comment]
This issue is now fixed by #2182.
