### ISSUE TITLE
Framebuffer Thrusters not Rendering Correctly

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#1307]
Not sure how I missed this, but FB Thrusters no longer look like proper heat distortions.
Instead they look like they slightly bend the thruster and the appearance is only noticeable at a distance.
Near:
![](https://puu.sh/uEWCD/de52a858c5.png)
Far:
![](http://puu.sh/uEWDo/14911022df.png)

Pic from JAD:
![](https://ibin.co/3FGTMpDvbOET.jpg)

**Comment by SamuelCho** [comment]
Can we narrow this down to a particular commit?

**Comment by TRBlount** [comment]
I'll see what I can do, but if this goes as far back as I think it does, we might be in for a ride.

**Comment by TRBlount** [comment]
Looks like the earliest build I could find where FB Thrusters still sort of worked was around early August of last year before the OpenGL Core merge, It doesn't help that all of the nightlies between August 9th and August 27th close themselves on startup, so that's about as much as I can give you.

By "sort of worked", I mean that the FB thrusters have animation instead of just static bending. The bending is still present.

**Comment by SamuelCho** [comment]
The thrusters effect is still there. Gamma correction might be throwing you off. http://imgur.com/a/dCjWl

**Comment by TRBlount** [comment]
That's what I thought at first actually, but I don't get the same results as you with current master.
https://i.gyazo.com/e861ad138042ddf6f8da58b4bbe34759.mp4

**Comment by SamuelCho** [comment]
i don't know what to tell you but i'm not getting that result in the latest revision of HEAD. Are you sure that -fb_thrusters is on?

**Comment by TRBlount** [comment]
The flag is in my cmdline_fso.cfg and in wxLauncher. I tested using a build compiled from the current master branch. 
Here's a debug log: http://pastebin.com/smN2mQ1a

**Comment by SamuelCho** [comment]
I can't reproduce this bug so this is a WNF at the moment. Does anyone else have the some problem? Could this be a vendor specific issue?

**Comment by TRBlount** [comment]
I know Axem has the same issue and we both have Nvidia 9xx series gpus.

**Comment by The-E** [comment]
Did a quick check on my end, Thrusters work correctly here. This suggests that this might be a vendor issue, given that I'm on AMD.

**Comment by TRBlount** [comment]
Alright. I'll do some driver updating to see if that fixes anything. Could it have anything to do with the heaps of uniforms that fail to be found during shader compilation in my debug logs?

**Comment by The-E** [comment]
I get those same warnings in my log, and have been for a long time, I think they're unlikely to be the issue here.

**Comment by asarium** [comment]
Those warnings are very misleading and should probably be removed. It's valid behavior for an OpenGL implementation to discard uniforms that are not used but FSO still shows a warning for them. It may be useful for shader development so the `mprintf` could be converted to an `nprintf` with an appropriate category.

**Comment by TRBlount** [comment]
Updating my drivers did nothing. Any other suggestions?

**Comment by asarium** [comment]
I'm on Linux with an AMD card (open source drivers) and I am also seeing this issue. I'll try again on Windows when I boot that to check if it also happens there. Since @The-E mentioned that it works on Windows, this may be a bug that happens everywhere except on the Windows AMD drivers?

**Comment by chief1983** [comment]
https://youtu.be/v8LU_926Nho

Seem to be working just fine for me as well on my Macbook.  Intel Iris Pro, OpenGL 4.1 INTEL-10.22.29, macOS 10.12.3, no deferred lighting but post-proc and fb thrusters are enabled, along with most other eye candy.

**Comment by asarium** [comment]
I did some debugging and the distortion map used by the thruster rendering seems to be broken somehow: 
![distortion](https://cloud.githubusercontent.com/assets/1013983/23868096/6c28825c-081e-11e7-8462-d9d79d92a94a.png) (you might need to magnify that a bit)
According to the input parameters that texture should have more or less random colors on the left edge but I'm not yet sure why that doesn't happen.

**Comment by TRBlount** [comment]
Interesting.

More info: Spoon reports -fb_thrusters as not working with a GTX 760 on Windows.

**Comment by asarium** [comment]
I think I found the issue, the distortion offset wasn't right so all the new value rendered to the the distortion map were discarded.
