### ISSUE TITLE
Medals name not displayed for medals added past the standard FS2 medal number

### ISSUE THREAD

**Issue by krevett62** [scp-fs2open/fs2open.github.com#1315]
I noticed that when I add new medals to the table, they display correctly in the case, but their name does not appear. Instead if I replace the base FS2 medals with the new ones, everything works fine and the new name is displayed. It might be a bug?

**Comment by asarium** [comment]
Where should the name be displayed? Can you upload a test mod which reproduces this bug?

**Comment by krevett62** [comment]
The name is displayed at the same place as those from FS2 medals. The mod I use is a custom version of this one http://www.hard-light.net/forums/index.php?topic=93242.0 with FS2 campaign and other assets available. The table has standard FS2 medals in the first part and renamed medal in the second part (used in the other campaign). Perhaps this is because medals bitmaps overlap with standard FS2 one (in fact it's just renamed medals), but the second campaign don't use FS2 medals anyway except wings and ranks. But if I remove the FS2 medals and just put the renamed ones in the table, names are displayed correctly (but in that case, I can't play anymore with FS2 medals in my custom version).
Sorry I can't post my custom version as it uses a lots of community models and is more than 4Gb it's just for personnal use, but the medal table is the same as the one you'll find in the link posted above.

**Comment by Goober5000** [comment]
Was this confirmed to be not-a-bug?

Medals were made dynamic some time ago so the limit should not be a problem.

**Comment by Goober5000** [comment]
I'm assuming this is, in fact, the overlapping issue.  @krevett62 can reopen if the bug reappears.
