### ISSUE TITLE
Insignia rendering uses clipping planes without support by the shaders

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1326]
I discovered this because an assertion I added failed while I was testing something in FSport. The problem here is that the passthrough shader has no support for setting the clip distance and even worse, it doesn't have access to the required matrix because it only has a combined model view matrix.

@SamuelCho Do you know if clipping works in view space? If yes we could transform the clipping equation into view space and compute the clipping value using the view space position we already have available in the passthrough shader.

**Comment by SamuelCho** [comment]
Yeah, clipping should work in view space.

**Comment by asarium** [comment]
Fixed by #1327.
