### ISSUE TITLE
3.8 RC1 ignoring all command line arguments, existing pilots, etc.

### ISSUE THREAD

**Issue by Sesquipedalian** [scp-fs2open/fs2open.github.com#1332]
For some reason, 3.8 RC1 doesn't recognize any of the command line arguments set by wxLauncher, or any existing pilot files. 

For example, with this command line, no mods are loaded and none of the specified settings are applied:

`/Volumes/STOVELL32GB/FS2_Open/fs2_open_3_8_0_RC1_x64.app -mod
fsport-mediavps_2014,fsport,mediavps_2014 -missile_lighting -3dshockwave -post_process
-soft_particles -fxaa -fb_explosions -rearm_timer -ballistic_gauge -ship_choice_3d
-weapon_choice_3d -3dwarp -warp_flash -snd_preload -no_set_gamma -output_sexps
-ambient_factor 75 -spec_exp 11 -spec_point 0.6 -spec_static 0.8 -spec_tube 0.4 -ogl_spec
60`

This should apply the "Baseline recommended" preset in wxLauncher's Advanced Aettings and the load up the FSPort mod + media VPs, but in fact the game loads exactly as if no command line arguments were set.
 
None of my existing pilot files appear either, and the new pilot I had to make when I ran 3.8 RC1 is not stored with the rest of my pilot files, either. (At the time I am writing this, I still haven't figured out where the newly created pilot file has been saved. All I know is that it is not in `/Volumes/STOVELL32GB/FS2_Open/data/players`, where it should be.)

When I switch back 3.7.4, everything works as expected. The only change I made was to switch which executable was selected in wxLauncher's Basic Settings tab.

This is on macOS 10.3.

**Comment by Sesquipedalian** [comment]
Never mind, I figured it out. The standard folder for storing FS2 files was moved from ~/Library/FS2_Open to ~/Library/HardLightProductions/FreeSpaceOpen, that's all.

**Comment by MageKing17** [comment]
Newer versions of wxLauncher (0.11 and up) automatically handle the new settings location.

**Comment by Sesquipedalian** [comment]
Cool, thanks.
