### ISSUE TITLE
Commit 519e89b6 blocks any further attempts at Solaris support

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1337]
code/globalincs/version.h line 40 causes the error `'namespace version { }' redeclared as different kind of symbol`.
It mentions the first definition of version was in `/usr/include/math.h, line 147: 'enum version'`.

This basically seems to indicate that 'version' is a reserved keyword on Solaris, and probably has been for some time.  I haven't attempted a Solaris build in a while which is why this was just now noticed.  If someone does have the time to see if this symbol can be globally renamed, it would remove a block towards efforts on supporting another distro (or two if you count OpenIndiana as separate from Solaris).  Mostly interested because I have recently acquired a pair of Sun workstations and planned to set them up with OpenIndiana and Solaris.

**Comment by asarium** [comment]
Was this fixed by #1341?

**Comment by chief1983** [comment]
Yup.
