### ISSUE TITLE
Specular highlights appear on faces pointing away from light sources

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#1353]
As you can see in the image below, surfaces that should not receive any illumination (env reflections and ambient light need not apply) render specular highlights. The issue is largely apparent at long distances, but still occurs at relatively short distances, they highlights are just significantly smaller.

![](https://puu.sh/vVuCt/834cff8423.png)

I'm currently looking into the issue.

**Comment by SamuelCho** [comment]
What's the result if you turn off environment maps? I'm pretty sure N dot L for specular directional lighting isn't producing that result.

**Comment by TRBlount** [comment]
The picture is with environment maps turned off actually.

**Comment by SamuelCho** [comment]
i'm gonna need a sample project/mod to tinker with this.

**Comment by TRBlount** [comment]
Alright. There is a chance this might just be an issue with very large models. That asteroid is 12km x 12km in the horizontal plane, making it significantly larger than most other models in Freespace.

**Comment by TRBlount** [comment]
Here's a test mod: http://lazymodders.fsmods.net/files/bigasteroid.rar

**Comment by SamuelCho** [comment]
i'm not seeing this same result on my machine. are you looking at the asteroid inside the "donut" or outside?

**Comment by SamuelCho** [comment]
So, my guess is the surfaces that you think shouldn't be receiving light are actually pointing towards the sunlight. It's just they're being finicky because the shadow cascades aren't large enough to capture the entire asteroid that's supposed to occlude that sunlight.

**Comment by TRBlount** [comment]
The issue is mostly noticeable from outside the donut. Also, I don't think surfaces that are for sure pointing away from a light source should be (directly) illuminated by said light source. The shadow cascades not being large enough makes sense I suppose, as with soft shadows enabled there's no easy way to fall back to the old method of shadowing the model (simply, surface not pointed at light source, don't illuminate).

**Comment by SamuelCho** [comment]
I don't know man. Other than the shadow cascade limitation, the lighting looks mostly correct to me, even outside the asteroid.

**Comment by TRBlount** [comment]
I just tested with shadows disabled and the lighting was mostly correct, so I'll go with the limitation being the cause as well.
