### ISSUE TITLE
Player Ship Glowpoint Lighting Doesn't Illuminate in Cockpit View

### ISSUE THREAD

**Issue by AndrewofDoom** [scp-fs2open/fs2open.github.com#1354]
Test Mod: https://www.mediafire.com/?lq9d00rzyrzgqy8

Load up lighttest.fs2 and look at the Fenris. Now go into third person and see the Fenris being lit by the player ship. This is a bug that happens regardless of whether or not the "show ship" flag is on.

**Comment by SamuelCho** [comment]
I don't think this is something that can be fixed very easily. Because of how cockpits are set up, light sources other than the directional light can't be applied. Cockpits are rendered in a completely separate pass from the main scene due to dimensional/depth issues.

**Comment by PatrickDCoffman** [comment]
@SamuelCho If I'm understanding you right, I think you misunderstood Andrew. The glowpoints are on the ship's hull as normal (cockpit models weren't being used when this was encountered).

**Comment by EatThePath** [comment]
In barking up what I think is the same tree I've come to believe that "show ship" would be required for this case, and the engine needs a way to render the player ship's glowpoint lights without rendering the player ship. Further, I suspect that "show ship" either doesn't work, or only works in conjunction with a cockpit model. All my tests have been without a cockpit model, and show the `ship_render_show_ship_cockpit` function never getting called.
