### ISSUE TITLE
Standalone disappears from FS2NetD

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1355]
As identified in #470 even after fixing the SIGPIPE crash (and in other situations as well), the server will disappear from FS2NetD.  It can still be reached via direct IP, and will usually re-connect to FS2NetD after the player disconnects from the standalone.  But a connection isn't likely to happen to a public server once it is gone from the FS2NetD game list so the only solution is to restart the server or manually connect and disconnect yourself.  Not very ideal.

To reproduce this issue, one only needs to fire up the standalone and then terminate the network connection temporarily, until the server fails to connect to FS2NetD for a game update.  At that point, re-establish the network connection.  The standalone will re-connect to FS2NetD, but not complete its re-init process, and fail to appear in the game list.

Affected platforms appear to be at least all *nix flavors (Mac, Linux, FreeBSD, Solaris).  Have not tested if anything similar exists for the GUI standalone on Windows yet.

**Comment by chief1983** [comment]
See comment https://github.com/scp-fs2open/fs2open.github.com/issues/470#issuecomment-302469047 specifically for more info on the missing server, it looks like there is some call to re-initialize the server that needs to happen but isn't and the server goes to sleep basically.

**Comment by notimaginative** [comment]
Is this still and issue with PXO?

**Comment by JohnAFernandez** [comment]
I haven't seen any instances of this problem since PXO came back.  The issues with PXO seem to be with trying to get the server onto the list promptly.
