### ISSUE TITLE
Feature idea: Add a mod flag for specifying the targeted FSO version

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1389]
We have quite a lot of modding flags throughout the FSO code the fix some behavior but which cannot be enabled since it might break retail compatibility.

I possible solution I had in mind could be to introduce a mod table flag that lets a mod specify which FSO version it's designed to be run on. That value could then be used for deciding if a bug fix should be applied or not.

That would also allow to implement a clear deprecation model where obsolete flags are disabled if the mod targets a recent enough version of FSO.

What are your thoughts on this?

**Comment by MageKing17** [comment]
This sounds like an interesting idea that could be added onto the existing "minimum FSO version" functionality to change the default values of flags that are recommended to be enabled in new mods anyway.

**Comment by Goober5000** [comment]
If you're thinking about a *table* flag, we already have the version-specific commenting capability which allows table features to be enabled or disabled based on the version.

**Comment by MageKing17** [comment]
> If you're thinking about a table flag, we already have the version-specific commenting capability which allows table features to be enabled or disabled based on the version.

This is a completely separate idea whereby a mod targeting a newer version of FSO would have retail-breaking bugfixes default to on instead of off, so they don't need to include a mod table and AI profile that explicitly turn them all on.
