### ISSUE TITLE
200+ subsystems

### ISSUE THREAD

**Issue by Jey-Galactica** [scp-fs2open/fs2open.github.com#1412]
Hi guys.
I'm actually a newbie in modding and 'll be very grateful if anyone could help me.
I'm trying to add my own ship to Diaspora:SA. It works fine, but only with <200 subsystems =) When I try to add more sub-s (actually there must be about 400) the game says "Number of subsystems for ship entry 'Cheron' (0) exceeds max of 200". As I found out it's connected with ship.cpp file, but I don't know how to find and correct it. I'd like to know if there's a way to change the max number of sub-s and also how it could be realized.
Thank you.

**Comment by The-E** [comment]
Is Cheron a new ship class you have defined? If so, it seems that its table entry is invalid, please post it here so that we can examine it.

**Comment by Jey-Galactica** [comment]
As I see, It's almost the same as Diaspora's battlestar, but only difference is a number of subsystems. It works good, when I try to import it with less then 200 subsystems. May be there's a mistake somewhere I can't see... 
[Cheron.txt](https://github.com/scp-fs2open/fs2open.github.com/files/1145561/Cheron.txt)

**Comment by The-E** [comment]
Two things: The 200 subsystems per ship limit is hardcoded. We can bump it, but I'm going to put on my game designer hat and ask whether you really, actually need that many turrets. A ship like that is very hard to interact with when flying against it, both for players and AI; putting it into a mission makes that mission almost certainly self-playing, as there is little the AI can do against it.

Furthermore, given the other limits in place in the engine and Diaspora's use of high fire-rate weaponry, it is entirely possible for a mission featuring this ship to run into the object or weapons limit, which leads to unwanted behaviour.

**Comment by Jey-Galactica** [comment]
@The-E 
I'm like a child with a toy, of course I want it :D 
So, who said, that I'm not gonna make some hostile ships worthy Cheron ;) Actually this boy is not for Diaspora, I'm just planning to make some kind of BSG mod with other ships
Nevertheless, I'm here just to find out if anyone can help me to make it work, so balance can be configured after all =)

**Comment by The-E** [comment]
Again: we _can_ bump that limit. That's not that big a change (although if we do it, it will not be in 3.8); what I'm asking is whether you _need_ a ship that singularly powerful, and making you aware that even if we were to remove the primary obstacle to using it you're facing right now, you may run into issues later on.

The years of experience I have in working with this engine tells me that a ship like that, big and humongous and bristling with guns, _isn't fun_. It's like putting Galactica into a mission where the opposition force is a single wing of Raiders; the player can sit back and watch Galactica's flak swat those things out of the sky without doing anything. Making fun missions featuring behemoths like that is _hard_, and I'm trying to save you a bunch of headaches here.

As an example of this on a much smaller scale: Look at BP:WiH's Serkr team. These are three corvettes, small vessels that, individually, aren't much of a threat to players. Put them together though, and suddenly all the AA fire they can throw presents a formidable obstacle to players and AI alike that is almost impossible to solve without insane flying or plot contrivance. And that, again, is just with three ships that are nowhere near approaching the subsystem count of this monster.

**Comment by Jey-Galactica** [comment]
@The-E 
hm... so, maybe (no doubt) I'm crazy, but I'd like to try. Why not?
P.s. There's also a headaches because of all turrets configurations) Not afraid of that)
If it's really not a problem for you, I'll try to do the rest)

**Comment by Goober5000** [comment]
I agree with @The-E here; there would have to be a very compelling reason to bump the limit.  "Because we can" or "why not?" aren't compelling reasons.

Furthermore, @asarium discovered that there actually is a limit due to the design of the game; the number of subsystems can't go above 256.
