### ISSUE TITLE
Force feedback occasionally stops working

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1417]
This has been reported numerous times on the forums (e.g. [here](http://www.hard-light.net/forums/index.php?topic=93709.msg1851201#msg1851201)). This is a regression from the SDL2 merge.

Since there is apparently no SCP coder with a force feedback device we can't reproduce and fix this so for now I'll leave this issue without a milestone and would not categorize it as a blocker for the 3.8 release.

**Comment by chief1983** [comment]
Actually I do have a Sidewinder Force Feedback Pro, with the custom USB adapter.  But as it is a custom adapter I'm not sure how reliable it would be for testing something like this.  It's probably beyond my abilities to independently debug though.

**Comment by MageKing17** [comment]
I also have a Logitech Force 3D Pro; my only problem is that it's currently not plugged in. It's been on my to-do list to investigate this problem since the first post about it.

**Comment by Goober5000** [comment]
I've got an MS SideWinder Force Feedback 2, but I'm also not familiar with the SDL2 code and don't have the time at the moment to learn it.  However, I could do some testing if people wanted to send debug builds.
