### ISSUE TITLE
old no-collide ship flag not recognized

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#1425]
It looks like the `no-collide` ship flag has been changed to `no_collide`.  Old missions saved with the `no-collide` flag will have this flag removed when you open them and save them in FRED.

(Since this flag is cleared when the mission is opened in FRED, I am also assuming that old `no-collide` flags will not be recognized if they are played in FSO, but I have not tested that aspect.)

**Comment by asarium** [comment]
Fixed by #1426.
