### ISSUE TITLE
FRED2 campaign editor doesn't show available missions with a mod enabled

### ISSUE THREAD

**Issue by resorath** [scp-fs2open/fs2open.github.com#1434]
When a mod is enabled, FRED2 won't show any available missions in the campaign editor (with missions in {FS2HOME}/{campaign_name}/data/missions folder). Only shows missions when mods are disabled, in which case it shows missions in the {FS2HOME}/data/missions folder as expected.

**Comment by MageKing17** [comment]
What version of FRED are you running? This is sounding like issue #1224 again.

**Comment by resorath** [comment]
3.7.4

Yes sorry, that is the same issue and looks to be resolved in 3.8.0 RC 3.
