### ISSUE TITLE
Merge the multilock code and required changes related to other PRs

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#1441]
If I remember correctly, the only objection @SamuelCho had to merging multilock was related to netcode. The suggested compromise is to display a warning or error when attempting to use the code with multiplayer and include a note in the wiki. I've been keeping a copy of the branch around up to date for Spoon's Wings of Dawn build, and thus far I've only had to make one change related to #647 in regards to seeker heads being ineffective.
If we merged #647 and then multilock, Wings of Dawn would no longer need a custom build and the feature would be available to more modders.

**Comment by MageKing17** [comment]
> Wings of Dawn would no longer need a custom build

...Except for the increased BMPMAN slot limit, you mean?

**Comment by TRBlount** [comment]
Ah, I forgot about that. Yes, there is also that issue, which should probably be addressed at some point. We really shouldn't encourage the use of custom builds at all.

**Comment by TRBlount** [comment]
BMPMan slot limit should no longer be an issue right? In addition, with the new insights from ngld with respect to the netcode, the old issues may become moot as fixes start rolling it.

**Comment by TRBlount** [comment]
In order to reach the Release 19.1 milestone, our current plan is to merge Multilock and then make the multiplayer related fixes for it a milestone for Release 20. The reasoning for this is there are already multiple features that are not supported by multiplayer that are quite important for users in single-player, so adding another one wouldn't affect the current state of the game.
