### ISSUE TITLE
Retail models are rendered completely black after #1318

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1472]
Well, not only retail models but some older too. Models from Mediavps 2014 are not affected. Tested on nvidia driver 385.41 on windows and intel 17.1.5 on debian.

> f1bf0a411c912f3cac4bef147043dfb563bdb74a is the first bad commit
> commit f1bf0a411c912f3cac4bef147043dfb563bdb74a
> Author: asarium
> Date:   Thu Feb 2 11:09:13 2017 +0100
> 
>     Use OpenGL texture arrays for animations
>     
>     This converts all usages of bmpman textures to OpenGL texture arrays.
>     That means that all frames of an animation are stored in a single OpenGL
>     texture object and can be accessed at the same time in a single draw
>     call. This should significantly reduce the overhead of drawing lots of
>     particles since all particles of a single animation can be drawn with a
>     single draw call.
>     
>     This fixes #1169.

**Comment by The-E** [comment]
Please post a log.

**Comment by asarium** [comment]
I can reproduce this and will try to find the cause for this.

**Comment by tomimaki** [comment]
Log if it's still needed.
https://pastebin.com/C2A4Vk0H

**Comment by tomimaki** [comment]
Yep, #1473 fixed this.
