### ISSUE TITLE
Excessive specular lighting with retail models

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1481]
There have been some reports that the specular lighting effects are a bit excessive when a model does not have a specular map and I agree. There is a constant in the shaders (`SPEC_FACTOR_NO_SPEC_MAP`)  which currently has the value `0.6`. That's pretty big for a model that was not built with specular lighting in mind.

Before the PBR additions, a missing specular map wouldn't contribute any specular lighting so this change is pretty significant. PBR requires specular lighting for properly displaying the models so the specular color can't just be ignored but the factor can be tweaked a bit. I tried it with 0.1 and it looks much better.

**Comment by chief1983** [comment]
Some comparison screenshots/videos might be nice.  I have a Mac again and can record video easily once I get FSO on it if someone else doesn't beat me to it, but this sounds like it solves something that's still been bugging me about PBR too.

**Comment by asarium** [comment]
Here are two screenshots for comparison of the two values:

`0.6`:
![screenshot from 2017-09-13 09-37-41](https://user-images.githubusercontent.com/1013983/30365250-7245db42-9867-11e7-8bd1-9dd5b50cda88.png)

`0.1`:
![screenshot from 2017-09-13 09-36-52](https://user-images.githubusercontent.com/1013983/30365262-7cf2e828-9867-11e7-81a7-734058fa3b91.png)

`0.01`:
![screenshot from 2017-09-13 09-42-45](https://user-images.githubusercontent.com/1013983/30365397-ecc4a182-9867-11e7-9b46-dc381238a97d.png)

For comparison, here is 3.7.4 (I'm not sure if that was running with shaders since that didn't work reliably with 3.7.4):
![screenshot from 2017-09-13 09-46-29](https://user-images.githubusercontent.com/1013983/30365653-b486eb80-9868-11e7-8fea-72167fd3713c.png)

**Comment by chief1983** [comment]
Does this get updated in deferred-f.sdr, main-f.sdr, or both?

**Comment by MageKing17** [comment]
It appears to be unused in deferred-f.sdr.

**Comment by asarium** [comment]
It is defined in `deferred-f.sdr` but never used which makes sense since the deferred renderer doesn't sample the object textures but instead uses the specular information already gathered by the main rendering code.
