### ISSUE TITLE
How to (possibly) fix BMPMAN

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#1503]
After the Discord discussion about WoDs usage of bmpman slots and the resulting changes in #1502 I though about how bmpman could be changed to fix the core issue. I don't know a lot about how the internals of bmpman work but I know how it uses the `bm_bitmaps` array for keeping track of what bitmaps are currently in use. If this data structure could be changed to support a variable number of entries then the main issue of bmpman would be solved so I though about how to do that.

I tried to use a hash map for storing the bmpman slots once but that has some issues with how the data is handled and the STL hash maps are also not the fastest solutions out there. My "solution" for this problem would borrow some aspects from a hash map but it would be optimized for how bmpman is currently working. The system would use multiple blocks (where each is similar to the current `bm_bitmaps` array) of fixed size. When bmpman needs to allocate a bitmap info then it will choose a free slot in one of the blocks and then assemble the 32-bit handle (bmpman currently uses an `int` so that cannot be changed to a 64-bit integer easily) by using the lower 16-bits as an index into the block and the upper 16 (15 actually since it is a signed integer) for storing the index of the block.

As far as I can tell, this system should allow bmpman to allocate a new block if the old block does not have enough slots left over which would fix the most pressing issue of bmpman (at least I think that is the most pressing issue).

Thoughts?

**Comment by TRBlount** [comment]
A logical -> physical addressing scheme should be sufficient. This means that we would get 32K blocks each holding 64k slots correct?

**Comment by asarium** [comment]
Yes, that's exactly what I mean. 64k slots is probably too much so this could be lowered to 4096 or something like that since it would use too much memory otherwise.

**Comment by z64555** [comment]
I'm wondering if a double ring system (similar to what beams and others use) would be of use.

**Comment by Goober5000** [comment]
Closing this issue since it was implemented in #1670.
