### ISSUE TITLE
White square motion debris after removing full nebula via sexp

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1507]
See attached mission

Mission starts off in a full nebula, if you press 1 the mission-set-nebula sexp is called to remove the nebula. Motion debris then becomes all white squares.

This happens with 3.8.0 and latest master.

![screen0106](https://user-images.githubusercontent.com/6625164/32691075-19ed8dca-c6c8-11e7-8b59-c1c8a88b935d.png)

[distorttest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/1463858/distorttest.zip)

**Comment by asarium** [comment]
I cannot reproduce this. The motion debris looks correct before and after changing the nebula. I tested this with Retail FS2 data and the MediaVPs.

**Comment by MageKing17** [comment]
That's because it was fixed by #1510; this should've been closed already.
