### ISSUE TITLE
play-dead AI goal's behavior is different than expected

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#1536]
So currently, some AI goals says they only go up to 89 (and can always be overwritten by the player) and others say they go up to 200 (and cannot be overwritten by the player if it's 100+), and so far as I've been able to test, this is accurate. However, there's no real reason for certain goals to be always overwritable, and moreover, this doesn't seem to have always been the case as some campaigns rely on play-dead being non-overwritable, despite it being, at least now, always overwritable.

**Comment by Flip-Sandwich** [comment]
Are there goals that are always overwritable regardless of priority? Since I think all AI goals can go up to 200 unless there's a few that have dumb hard caps at 89 so they can't which ones are those I'll take a look

**Comment by Baezon** [comment]
Play-dead, off the top of my head, there was at least one other, though, I can't quite check right now. Based on my testing all the ones whose sexp blurbs said they could only go up to 89, were those always overwritable ones.

**Comment by Flip-Sandwich** [comment]
garble garble this doesn't make sense to me, nothing in the code i can see right now has any different priorities for play-dead and any other order i'll keep looking

**Comment by Baezon** [comment]
Can you confirm through testing that is indeed always overwritable, at least for you? I've not actually seen any confirmation from others about this, and I'm certainly not willing to rule out it's something specific to my system, but I've been able to reproduce it in a variety of contexts.

**Comment by Flip-Sandwich** [comment]
Yeah play-dead is always overwritable even if you set it to 200 via initial orders or 200 via SEXP and I have no idea what's causing it

**Comment by Baezon** [comment]
Here's a test mission for anyone interested. He gets a play-dead order with a priority of 200 one second in, but you can still order him around.
[test.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2131075/test.txt)

**Comment by MageKing17** [comment]
Okay, so, I ran the test mission through a debugger and finally figured out what's going on... the ship loses the `play-dead` goal the frame after it's given it. Why? Because apparently three goal types call `ai_clear_ship_goals( aip );` (for reasons I'm not really clear on): `AI_GOAL_STAY_STILL`, `AI_GOAL_PLAY_DEAD`, and `AI_GOAL_FORM_ON_WING`. That means they wipe *themselves* from the goal list, so any other goal at any priority will override them. I'm not sure what the consequences of changing that behavior would be.

**Comment by Goober5000** [comment]
Hmm.  Well, I have two ideas on how to address that:

1) Add a new sexp `prevent-new-goals` which will set a flag in the ship's AI structure preventing any goals from being added at any priority.  There would be a complementary `allow-new-goals` sexp (or perhaps instead a true/false argument to a single sexp) to allow the flag to be cleared.

-or-

2) Add a new sexp to set the allowed orders for a ship.  The allowed orders could be cleared or changed during the mission at the FREDder's discretion.

**Comment by Goober5000** [comment]
Of course, there's always the option of clearing all goals *but* the newly added one, and tying the new behavior to an ai-profiles flag.

**Comment by Goober5000** [comment]
Here's another idea: add a new goal called `play-dead-persistent`, which works just like `play-dead` except sticks around in the AI goal list until cleared.  This should be the easiest goal-related option to implement.

The new sexp for setting allowed orders, that I mentioned in 2) above, is also a good thing to add.

**Comment by Goober5000** [comment]
Turns out `set-player-orders` already exists.

**Comment by Goober5000** [comment]
Added `ai-play-dead-persistent`.
