### ISSUE TITLE
MacOS: Cannot make multiple builds in a row

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1549]
```
PhaseScriptExecution CMake\ PostBuild\ Rules build/freespace2/FS2_Open.build/Debug/Freespace2.build/Script-0B78269E44504361ACB0B5CF.sh
    cd /Users/cliff/fs2_open
    /bin/sh -c /Users/cliff/fs2_open/build/freespace2/FS2_Open.build/Debug/Freespace2.build/Script-0B78269E44504361ACB0B5CF.sh
echo "Copying resources into bundle..."
Copying resources into bundle...
cp -a /Users/cliff/fs2_open/freespace2/resources/mac/Resources /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Resources
mkdir -p /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Resources/English.lproj/
cp -a /Users/cliff/fs2_open/build/freespace2/InfoPlist.strings /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Resources/English.lproj/
echo "Creating '\$<TARGET_FILE_DIR:Freespace2>/../Frameworks/'..."
Creating '$<TARGET_FILE_DIR:Freespace2>/../Frameworks/'...
mkdir -p /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Frameworks/
echo "copying '/Users/cliff/fs2_open/build/lib/prebuilt/SDL2.framework'..."
copying '/Users/cliff/fs2_open/build/lib/prebuilt/SDL2.framework'...
cp -a /Users/cliff/fs2_open/build/lib/prebuilt/SDL2.framework /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Frameworks/
cp: cannot overwrite directory /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Frameworks/SDL2.framework/Resources with non-directory /Users/cliff/fs2_open/build/lib/prebuilt/SDL2.framework/Resources
cp: cannot overwrite directory /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Frameworks/SDL2.framework/Versions/Current with non-directory /Users/cliff/fs2_open/build/lib/prebuilt/SDL2.framework/Versions/Current
cp: cannot overwrite directory /Users/cliff/fs2_open/build/bin/Debug/fs2_open_3_8_1_x64-DEBUG.app/Contents/MacOS/../Frameworks/SDL2.framework/Headers with non-directory /Users/cliff/fs2_open/build/lib/prebuilt/SDL2.framework/Headers
make: *** [Freespace2_buildpart_2] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ PostBuild\ Rules build/freespace2/FS2_Open.build/Debug/Freespace2.build/Script-0B78269E44504361ACB0B5CF.sh
(1 failure)
```

It looks like there is some sort of issue with copying the SDL2 framework into the already existing app location.  I don't recall this having been an issue with the CMake process in the past, but it's been a while since I have tried actually building on a Mac, just getting back into it again.

Not sure why it thinks it is trying to overwrite a directory either, as the initial paths referenced look to be symlinks to directories, and not actual directories.

**Comment by ngld** [comment]
Looks like `cp` resolves the symlink during that check and then thinks it's trying to replace a directory with a symlink. [Apparently it's a known problem](https://stackoverflow.com/questions/18365834/cp-a-cannot-overwrite-symlinked-directory).

A simple `rm -rf` on the `SDL2.framework` folder or not copying the folder at all if it already exists should solve this issue.

**Comment by chief1983** [comment]
Yeah in the meantime I realized that as long as I move the .app out of the bin folder instead of copying it, it will just rebuild it successfully anyway.  But having an automated workaround in case I didn't move the app out of the way would be ideal, yeah.

**Comment by chief1983** [comment]
Looking at it, the latter suggestion isn't ideal because it could be modified from the framework that is already in the location, if a clean was not done in advance.  The former, only solves the problem for this one framework, and repeating it for every framework seems tedious to me.  Not saying it happens now but it doesn't bulletproof it from happening in the future.  I wonder if it would be cleaner to remove the entire bundle at the beginning of the compilation process.  Recreating the bundle is essentially what happens anyway as every file should be overwritten so it shouldn't add any more time than it does to delete the files (which overwriting them probably has to do anyway).

**Comment by Goober5000** [comment]
Closing this since we're not currently building for MacOS.
