### ISSUE TITLE
Need to get all CI builds to use at least SDL 2.0.5

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#1553]
I just happened to notice that MacOS nightly builds include the SDL.framework that is indicating they are version 2.0.4.  This would mean that haptic would be broken in them as of #1328 since it reverted the kludge that allowed haptic to work with a bug that existing in 2.0.4.  SDL 2.0.7 is out now, I am not sure where the CI gets its framework from yet, but I am guessing it is whatever is available on the CI platform by default.

**Comment by asarium** [comment]
All the builds use the SDL framework from the [scp-prebuilt](https://github.com/scp-fs2open/scp-prebuilt/tree/master/mac/SDL2.framework) repository. If you want to update that then just push the new version of the SDL framework into that repository and wait until all the packages have been uploaded to GitHub. Then you need to copy the commit hash of the release (everything after the `bin-`) and paste it here: https://github.com/scp-fs2open/fs2open.github.com/blob/17374106d143227ae48cc1d900d6d3cbf2acd25a/lib/prebuilt.cmake#L2

The next build will download the new binaries and compile as usual.

**Comment by chief1983** [comment]
Ah, that sounds more easily solved than I'd expected, I will look into both updating the included libsdl and the prebuilt stuff to 2.0.7 then.
