### ISSUE TITLE
Dynamic Lights flickering if Deferred Lighting and Soft Shadows enabled simultaneously.

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#1579]
First noticed this in the F3 lab. Click on the image for a video (and ignore the people talking).
[![](https://img.youtube.com/vi/x2Hpi-1cHpI/0.jpg)](https://www.youtube.com/watch?v=x2Hpi-1cHpI)
Other symptoms include vertical and horizontal lines marking an area of the screen where the mouse light does not affect the model. The light flickering does occur in game with things like beam cannon lights. Already verified that this occurs before GGX got merged in, so it's a little older than that.

To reproduce, simply have both Deferred Lighting and Soft Shadows enabled simultaneously.

**Comment by TRBlount** [comment]
This has been narrowed down to commit e319b6f, which is associated with #1489.

**Comment by asarium** [comment]
I cannot reproduce this with an AMD RX 480 with the Linux open-source drivers. What GPU do you have?

**Comment by TRBlount** [comment]
I've got a GTX 970.

**Comment by TRBlount** [comment]
I believe Spoon is able to reproduce my issue on his GTX 760. So I would say this appears to be an issue with Nvidia for the time being.

**Comment by chief1983** [comment]
I think I was seeing this light flickering on my Mac in the F3 lab as well, and for the light flicker I don't need shadows enabled.  Just deferred I guess.  Shadows won't run well at all on my Macs currently, both of which have Intel Iris GPUs with Retina displays.  This may be a different issue though, but the flicker is definitely noticeable.  I may try to record a short video of it with Quicktime later.  Also only seems to be a thing in the F3 lab too.

**Comment by TRBlount** [comment]
Mhm, Spoon captured some videos for us.
https://www.dropbox.com/s/f8wst2po8662ps1/Fs2_open_Wings_of_Dawn-EX12-SSE%202018-01-17%2017-14-32-41.webm?dl=0

https://www.dropbox.com/s/at1a7x8y7q5uk02/Fs2_open_Wings_of_Dawn-EX12-SSE%202018-01-17%2017-16-19-55.webm?dl=0

Seems to corroborate my issue.

**Comment by chief1983** [comment]
Ah, I was only seeing flickering while moving the ship.  Not stationary flickering.  I can try to confirm tonight on my 970 at home though.

**Comment by chief1983** [comment]
I may want to re-open this, as I think the issue is apparent on my Intel Iris-powered Macbook as well.  The 12/11 build does not seem to exhibit any flicker in the F3 lab but every build since including the latest nightly does, when I turn to the side of the Orion and zoom in a bit, and move the mouse around, having the spotlight on the broadside of the ship will suddenly cause a mad flickering.

**Comment by chief1983** [comment]
I can confirm I have two different Macbooks that exhibit problems after the clipping plane change.  The second one seemed fine after the Orion but I was able to see flickering issues with certain parts of the retail Hercules.  It is a Mid-2014 13" with an Intel i5 and Iris 5100 GPU.  It reports the version as 4.1 INTEL-10.30.12.

**Comment by The-E** [comment]
Can you try it on a more recent build? I can tell that the one you have is relatively old; It's still using the old lab.

**Comment by chief1983** [comment]
Was building one at the moment actually.

**Comment by chief1983** [comment]
I don't seem to be getting any lighting at all now.

**Comment by The-E** [comment]
Gonna be needing an fsolog then.

Also, check the lighting detail setting.

**Comment by chief1983** [comment]
I will probably move that to another ticket then.  I can still reproduce the flicker effect in our FotG build at least, in the regular tech room.  Trying to see if I can with MediaVPs for something sharable.  It may depend on certain maps that retail doesn't have, or I just haven't found the right model with as bad of a problem.

**Comment by asarium** [comment]
I think I found a solution to the clipping problem which should work better for all GPU vendors: https://github.com/asarium/fs2open.github.com/tree/fix/modelClippingFlicker

Test builds are available here: http://swc.fs2downloads.com/builds/test/modelClippingFlicker/

**Comment by tomimaki** [comment]
Tested on Intel HD 630 (22.20.16.4691), Nvidia 1050 (397.64) and AMD 6650M (Mesa 18.03). No flickering or other issues. Interesting thing - [it fixed shadow glitch](https://www.hard-light.net/forums/index.php?topic=93867.0) on Mesa.

**Comment by chief1983** [comment]
It compiles on Mac, at least.  I'll give it a spin later.

**Comment by chief1983** [comment]
Ran into a probably unrelated crash while testing it, but did not notice any flicker issues or shadow glitches on the Intel Macbook.  Have a couple more machines to test it on though.
