### ISSUE TITLE
Default lighting values not aesthetically pleasing

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#1587]
The default lighting values embedded in the exe, which for reference are:

- Directional lights: 1.0
- Tube lights: 1.0
- Point lights: 1.0
- Ambient factor: 128
- Bloom: 75

...are kinda bad. They produce images that are rather flat; in some circumstances, so flat in fact that shadows get swallowed whole by ambient lighting or ship self-illumination. 

Do note that, at the moment, the engine exposes two values (OGL Spec and specular exponent) which do nothing. They should thus not be considered in this discussion, and will be removed in a forthcoming nightly.

So, let's get to making better ones. Reducing bloom is probably the easiest of these; a value of 25 to 30 should produce an effect that is pleasing while not overwhelming.

For reference, here's a playthrough of SM1-09 with the default settings:
https://youtu.be/S42eaMJ50-E

And here's the same mission with -no_emissive_light:
https://youtu.be/_KB0psGhEd0

And again, with -no_emissive_light and the mediavps enabled:
https://youtu.be/IevPmEJxYXA

**Comment by FrikgFeek** [comment]
There's also an interesting way that the lighting interacts with PBR and non-PBR assets. PBR assets will have really dark "main" textures which are the only ones ambient light is applied to(well, it also applies to team colours and added decals). This means -ambient_factor means basically fuck all for PBR models.

Now, they'll also have bright -reflect textures, like non-PBR models with their -shine textures. This is the only part spec_static actually applies to. Now, static lighting does seem to apply to diffuse but it isn't controlled by spec_static. 

What this means in practice is that PBR models will mostly be affected by -spec_static while non-PBR ones will mostly be affected by -ambient_factor.

In my opinion both ambient_factor and spec_static should apply to both diffuse and spec. This way modders(and players) would be able to achieve a somewhat similar lighting look for both PBR and non-PBR models which is what a vast majority of mods currently have.

Additionally, for missions where $Ambient light level: is set to 0 or 7895160(120 on all 3 channels, the default setting) or lower any ambient factor below 70.2 will be identical to 0 as it will result in a "final" ambient value below 0.02. This mission ambient setting is used in all MediaVPs missions and a vast number of mod missions as well. Just a note for tweaking defaults.


I've created an imgur album with pictures of what PBR and non PBR ships look like under different lighting settings to demonstrate my point. 
https://imgur.com/gallery/v8IRA

**Comment by Goober5000** [comment]
@The-E who would you recommend to figure out a new set of default lighting values?

**Comment by The-E** [comment]
Sorry for taking so long to get back to this.
Yes, I would recommend adjusting at least some of those values. Setting the default bloom to something much lower (like 25 or 30) would be a good. In addition, making no-emissive-light the default when HDR and postprocessing are enabled would also be an improvement; I'll post a PR with these changes when I get home from work

**Comment by Goober5000** [comment]
Addressed in #2146
