### ISSUE TITLE
Weird graphical artifacts in main menu?

### ISSUE THREAD

**Issue by hxazgalor** [scp-fs2open/fs2open.github.com#1591]
I just got FS2 Open 3.8.0 and installed it. I got some warning at first but I ignored it (which I probably shouldn't have), and when I ran the game, I seem to be getting weird graphics glitches in the main menu. See the images I've attached below:

![fs2_open_3_8_0_sse2 2018-02-04 22-06-23-51](https://user-images.githubusercontent.com/12862476/35778329-c470102a-09f7-11e8-9b96-c470c7eb1e55.jpg)

![fs2_open_3_8_0_sse2 2018-02-04 22-06-26-04](https://user-images.githubusercontent.com/12862476/35778332-ca23cc28-09f7-11e8-8d1b-5b324a607a19.jpg)

![fs2_open_3_8_0_sse2 2018-02-04 22-06-27-78](https://user-images.githubusercontent.com/12862476/35778335-cd5e5232-09f7-11e8-9119-e4482a79beb2.jpg)

![fs2_open_3_8_0_sse2 2018-02-04 22-06-30-12](https://user-images.githubusercontent.com/12862476/35778336-cf90da7a-09f7-11e8-9d38-baafd5dd1dfb.jpg)

![fs2_open_3_8_0_sse2 2018-02-04 22-06-34-06](https://user-images.githubusercontent.com/12862476/35778339-d4384798-09f7-11e8-95a8-05ca93251a53.jpg)

![fs2_open_3_8_0_sse2 2018-02-04 22-06-45-31](https://user-images.githubusercontent.com/12862476/35778343-d6962fdc-09f7-11e8-816d-f758c97902e0.jpg)

Unfortunately, I don't remember what the warning said. I don't seem to be getting it anymore either. Running the game is OK, but I get the weird glitches you see in the pics. Note how some of the elements seem to stand out like stickers pasted on a mismatched background, as well as the 'shadows' in the corner of most of the menus. In the Tech Room, you'll notice the divider splitting the preview screen.

Any idea why this happened? Thanks in advance.

**Comment by The-E** [comment]
Please follow the steps outlined in this post: https://www.hard-light.net/forums/index.php?topic=56279.msg1180359#msg1180359 and post the fs2_open.log here.

**Comment by Goober5000** [comment]
Closing due to no follow-up in several months.
