### ISSUE TITLE
Load Screen 640 warning should be removed from FRED

### ISSUE THREAD

**Issue by AdmiralNelsonFSO** [scp-fs2open/fs2open.github.com#1601]
The warning message "Warning: Mission: found an entry for $Load Screen 1024: but not a corresponding entry for $Load Screen 640:!" is functionally obsolete in 2018 as it is extremely unlikely that anyone will play FSO in such a low resolution.  Please suppress this warning.

**Comment by chief1983** [comment]
Not sure that's entirely true.  There are still a good number of small laptops out there still with fairly small resolutions (I have a small Lenovo with one) and often run in windowed mode on various machines at 800x600 for testing, etc.  Perhaps for mods that have no intention of providing low-interface artwork though, a setting could be added to notify the engine of that fact?  Maybe it could be in a default debug filter that could be disabled when not needed?

**Comment by The-E** [comment]
The warning popup is unnecessary. The log print should be retained, but the full warning popup routine is not needed.

**Comment by Goober5000** [comment]
I personally think there should always be both sets of interface art - which is the policy I've followed in FSPort, TVWP, and Scroll - but if mod creators are making the deliberate decision to only create the 1024 art, then there's no sense irritating them with popups.  I'll make a PR.
