### ISSUE TITLE
Lighting detail settings make no sense

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#1634]
I would like to propose a theory: The way the lighting detail options work right now make absolutely no sense.
As evidence, I present what the option currently does:

lighting 0:

- flat lighting for insignia via light_apply_rgb
- directional lights are enabled

lighting 1: 

- applies static lighting to insignia via light_apply_rgb by manually computing the light influence for a given set of insignia 

lighting 2:

- no difference to 1

lighting 3:

- normal/height/ambient/misc maps enabled
- all weapons cast light 
- debris lightning casts light

lighting 4+:

- explosions cast light

This, I think, could be improved. What we want, I think, is to give the user a tighter control over how many lights are added to a scene; by just switching on all weapon lights at 3 (and there being no explicit difference between detail level 1 and 2), there's room here to add some granularity. A reworked scheme could look like this:

lighting 0:

- render all directional lights
- use all lights in light_apply_rgb
- enable misc maps
- use simplified lighting model in the shaders

lighting 1: 

- enable normal/ambient mapping

lighting 2:

- enable height mapping
- render beam lights

lighting 3:

- render lights from explosions, warp
- use GGX lighting model

lighting 4:

- render lights from weapons
- render lights from glowpoints

Notes:
- Lighting from beams, explosions and warps is among the strongest lighting we currently encounter in the game. As such, it should be enabled way earlier than it is now.
- Normal/Ambient mapping has a dramatic effect on the overall look and, as these things go, is not that performance intensive (and is easily switched off via cmdline if it becomes an issue), so it should happen way sooner
- light_apply_rgb is a bad thing. I want to investigate how much effort it would be to rip the insignia rendering code out of the game and replace it with the decal rendering we got in there now (at which point, they'd be governed by some reworking of the model detail slider, I think)

Questions, comments, concerns?

**Comment by SamuelCho** [comment]
Yeah this makes a lot more sense. But question: when you say simplified lighting model, do you mean switch from GGX to Blinn-Phong?

**Comment by The-E** [comment]
Yeah. I mean, the function is still in the .sdr's; unless you object, setting a few #defines to control which model gets used sounds simple enough to me.

**Comment by SamuelCho** [comment]
I just hope the delta between Blinn-Phong and GGX isn't too large but I guess if you're running with the lowest lighting settings, you probably aren't expecting to see the exact specular lobe the texture artist intended for you to see.

I think this is a good idea all in all.

**Comment by The-E** [comment]
Here's the result of the changes in #1638:

Lighting Detail 0:
![screen0077](https://user-images.githubusercontent.com/280879/36963528-f5f5214a-2053-11e8-91bc-bd4788a71658.png)
Lighting Detail 1:
![screen0078](https://user-images.githubusercontent.com/280879/36963545-07602c4a-2054-11e8-9bb0-ba5c40d2e54d.png)
Lighting Detail 2:
![screen0079](https://user-images.githubusercontent.com/280879/36963559-146f87b4-2054-11e8-93b2-7e5d4eccfa8d.png)
Lighting Detail 3:
![screen0080](https://user-images.githubusercontent.com/280879/36963570-1af67f34-2054-11e8-995d-50709b408877.png)
Lighting Detail 4:
![screen0082](https://user-images.githubusercontent.com/280879/36963583-22a3de7a-2054-11e8-86d3-a666d249c3b9.png)

@SamuelCho I think the delta between BP and GGX is acceptably low
