### ISSUE TITLE
Stores/Hard Points display issue in DIASPORA

### ISSUE THREAD

**Issue by Nightstorm1** [scp-fs2open/fs2open.github.com#1640]
![before](https://user-images.githubusercontent.com/26633784/36950486-1ddbe1be-1fbc-11e8-8014-d0148ac38255.jpg)

![after](https://user-images.githubusercontent.com/26633784/36950485-1dc62dd8-1fbc-11e8-9aa6-b07b9a3366f6.jpg)

Before picture is from Diaspora 3.7.5 Beta R2 x64 build.

After picture is from the 3/4/18 3.8.1 Nightly x64 build.  You can see how the stores appear to be in a "third person" view compared to top down and the wireframe is now solid.

In the 10/22/17 Nightly x64 build the stores display was correct but the render to texture DRADIS display wasn't present.

In the 11/18/17 Nightly x64 build the stores display had the wireframe but the stores were in third person and the DRADIS was working again.

There didn't appear to be builds between those two.

I personally love how the newer DRADIS renders work with the contacts fading before a sweep picks them up again.  The new lighting looks fantastic but the stores display is an iconic part of the DIASPORA HUD that I'd love to see working as it did before

**Comment by asarium** [comment]
I fixed the invalid weapon orientation issue and I'll try to see if I can find a solution for the outline rendering issue.

**Comment by Nightstorm1** [comment]
Awesome.  Thank you, I look forward to testing out the next nightly.

**Comment by asarium** [comment]
I also fixed the model outline issue. Once those changes have been merged the hardpoint gauge should work again like it used to.

**Comment by asarium** [comment]
The two fixes have been merged and should appear in the next nightly.

**Comment by Nightstorm1** [comment]
Outstanding!  Thank you.  I look forward to testing it out :)
