### ISSUE TITLE
Stores display problem DIASPORA

### ISSUE THREAD

**Issue by Nightstorm1** [scp-fs2open/fs2open.github.com#1647]
Starting with 3/6/18 x64 Nightly the stores display issues have been improved but now there is a scale and alignment problem relative to the displayed craft outline.  

Left side are taken from 3.8.0 Final and right side from the 3/7/18 Nightly x64 build.

![stores](https://user-images.githubusercontent.com/26633784/37122604-ccd9b74c-2226-11e8-9111-cf92ae604c3d.jpg)

**Comment by asarium** [comment]
I found the issue and fixed in the pull request shown above.

**Comment by Nightstorm1** [comment]
Awesome :)  Thank you!
