### ISSUE TITLE
Expose GL_anisotropy a bit better

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#1658]
Right now, whether or not we use anisotropic filtering is controlled entirely by the GL_anisotropy variable, which is set via the OGL_AnisotropicFilter config value in fs2_open.ini. As far as I can tell, that value defaults to 0; this is then overridden in opengl_tcache_init to be between 1.0f (the min value as defined by OGL) and whatever the max supported level of the card is. 

I would propose that this is not entirely optimal. By default, we should be using something better; the maximum supported level is, I feel, a good default. 
Secondly, this to me seems like a parameter that should be controlled via the commandline, or at least be configurable there; Making it part of the texture quality slider is also an option.

**Comment by Goober5000** [comment]
Closing this because #1660 addresses it.
