### ISSUE TITLE
Debug Build Can't Recognize Debrief Variable Name

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#1663]
[debrief-var-issue_fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/1821966/debrief-var-issue_fs2_open.log)

I am using an variable name starting with $A in the debriefing stage. The variable name is "$All-MissionCount". When running debug builds the game crashes at the debrief screen and states:

WARNING: "Invalid text color tag '$A' used in mission: '_GCWC_R_1.fs2'. " at missionbriefcommon.cpp:1440

In discussion with folks on the Discord the first thinks this is a custom color tag instead of the start of a variable name. With the normal build, (ie not debug) this of course doesn't cause an issue, but it does show an error with running debug build. This isn't a critical issue, but it would be awesome to not see this error popup each time I used variables in the debreif while playing with a debug build.

**Comment by wookieejedi** [comment]
Here is a test mission using retail which shows this. 
[variable-name-error.zip](https://github.com/scp-fs2open/fs2open.github.com/files/1822748/variable-name-error.zip)

**Comment by MageKing17** [comment]
This seems to indicate that color tags are being checked before variables, which... shouldn't happen. AFAICT, `debrief_init()` handles replacing the variables, and then color tags get checked later. So something screwy is happening here, clearly; I'll see if I can figure out what.

**Comment by wookieejedi** [comment]
Just wondering if there might be any updates on this one : )

**Comment by MageKing17** [comment]
Sorry; I forgot all about this! I'll try to take a look this weekend.

**Comment by wookieejedi** [comment]
No worries, thanks!

**Comment by MageKing17** [comment]
The problem is with your mission file; the variable name is `$All-MissionCount`, so the debriefing code that replaces variables is looking for `$$All-MissionCount` and not finding it... so it tries to interpret it as a text tag, and can't find a matching one!

**Comment by wookieejedi** [comment]
Thanks for checking into this! Gothca, on my end even if I fix that name I still get the error sadly. 
[variable-name-error(2).zip](https://github.com/scp-fs2open/fs2open.github.com/files/2161455/variable-name-error.2.zip)

**Comment by MageKing17** [comment]
I get no warnings about invalid color tags with that version of the mission, and the variable is correctly replaced with the number "2"; are you sure you loaded the correct version of the mission when you tested it?

**Comment by wookieejedi** [comment]
Right you are, I just noticed that I replaced the one in my FS2 directory but not the App data one. I'm sorry for the inconvenience! Thanks for taking a look at this regardless!
