### ISSUE TITLE
Assertion Error with Incorrect # Icons-Newest Nightly 

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#1664]
If the number of icons in a briefing stage in the mission text file doesn't match the actual number of icons then the mission crashed with the newest nightlies. For example, if $num_icons: 1 and there are actually two icons then the game crashes. This doesn't happen with nightlies more then a month old it seems. Very minor bug but discussion on Discord suggested I should always report any assertions errors.  

Error displayed is the following:
ASSERTION: "bs->num_icons == icon_num" at missionparse.cpp:1564

**Comment by asarium** [comment]
Could you add a test mission (preferably with FS2 retail data) which reproduces this issue?

**Comment by wookieejedi** [comment]
Sure, here you go! Mission has 1 briefing stage with two icons. But I changed the number of icons to say 3 in a text editor to get the assertion  crash to happen. 

[num-icon_assert.zip](https://github.com/scp-fs2open/fs2open.github.com/files/1822743/num-icon_assert.zip)
