### ISSUE TITLE
Team Glows are broken (again)

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1683]
At some point between October 22 2017 and November 18 2017 (sir knightly wasn't working in between those points), team color glows stopped working.

You can easily see it with JAD2.2, go to the F3 lab, select the SD Ravana and hit T or Y to cycle through the team glows.

**Comment by asarium** [comment]
I have tracked this bug to my model uniform buffer changes.

**Comment by asarium** [comment]
I fixed the issue in the pull request shown above.
