### ISSUE TITLE
Update qtFRED README.md

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#1696]

**Comment by niffiwan** [comment]
@z64555 have you any more details of what specifically you wanted updated?

**Comment by z64555** [comment]
Ok, qtFred's README needs to mention the Golden Rule.  Although its probably common practice among qt developers,  folks used to other UI kits may be unfamiliar with it.

Brief description on CMake may be required, or a simple link to their website.

Directory map of the major subdirs within qtfred/ is needed.

Those three are what I can think of at the moment.  Basic idea is that the README should have all the information and links needed in order for a new dev to understand the organization of the build environment.

Basic Licensing info should be mentioned somewhere as well, either in the readme or as a seperate file.  It's on the project wiki, but there needs to be an "offline" copy, too.
