### ISSUE TITLE
Main editor: get mission files loading/saving

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#1697]

**Comment by asarium** [comment]
Mission loading should work completely. The mission save code seems to depend on a lot of editor functionality but I'll take a look at how important that is to get this working.

**Comment by asarium** [comment]
I copied the mission save code over to qtFRED and got it to work with pretty much no changes. I removed the campaign save code since that requires some interaction with the currently non-existent campaign editor.
