### ISSUE TITLE
If deferred lighting is disabled, nebula fogging does not work

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#1717]
See attached screenshot.  This can most easily be seen by loading up Mystery of the Trinity and looking in the direction of the debris field.

The command-line is:
C:\GOG Games\Freespace 2\fs2_open_3_8_1_AVX.exe -mod "MediaVPs_2014" -nospec -nomotiondebris
-nonormal -noheight -nolightshafts -no_deferred

Removing -no_deferred fixes the fogging.

![screen0110](https://user-images.githubusercontent.com/1878523/39391635-e4768558-4a74-11e8-8f7f-921ca3dd5c13.png)

![screen0109](https://user-images.githubusercontent.com/1878523/39391626-b458806a-4a74-11e8-945e-a6d02c8ddd86.png)

**Comment by asarium** [comment]
I'll take a look at how hard it is to fix this but at this point it might be a good idea to drop the non-deferred rendering path completely.

@SamuelCho Any comments on that?

**Comment by Goober5000** [comment]
@asarium @SamuelCho Keep the non-deferred rendering path.  Without -no_deferred, my computer slows down significantly.

**Comment by asarium** [comment]
Try lowering your lighting settings. @The-E made some improvements that should improve your performance when you lower the setting in the options menu. It's likely that the only reason the non-deferred render path is slower is because it decreases the lighting quality.
