### ISSUE TITLE
scrambled messages deforms unicode strings

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1720]
Either by sexp or by EMP, if the player has scrambled messages it will deform the unicode string. In retail, the deformed characters will just not draw, but in scripts it will bring the game to a halt.

Test Mod by Novachen below:
[ScrambledMessage.zip](https://github.com/scp-fs2open/fs2open.github.com/files/1959235/ScrambledMessage.zip)

**Comment by asarium** [comment]
I fixed the code for messages without a voice file but the code with a voice file uses absolute offsets into the text array so it is harder to convert that to our unicode API.
