### ISSUE TITLE
Directive counter occasionally goes negative

### ISSUE THREAD

**Issue by plieblang** [scp-fs2open/fs2open.github.com#1722]
The counter next to a HUD directive sometimes goes into the negatives like -997 or -996.  According to @Flip-Sandwich, this happens when all ships in the first wave of a wing are destroyed.
![directive](https://user-images.githubusercontent.com/17536531/39561630-7a62c342-4e6c-11e8-8e5e-7fd54d0818c7.png)

**Comment by asarium** [comment]
Do you have a test mission to reproduce this? That would make fixing this bug much easier.

**Comment by plieblang** [comment]
Mission for the 2014 MVPs (GitHub doesn't support fs2 files, so just change the file extension).  The bug happens in 3.8.0 as well as the latest nightly.
[DirectiveTest.txt](https://github.com/scp-fs2open/fs2open.github.com/files/1971407/DirectiveTest.txt)
