### ISSUE TITLE
Update Lua to some more recent version?

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#1728]
The Lua version in the source code is 5.1, last updated in 2012.  Native support for bitwise operators wasn't added until 5.3, so it would be nice to have that version at least.

**Comment by chief1983** [comment]
I think that's a fundamentally different version that would be a major undertaking to switch to, from what I understand.  Would probably break all existing scripts, or many of them.

**Comment by asarium** [comment]
Exactly, newer versions of Lua are not compatible with older scripts and it's also not feasible to run two different versions of Lua at the same time.

**Comment by Goober5000** [comment]
Wut?  5.2 and 5.3 are not reverse-compatible with 5.1?  If true, that's moronic.

How exactly are they not compatible?

**Comment by asarium** [comment]
All the changes between 5.1 and 5.2 are listed here: https://www.lua.org/manual/5.2/readme.html#changes

There were some changes to the libraries Lua provides which may break existing scripts. Also, if we want to support LuaJIT we need to keep using 5.1 since that is the version LuaJIt provides.

**Comment by Goober5000** [comment]
Looking over the changes and incompatibilities, I think it's highly unlikely any script would be affected by them.  However, the LuaJIT is a much more serious obstacle.

I guess this can be deferred until LuaJIT supports 5.3.

**Comment by EatThePath** [comment]
I have misgivings about updating being safe, but that aside, luajit does not seem to intend ever introducing compatibility with other versions. See https://github.com/LuaJIT/LuaJIT/issues/929 for instance. IMO this could be considered a closed issue unless the situation seriously changes in the future.

**Comment by Goober5000** [comment]
Yeah, that seems pretty conclusive.

**Comment by Goober5000** [comment]
'Wontfix' label added for ease of searching in the future.
