### ISSUE TITLE
Directional light adjustment doesn't work with deferred lighting.(spec_static does nothing)

### ISSUE THREAD

**Issue by FrikgFeek** [scp-fs2open/fs2open.github.com#1734]
Lighting from suns seems to only apply to cockpits(black in the shine map) but either don't apply or don't make a visible difference to the rest of it. 

This started with the February 27 nightly.

I tested both in-mission and in the lab but they should be using the same renderer anyway.

This is most likely caused by directional lights using the deferred renderer since this https://github.com/scp-fs2open/fs2open.github.com/commit/0d188fe076683f6568b60086f94f7fae5a8d23eb commit.
The current directional light code doesn't have a static_light_factor so spec_static can't affect it. 

With older models this isn't as much of a problem but with PBR ones most of their lighting comes from directional lighting rather than ambient so there's no way to adjust their look.

**Comment by asarium** [comment]
This has been fixed.
