### ISSUE TITLE
Collection of Strings that should, but are not translateable yet

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#1738]
During the Test of #1736, i encountered a string, that still can not be translated.

So i looked through the code and collected some strings that are used in the game, but are not translateable, because they are missing a XSTR in general for the strings.tbl or have an ID of -1.
Of course this collection does not includes strings, which were commented out.
For a complete translateable game i think it would be helpful, that these strings could be translated as well due to the strings.tbl.

barracks.cpp - Line 436
`STRCPY1(Stat_labels[Num_stat_lines], "Current Score:");`

This text is displayed in the barracks screen in the Pilot info.

hudtargetbox.cpp - Line 1037
`sprintf(outstr, NOX("impact: %.1f sec"), dist/speed);`

This text is displayed if you target a bomb. It shows how long it takes to reach its target.

aigoals.cpp - Lines 127 to 128
`	case AI_GOAL_FLY_TO_SHIP:
		return XSTR( "rendezvous with ", -1);`
This one is used in the target box as well. When a AI ship uses a Autopilot this text appears. Or at least that is, what i know about it. I never encoutered it myself, because i never played WCS, which is the most prominent mod for this feature ^^.

hud/hud.cpp - Line 2898
`sprintf(outstr, "Waiting...");`

This one appears after the Support ship has docked with the player ship, but not have started the rearming procedure.

keycontrol.cpp - Line 1070
`HUD_sourced_printf(HUD_SOURCE_HIDDEN, XSTR("Issuing rearm request for %s", -1), Ships[obj_to_rearm->instance].ship_name);`

If i remember it correctly, that text is part of a SCP exclusive cheat, where you can force the Support ship to rearm/repair a specific ship. So it is a System message that appear if you use this cheat.

keycontrol.cpp - Line 1075
`HUD_sourced_printf(HUD_SOURCE_HIDDEN, XSTR("Cannot issue rearm request for %s", -1), Ships[obj_to_rearm->instance].ship_name);`

The same, only that this is the message that appears, if it does not work for the targeted object.

multiui.cpp - Lines 4976 to 4979
`								XSTR("A time limit is being used in a co-op game.\r\n"
									"  Select \'Cancel\' to go back to the mission select screen.\r\n"
									"  Select \'Yes\' to continue with this time limit.\r\n"
									"  Select \'No\' to continue without this time limit.", -1));`

This message appears, if you try to start a multiplayer coop mission with a time limit.

multiui.cpp - Lines 4991 to 4994
`								XSTR("A kill limit is being used in a co-op game.\r\n"
									"  Select \'Cancel\' to go back to the mission select screen.\r\n"
									"  Select \'Yes\' to continue with this kill limit.\r\n"
									"  Select \'No\' to continue without this kill limit.", -1));`

This message appears, if you try to start a multiplayer coop mission with a kill limit instead.

controlsconfigcommon.cpp
No lines here, because actually the translation of the bindable functions seems to be handled differently.
But well, the following functions appear only in english in the game and so can not be translated into other languages:

- Glide when pressed
- Toggle Gliding
- Cycle Primary Weapon Firing Rate
- Top-Down View
- Target Padlock View
- Toggle Auto Pilot
- Cycle Nav Points

Also there is a "Energy" String in the Ballistic Weapon Gauge, that should also be translateable.
Actually i am not sure in which file this one is.

Within the limit to 1637 (which is the highest currently) there are also some unused ids, which can be used for some of the abovementioned.
1603
1611
1616
1621

Also there are some duplicates in SCP features, so ids which have the same text, but with different ids. But because of compatibility reasons to translations that were created in the past (and because the strings.tbl is nearly unchanged since retail they could still work), i do not think, that a clean up of them is very useful. It is not a big issue anyway.

**Comment by Goober5000** [comment]
Is this all done?  If so, it should be closed.

**Comment by NovachenFS2** [comment]
Except for the translation of the control functions which are handled differently i included all translateable strings with #1795.
