### ISSUE TITLE
Small Localized Variable Problems

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#1739]
Because of the Discussion in #1730 i tested a bit with the Translated Variables and found some small problems during this.

In the modify-variable-xstr SEXP the default text is being used in the english language setting, even if the text in the tstrings.tbl under #default is different. This is different to the behavior the rest of the game has, because it prioritize the tstrings.tbl over every text in the tables and missions, most likely to be able to fix spelling errors for example without to change the mission and table files. So the default text from the SEXP should only be used if the ID is invalid or not given at all.

If a string have to be end with a space, because this string will be later concaternate with an Integer where the space is the seperator between them, the Space does not seem to be carried over.
In the translated version the concaternate Variable appears together without a seperator between.

[LocalVAR.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2068764/LocalVAR.zip)
This is a small mod for that, which is based of a scenario from the first BtA: Mefistofele mission, where i encountered this problem.
In this mod, the text in #default of the tlc.tbm is different to the text in the modify-variable-xstr SEXP of the test mission.
And there is a german translated version of the variables as well.

Interestingly, one of the two concaternates variables shows the right behavior here even in the translated version. No idea why this is, because the second entry does not work as it should.

In the testing LocalVAR mission, you have to scan the Poseidon to show its Communication and Jump Drive Energy (which is static here). So there are two Variables, which were connected from a string and number variable.

**Comment by asarium** [comment]
I found the issue and fixed it: #1743

The problem was that FSO intentionally drops white space at the end of strings when reading them from tstrings.tbl. Since FSO always uses the default text if the default language is used this does not happen when using English as the language.

>In the modify-variable-xstr SEXP the default text is being used in the english language setting, even if the text in the tstrings.tbl under #default is different. This is different to the behavior the rest of the game has, because it prioritize the tstrings.tbl over every text in the tables and missions, most likely to be able to fix spelling errors for example without to change the mission and table files. So the default text from the SEXP should only be used if the ID is invalid or not given at all.

FSO always uses the default text if the default language is used. In that case the entry from tstring.tbl is not used. SEXP variables are not a special case here so I don't know why you are seeing different behavior in that case. Here is the relevant code:

https://github.com/scp-fs2open/fs2open.github.com/blob/b848823a2fbde9b913ba87fe97c9950751d34213/code/localization/localize.cpp#L823-L824

**Comment by NovachenFS2** [comment]
Oh really? My bad.

Actually i was sure, that the tstrings is prioritized. It would had made sense for me, because you would be able to correct spelling errors for all languages in the same file. But okay, then i was mistaken and i do not know, why i had the impression why the tstrings is prioritized.
Sorry for that mistake then.

**Comment by asarium** [comment]
If you have a case where the tstrings value is prioritized please let me know so that I can make the behavior consistent. I am not saying that there can be no bugs in the code but only that the default text is usually prioritized.

**Comment by NovachenFS2** [comment]
If i find one, i will make an issue for that ;). Maybe i simply mixed up something. I was underway in the tstrings.tbl for so long in the last couple of years, maybe i starting to see ghosts.
