### ISSUE TITLE
"Assert: "model_instance_num < (int)Polygon_model_instances.size()" File: modelread.cpp Line: 3191" In tech lab.

### ISSUE THREAD

**Issue by FrikgFeek** [scp-fs2open/fs2open.github.com#1745]
I've been consistently hitting this assert by trying to load any model in the tech lab after flying a mission. Happens for retail, MVPs, and mods.

Repro steps:

Load any non-nebula mission.
Kill 2-3 ships or just watch them die. ~+K or just load King's Gambit on insane where the Mjolnirs will just autokill everything.
Load any model in the tech lab. If this doesn't hit it load a few more.

Log with this specific Assert(hit with retail data):
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/2073209/fs2_open.log)

Log with similar Assert but different wording(hit in Inferno):
[fs2_open(model id).log](https://github.com/scp-fs2open/fs2open.github.com/files/2073210/fs2_open.model.id.log)

**Comment by tomimaki** [comment]
#1659 should fix this.

**Comment by z64555** [comment]
@FrikgFeek Did #1659 fix this issue?

**Comment by Goober5000** [comment]
Confirmed fixed by @FrikgFeek
