### ISSUE TITLE
Slowdown in the 'Misc' Controls Menu with Unicode characters

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#1754]
Never saw this before, because i simple clone my pilots, so that i never have to change my controls.

But now i got into the menu by accident and experienced a massive slowdown in the said menu. My FPS went so downhill where i was not even able to press the buttons to bind a control or to scroll down by the arrow graphic properly.

I do not have this problem with the english default language (due to the lack of unicode characters i think) aswell i do not have the problem with deactivated unicode mode.

To reproduce this: Start FreeSpace2 with the attached mod (actually it is the normal Unicode Test mod) in the german language setting. Go into options -> "Steuerung konfigurieren" and then "Andere".

I experienced this on two different computers (Laptop and my normal PC), so it does not seem to be a problem in my Windows10 x64. I used the last released nightly for this.

[unicodeTest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2087353/unicodeTest.zip)

**Comment by asarium** [comment]
When I follow your steps I encounter a failed assertion so something is definitely going wrong. The translated keycodes appear to still use the old special character encoding and they are hard-coded into the engine so you can't even change them through tstrings.tbl.

I'll take a look at how this could be fixed since it would be nice to have proper support for translating key codes into other languages apart from the built-in ones.

**Comment by NovachenFS2** [comment]
Ah yes, if i use a debug build it crash right away. Never tested that.

With a normal build i have the slowdown instead. Except for the controls i mentioned in #1738 all of them can be changed through the strings.tbl however.

**Comment by asarium** [comment]
I wasn't talking about the controls but about the key names, e.g. "Spacebar" or "Leertaste". The engine has a few big arrays where those names are hard-coded without any possibility of translating the name. Those arrays always bothered me anyway so I'll try to find a solution for adding proper translation support for them.

**Comment by asarium** [comment]
Just to keep this updated, the issue appears to be that NanoVG updates the the font atlas texture for every rendered string for some reason. That is the cause for the observed slowdown but I couldn't find the reason why NanoVG does the updates yet.

**Comment by asarium** [comment]
I found the issue and fixed it in the PR above.
