### ISSUE TITLE
The "cap-waypoint-speed" SEXP does not respect 0

### ISSUE THREAD

**Issue by plieblang** [scp-fs2open/fs2open.github.com#1758]
Giving "cap-waypoint-speed" an argument of 0 does nothing.  The ship's speed is not limited at all.
I've attached a test mission, but the only steps necessary to reproduce are to cap a ship's waypoint speed at 0 and then give it an order to fly to a waypoint.
[cap_waypoint_speed_test.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2124696/cap_waypoint_speed_test.txt)

**Comment by Goober5000** [comment]
This is by design.  The AI code only processes the speed cap if it is above 0.  Otherwise you'd get divide-by-zero errors and so forth.

Why would you want to cap the speed to 0?  Just remove orders or tell the ship to play dead.

**Comment by plieblang** [comment]
I wanted to use it to get a ship to rotate to face another ship without moving and at its tabled rotation speed.  I know there's ship-maneuver, but that's really not feasible if you don't know the ship's heading in advance.  I suppose you could do some calculations based on heading, but that's still a lot more complicated.
Since this is by design, could the documentation (ie the SEXP dump file) be changed to mention this?

**Comment by Goober5000** [comment]
Have you tried `set-object-facing-object`?

I'll open a new PR to change the SEXP documentation; that's a good idea.

**Comment by plieblang** [comment]
IIRC, set-object-facing-object flips the ship instantly if given no time argument.  Calculating the correct time has the same problem as `ship-maneuver`.
I'll probably use `cap-waypoint-speed` with 1 and then use `is-facing` to clear the ai goal.
