### ISSUE TITLE
FRED fails to launch FSO if the exe files aren't in the working directory

### ISSUE THREAD

**Issue by ngld** [scp-fs2open/fs2open.github.com#1775]
Usually (i.e. before Knossos) both FSO and FRED would be in the FS2 root directory which would also be the working directory. However, due to the way Knossos works, this is no longer the case. The root directory still is the current working directory but the exe files are stored elsewhere.

The relevant function for FRED2 is [`CFREDView::OnRunFreeSpace`](https://github.com/scp-fs2open/fs2open.github.com/blob/e8ef727a199f00b44b0fe186e498bf5bbb823897/fred2/fredview.cpp#L3768) which apparently hasn't been ported over to qtFRED, yet.

The function is called when a user clicks on File > Run FreeSpace in FRED. It takes the name of the current executable and replaces `fred2_open` with `fs2_open` and tries to launch the exe with the resulting name. To make this work with Knossos, FRED would have to identify the folder containing its exe file is and use that to build the correct path to FSO's exe.

**Comment by wookieejedi** [comment]
This can be closed now that #2192 is merged.
