### ISSUE TITLE
Inserting a semicolon into FRED's designer notes invalidates the mission

### ISSUE THREAD

**Issue by plieblang** [scp-fs2open/fs2open.github.com#1802]
If there is a semicolon in the mission notes and no following newline, FRED is unable to load the mission.  From what I can tell, this is because `$End Notes:` is parsed as part of a comment and thus is ignored, making the mission file invalid.
To reproduce, add a line containing a semicolon to the designer notes section and make sure there is no following line (this includes blank lines).

**Comment by asarium** [comment]
Thanks to @plieblang, this should be fixed by #1803.
