### ISSUE TITLE
Restart mission fails

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#1815]
Current source.
Issue doesn't occur on build 23 July 2018.

**Comment by asarium** [comment]
To be honest, that issue description is not very useful. It doesn't say anything about with what mod or campaign this occurs (maybe only a specific mod or all mods) or what steps need to be taken to reproduce this issue.

Fortunately, I could still reproduce the issue and I'll take a look at it.

**Comment by tomimaki** [comment]
I thought if I don't write what mod then it means that doesn't matter. ;) I checked Dawn of Sol then retail data.
