### ISSUE TITLE
MVE cutscenes no longer work with the 8/11 nightly

### ISSUE THREAD

**Issue by plieblang** [scp-fs2open/fs2open.github.com#1828]
When in MVE format, the opening FS2 cutscene plays neither on launching the game nor from the techroom.
This may be due to the movie looping feature introduced in that nightly.
https://fsnebula.org/log/5b736ebdcb0d3351ec39ca39

**Comment by asarium** [comment]
This does look like it is being caused by seeking inside the file which was added by the looping code. I'll take a look at it.
