### ISSUE TITLE
Ignorable multiplayer campaigns

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#1838]
Well, i thought that was also fixed with #1666, but it was not.

The #Ignored Campaign File Names does not apply for Multiplayer Campaigns.
They are still appearing next to its missions in the multiplayer menus.

**Comment by Goober5000** [comment]
AFAIK there's no intrinsic reason why multiplayer campaigns can't be ignored; it's just a matter of putting the right code in the right place.  Pinging @Karajorma as he was the one who originally added this feature.

**Comment by Karajorma** [comment]
Yeah, there's no reason for it to ignore MP campaigns. I can't look at the code to see why it does at the moment.

**Comment by Goober5000** [comment]
It's simply because the single-player campaign list and the multiplayer campaign list are generated in two different functions.  I'll add the code to make it work; the only reason I didn't do so at first was because I didn't know if it was intentional.
