### ISSUE TITLE
set-object-position for waypoints is broken in multi

### ISSUE THREAD

**Issue by ngld** [scp-fs2open/fs2open.github.com#1840]
`multi_sexp_set_object_position` and `sexp_set_object_position` use the waypoint's `net_signature` to identify the waypoint in network packets. This doesn't work since the `net_signature` is never set.
`multi_sexp_set_object_position` uses `multi_get_network_object` to retrieve the waypoint on the client. That function returns `nullptr` due to the invalid `net_signature` which causes an access violation and crashes FSO.

To fix this, both functions should be updated to use a different way to identify waypoints (the waypoint's name and `find_matching_waypoint` sounds like a good idea) or initializing `net_signature` in `waypoint_create_game_object`.

**Comment by FSCyborg** [comment]
After finding a bug with net_signature assignment, and the fact that it is a system that is independent on clients and servers.  We should use find_matching_waypoint.

**Comment by Goober5000** [comment]
Er, the very purpose of `net_signature` is to have an unambiguous way to reference the same object on clients and servers.  If I'm not mistaken, ships, weapons, and asteroids all use it.  Waypoints should too.

**Comment by FSCyborg** [comment]
This is how I see it so far. If net_signature were set by just the server, sure, but since it's set independently by server and host, they both have to have the same exact method for setting them, or you will start getting info from the server getting incorrectly applied to things on the client.  Adding it to net_signature would more than likely require a bump in the multiplayer version.

**Comment by Goober5000** [comment]
How is `net_signature` set for ships and weapons?

**Comment by JohnAFernandez** [comment]
For ships it is set on creation because ship creation will happen the same during parse, or will be created through a packet from the server using ship create.  Weapons are created using the signature from the server.

**Comment by JohnAFernandez** [comment]
But since we were working on a multi bump anyway, I added waypoints to the net signature list and just have to set up how it gets those signatures.

**Comment by JohnAFernandez** [comment]
And here's the pull request #2752

**Comment by JohnAFernandez** [comment]
OK.  Forgot to close this.  Waypoints now have net signatures.  If any further issues come up feel free to reopen and ping me.
