### ISSUE TITLE
Specular maps aren't being applied correctly.

### ISSUE THREAD

**Issue by FrikgFeek** [scp-fs2open/fs2open.github.com#1843]
There seems to be an issue with how spec maps are applied. With certain assets there seems to be some crossover with other maps or some problem which causes very ugly purple and green artifacting.

This is especially noticeable when directly facing lights because of how gloss is applied.

Some examples with MediaVPs assets:

https://cdn.discordapp.com/attachments/480764424035106826/484436541205250059/screen0171.png

high -spec_static produces very obvious artifacting

https://cdn.discordapp.com/attachments/480764424035106826/484437257781248002/screen0006.png

The Arcadia looks discoloured with the spec map applied compared to no spec. You can also see the artifacting even though it's not as exaggerated.

https://cdn.discordapp.com/attachments/480764424035106826/484437303033462784/screen0007.png

**Comment by chief1983** [comment]
I had always thought that the artifacting was due to DDS compression artifacts.  Unless that's a separate problem that also looks similar.

**Comment by The-E** [comment]
Looking at it, it seemed to me that the spec color not being colorspace-correct exaggerated DDS artefacting in the texture.

With the patch referenced above applied, this is the result:
https://media.discordapp.net/attachments/480764424035106826/484440415077138432/screen0008.png (without specmap)
https://media.discordapp.net/attachments/480764424035106826/484440548036313115/screen0009.png (with specmap)
