### ISSUE TITLE
Model Point Shields hit by blast damage disappear.

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#1847]
Reported by Spoon
Whenever a ship with active model point shields is hit by any form of blast damage, the shields disappear. Additionally, this only occurs with the players ship.

**Comment by TRBlount** [comment]
This was determined ti be caused by a script. Closing.

**Comment by Kingspoon** [comment]
This issue turned out to be a bug with the shield equalize script that was conflicting with the model point shield code, and not with the model shield code itself. This issue can be closed.
