### ISSUE TITLE
game_settings.tbl proposal: $Disable Dual Secondary Fire

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#1851]
This proposal would involve a new flag to game_settings.tbl that would disable the dual secondary linking feature in retail FreeSpace 2, to enable mod authors both to break with established FS convention in yet another way, and to balance missiles around the assumption that they can only be fired singly rather than in pairs (fewer missiles, higher damage).

**Comment by NovachenFS2** [comment]
I actually think, that such feature would make more sense as a weapons.tbl flag... because there is one for Primary Weapons already?

**Comment by EatThePath** [comment]
I could definitely use this. It's a good knob to let mods be more distinct from one another or make missiles more distinct within a mod, and will be even moreso when multi-lock is mainline

**Comment by FSCyborg** [comment]
Officially claiming this one. Just realized my last enhancement is not in because I missed that asarium requested more changes... >.>

**Comment by MageKing17** [comment]
Implemented in #2347.
