### ISSUE TITLE
ship-invisible SEXP turns off Auto Target

### ISSUE THREAD

**Issue by AdmiralNelsonFSO** [scp-fs2open/fs2open.github.com#1855]
When the ship-invisible SEXP is applied to a ship auto target is switched off.  The effects of this SEXP should be confined to the ship to which it has been applied and not to the player's HUD settings.  See [https://youtu.be/zx4FbNco4zQ](url) for a video. Per m|m "hud_cease_targeting unsets the flag for auto targetting." and "I have no idea why that SEXP doesn't just use the simpler set_target_objnum..."

**Comment by Goober5000** [comment]
Agreed.  This sounds like a Volition mistake -- reminds me of the mistake in the `targeted` sexp.
