### ISSUE TITLE
Docking Bug with Warp-In

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#1867]
It appears that a docked ship appears both visually and on the radar about a second before the ship it is docked to appears, but this only happens if the large ship is using a warp-in effect. If the the box "No Warp Effect" is checked in FRED then both ships arrive exactly at the same time as expected. Thus, it seems the warp-in animation is delaying the actual arrival of the large ship, but not the smaller ship it is docked with. I have attached a sample mission which shows this. 

This lag effect is especially apparent on ships that have $Warpin Type: Hyperspace, because
 in that case the docked ship appears, disappears, then appears again as it warps in. 

[_Dock_Test.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2402732/_Dock_Test.txt)

**Comment by wookieejedi** [comment]
From section of shipfx_warpin_start() in shipfx.cpp: 

        // docked ships who are not dock leaders don't use the warp effect code
	// (the dock leader takes care of the whole group)
	if (object_is_docked(objp) && !(shipp->flags[Ship::Ship_Flags::Dock_leader]))
	{
		return;
	}

So it looks like the dock leader is not being set correctly, or the dock leader is not properly taking care of the whole group? Mainly documenting this so I remember.

**Comment by Goober5000** [comment]
> So it looks like the dock leader is not being set correctly, or the dock leader is not properly taking care of the whole group?

The second of these.  If the dock leader wasn't being set correctly, a lot more things would be going wrong.

**Comment by wookieejedi** [comment]
Ah good to know. Still strange that even with only one ship the bug still occurs...

**Comment by Goober5000** [comment]
Can you test previous builds and see if this is a recent bug or has been around for a while?

**Comment by wookieejedi** [comment]
Sure, will let you know what I find!

**Comment by Goober5000** [comment]
By visually, do you mean you can see it, or just that you can target it?

I think this is just due to things being visible in stage 1 when they should only be visible in stage 2.

**Comment by wookieejedi** [comment]
I can visually see it and target it. The ship/dockees will show up for about two seconds, then disappear as stage two warpin commences. I think you are right.

**Comment by Goober5000** [comment]
Now that #1932 has been merged, can you test this on the next nightly build?

**Comment by wookieejedi** [comment]
Indeed! I tested it on the most recent nightly (Dec 8th) and unfortunately the bug still exists, so it must be related to something else?

**Comment by Goober5000** [comment]
It must be. :-/

Have you been able to test some previous builds?

**Comment by wookieejedi** [comment]
Yep! I have tested as far back as February 03 2017 and the bug is still present, so I will keep testing older builds.

**Comment by wookieejedi** [comment]
As far as I can tell this bug has been present since the Hyperspace effect was first added unfortunately.

**Comment by niffiwan** [comment]
this is causing some issues for FotG, I'll see if I can figure out what's going on...

**Comment by niffiwan** [comment]
@Goober5000 Is there a simple way to find out who a docked-ship's dock-leader is once "in-mission"? e.g. [when setting up radar blips for display](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/radar/radarsetup.cpp#L89)? I've found code in [missionparse](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/mission/missionparse.cpp#L6429) but that relies on parse-objects...

**Comment by Goober5000** [comment]
Yes, check the `Ship::Ship_Flags::Dock_leader` flag.  See for example `shipfx_warpin_start`.

**Comment by niffiwan** [comment]
That's great when you're operating on the dock leader; but I was thinking of the case where Triton1 is the dock leader, Gamma1 is docked to Triton1, we're operating on Gamma1 and we'd like to know that Triton1 is the dock leader.

**Comment by Goober5000** [comment]
In that case you would need to create a new function which is passed to `dock_evaluate_all_docked_objects` and finds out which one of them has the `Dock_leader` flag set.

**Comment by niffiwan** [comment]
[issue1867-testcase.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2897385/issue1867-testcase.zip)

For reference; testcase used for this issue (note; mod was used with mediavps)

**Comment by Goober5000** [comment]
Fixed by #1991
