### ISSUE TITLE
Can't exit application if error is thrown

### ISSUE THREAD

**Issue by Artyrm** [scp-fs2open/fs2open.github.com#1886]
Recent nighties do this as well. 
For example if such error is thrown it is useless to press "Exit", it has no effect (maybe error cycles again to this window).

![2018-09-30 11 30 36](https://user-images.githubusercontent.com/21180686/46255580-4752ee80-c4a7-11e8-9ed6-bba3acfd0d18.png)

**Comment by Artyrm** [comment]
Now I know two thing: this is specific to this exact error (with others I managed to press Exit or Debug). And it is somehow connected to Window focus, since:
  1) Pressing on any part of this little window brings it to background, so you need to Alt-Tab it again to see.
  2) I ran the game in windowed mode with resolution less than the screen, and this time I was able to press buttons on this window.

**Comment by tomimaki** [comment]
_being unable to press Debug, Continue, or Exit if I happen to accidentally run FSO in a non-windowed mode._ 

Issue started since upgrading SDL from 2.0.5 to 2.0.7 #1569
More precisely SDL 2.0.6 and later are problematic.

**Comment by Artyrm** [comment]
I believe first thing to try is to find out what is the difference between windows we can click on an windows we can't.

**Comment by FSCyborg** [comment]
Upgrading did fix the immediate issue.  But it will need general testing to see if the new version breaks anything else.
