### ISSUE TITLE
TrueType fonts don't display in Release builds while appearing in Debug builds when Unicode Mode is enabled

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#1901]
[UnicodeModeBugTest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2484589/UnicodeModeBugTest.zip)
Since the implementation of Unicode Mode, TrueType fonts aren't displayed completely in Release builds while appearing in Debug builds.

**Comment by Artyrm** [comment]
I don't think so.

![2018-10-16 22 13 26](https://user-images.githubusercontent.com/21180686/47041191-d2630280-d190-11e8-8bdb-db33f1d012cf.png)

**Comment by bryansee** [comment]
> 
> 
> I don't think so.
> 
> ![2018-10-16 22 13 26](https://user-images.githubusercontent.com/21180686/47041191-d2630280-d190-11e8-8bdb-db33f1d012cf.png)

But I tested out both Debug and Release and the difference is striking.
![truetype fonts in debug](https://user-images.githubusercontent.com/2004725/47041445-5d58f280-d1bb-11e8-94d0-8cf54dba3ac8.png)
![truetype fonts in release](https://user-images.githubusercontent.com/2004725/47041446-5d58f280-d1bb-11e8-9e06-30f0dc527356.png)

**Comment by bryansee** [comment]
> 
> 
> You may tested something wrong. My experience (and screenshot provided) shows that the statement in your issue is overgeneralized.

Then how did you get it?

**Comment by Artyrm** [comment]
I did nothing special. Did everything like in BtA for example.

**Comment by bryansee** [comment]
> 
> 
> I did nothing special. Did everything like in BtA for example.

How?

**Comment by Artyrm** [comment]
Like that.

[rus_mod.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2484653/rus_mod.zip)

**Comment by bryansee** [comment]
> 
> 
> Like that.
> 
> [rus_mod.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2484653/rus_mod.zip)

Still the same.

I bet Asarium will look into this.

![debug](https://user-images.githubusercontent.com/2004725/47044397-aeb8b000-d1c2-11e8-9478-d7cd27a7b89f.png)
Debug
![release](https://user-images.githubusercontent.com/2004725/47044398-aeb8b000-d1c2-11e8-8a83-28112c4b6c5f.png)
Release

**Comment by Artyrm** [comment]
Is it your build or some nightly?

**Comment by bryansee** [comment]
I'm using a latest nightly build.

**Comment by Artyrm** [comment]
I do the same, strange enough. Well, lets hope Asarium will figure out, indeed.

**Comment by bryansee** [comment]
> 
> 
> I do the same, strange enough. Well, lets hope Asarium will figure out, indeed.

Me too. And others will hope he does.

**Comment by bryansee** [comment]
> 
> 
> I'll try this when I have some time.

Make it so when you have some time.

**Comment by Artyrm** [comment]
I have report that my mod works as intended for other users. What setup do you have? Is it Windows PC? I'm trying to figure out differences you and me have.

**Comment by NovachenFS2** [comment]
I actually does not have problems with unicode either.

But maybe that has something to do with hooking problems i have encountered with another programs. If i am using DxTory (Recording/FPS display program) the game crashes with release builds right away, except if i tell the program to delay the hooking for at least one second.
Debug builds are working fine right away and does not need this "workaround".

If i am using Trillian (a multi-protocol IM) i can not use it's in game chat overlay, because it is not displayed as well no of the ships is rendered in the game with it, but that also happen in debug builds.

So only some input to approach this problem maybe from another direction. No idea if this has something to do with it, but well.

**Comment by bryansee** [comment]
Artyrm, I am using a Windows 10 PC.

**Comment by Artyrm** [comment]
@NovachenFS2 IDK if it is related. But with overlay problems you could try the game with -Window flag.

@bryansee That's at least one difference - I'm on WIn7. What videocard? Do you use any OpenGl hooks?

**Comment by Artyrm** [comment]
And I just thought. Can you try my mod with "Russian" set as a language in FSO .ini?

**Comment by bryansee** [comment]
> 
> 
> And I just thought. Can you try my mod with "Russian" set as a language in FSO .ini?

It makes no difference, still.

![rus release](https://user-images.githubusercontent.com/2004725/47160521-b7c09300-d322-11e8-8448-e20d88a1a11f.png)
![rus debug](https://user-images.githubusercontent.com/2004725/47160523-b7c09300-d322-11e8-8f74-c9ec6903a5b5.png)

I am using ATI Radeon 5670. I use OpenGL.

**Comment by Artyrm** [comment]
Here is what's strange. Apparently those writings should be in Russian, since they appear at all. That could mean that mod hasn't become active as it should. Could upload a log for this?

I heard that ATI cards could act strange with FSO Engine. Personally, I have Radeon Mobile HD 5000 that shows corrupted meshes in target view. But that may be the next thing, once we understand what happens with mods.

**Comment by bryansee** [comment]
Here's the log file.

[fs2_open_log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2492910/fs2_open_log.txt)

I know it's strange. It's up to asarium to find out what's the cause of this and solve it as soon as possible.

**Comment by bryansee** [comment]
Here's the FSO ini file.
[fs2_open_ini.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2492973/fs2_open_ini.txt)

**Comment by Artyrm** [comment]
Can you place Language settings the last in the [Default] section and before [Sound] (I have it more like that) and see if it does something?

**Comment by bryansee** [comment]
Yes.

However, I got the same result. Here are the files.
[fs2_open_log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2493179/fs2_open_log.txt)
[fs2_open_ini.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2493180/fs2_open_ini.txt)

I think it's the full-screen mode.

**Comment by Artyrm** [comment]
Ok, so the language is still not working. I'm now uploading my mod to Knossos to try it on my ATI machine. And also I can grant you access to test it with full dependencies (I based it on MediaVps 3.8.2).
BTW maybe to upload logs via Knossos will be easier (It can be done via options of the mod you're running).

**Comment by Artyrm** [comment]
Yep, I got it. All letters are gone. I tried to switch to Russian but FSO refused to run at all, so I'm rebooting now.

Anyways now my main version is ATI Video. Maybe you can try to run on internal video ore something?

**Comment by asarium** [comment]
It appears that this is specific to the AMD HD 5000 GPU series. Since I do not have such a GPU any more I cannot help with this issue.

**Comment by Artyrm** [comment]
@bryansee I maybe could return to it sometime later, since for now I have no debug environment on that laptop with ATI. Meanwhile  you can try to find more ATI users, so we can join forces on that.

**Comment by bryansee** [comment]
> 
> 
> @bryansee I maybe could return to it sometime later, since for now I have no debug environment on that laptop with ATI. Meanwhile you can try to find more ATI users, so we can join forces on that.

Me too.

**Comment by Artyrm** [comment]
So, we have some OpenGL issue. Feature that works in Debug, but do not work in Release. So I searched with the following regex throughout the code: #ifndef NDEBUG[\S\s]*OpenGL[\S\s]*#endif
The differences in those places should be investigated first:

```
  G:\Games\Freespace\Source\fs2open.github.com.git\code\graphics\opengl\gropengl.cpp(184):#ifndef NDEBUG
  G:\Games\Freespace\Source\fs2open.github.com.git\code\graphics\opengl\gropengl.cpp(1009):#ifndef NDEBUG
  G:\Games\Freespace\Source\fs2open.github.com.git\code\graphics\opengl\gropengl.cpp(1205):#ifndef NDEBUG
  G:\Games\Freespace\Source\fs2open.github.com.git\code\graphics\opengl\gropengl.cpp(1415):#ifndef NDEBUG
  G:\Games\Freespace\Source\fs2open.github.com.git\code\graphics\opengl\gropengltexture.cpp(930):#ifndef NDEBUG
  G:\Games\Freespace\Source\fs2open.github.com.git\code\graphics\opengl\gropengl.h(46):#ifndef NDEBUG
```

**Comment by bryansee** [comment]
I tested that mod on my laptop. Same, but this time, the Debug build displayed no TrueType fonts at all. I'm using ATI Radeon R6 (AMD A10-8700P) graphics.

FS2 Open Log
[fs2_open_log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2501338/fs2_open_log.txt)
Debug
![debug ati mobility](https://user-images.githubusercontent.com/2004725/47292794-b2bd5580-d63a-11e8-90fd-cb9d4648f63f.png)
Release
![release ati mobility](https://user-images.githubusercontent.com/2004725/47292795-b2bd5580-d63a-11e8-88ad-5905ae8856a2.png)

**Comment by Artyrm** [comment]
Oh, well, it getting worse. But we're lucky that first time it was different in Debug. We could use this difference to find the reason.

**Comment by bryansee** [comment]
> 
> 
> Oh, well, it getting worse. But we're lucky that first time it was different in Debug. We could use this difference to find the reason.

It's not just on AMD HD 5000. But also graphic cards such as AMD Radeon R6. I hope asarium take notice of this.

**Comment by ngld** [comment]
This bug only seems to appear on AMD Radeons... Maybe it's a driver bug?
Anyway, here are two more people with the same issue:

https://www.hard-light.net/forums/index.php?topic=95196.msg1875560#msg1875560
https://www.hard-light.net/forums/index.php?topic=95196.msg1876020#msg1876020

**Comment by Artyrm** [comment]
You can recommend them to run Debug as a workaround for now.

**Comment by bryansee** [comment]
> 
> 
> This bug only seems to appear on AMD Radeons... Maybe it's a driver bug?
> Anyway, here are two more people with the same issue:
> 
> https://www.hard-light.net/forums/index.php?topic=95196.msg1875560#msg1875560
> https://www.hard-light.net/forums/index.php?topic=95196.msg1876020#msg1876020

This shows I and Artyrm aren't the only ones. It may be, or it may not. As the latter pointed out, Debug is the only workaround for now.

It may be something to do with the code itself.

**Comment by bryansee** [comment]
Can this be related to [models not being displayed](https://github.com/scp-fs2open/fs2open.github.com/issues/1941)?
