### ISSUE TITLE
Ships not following orders to depart to bay if flag "no-subspace-drive" is set.

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#1904]
If I set the flag "no-subspace-drive" and the departure to docking bay then I can't tell the ship to depart (via docking bay). The ship will still follow it's departure cues to depart via the docking bay but the player cannot tell it to depart to the docking bay because the order is grayed out. Example mission is attached. 

[NoDockTest.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2493100/NoDockTest.txt)

**Comment by Artyrm** [comment]
I'll leave it here for now. That roughly how I understand the intended State Machine. Maybe I'll have some time to implement it the right way.

![depart](https://user-images.githubusercontent.com/21180686/47518158-d1b62480-d892-11e8-94f6-6dcc51aaa3fd.png)

**Comment by wookieejedi** [comment]
This seems to be fixed now, so I'm going to close this.
