### ISSUE TITLE
Mission mood not working when more than one persona is defined.

### ISSUE THREAD

**Issue by Kingspoon** [scp-fs2open/fs2open.github.com#1925]
#Message Frequencies and #Moods only work when a single personas is set, oddly enough. When any other personas is added to messages.tbl they stop working.

Provided is a retail test case that illustrates the issue.
The test mission has only one event, which is set-mission-mood to Simulator. Which is suppose to exclude messages like Praise from the Generic persona. 

Using the provided messages.tbl with two personas, shooting the basilisks in quick succession results in the wingmen praising you, despite this being _strictly forbidden._ Stop praising the player, damn you.

Also included is messages1.tbl which has only the Generic persona defined. When this messages.tbl is used, no praising occures, the mood is respected. And they only praise again if you set the set-mood event to false. Ergo, mission mood clearly works... just with only one persona.

[messages.tbl.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2558302/messages.tbl.zip)

**Comment by MageKing17** [comment]
In messages.tbl, "$Allow substitution of missing messages:" is only set to False for the Kunoichi persona. Since Generic is not forbidden from using a substitute if it can't find a matching message, it goes for the closest match: the message excluded due to mood restrictions.

**Comment by Kingspoon** [comment]
It did not occur to me that this was a persona specific flag. I thought it was a global flag that goes at the end of #personas and above #messages and prevents all personas from subsituting missing messages. 
Now that you've pointed this out it makes sense and I guess that makes this a non-issue.

The wiki page is not wrong, but the way its formatted clearly bamboozled me.

**Comment by MageKing17** [comment]
The wiki could do with more clarity in a lot of things, but at least it sounds like this problem is solved!
