### ISSUE TITLE
gr.setTarget() with no args leads to segfault

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#1935]
This seems to originate with #1881 

If the optional argument is absent the expected result is that the render target is set to the screen. Instead FSO tries to call isValid() on a nullptr [here](https://github.com/scp-fs2open/fs2open.github.com/pull/1881/files#diff-db13c3ab66382b6237fa96eb48d2f50aR442)

Here's a minimal script that'll reproduce the issue; FSO should crash on startup before the intro movie plays.

```
#Conditional Hooks

$Application: FS2_Open

$On Game Init: [

    gr.setTarget()

]

#End
```

**Comment by asarium** [comment]
This should be fixed by #1935.
