### ISSUE TITLE
Models, including skyboxes, won't display

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#1941]
In lieu of FS2 retail data, total conversion/standalone models don't display along with any [TrueType fonts besides the librocket UI interface](https://github.com/scp-fs2open/fs2open.github.com/issues/1901). It should be noted that Unicode Mode is supposed to work without traditional bitmap fonts when used in standalone/total conversion mods.

Included is the log file:
[fs2_open_log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2630501/fs2_open_log.txt)

A screenshot:
![no rendered model](https://user-images.githubusercontent.com/2004725/49245317-eca92500-f44c-11e8-91c2-7d9a4ae5740e.png)

[File link](https://db.tt/BPcj1AhPlb)

**Comment by TheMatthew** [comment]
I've seen this before, it was visible with a Radeon 6870, but upgrading to a 7870 fixed it. It may be a hardware support issue too. Just a though.

**Comment by TheMatthew** [comment]
I just looked at your log, you may be having the same problem as I did. :)

**Comment by TheMatthew** [comment]
I have the bug in windows, not in Linux... I think you have the same bug, it's there since 3.8.x.

Not saying the fonts are not a bug, I didn't explore that... Also, they may be related.

Heads up, older Nvidia cards have the problem too, in both Windows and Linux.

**Comment by bryansee** [comment]
I'm using latest nightly build, with the -res command line option.

**Comment by bryansee** [comment]
Even with Unicode Mode disabled, the rendering bug still persists - see screenshots of Debug and Release builds.

![release 2](https://user-images.githubusercontent.com/2004725/49998970-9ac9d880-ffd0-11e8-96ec-7ee485c529d1.png)
![release 1](https://user-images.githubusercontent.com/2004725/49998971-9ac9d880-ffd0-11e8-9f68-5add48a82d47.png)
![debug 2](https://user-images.githubusercontent.com/2004725/49998987-a1f0e680-ffd0-11e8-95d8-550d9e1a5e2b.png)
![debug 1](https://user-images.githubusercontent.com/2004725/49998988-a1f0e680-ffd0-11e8-9923-574bfb237369.png)

**Comment by TheMatthew** [comment]
@bryansee cool investigation, why do you think the "cruiser fighter thing" in screenshot 3 displays though? That is very odd for me.

@hlp do you have a bug open for older amd/nvidia cards? I think one thing that can be done is to display a warning if the card is on a known blacklist.

**Comment by asarium** [comment]
I would like to debug this but without the required hardware (my RX 480 runs fine on Windows and Linux) I cannot do much about this.

**Comment by TheMatthew** [comment]
Thanks!
