### ISSUE TITLE
Assert: "block_index >= 0 && block_index < (int) bm_blocks.size()"

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1944]
Something in @asarium 's commit (e901e44) on Nov 18 broke the visual novel script used by JAD and WoD. Release will crash to desktop without error, fast debug will give
```Assert: "block_index >= 0 && block_index < (int) bm_blocks.size()"
File: bmpman.cpp
Line: 135
Bitmap handle 1082402341 has an invalid block number 16516!
```

And a full debug build attached to Visual Studio will... work completely fine! I didn't look to see which commit it was exactly, but I'm hoping m!m will know more!

To reproduce the issue, play any VN mission in JAD (most _a or _c missions)

**Comment by asarium** [comment]
I fixed the assertion issue but I am seeing another Lua error after that:
```
Lua Error: LUA ERROR: [string "cmpprogress-sct.tbm - On Game Init"]:20: attempt to index field 'Missions' (a nil value)

------------------------------------------------------------------
ADE Debug:
------------------------------------------------------------------
Name:		Unlock
Name of:	method
Function type:	Lua
Defined on:	9
Upvalues:	0

Source:		cmpprogress-sct.tbm - On Game Init
Short source:	[string "cmpprogress-sct.tbm - On Game Init"]
Current line:	19
- Function line:	11
------------------------------------------------------------------


------------------------------------------------------------------

stack traceback:
	[C]: ?
	[string "cmpprogress-sct.tbm - On Game Init"]:20: in function 'Unlock'
	[string "String: CmpProgress:Unlock('M6b')"]:1: in main chunk
------------------------------------------------------------------

------------------------------------------------------------------
```

Do you know if this is "expected" or if this might also be caused by my changes?

**Comment by AxemP** [comment]
No, not "expected" but I'll try to get more detail from you about that new issue on the weekend. The immediate problem with the VN stuff is solved with that commit. :)

**Comment by asarium** [comment]
Ok, thank you for testing that.

I did some digging through the scripts and logs and it looks like your script tries to load the file `mindex_EACampaign4.cfg` which does not exist. This means that the error message makes sense and is likely not caused by my changes.
