### ISSUE TITLE
Passing value 2.0 to asin() leads to implementation-defined result

### ISSUE THREAD

**Issue by Echelon9** [scp-fs2open/fs2open.github.com#196]
The following code can be found in code/weapon/swarm.cpp
```
 21:  #define SWARM_DIST_OFFSET 2.0 //distance swarm missile should vary from original path
...
266: if (missile_dist==0.0f) // Just in case of div by 0, which can happen with local SSMs
267:		swarmp->angle_offset = (float)asin(SWARM_DIST_OFFSET);
268: else
269:		swarmp->angle_offset = (float)(asin(SWARM_DIST_OFFSET / missile_dist));
```

The asin(x) or inverse sine trigonometric function has the domain for real results where x is [-1,1].

By passing the value 2.0 in at least one path through that function we run the risk of implementation-defined i.e. unknowable and not guaranteed outputs.

Note: The code may also run into this issue under other paths, but this is one that is certainly to run into the issue.

It appears the original intent of the function may have been to use SWARM_DIST_OFFSET as a form of multiplication factor, rather than the value to pass to asin() itself.

**Comment by Goober5000** [comment]
Elsewhere in the function, and in the original public code release, the code looks like this:
```
if ( missile_dist < SWARM_DIST_OFFSET ) {
	missile_dist=i2fl(SWARM_DIST_OFFSET);
}
swarmp->angle_offset = (float)(asin(SWARM_DIST_OFFSET / missile_dist));
```
It looks like the code you noticed was incorrectly written.  The original version ensures an input domain of (0, 1].

**Comment by Echelon9** [comment]
Thanks for looking at this history. I'll queue up a fix for it.

**Comment by Echelon9** [comment]
Resolved.
