### ISSUE TITLE
CTD when using Ships with Tabled Hyperspace Warpin Effect

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#1969]
Ships using a hyperspace warpin effect cause a CTD with today's nightly (Jan 13). This was no the case with builds from Jan 12 or before. Running debug builds the crash does not happen but the hyperspace warpin effect does not occur, a different warpin effect occurs. Attached is a sample table and mission to showcase. 

Github always wants me to upload the files as txt...

[hyperspace-shp.tbm.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2753557/hyperspace-shp.tbm.txt)
[Hyperspace Test.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2753558/Hyperspace.Test.fs2.txt)

**Comment by Goober5000** [comment]
This must be related to #1966 but I'm not sure how...
