### ISSUE TITLE
ship-create'd ships now crash FSO when they warpout

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#1982]
This seems to have been introduced by #1970 - I reverted merge #1970 and that seems to stop the issue occurring (@Goober5000  :grin:)

I think the cause is basically that [initialising the warp effect later](https://github.com/scp-fs2open/fs2open.github.com/pull/1970/files#diff-88098ad7c34083a6bd8b42e955eeca45R2032) means that SEXP ship-create and LUA createShip no longer initialise the warp effects. Inspection via a debugger shows that [`shipp->warpout_effect`](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/ship/shipfx.cpp#L724) is a nullptr.

I found the bug in BtA mission "Rebels And Revolutionaries" which uses a script to create & warp out a bunch of probes. I'll attach my retail compatible repro mission, just order "dummy 1" to depart via the comms menu as soon as the Ulysses appears and FSO should CTD.

**Comment by niffiwan** [comment]
[sc.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2799962/sc.zip)

**Comment by Goober5000** [comment]
Good ticket. :+1: Will investigate.

**Comment by niffiwan** [comment]
[1982-lua-testcase.zip](https://github.com/scp-fs2open/fs2open.github.com/files/2824128/1982-lua-testcase.zip)

Here's a 2nd test case to cover lua createShip. This should create an Ulysses, then warp it out automatically ~9 secs later.

**Comment by Goober5000** [comment]
I tested the latest version of the PR with both test missions, and both cases now work.  LMK if you approve.

**Comment by niffiwan** [comment]
approved - just needs Travis made happy...
