### ISSUE TITLE
Opening FS2 3.8.0 for Mac Causes Crash

### ISSUE THREAD

**Issue by Ozone14k** [scp-fs2open/fs2open.github.com#1989]
Hello everyone,

I'm excited about the new improvements in the FreeSpace Open engine. I have been unable to use the 3.8.0 on a Mac running 10.14, however. Regardless of whether FreeSpace Open 3.8.0 is started from the wxlauncher or from the FreeSpace 2 folder it plays the initial opening cutscene and if you press any key to skip it, the screen immediately goes black and minimizes to the dock. Clicking on the minimized window makes it full screen, which is just a black screen, and an error pop-up flashes for a fraction of a second before minimizing again. From the glimpse it I get, it looks like it says,

 "Error. An output of -1 was expected."

If I watch the entire FreeSpace opening cutscene, then the game acts normal, but then usually crashes in a mission somewhere. Any help would be greatly appreciated. Thanks!

**Comment by ngld** [comment]
Can you check if this issue still occurs with a [recent nightly](https://www.hard-light.net/forums/index.php?topic=95424.0)?
Also, please run the FASTDEBUG build and upload the debug log ([instructions are here](http://www.hard-light.net/forums/index.php/topic,56279.msg1180359.html#msg1180359)).

**Comment by Ozone14k** [comment]
Hello ngld,
Thank you for your quick response! I have run the FASTDEBUG and was able to see the full error message, which reads:

"Error: Player file has invalid radar range -1

File: plr.cpp
Line: 143"

The debug log reads:
EBUG SPEW: No debug_filter.cfg found, so only general, error, and warning
categories can be shown and no debug_filter.cfg info will be saved.
==========================================================================
Opened log 'data/fs2_open.log', Sat Feb 16 15:37:05 2019 ...
  Initializing SDL...
FreeSpace 2 Open version: 3.8.0
Passed cmdline options:
  -noenv
  -noglow
  -nospec
  -nonormal
  -noheight
  -nolightshafts
  -no_deferred
  -old_collision
  -window
Building file index...
Found root pack '/Users/andrew/FreeSpace2/multi-mission-pack.vp' with a checksum of 0x377695e0
Found root pack '/Users/andrew/FreeSpace2/root_fs2.vp' with a checksum of 0xce10d76c
Found root pack '/Users/andrew/FreeSpace2/smarty_fs2.vp' with a checksum of 0xddeb3b1e
Found root pack '/Users/andrew/FreeSpace2/sparky_fs2.vp' with a checksum of 0x164fe65a
Found root pack '/Users/andrew/FreeSpace2/sparky_hi_fs2.vp' with a checksum of 0xa11d56f1
Found root pack '/Users/andrew/FreeSpace2/stu_fs2.vp' with a checksum of 0xd77da83a
Found root pack '/Users/andrew/FreeSpace2/tango1_fs2.vp' with a checksum of 0x4c25221e
Found root pack '/Users/andrew/FreeSpace2/tango2_fs2.vp' with a checksum of 0x86920b82
Found root pack '/Users/andrew/FreeSpace2/tango3_fs2.vp' with a checksum of 0x705e8d71
Found root pack '/Users/andrew/FreeSpace2/warble_fs2.vp' with a checksum of 0xd85c305d
Searching root '/Users/andrew/Library/Application Support/HardLightProductions/FreeSpaceOpen/' ... 1 files
Searching root '/Users/andrew/FreeSpace2/' ... 26 files
Searching root pack '/Users/andrew/FreeSpace2/multi-mission-pack.vp' ... 110 files
Searching root pack '/Users/andrew/FreeSpace2/root_fs2.vp' ... 157 files
Searching root pack '/Users/andrew/FreeSpace2/smarty_fs2.vp' ... 10 files
Searching root pack '/Users/andrew/FreeSpace2/sparky_fs2.vp' ... 3027 files
Searching root pack '/Users/andrew/FreeSpace2/sparky_hi_fs2.vp' ... 1337 files
Searching root pack '/Users/andrew/FreeSpace2/stu_fs2.vp' ... 2355 files
Searching root pack '/Users/andrew/FreeSpace2/tango1_fs2.vp' ... 32 files
Searching root pack '/Users/andrew/FreeSpace2/tango2_fs2.vp' ... 15 files
Searching root pack '/Users/andrew/FreeSpace2/tango3_fs2.vp' ... 10 files
Searching root pack '/Users/andrew/FreeSpace2/warble_fs2.vp' ... 52 files
Found 12 roots and 7132 files.
Setting language to English
Game Settings Table: Using Standard Loops For SEXP Arguments
Game Settings Table: Using standard event chaining behavior
Game Settings Table: External shaders are DISABLED
Initializing OpenAL...
  OpenAL Vendor     : Apple Computer Inc.
  OpenAL Renderer   : Software
  OpenAL Version    : 1.1

  Found extension "AL_EXT_float32".
You are not using OpenAL Soft. Disabling enhanced sound.

  Sample rate: 0 (44100)
  EFX enabled: NO
  Playback device: Built-in Output
  Capture device: Built-in Microphone
... OpenAL successfully initialized!
Failed to init speech
  Initializing SDL video...
Initializing OpenGL graphics device at 1280x800 with 32-bit color...
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 2
SDL: Creating window at 0,0 because window has same size as desktop.
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 2
  Actual SDL Video values    = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  OpenGL Vendor    : Intel Inc.
  OpenGL Renderer  : Intel(R) Iris(TM) Graphics 6100
  OpenGL Version   : 4.1 INTEL-12.4.7

Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
Shader Variant Features:
Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
   Loading built-in default shader for: effect-screen-g.sdr
Shader Variant Features:
	Geometry shader point-based particles
Compiling new shader:
	Distortion Effects
   Loading built-in default shader for: effect-distort-v.sdr
   Loading built-in default shader for: effect-distort-f.sdr
Shader Variant Features:
Compiling new shader:
	Shield Decals
   Loading built-in default shader for: shield-impact-v.sdr
   Loading built-in default shader for: shield-impact-f.sdr
Shader Variant Features:
Compiling new shader:
	Deferred Lighting
   Loading built-in default shader for: deferred-v.sdr
   Loading built-in default shader for: deferred-f.sdr
WARNING: Failed to find uniform 'specFactor'.
Shader Variant Features:
Compiling new shader:
	Clear Deferred Lighting Buffer
   Loading built-in default shader for: deferred-clear-v.sdr
   Loading built-in default shader for: deferred-clear-f.sdr
Shader Variant Features:
Compiling passthrough shader...
Compiling new shader:
	Passthrough
   Loading built-in default shader for: passthrough-v.sdr
   Loading built-in default shader for: passthrough-f.sdr
Shader Variant Features:

Compiling passthrough shader...
  Max texture units: 2 (16)
  Max client texture states: 2 (1)
  Max elements vertices: 1048575
  Max elements indices: 150000
  Max texture size: 16384x16384
  Max render buffer size: 16384x16384
  Can use compressed textures: YES
  Texture compression available: YES
  Post-processing enabled: NO
  Using trilinear texture filter.
  OpenGL Shader Version: 4.10
... OpenGL init is complete!
Initializing path renderer...
Size of bitmap info = 1039 KB
Size of bitmap extra info = 64 bytes
ANI cursorweb with size 24x24 (25.0% wasted)
ANI cursorweb.ani with size 24x24 (25.0% wasted)
GRAPHICS: Initializing default colors...
SCRIPTING: Beginning initialization sequence...
SCRIPTING: Beginning Lua initialization...
LUA: Opening LUA state...
LUA: Initializing base Lua libraries...
LUA: Beginning ADE initialization
ADE: Initializing enumeration constants...
ADE: Assigning Lua session...
SCRIPTING: Beginning main hook parse sequence....
Wokka!  Error opening file (scripting.tbl)!
TABLES: Unable to parse 'scripting.tbl'!  Error message = Failed to open file.
SCRIPTING: Inititialization complete.
SCRIPTING: Splash screen overrides checked
SCRIPTING: Splash screen conditional hook has been run
Using high memory settings...
Wokka!  Error opening file (interface.tbl)!
WMCGUI: Unable to parse 'interface.tbl'!  Error message = Failed to open file.
Dutifully converting retail sound 36, 'l_hit.wav' to a 3D sound...
Dutifully converting retail sound 37, 'm_hit.wav' to a 3D sound...
Initializing Joystick...
  No joysticks found
Printing joystick info:
  No joystick is being used.
Current soundtrack set to -1 in event_music_reset_choices
Wokka!  Error opening file (armor.tbl)!
TABLES: Unable to parse 'armor.tbl'!  Error message = Failed to open file.
ANI support1 with size 108x24 (25.0% wasted)
ANI damage1 with size 148x25 (21.9% wasted)
ANI wingman1 with size 71x53 (17.2% wasted)
ANI wingman2 with size 35x53 (17.2% wasted)
ANI wingman3 with size 14x53 (17.2% wasted)
ANI toggle1 with size 57x20 (37.5% wasted)
ANI head1 with size 164x132 (48.4% wasted)
ANI weapons1 with size 126x20 (37.5% wasted)
ANI objective1 with size 149x21 (34.4% wasted)
ANI netlag1 with size 29x30 (6.2% wasted)
ANI targhit1 with size 31x21 (34.4% wasted)
ANI time1 with size 47x23 (28.1% wasted)
ANI targetview1 with size 137x156 (39.1% wasted)
ANI targetview2 with size 4x96 (25.0% wasted)
ANI targetview3 with size 7x20 (37.5% wasted)
ANI 2_energy2 with size 86x96 (25.0% wasted)
ANI 2_reticle1 with size 40x24 (25.0% wasted)
ANI 2_leftarc with size 103x252 (1.6% wasted)
ANI 2_rightarc1 with size 103x252 (1.6% wasted)
ANI 2_toparc2 with size 35x24 (25.0% wasted)
ANI 2_toparc3 with size 41x29 (9.4% wasted)
ANI 2_lead1 with size 26x26 (18.8% wasted)
ANI 2_lock1 with size 56x53 (17.2% wasted)
ANI 2_lockspin with size 100x100 (21.9% wasted)
ANI energy1 with size 12x41 (35.9% wasted)
ANI 2_radar1 with size 209x170 (33.6% wasted)
TABLES => Starting parse of 'ssm.tbl'...
ANI cursor with size 24x24 (25.0% wasted)
ANI cursor.ani with size 24x24 (25.0% wasted)
FFmpeg library initialized!
FFmpeg: License: LGPL version 2.1 or later
Ships.tbl is : VALID
Weapons.tbl is : VALID
cfile_init() took 113
Initializing head tracking...
  No supported provider found, headtracking will be disabled...
Headtracking is not enabled...
Creating player for movie 'intro.mve'.
FFMPEG Log: [theora @ 0x7fcdc8994000] 7 bits left in packet 82
FFMPEG Log: [ogg @ 0x7fcdc8983a00] Broken file, keyframe not correctly marked.
FFMPEG Log: [theora @ 0x7fcdc82ac800] 7 bits left in packet 82
FFmpeg: Using video codec Theora (theora).
FFmpeg: Using audio codec Vorbis (vorbis).
Compiling new shader:
	Video Playback
   Loading built-in default shader for: video-v.sdr
   Loading built-in default shader for: video-f.sdr
Shader Variant Features:
FFMPEG Log: [ogg @ 0x7fcdc8983a00] Broken file, keyframe not correctly marked.
FFMPEG Log: [ogg @ 0x7fcdc8983a00] Broken file, keyframe not correctly marked.
FFMPEG Log: [ogg @ 0x7fcdc8983a00] Broken file, keyframe not correctly marked.
Got event GS_EVENT_GAME_INIT (49) in state NOT A VALID STATE (0)
PLR => Loading 'Andrew.plr' with version 2...
PLR => Parsing:  Flags...
PLR => Parsing:  Info...
PLR => Parsing:  Scoring...
PLR => Parsing:  ScoringMulti...
PLR => Parsing:  HUD...

Error: Player file has invalid radar range -1

File: plr.cpp
Line: 143

Int3(): From /Users/travis/build/scp-fs2open/fs2open.github.com/code/osapi/dialogs.cpp at line 355
  1   fs2_open_3_8_0_x64-FASTDBG          0x00000001056d3471 _Z10debug_int3PKci + 49
  2   fs2_open_3_8_0_x64-FASTDBG          0x00000001056d01c1 _ZN2os7dialogs5ErrorEPKc + 849
  3   fs2_open_3_8_0_x64-FASTDBG          0x00000001056d1480 _ZN2os7dialogs5ErrorEPKciS2_z + 736
  4   fs2_open_3_8_0_x64-FASTDBG          0x000000010574ea94 _ZN9pilotfile12plr_read_hudEv + 164
  5   fs2_open_3_8_0_x64-FASTDBG          0x00000001057518a9 _ZN9pilotfile11load_playerEPKcP6player + 777
  6   fs2_open_3_8_0_x64-FASTDBG          0x0000000105589838 _Z33player_select_get_last_pilot_infov + 136
  7   fs2_open_3_8_0_x64-FASTDBG          0x0000000105589746 _Z18player_select_initv + 1190
  8   fs2_open_3_8_0_x64-FASTDBG          0x0000000105384c33 _Z16game_enter_stateii + 3075
  9   fs2_open_3_8_0_x64-FASTDBG          0x00000001054310b6 _Z17gameseq_set_stateii + 326
  10  fs2_open_3_8_0_x64-FASTDBG          0x00000001053834d3 _Z18game_process_eventii + 2355
  11  fs2_open_3_8_0_x64-FASTDBG          0x00000001054314ad _Z22gameseq_process_eventsv + 157
  12  fs2_open_3_8_0_x64-FASTDBG          0x00000001053865f9 _Z9game_mainiPPc + 473
  13  fs2_open_3_8_0_x64-FASTDBG          0x0000000105387da0 _Z11actual_mainiPPc + 560
  14  fs2_open_3_8_0_x64-FASTDBG          0x0000000105387ff2 main + 34
  15  libdyld.dylib                       0x00007fff75959ed9 start + 1
  16  ???                                 0x0000000000000001 0x0 + 1

**Comment by ngld** [comment]
> Error: Player file has invalid radar range -1

That means your pilot savefile is corrupted. If you can still get to the HUD config screen, try resetting your HUD. If that doesn't help, [see this thread](https://www.hard-light.net/forums/index.php?topic=94444.0) for other things to try.

**Comment by Ozone14k** [comment]
Hello ngld,

Thank you so much for your help! Resetting the HUD resolved the error. I did however lose my pilot data and history. No worries though because I'm eager to play through the campaign again with the updated graphics.

**Comment by MageKing17** [comment]
In recent nightly builds, a radar range of -1 is already made a non-fatal warning, so I'm closing this.
