### ISSUE TITLE
ships with hyperspace warp type are briefly in the wrong radar position at start of their warp

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#1992]
When a hyperspace warp-type ship warps in, it briefly appears at the wrong radar location. It should start  waaaay off in the distance; however the radar blip briefly appears at its destination before reappearing waaaaay off in the distance.

This is reasonably hard to notice (the radar blip may only be in the wrong place for a single frame?); thus is a minor issue. 

Test mission & modular table attached below.
[bbb-shp.tbm.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2897402/bbb-shp.tbm.txt)
[docktest-hyp.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/2897403/docktest-hyp.fs2.txt)

Short vid showing the issue:
https://www.youtube.com/watch?v=cjqWHVSUC6M

**Comment by Goober5000** [comment]
This is also fixed by #1991, right?

**Comment by niffiwan** [comment]
unfortunately not; it's a separate issue that I didn't want to hold up the #1991 fixes for

**Comment by FSCyborg** [comment]
I'm building a possible fix now.

**Comment by FSCyborg** [comment]
PR has been merged! This can he closed! :D
