### ISSUE TITLE
Could not find index 'Weapon' in type 'HookVariables' when using $On Weapon Collide

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#1996]
This problem comes up pretty erratically, and I can't uncover the exact root cause. 99% of the time, everything works as expected, but 1% of the time, it suddenly raises an odd error.

`Could not find index 'Weapon' in type 'HookVariables'`

Where the trace stack points to a script with these at the indicated lines

```
$On Weapon Collision:
[
if hv.Self:getBreedName() == "Ship" and hv.Weapon.Parent:isValid() and (hv.Weapon.Team ~= hv.Self.Team) then
	local parent = hv.Weapon.Parent
```

Weapon should be a perfectly valid hook variable here.

Going through a debug build and waiting for it to trip the error again gives me this call stack

https://pastebin.com/yaB8gZac

Reproducing this is hard because, again, I can't narrow down what is actually causing this. But m!m and I think its probably a regression because this script was working fine before (with JAD2.21 and 2.22) and no drastic changes were made to the script for about 2 years now.

**Comment by Goober5000** [comment]
Ah, brilliant!  Thank you very much, that stack trace was exactly what I needed.

The problem lies in this snippet of code:

```
if ( valid_hit_occurred )
	{
		wp->collisionInfo = new mc_info;	// The weapon will free this memory later
		memcpy(wp->collisionInfo, &mc, sizeof(mc_info));

		Script_system.SetHookObjects(4, "Ship", ship_objp, "Weapon", weapon_objp, "Self",ship_objp, "Object", weapon_objp);
		bool ship_override = Script_system.IsConditionOverride(CHA_COLLIDEWEAPON, ship_objp);

		Script_system.SetHookObjects(2, "Self",weapon_objp, "Object", ship_objp);
		bool weapon_override = Script_system.IsConditionOverride(CHA_COLLIDESHIP, weapon_objp);

		if(!ship_override && !weapon_override) {
			if (shield_collision && quadrant_num >= 0) {
				if ((sip->shield_impact_explosion_anim > -1) && (wip->shield_impact_explosion_radius > 0)) {
					shield_impact_explosion(&mc.hit_point, ship_objp, wip->shield_impact_explosion_radius, sip->shield_impact_explosion_anim);
				}
			}
			ship_weapon_do_hit_stuff(ship_objp, weapon_objp, &mc.hit_point_world, &mc.hit_point, quadrant_num, mc.hit_submodel, mc.hit_normal);
		}

		Script_system.SetHookObjects(2, "Self",ship_objp, "Object", weapon_objp);
		if(!(weapon_override && !ship_override))
			Script_system.RunCondition(CHA_COLLIDEWEAPON, ship_objp, wp->weapon_info_index);

		Script_system.SetHookObjects(2, "Self",weapon_objp, "Object", ship_objp);
		if((weapon_override && !ship_override) || (!weapon_override && !ship_override))
			Script_system.RunCondition(CHA_COLLIDESHIP, weapon_objp);

		Script_system.RemHookVars(4, "Ship", "Weapon", "Self","Object");
	}
```

Once I knew where to look, it wasn't long before I could figure it out.  The problem is that the hook variables are set *multiple times*.  The `Weapon` variable is valid for the first condition, but then it is subsequently overridden and is no longer valid when the hook is actually called.

I will soon have a PR that should fix this.

**Comment by asarium** [comment]
@Goober5000 I don't think that is the problem here since hook variables are kept until they are removed which does not happen in that snippet until the end of the `if` block.

**Comment by Goober5000** [comment]
@asarium Aren't they shadowed by the next batch of hook variables? I confess to not being super familiar with the scripting system, but that seems the most likely explanation for why the Weapon hook variable would suddenly be missing.

**Comment by asarium** [comment]
No, `SetHookObjects` simply sets those HookVariables and replaces any value that might have been there before. There is no shadowing or scoping going on.

The important thing here is that the bug only gets triggered in very few cases so it is unlikely that it is an obvious coding error and more likely that some kind of memory corruption is going on here. Unfortunately, going over the code with Valgrind did not show anything relevant.

**Comment by AxemP** [comment]
Just wanted to say that with this PR applied, I haven't had any new instances of the error, and I played through it like 3 or 4 times. I think it should've happened for sure in atleast one of those playthroughs.

**Comment by Goober5000** [comment]
:+1:

**Comment by asarium** [comment]
I just want to add that this likely did not solve the root problem here but at least the Lua error is gone with this.

**Comment by Goober5000** [comment]
True... are you anywhere closer to solving the problem with the table information Axem provided?
