### ISSUE TITLE
Bug: `detail_sphere` and `detail_box` don't work correctly with `show ship` flag

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#2015]
Using the `show ship` flag seems in conjunction with `detail_sphere` or `detail_box` does not work as expected. In short, `detail_sphere:-1` does the opposite of what is expected when using `show ship` flag and internal view. Detailed tests are listed below:

Objective: Make a `$detail_sphere:-1` in the `detail0` submodel of a pof with a radius of 100. 
Expected Behavior:
The model should only render if the player's view or distance is outside the detail sphere. 
Observed Behavior:
Using `show ship` and internal view results in the model still rendering (incorrectly) even though the view is within the detail sphere radius and `$detail_sphere:-1`. 

Objective: Make a `$detail_sphere:1` in the `detail0` submodel of a pof with a radius of 100. 
Expected Behavior:
The model should only render if the player's view or distance is inside the detail sphere. 
Observed Behavior:
Using `show ship` and internal view results in the model not rendering (incorrectly) even though the view is within the detail sphere radius and `$detail_sphere:1`. 

Also, everything works as expected in external view, so it it leads me to think it's an bug with `show ship` or the internal view camera distance. 

I have attached a mission and modified pof to showcase this likely bug. I would be happy to provide any additional tests or answer any questions. 

[data.zip](https://github.com/scp-fs2open/fs2open.github.com/files/3085115/data.zip)

**Comment by wookieejedi** [comment]
So I did some digging and the issue seems to be due to inconsistent `viewpos` values. The function that determines if the detail_sphere or box is rendered is `bool model_render_check_detail_box(vec3d *view_pos, polymodel *pm, int submodel_num, uint flags)` and that function uses `view_pos` which when printing the values each frame it appears to be very inconsistent when in internal view. This results in the rendering not occurring as expected. Here is my tests:
```
Internal View:
viewpos is 997.783203, -10.073664, -1278.403320 
render_detail_sphere? is -1 
viewpos is -22.668497, 6.508561, 0.132012 
render_detail_sphere? is 1 
viewpos is 997.783020, -10.073786, -1278.403564 
render_detail_sphere? is -1 
viewpos is -22.845505, 6.363339, -0.187189 
render_detail_sphere? is 1 
viewpos is 997.782898, -10.073902, -1278.403687 
render_detail_sphere? is -1 
viewpos is -23.061804, 6.264188, -0.377727 
render_detail_sphere? is 1 
viewpos is 997.782715, -10.074001, -1278.403687 
render_detail_sphere? is -1 

External View:
viewpos is -6.529016, 20.159502, -32.674122 
render_detail_sphere? is 1 
viewpos is 36.286865, 6.281302, -83.968140 
render_detail_sphere? is 1 
viewpos is 0.000046, 6.192968, -21.056107 
render_detail_sphere? is 1 
viewpos is -9.202076, 21.426908, -36.144173 
render_detail_sphere? is 1 
viewpos is 36.286865, 6.281302, -114.060913 
render_detail_sphere? is 1 
viewpos is 0.000046, 6.192969, -21.056108 
render_detail_sphere? is 1 
viewpos is -11.921576, 22.391314, -43.327675 
render_detail_sphere? is 1 
```
So it seems there is likely a bug in how `viewpos` vector is calculated?

**Comment by wookieejedi** [comment]
Okay nm, it is caused by something to do with `show ship`...And the issue seems to be in this function void `ship_render_show_ship_cockpit(object *objp)`. It's does a few matrix calculations so I am not sure where the bug might be?

**Comment by Goober5000** [comment]
Reported fixed
