### ISSUE TITLE
Vertical sync doesn't work on nightlies after April 30th.

### ISSUE THREAD

**Issue by FrikgFeek** [scp-fs2open/fs2open.github.com#2027]
This might be an AMD-only issue, I don't have an Nvidia GPU or intel iGPU to test this on.
V-sync is enabled by default and it doesn't work in more graphically intensive missions on my system. With MVPs 3.8.x loading Massive Battle gets me 120 FPS on a 60Hz monitor and results in noticable screen tearing, especially when using the afterburner or weapons like the maxim with screenshake effects. I have no idea why more demanding missions would break V-sync and therefore result in higher FPS.
'Lighter' missions like Surrender, Belisarius or Into the Maelstrom are properly V-sync'd at 60 FPS with no screen tearing. What's even weirder is that pressing escape twice or using the pause function temporarily "fixes" this issue until a menu is opened(by pressing F1, F2, F3, or F4 to open their respective menus).

**Comment by FSCyborg** [comment]
Most relevant commit might be the one fixing #1827 , #2025 .  I don't think I'm able to handle this one yet, but I figured I could make a possible connection.

**Comment by z64555** [comment]
Anyone able to repro?

**Comment by Goober5000** [comment]
Bueller?  Bueller?

**Comment by FSCyborg** [comment]
I haven't tried, but we just got a report from Antares on the forums.  They are on an Intel HD 4400 .

**Comment by FSCyborg** [comment]
Was also able to reproduce with retail data, also on an Intel GPU.  It's playable but annoying.

**Comment by JohnAFernandez** [comment]
I was *only* able to reproduce on my previous computer, and I no longer have access to that computer. Attempting to reproduce on this one fails miserably.  Everything runs very smoothly.

**Comment by Goober5000** [comment]
Let's assume this is fixed then.  We can always reopen later if it reappears.
