### ISSUE TITLE
Destroyed subsystems revert to undestroyed Model when ship dies

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#2046]
Destroyed subsystems revert back to the un-destroyed model when a ship dies. Here is an attachment image along with an attachment mission file. In the mission the panel subsystem is destroyed, then the ship is destroyed a second later. As the ship dies, the panel changes from it's destroyed model to un-destroyed model. 
![screen0316](https://user-images.githubusercontent.com/14077810/57824290-9c0e5580-7768-11e9-9814-0303fe4fe514.png)
![screen0317](https://user-images.githubusercontent.com/14077810/57824292-9f094600-7768-11e9-89d5-df0d51c0e225.png)

[sub_test.txt](https://github.com/scp-fs2open/fs2open.github.com/files/3185270/sub_test.txt)
(Just change the .txt fo .fs2)

**Comment by Goober5000** [comment]
Can you check if this happened in retail too?

**Comment by wookieejedi** [comment]
Noting here too, the bug is not present in retail.

**Comment by Goober5000** [comment]
:thinking: 

Can you try testing some old builds?  Look in the official release threads:
http://www.hard-light.net/forums/index.php?topic=92181.0

A link to the previous release will be somewhere in the first post, in tiny print.

**Comment by wookieejedi** [comment]
Sure! So from my first pass of tests, the bug is present in 3.7.4 but is not present in 3.7.2. Will examine the nightlies between those to see if I can tell which one changed it.

**Comment by wookieejedi** [comment]
Hmm so it turns out most of the links to the old nightly builds are dead, so I am unable to test individual nightly builds. Using that time-frame (between April 23, 2015 and July 4, 2016) I searched mantis and found a possibly related ticket here: http://scp.indiegames.us/mantis/view.php?id=3164

And I did the same search in the closed PR section during that time range. I didn't find anything that stood out right away, but #88 (https://github.com/scp-fs2open/fs2open.github.com/pull/88) and #460 (https://github.com/scp-fs2open/fs2open.github.com/pull/460/files) seem like possible options? I'm not too sure what to do at this point.

**Comment by Goober5000** [comment]
That's excellent detective work.  At first glance the two github issues probably aren't related, but the Mantis issue probably is.

The next step is to use `git bisect` to narrow down the precise change that introduced the bug.  Hopefully it will be a simple commit rather than a large commit like the new rendering code.

I can show you how to use `git bisect` on Discord.

**Comment by wookieejedi** [comment]
Thanks, this might also be a possible option to look more into https://github.com/scp-fs2open/fs2open.github.com/pull/486/files.

**Comment by wookieejedi** [comment]
It seems I can't get builds to compile for mid 2015 to 2016 (3.7.4) (thanks for all the folks who helped me get this far with the testing). I had two successful compiles and tests, so I at least shaved off a few months. I'm not to sure how to proceed, and am bummed the builds stopped compiling due to the gc error, because it seems pretty straight forward to find the bug if it did. Here is what I did find though, and I will post this in github too, so hopefully if anyone else wants to take a crack at it they can. 

```
$ git bisect start

$ git bisect bad 63eff42 (March 29 2016)

??

$ git bisect good 0a9ae3eb4 #228 ( July 6 2015)
$ git bisect good a47ac6c5e #211 (July 2, 2015)
$ git bisect good 083905b # 39 (March 2014) 
```

**Comment by wookieejedi** [comment]
Okay ran a full bisect session, and found the commit which introduced the bug:
```
64ad950a802f8bae62a67c54b0e95e6f6271554b is the first bad commit
commit 64ad950a802f8bae62a67c54b0e95e6f6271554b
Author: SamuelCho <samuel.s.cho@gmail.com>
Date:   Tue Dec 1 23:53:24 2015 -0800

    Allow model rendering code to use polymodel_instance. Removes the reliance on ship_model_start/stop for rendering models. Also fix a bunch of oversights involving blown off models in the polymodel_instance code.
```

**Comment by Goober5000** [comment]
Reopening since @wookieejedi reports it isn't fixed yet.
