### ISSUE TITLE
FRED and FSO treat missions with minor sexp errors as corrupted

### ISSUE THREAD

**Issue by WoolieWool** [scp-fs2open/fs2open.github.com#2067]
In current builds of FRED2_Open, if you save a mission with illegal data in any sexp, it will thenceforth treat the mission as entirely corrupted, refusing to reload it after saying or load it ever again (until, presumably, you fix the error in a text editor). For a demonstration of this effect, I've created two missions. Gallant.fs2 has a sexp controlling the appearance of support ships from an Arcadia class installation. Goofus.fs2 replaces that installation with a GTCv Deimos, and FRED, instead of pointing our the broken sexp and yelling at you to fix it, simply says "Error: Failed to reload mission after saving. Report this bug now! / File: freddoc.cpp / Line: 658". 

[missions.zip](https://github.com/scp-fs2open/fs2open.github.com/files/3413138/missions.zip)
![error](https://user-images.githubusercontent.com/14041765/61572445-53726180-aa63-11e9-80a6-f5beff2c0646.png)

**Comment by FSCyborg** [comment]
Found the issue.  About 5 months ago, we updated the mission parser to not crash FSO when there was a SEXP error and instead just return the parse as failed.  Problem is, we forgot that FRED can handle it.  So we just need to add a little check before returning the parse as failed.
