### ISSUE TITLE
FSO has issues with paths that have unicode characters

### ISSUE THREAD

**Issue by MageKing17** [scp-fs2open/fs2open.github.com#2086]
The specific problem was noted when a user with a `ó` character in their username had a suspiciously-empty `%AppData%\HardLightProductions\FreeSpaceOpen\` folder; basically, Knossos could write fs2_open.ini there, but FSO couldn't find it there, and would therefore run in legacy mode. Creating a new Windows user with just regular ASCII characters in the name resulted in expected behavior.

I don't personally know all the work that would be involved in allowing FSO to work with unicode filepaths, but I assume it would be a fairly intensive effort.

**Comment by asarium** [comment]
The answer to how much work this would be is "quite a lot of". Basically we would need to convert all the file handling to the Unicode variants provided by the Windows API. Alternatively, we could also try to move to `std::/boost::filesystem` which handles all that stuff by itself.

**Comment by asarium** [comment]
It's probably possible by decoding the path with our utf-8 parser and checking if all the characters fall within the ASCII range.
