### ISSUE TITLE
Enhancement idea: Auto-Follow

### ISSUE THREAD

**Issue by TheMatthew** [scp-fs2open/fs2open.github.com#2090]
I was playing Rebel Galaxy Outlaw, and realized how auto-follow is not the be-all end all of dogfighting, in fact, it's rather mediocre, and that is a great strength for it. It can be a very interesting dogfighting element sometimes only. I think it would be a good idea to discuss if it has it's place in the scp engine.

**What** autofollow would bank a ship towards the target in a "Lead pursuit" (or lag if lead is too gamebreaking.

**Why** several reasons:
1- To break away from a turning battle
2- To allow pilots to gain their bearings a bit more.
3- To allow faster craft in mods without sacrificing accessibility
4- To allow players with disabilities to play fs2.

**How** If it were up to me, a key could be bound to auto-follow target. This would align our cross-hair to the reticle (where the target will be). It may be mutually exclusive to glide.

**Is it a priority?** Probably not, but it would be a cool idea in my opinion worth discussing.

**Comment by asarium** [comment]
This sounds very much like a feature that could be implemented using a Lua script.

I am generally opposed to adding such specific features to the engine since then we can't change it significantly due to our backwards compatibility guarantee.

**Comment by Goober5000** [comment]
Yeah, I agree.
