### ISSUE TITLE
set-object-facing and set-object-facing-object with specified turn times don't work at all reasonably

### ISSUE THREAD

**Issue by tcrayford** [scp-fs2open/fs2open.github.com#2092]
There's two sexps for controlling a ships orientation, `set-object-facing` and `set-object-facing-object`. These two take an optional "turn time in milliseconds". But that time does extremely strange things.

For example, if you set turn time to a reasonably high number, it will do *nothing* to the object, even with `play-dead` AI orders, the object will just stay still.

If you set turn time to a very low number (like 1 or 2 milliseconds), the object will rotate, but exceed and miss the target typically.

Ultimately, both of these sexps (when used with a turn time) call down into https://github.com/scp-fs2open/fs2open.github.com/blob/4f884b50356e2e7b8ea14c2cded133eff393e397/code/ai/aicode.cpp#L1253, which sets the physics object's `rotvel` vector. That… tries to turn towards the specified location, but only on this frame. It gets reset on the next frame (according to @Goober5000 in HLP discord).

None of this seems to be what should be happening when called in this way.

**Comment by Goober5000** [comment]
1 or 2 milliseconds is far too low.  I think turn-time is supposed to be the total amount of time for the turn to complete.  Try something like 2000 or 4000 milliseconds.

**Comment by Goober5000** [comment]
It's actually the time it would take to make one complete rotation.  Here's where the code calculates angular velocity:

```
		//	Set max turn rate.
		vel_limit.xyz.x = PI2/turn_time;
		vel_limit.xyz.y = PI2/turn_time;
		vel_limit.xyz.z = PI2/turn_time;
```

**Comment by Goober5000** [comment]
Closing the issue now that help has been updated.
