### ISSUE TITLE
Looping music/sounds have a small pause when looping

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#2097]
When using the `play-sound-from-file` sexp, there's always been this very small pause or gap when the music is supposed to loop back. It'd be super if this could be made so much more seamless and less terrible!

Here's a sample mission of the afterburner loop sound being used in the sexp which shows the problem quite well: 

[soundlooptest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/3640423/soundlooptest.zip)

**Comment by Goober5000** [comment]
When the track finishes playing, and it is a looping sound, code in audiostr.cpp will simply call the Play function again.  This is the beginning of that function:
```
// Play
void AudioStream::Play (float volume, int looping)
{
	if (m_buffer_ids[0] != 0) {
		// If playing, stop
		if (m_fPlaying) {
			if ( m_bIsPaused == false)
				Stop_and_Rewind();
		}

		// Cue for playback if necessary
		if ( !m_fCued )
			Cue ();
```

The combination of `Stop_and_Rewind()` and `Cue()` causes the track to be reinitialized and re-buffered.  The code is fairly explicit about this.  Unfortunately, the simple non-skippable steps (such as resetting flags) are interleaved with the complicated skippable steps (such as copying the entire track into the buffer) and it's not clear to me how to untangle them.

**Comment by MageKing17** [comment]
Surely it would make more sense to just set `AL_LOOPING` instead of manually playing it again?

**Comment by Goober5000** [comment]
I couldn't say; I didn't write the code.  I only see `AL_LOOPING` used for sound effects though, and even then only for displaying error messages.

**Comment by MageKing17** [comment]
`OpenAL_ErrorPrint()` doesn't mean the line is used for displaying error messages, it means that *if* the line generates an error, it'll print the error to the debug log.
