### ISSUE TITLE
Music/Sounds don't pause in the F2 and escape menu

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#2099]
As it says on the tin, background music and sounds played from file will continue to play in the F2 options menu and in the escape menu ("Do you want to leave the mission?"), unlike the other menus and while paused. While I _personally_ would prefer if it paused in all cases, it should at least be consistent.

**Comment by Goober5000** [comment]
So we have:

* Pause key: pauses music
* Escape key: does not pause music
* F2 key: does not pause music
* ???

What are the "other menus" you are referring to?

**Comment by Baezon** [comment]
F1, the key help menu, F3, the wing tracking menu, and F4, the objectives/messages/events tracker, all pause music.

**Comment by Goober5000** [comment]
Gotcha.

**Comment by Baezon** [comment]
...I also just noticed that the F3 and F4 menus will resume the music if you re-enter them after having alt-tabbed away. An additional note is that the F2 and escape menus will continue to play music while alt-tabbed, while the F3 and F4 menus will only play music while the game is in focus (once you have gotten them to start playing music again by alt-tabbing into them).

I should note my specific case is entirely play-sound-from-file, so some of this stuff may only be true for that, and not necessarily normal background music.

**Comment by Goober5000** [comment]
Background music and play-sound-from-file are handled the same.

The alt-tab thing is a separate bug, since application pause & resume is handled elsewhere.  I've already created a fix for this bug; will post a PR shortly.
