### ISSUE TITLE
Setting ship orientation via scripting sometimes doesn't set properly

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#2166]
There is an issue where setting  a ship's orientation via scripting sometimes doesn't set it properly...though this only happens with certain orientations.

I made a test mission and test script which shows it (reproducible). I set a ship's orientation to itself via scripting, but that somehow made the orientation change. To view, run the mission in debug mode and you can see the ship jump in mission and the debug output say that the orientation changed even though it shouldn't have. 

The ship has no orders or velocity, and this bug only happens with certain starting orientations.

This is the relevant section for those who don't want to download files:

```
local ship = mn.Ships["Test Ship"]

print("Checking 1: Test Ship P, B, H = " .. math.deg(ship.Orientation.p) ..", ".. math.deg(ship.Orientation.b) ..", ".. math.deg(ship.Orientation.h) .."...\n")
-->Checking 1: Test Ship P, B, H = 18.886552224974, -2.3717680348047, -22.134541109294...

ship.Orientation = ba.createOrientation(ship.Orientation.p, ship.Orientation.b, ship.Orientation.h)

print("Checking 2: Test Ship P, B, H = " .. math.deg(ship.Orientation.p) ..", ".. math.deg(ship.Orientation.b) ..", ".. math.deg(ship.Orientation.h) .."...\n")
	-->Checking 2: Test Ship P, B, H = 21.738086194015, -2.3717680348047, -22.134541109294...
	
--those two checks should be the same, but they are not equal regarding pitch (for some reason?)
--the ship is not moving and has no orders
--this only happens with certain starting orientations
```

[Orientation Test_fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/3906046/Orientation.Test_fs2.txt)

[ort_test-sct_tbm.txt](https://github.com/scp-fs2open/fs2open.github.com/files/3906047/ort_test-sct_tbm.txt)

**Comment by wookieejedi** [comment]
Also the issue is not with `ba.createOrientation()`, rather the issue is setting a ship's orientation equal to another orientation. In other words,  `ship.Orientation = new_orientation` can cause issues. Though `ship.Orientation = ship.Orientation` works fine.

**Comment by wookieejedi** [comment]
This is related to `angles_2_matrix ` not being completely correct all of the time with angles that is returns from a 3x3 matrix.

**Comment by FSCyborg** [comment]
So, just to clarify, the actual issue was another function which is fixed in 2167?

**Comment by wookieejedi** [comment]
That is correct, once 2167 gets merged then this issue will be officially fixed.

**Comment by Goober5000** [comment]
Fixed via 2167
