### ISSUE TITLE
Mainhall 2D Sounds Play In Rear Channel

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2173]
Mainhall sounds are 2D sounds only. The table can specify a left/right pan. However, the sounds are playing only in the rear audio channels in a surround sound environment.

**Comment by MageKing17** [comment]
As somebody who doesn't use a surround sound system: would you rather 2D sounds only played from the front speakers, or would you prefer both sets be active at once?

**Comment by MjnMixael** [comment]
Off the top of my head I don't know where else 2D sounds are used, but I think it makes sense for them to only be in the front speakers. But that would include Center which probably makes this slightly more difficult.

**Comment by MageKing17** [comment]
sounds with no panning play from all speakers (or should)

**Comment by MjnMixael** [comment]
The mainhall sounds do have panning, though. You can specify in the mainhall.tbl left (-1.0) to right (1.0).

**Comment by MageKing17** [comment]
by "no panning" I mean "a pan of 0", and I assumed that's what you meant by "center"
