### ISSUE TITLE
Feature Request: Fire-turret sexp analogous to fire-beam sexp

### ISSUE THREAD

**Issue by RhymesHLP** [scp-fs2open/fs2open.github.com#2176]
An issue that's come up internally for the Inferno team has been trying to balance capship-heavy missions with lots of turrets. While there are some tools that allow FREDders to control turret rate of fire, or to set them to safe or free-fire, there currently is no way in FRED to tell a turret (or set of turrets) "fire at this target," as there is for beam cannons. A fire-turret sexp would give FREDders more fine control over capital ship behavior and mission balance, without needing to resort to scripts or complicated sexps to achieve the same result.

**Comment by wookieejedi** [comment]
FYI this has also been discussed with #1062

**Comment by Goober5000** [comment]
Yeah I'm closing this so we don't have duplicate issues.

**Comment by RhymesHLP** [comment]
Seeing as the other one hasn't been touched since 2016 and appears to have had no progress made on it in the intervening three years, I thought it was worth bringing back up again.
