### ISSUE TITLE
Briefing Icon created from Jump Node causes FRED to crash

### ISSUE THREAD

**Issue by Neonshivan** [scp-fs2open/fs2open.github.com#2181]
When attempting to create a briefing icon with the jump node selected causes FRED to crash.

To recreate the issue:

1. Open FRED and create a Jump Node
2. Go to the Briefing editor and select the jump node
3. Attempt to create an icon with the jump node
4. Watch FRED attempt to divide by zero and crash

**Comment by Goober5000** [comment]
Fixed via #2184
