### ISSUE TITLE
Enhancement: Target nearest enemy starfighter

### ISSUE THREAD

**Issue by countbuggula** [scp-fs2open/fs2open.github.com#2215]
Please consider adding a key binding to target the nearest enemy starfighter.  Currently there are only options to target nearest attacking craft and nearest enemy craft.  In missions with large amounts of capital ships, this would make finding enemy starfighters (especially those attacking other craft) much easier to find.

Note, this is a feature that has been included in every X-Wing game since the original '93 release.

**Comment by Goober5000** [comment]
Closing per comments on other ticket

**Comment by z64555** [comment]
Scripted controls is a feature we're working on, and would like mod devs to try experimenting with them.  As the controls code is upgraded over time (hopefully within the next few months) the scripted controls support will be expanded and made more robust.
