### ISSUE TITLE
laptop+external monitor setting not taken into account

### ISSUE THREAD

**Issue by dseddah** [scp-fs2open/fs2open.github.com#2228]
Hi again,

when run in a dual monitor setting, fso only runs on the laptop screen, not the external. afaik there's no option to use the second display.

Step to reproduce
1° connect a second monitor (here via hdmi) to my macbook pro in extended screen mode (no mirroring)
2° run fso via knossos in either screen
3° game only plays on laptop

configuration
macbook pro (15,2  - ATI) 10.14.6
fso 3.8.0 and 3.8.1 from github

**Comment by The-E** [comment]
FSO does not specify which screen to use; this is, at the moment, entirely up to the OS and SDL to determine.
IIRC, On Windows, this defaults to whatever the user has specified as the "main" display; I do not know if MacOS has a similar setting, but this might be something you could try?

**Comment by Goober5000** [comment]
Closing for lack of response.
