### ISSUE TITLE
Deprecated flag -no_emissive_light in command line enables emissive light on builds after PR #2146

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#2237]
I thought there is something wrong and emissive light is all time enabled regardless of flags. Then I accidentally removed -no_emissive_light, which shouldn't affect lighting on builds after 1 December 2019, but it does.
-no_emissive_light in command line:
![screen0478](https://user-images.githubusercontent.com/18072803/72225648-2624ed00-3588-11ea-9129-9998b14a9ab2.png)
Without -no_emissive_light in command line:
![screen0479](https://user-images.githubusercontent.com/18072803/72225655-38069000-3588-11ea-99a2-9851d46b2761.png)

**Comment by Goober5000** [comment]
Link to #2146.  Paging @The-E to take a look.
