### ISSUE TITLE
no widescreen on menu

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#2255]
Hi,

Just installed the version 19 that seem work fine, but only the gameplay is in widescreen all menu are in 4:3 1020x768 like the previous version.

There is a way to force all menu to widescreen 1920x1080 ?

**Comment by Goober5000** [comment]
There is a command-line option, `-stretch_menu`.

**Comment by MageKing17** [comment]
We can't have 1920x1080 menus without 1920x1080 menu assets. There's an [incomplete test mod](https://fsnebula.org/mod/UITest) to implement HD menu assets, but it is (as previously mentioned) incomplete.
