### ISSUE TITLE
no ffb on version 19.0 work fine in 3.8 

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#2258]
hi,

I have updated to version 19.0 but the force feedback not work.

Back to version 3.8 the ffb work fine.

Can you check please ?

**Comment by z64555** [comment]
Hey luca, are you still around?  Do you still have this issue?

The only force feedback controller I have is a busted up Xbox controller, and it needs some updates to the FFB code before it'll let FSO use it.

**Comment by luca2125** [comment]
Hi z64555,

We have already discussed on discord "marco000" about:

https://discord.com/channels/@me/771053661882810380

are you working about FFB code ?

**Comment by z64555** [comment]
I wanted to try to look into this, but the only force feedback controller I have is an Xbox controller.  FSO's looking for support of certain waveforms and hasn't been updated to use SDL_HAPTIC_LEFTRIGHT which is what Xinput controllers use.

So, as said before, in order for me to even test behavior I'd have to update the FFB code, maybe even overhaul it.

Most of the discussion in discord was over the GUID mismatch between knossos, which I should try to address in the controls code overhaul that's in review.

**Comment by luca2125** [comment]
When I have connected only one device with force feedback (Sidewinder Force Feedback 2) the force feedback work. 

The problem is that sometimes (not always) after a update of windows or change the USB device the force feedback not work.

I can tell you that when work, work fine.

A bit detail but not very important, this game don't allow to set the force level (spring effects , overvall effects).

However the default setting is good for my device and for my preference I don't known for other users like to change ...

**Comment by z64555** [comment]
Right, so. The intended workaround for this until forcefeedback can be properly addressed is to make use of the multi-joy feature that's upcoming.  You'd assign your haptic/force feedback joystick as joy-0, and all other joysticks/virtual joysticks as joy-1, joy-2, or joy-3 and bind them accordingly.

**Comment by z64555** [comment]
Delayed until 21.4, when Controls4/5 gets merged.

**Comment by luca2125** [comment]
It is a very good news if the force feedeback will be fixed in future, the time is not important.

**Comment by z64555** [comment]
Delayed again until 21.6 due to issues with getting Controls5 merged.  This was a stressful summer...

**Comment by luca2125** [comment]
thank you I will test when will be done.

**Comment by z64555** [comment]
@luca2125 Please test with the latest RC: [Release 22.0 RC2](https://github.com/scp-fs2open/fs2open.github.com/releases/tag/release_22_0_0_RC2)

It is also available on knossos

**Comment by luca2125** [comment]
thank you unfortunatenly I can't test at the moment I'm full of work.  But in the future I will do.

**Comment by JohnAFernandez** [comment]
@luca2125 would you have time to test any of recent build, like 22.2 RC1?  It is again available on Knossos.

**Comment by luca2125** [comment]
I have download the last version 22.2 RC1 and replace all files on my previous FSO folder.

When start he alert me that the version is changed.

However without apply any changed in the option, I have started the game and I see that the Force Feedback work well.

Only for my curiosity: do you have added multiple controller support ?

Thanks !

**Comment by JohnAFernandez** [comment]
Thanks for checking!

We did add multi-controller support in the engine.  Launcher support is still on its way, but changes can be made to certain files manually to add them in.
