### ISSUE TITLE
Librocket related shader issue

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2266]
This bug shows up on the first 20.0 nightly. Does not appear in 19.0 final.

> Failed to load apng: (file single-player-o.png) animation duration <= 0.0f, bad data?
> Compiling new shader:
> 	libRocket UI
>    Loading built-in default shader for: rocketui-v.sdr
>    Loading built-in default shader for: rocketui-f.sdr
> Fragment shader failed to compile:
> 0(19) : error C7011: implicit cast from "int" to "bool"
> 
> OpenGL Debug: Source:OpenGL	Type:Error	ID:1282	Severity:High	Message:GL_INVALID_OPERATION error generated. Handle does not refer to the expected type of object (GL_PROGRAM_OBJECT_ARB)
> 
> Error: A shader failed to compile! Check the debug log for more information.
> File: gropenglshader.cpp
> Line: 748

I'm guessing it's related to this commit.. #2133 But I don't know for sure.

**Comment by asarium** [comment]
Probably broken by my changes to how uniforms are handled.

**Comment by MjnMixael** [comment]
Was this supposed to be fixed in the Feb 12 nightly? Cause I'm still getting this error.

**Comment by asarium** [comment]
Is it still the same error or something else?

**Comment by MjnMixael** [comment]
Yes, I believe it's the same.

> Compiling new shader:
> 	libRocket UI
>    Loading built-in default shader for: rocketui-v.sdr
>    Loading built-in default shader for: rocketui-f.sdr
> Shader failed to link:
> Vertex info
> -----------
> error: type mismatch between shaders for uniform (named textured)
> 
> 
> Error: A shader failed to compile! Check the debug log for more information.
> File: gropenglshader.cpp
> Line: 748

**Comment by asarium** [comment]
Yep, I should have actually compiled the shader after making the change...
