### ISSUE TITLE
Invalid Entry in Particle.tbl causes Debug to Abort()

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2269]
If at any time you set **+Deviation: 0.0** in the particle.tbl, FSO will immediately abort during tbl parse because the value must be greater than 0.  It took some significant trial and error to find the cause. I would think the FSO could handle this a little more gracefully and print something more helpful in the log before the Abort().

Currently it simply stops parsing and printing entirely.

**Comment by asarium** [comment]
Thank you for the report. The pull request above should display a more or less helpful error message and use a default value if an invalid value is specified.
