### ISSUE TITLE
Feature Request: Bump weapon class limit

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#2274]
Could the weapon class limit be bumped soon? JAD is currently at the max 300 weapon classes and with the latest MediaVPs (4.1.1) it's now thrown over. So either I need to patch out the weapon class changes or keep JAD at MediaVPs 4.0 unless the limit gets bumped/removed/turned into pudding.

**Comment by JohnAFernandez** [comment]
500 is probably good for a little while at least.  Hopefully by then we can safely vectorize and remove the limit.
