### ISSUE TITLE
Add Ray Tracing support

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#2275]
hi,

I think can be very interesting if the game will support ray tracing.

With the next upcoming nvidia video card the frame rate will be more accebtable I suppose.

This change can match this game with the more recent games.

**Comment by The-E** [comment]
Having raytracing support would be cool, but as with all large-scale changes, they depend entirely on whether or not someone actually steps up to work on it; It's not something we can reasonably put on any sort of timeline or make firm promises about.
