### ISSUE TITLE
Feature Request: Add deprecated/obsolete section to scripting.html

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#2277]
As discussed on discord, it'd be good to have a clear section of generated documentation to indicate obsolete scripting functions. For example, the `ts.createParticle` function is obsolete in target versions 20 and above which has the chance to trip people up. Someone unfamiliar with this may think they're going insane the function suddenly vanishes with just a table edit. So a section in the scripting.html to clearly show that should be most beneficial for debugging.

**Comment by asarium** [comment]
Error messages were improved with #2278.
