### ISSUE TITLE
FRED2_Open improperly reporting version number?

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#2281]
It seems like recent versions of FRED2_Open are improperly identifying themselves as 3.8.1:
![obraz](https://user-images.githubusercontent.com/46261609/75580000-43921580-5a67-11ea-9661-f60b6145c7f7.png)

**Comment by Goober5000** [comment]
The version number is pulled from the `IDR_MAINFRAME` definition in fred.rc.  I'll open a PR.

**Comment by asarium** [comment]
While you are at it, maybe you could implement it in a way so that it automatically pulls the version from our common definitions?

**Comment by Goober5000** [comment]
That's what I'm investigating.  Easier said than done...

**Comment by chief1983** [comment]
I thought that was done long ago to be honest

**Comment by Goober5000** [comment]
I suspect someone *looked* at it a long time ago, but gave up after it proved impossible.  Maybe it's not impossible, but stackoverflow and google proved fruitless, and Microsoft documentation seems intentionally designed to prevent you from learning anything meaningful about the API.
