### ISSUE TITLE
Controls combo allowing you to accidentaly exceed INT_MAX coordinates in FRED2_Open

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#2283]
I've recently experimented a bit with FRED controls and it turns out there's a combo of settings that can easily lead you to moving your camera beyond acceptable coordinates. In order to do it, you need to:
- Use the 'Select and Move' mode,
- Use the 'Rotate around object' mode,
- Grab an object (the camera will snap on to the selected one so doesn't matter what you grab) and then rapidly move your mouse around while holding the object.

The error is 100% reproduceable, ending with a crash - but it actually happened to me to also experience a BSOD while trying to cause this.
I think the problem here is solveable by locking the location of the selected object when in 'Rotate around object' mode, but I think there are a couple other solutions possible. Discuss?

**Comment by MitoPL** [comment]
Actually, here's a screenshot of the coordinates after crashing :P
![obraz](https://user-images.githubusercontent.com/46261609/81430533-dc2bcc80-915f-11ea-9d99-c9be929080e1.png)

**Comment by Goober5000** [comment]
I have been bitten by this bug many times in the past, so I can confirm it.

**Comment by JohnAFernandez** [comment]
I think what we need to do is just disable the combination of controls.  They're too unwieldy to use in combination anyway.

**Comment by Goober5000** [comment]
Or use Mito's suggestion:
> I think the problem here is solveable by locking the location of the selected object when in 'Rotate around object' mode

**Comment by tomimaki** [comment]
QtFRED is also affected.

**Comment by JohnAFernandez** [comment]
Currently implementing Mito's suggestion.
