### ISSUE TITLE
F3 Lab Weapons Do Not Display Correctly

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2303]
In the F3 Lab, all weapons seem to only display the first weapon in the list. Issue first shows in the 20201315 Nightly, so I suspect #2301 is the cause. Paging @Goober5000

**Comment by Goober5000** [comment]
These weapons?

![weapons](https://user-images.githubusercontent.com/1878523/77350298-a9925580-6d12-11ea-8f08-5671bf663af2.jpg)

I ran a test using the most recent code in Git.  Is this fixed for you or do you mean something else?

**Comment by MjnMixael** [comment]
Sorry, I should have been more clear. The list appears fine. It's the model/bitmap that does not display properly.

**Comment by Goober5000** [comment]
Thanks.  PR incoming.
