### ISSUE TITLE
Feature request: Target-independant beam deviation.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2304]
As I understand the current mechanics, beams are designed to have the same chance to miss targets of all sizes, by way of their firing angle being multiplied by the radius of their target. While this has utility, it would be very nice to have the option to give beams a cone of fire in absolute terms, allowing for beams that can miss small targets without their field of fire ballooning wildly against big targets.

**Comment by JohnAFernandez** [comment]
Fulfilled!  Woohoo!
