### ISSUE TITLE
How can select the joystisck ?

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#2305]
Hi,

I have 3 devices:

1) Microsoft Sidewinder (with ffb)
2) Throttle
3) vjoy
4) Pedals

How can I choose "vjoy" ?

The game automatically choose always "Microsoft Sidewinder" but I like to use it only for ffb device.

There is a way (command line or other) to choose vjoy ?

**Comment by Goober5000** [comment]
Are you using Knossos or wxLauncher?

**Comment by luca2125** [comment]
Hi Goober5000, 

Many thanks for your response !!!

I use wxLauncher however I have partially solved using these lines:

CurrentJoystick=1
CurrentJoystickGUID=0300000034120000ADBE000000000000

inside file:
fs2_open.ini

There are some small compromise in this mode:

1) The current joystsick can change when I plug and unplug other controllers.
2) The CurrentJoystickGUID change after install windows.

For my opinion can be a good idea if is possible add another line like "CurrentJoystickName1" with default name empty, that if not null override the previous 2 settings.

If in the future you will plan to add a multiple joystick support the next can be CurrentJoystickName2, CurrentJoystickName3, etc..

A solution like this can solve the problem.

This is only a small suggest,

**Comment by Goober5000** [comment]
I am sorry but I am not very familiar with the joystick code.  I do know that some people who have had joystick trouble in wxLauncher have been able to successfully use their joystick in Knossos.

**Comment by z64555** [comment]
FSO selects joysticks by using the Joystick GUID and index saved in the fs2_open.ini or in the registry.

First, FSO checks all joystick devices it finds to see if the CurrentJoystickGUID matches the GUID of any joystick SDL can find.  Should there joysticks that have the same GUID, FSO then checks their index.

The Index is highly subject to how the operating system looks for peripheral devices, and can change during a restart or even when peripherals are moved to a different USB port.

Once the CurrentJoystickGUID is set in the .ini, FSO should be able to find the joystick again should it be removed from its port or even moved to a different port.  However, there is no provisions to account for when the GUID of the stick to suddenly change, which may be the case with third-party virtual joysticks such as vJoy.

To answer the original question, to have FSO select your desired joystick you need to set the CurrentJoystickGUID to the GUID of your joystick.  FSO does not currently have a tool for clients to determine the GUID of their joystick, but you may be able to search through the debug logs to find them.
