### ISSUE TITLE
FRED2 is stripping bank values from missions

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2333]
Present in 20200414, not in 20200409

If a mission specifies weapon banks, then FRED will remove those upon loading a mission. After you set banks, then it will write them out in the first save after you do, but forget them again in any subsequent saves.

For testing I have made a mission with a fenris that has every turret replaced with long range flak. To reproduce, simply open the mission and see if that's what it is equipped with.

[weapon_strip_test.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4478420/weapon_strip_test.zip)

**Comment by Goober5000** [comment]
Your test mission doesn't have any long range flak on the Fenris. :-P

**Comment by EatThePath** [comment]
> 
> 
> Your test mission doesn't have any long range flak on the Fenris. :-P

I must have forgotten to restore it after my last local repro. Whoops.
