### ISSUE TITLE
Wrong number of subexplosions spawned for ships during deathroll while using time compression (using ScreenCam Script)

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#2364]
If you are in the mission space and using any sort of time compression, the amount of subexplosions for any ship during its deathroll isn't the same as when not using any time compression (x1). Especially visible when using the ScreenCam Script with its x0.001 compression.
To recreate: load up any mission and have ScreenCam Script in your game files, reach a moment when some larger ship goes down to 0% hull integrity, and then engage ScreenCam's x0.001 time compression and wait a bit. If you disable the compression, you'll be greeted with a massive cloud of explosions around the ship.

It was mentioned on HLP's Discord that it looks as if the subexplosion spawning is bound to the framerate, not absolute timescale. I don't know, just reporting.

**Comment by JohnAFernandez** [comment]
I have a possible fix for this.  About to be tested.

**Comment by JohnAFernandez** [comment]
It did not end up being a timing issue.  Switching to a higher resolution timestamp did nothing.

So my best guess for this is it has something to do with the model code.  It turns out, the more polies a model has, the more this happens.

**Comment by JohnAFernandez** [comment]
Long story short, there was another script that was spawning fireballs with incorrect timing.
