### ISSUE TITLE
Lab: Override diffuse color also overrides background skybox color

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#2365]
If you use the Lab, view a ship and use a background that uses a skybox, "Override diffuse color" under "Material Overrides" will also change the color of the skybox in the background.
To recreate: launch FSO with MediaVPs mod, enter the Lab, select a ship and a background, then enable the aforementioned option and fiddle with its respective sliders. Retail mission backgrounds and nebula mission backgrounds will not generate this effect, while remaining MediaVPs missions will.

**Comment by Goober5000** [comment]
From Discord:

> the problem is, the overrides are global. if you override diffuse maps, then every diffuse map including the skybox textures will be overridden

> So this is more of a "too much of a hassle to fix" instead of "it's supposed to be like that"
