### ISSUE TITLE
Freetype needs to be bundled into app if possible

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#2370]
In recent macOS distributions (probably starting with Catalina), freetype doesn't seem to be automatically available anymore.  We can probably remedy this by making sure that we bundle the dylib with the app like we do for other libraries on macOS.

`cliff:~/knossos_src [master]  $ ~/Knossos/bin/FSO-20.1.0-20200505/macosx/fs2_open_20_1_0_20200505_7ec425f_x64-FASTDBG.app/Contents/MacOS/fs2_open_20_1_0_20200505_7ec425f_x64-FASTDBG 
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /Users/cliff/Knossos/bin/FSO-20.1.0-20200505/macosx/fs2_open_20_1_0_20200505_7ec425f_x64-FASTDBG.app/Contents/MacOS/fs2_open_20_1_0_20200505_7ec425f_x64-FASTDBG
  Reason: image not found
Abort trap: 6`

Installing freetype from homebrew is a workaround, but I'm not sure we want this to be a habit for users given we've already avoided this with other similar libraries.

**Comment by JohnAFernandez** [comment]
Ok. Since I believe this was only an issue on mac and we merged the prebuilts on mac, this should be closed
