### ISSUE TITLE
In mission going into Controls Config or Hud Config doesn't stop sound.

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#2385]
Minor thing. When you press F2, sound (music, beams etc.) stops playing, but not in Controls Config or Hud Config.

**Comment by tomimaki** [comment]
Dunno if intentionally or not but PR #2100 omitted Controls and Hud Config.

**Comment by Goober5000** [comment]
Is it even possible to get to Controls Config or Hud Config without going through the F2 screen first?  At that point the audio should have already stopped.

**Comment by tomimaki** [comment]
#2703 fixed it.
