### ISSUE TITLE
Enable more features in multiplayer

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#2386]
As mentioned in #1441, there are quite a few features that aren't available in multiplayer despite being used quite often in singleplayer. Since #2207 is close to being ready to merge and the multiplayer version bump soon after that, I thought it would be a good idea to have some discussion about what features that are available in singleplayer would be most desired for multiplayer use.

**Comment by JohnAFernandez** [comment]
@TRBlount what features did you have in mind?  

For myself, I'll guess I'll put it out there that I've been wanting to implement a packet which is written by lua and then sent by fso.

Everything else I wanted to do is pretty much done except for client to client rollback (aesthetics only).

**Comment by niffiwan** [comment]
IIRC multiplayer campaigns don't flow very well, it's more like playing a series of single missions. What about making multi-campaigns behave more like single player?

**Comment by JohnAFernandez** [comment]
Just had an idea about the multiplayer campaigns.  We could have the multi campaign progress save by difficulty and by events completed.  So, if a status in the campaign is reached in medium, it can be picked back up by anyone who has gotten to that point before.  That would take some work, but it could be a long term goal, if anyone starts playing multi regularly.

**Comment by JohnAFernandez** [comment]
Just as a note, Object Update packet upgrade and rollback primaries and secondaries pull request onto taylor's branch is here:  https://github.com/notimaginative/fs2open.github.com/pull/4

**Comment by JohnAFernandez** [comment]
Looks like Red Alert is going to be enabled in multi by the time we get this done.

**Comment by JohnAFernandez** [comment]
Also, I think we should also look into allowing command brief/fiction viewer and briefing cutscenes to the modes that are able to send game update packets (if I'm remembering the name right) so that no one has to do weird workarounds to get those types of text in anymore.

**Comment by notimaginative** [comment]
Command briefs, fiction viewer, red alert, and cutscenes should now be in working order on multi.

Besides campaign progress, are there any another singleplayer things that might be good to add?

**Comment by JohnAFernandez** [comment]
We're now adding directives that previously didn't work.... I think campaign progress is the big thing.

**Comment by JohnAFernandez** [comment]
Pushing this to 21.4 because there are some features we want to add that are definitely not finished.

**Comment by JohnAFernandez** [comment]
We have a lot of issue clutter.  So I am closing this.  We can work on enabling newer features in multi on a case by case basis as they are requested.
