### ISSUE TITLE
FR: Scrolling lists in the Lab?

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#2398]
One problem that is often faced in large mods with many ship/weapon classes and custom fonts larger than standard retail one is the fact that the lists can be too long for the screen to properly display, effectively cutting off the user from some part of available ship/weapon classes. This is also related to the description box, where a description might be too long for the default box size to accomodate, and it isn't fully displayed. Kind of annoying if someone likes to use the Lab as a better version of the Tech Room like I do.

Suggested solutions:
1. Make lists and the description box scrollable, preferably only if their contents are not fitting inside their default sizes,
2. Make lists use multiple columns for their contents if they can't fit inside a single one, in this case the description box would still need to be scrollable or resizeable.

Affected mods: Blue Planet (before GTVA-TEI and UEF-Civ got their separate sections, but Terran race is still cutting it pretty close for a 1080p display), Aftermath: Reboot (due to sheer amount of ships in Terran race and the amount of missile classes). Description box problem is specifically visible when trying to read Blue Planet tech descriptions, for example GTD Erebus or GTCv Bellerophon.

**Comment by Goober5000** [comment]
The main problem here is that WMC-GUI does not have a scroll box control.  Such a control would have to be created to make the lists scrollable.

**Comment by EatThePath** [comment]
Instead of a scroll box, could you detect when the box gets too big and split it into multiple pages? Previous/next page buttons seem more easily done from scratch than scrolling

**Comment by MitoPL** [comment]
@Goober5000 Hence I also suggested an alternate solution in the form of multiple columns and resizeable boxes. @EatThePath 's idea also seems interesting, and might be easier for you guys to execute?

**Comment by MjnMixael** [comment]
Solved with imgui
