### ISSUE TITLE
Feature request: Let -weaponspew cover all weapons

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2407]
Limiting it to just player-usable weapons makes plenty of sense for certain uses, but it'd be useful to me at least if I had the option of making it cover all weapons. Maybe -weaponspewall?

If nothing else it'd help in keeping tabs on exactly how many weapon slots a mod stack is using.

**Comment by Goober5000** [comment]
Only because this is a fairly minor change...

**Comment by EatThePath** [comment]
resolved by #2409 and #2467
