### ISSUE TITLE
Assert when using $Substitute to mix flak and non-flak

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2415]
Weapon A does not have the flak flag, but uses $Substitute: to fire weapon B part of the time. Weapon B has flak. 

This appears to behave just fine on non-debug builds, but on debug builds trips an assert that appears to be there to verify flak effects are only being asked for from flak turrets. 

https://fsnebula.org/log/5ecad881cb0d3321adc98627

Log is running on a recent build of the multilock test branch, because that's what I had a full debug of already built, but I've verified I hit the assert in current nightly fast debugs. 

I'll see about building an isolated test case for this.

**Comment by EatThePath** [comment]
Repro: grab https://api.fsnebula.org/mod/etp_bugtest and launch the FlakTest mission. Should get the assert immediately.

**Comment by JohnAFernandez** [comment]
From discord: I put not a bug because as it stands, it's not a bug.  If you want to add that behavior you should probably do some solid testing to make sure it doesn't have unintended consequences.  I'm not saying we shouldn't enable it.  We just need to make sure it's reasonably safe to.

More experienced coders feel free to override me.

**Comment by Goober5000** [comment]
I agree.  Mixing weapon types is probably a recipe for mysterious and hard-to-solve errors.

**Comment by MageKing17** [comment]
Any time user data trips an assertion is a bug; if flak and non-flak shouldn't be mixed like this, we should provide a useful error message instead of letting an assertion trip.

**Comment by Baezon** [comment]
The compatability should be fairly simple in this case based on the investigation I've done before. Ill try to see if I can make this work.
