### ISSUE TITLE
Feature Request: Tech-Remove-Intel-XSTR

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2425]
What I'm trying to do is have an Intel entry update as the campaign progresses. There may be a better way to do this, but this is my current idea of a way that might be simple to implement. With Tech-Remove-Intel, I can remove the old entry and use Tech-Add-Intel to add a new entry that essentially replaces the one that was there previously.

In my specific case, I have an Intel entry for a faction that is opposing the player, but 2/3rds through the campaign they are a full on separatist movement and the original entry no longer makes sense.

**Comment by Goober5000** [comment]
This should be fairly easy to do.  And, in fact, most of the infrastructure is already in place; it's just a matter of writing the sexp and setting the flag.

I believe that adding one entry and removing the old entry is, indeed, the best way to do this.  Making tech room entries "changeable" would open up a huge coding can of worms.

**Comment by Goober5000** [comment]
Implemented in #2426.
