### ISSUE TITLE
FR: Mission cleanup SEXP

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2428]
It would be useful to have a way to clean up long lifetime derbis and weapons fire from a mission. I can imagine wanting to clean up derbis, lasers, missiles and possibly particle effects, though those last are usually not long lived enough to be an issue.

Personally my immediate needs would be met by one SEXP that does all of these, but I could imagine people wanting to only do one of these. Ether having three or four separate SEXP or one that takes as many true/false arguments seem equally valid

My immediate use case is for missions where the passage of time or a shift in location is implied without breaking it into two missions, such as a mid-mission jump. There may be other cases where this is useful, too.

**Comment by Goober5000** [comment]
We already have the `remove-weapons` sexp, but we don't currently have a `remove-debris` sexp.

**Comment by EatThePath** [comment]
> 
> We already have the `remove-weapons` sexp

Ah, my bad then. Looks like it's another one that's missing from the wiki sexp pages
