### ISSUE TITLE
Multi: Available player orders are different based on whether the game is peer-to-peer or standalone hosted

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#2440]
What it says on the tin, standalone servers for some reason often do not let you give ai orders.  As a minor bug I have not investigated the cause, I'm posting on here because I don't want to forget.

**Comment by notimaginative** [comment]
Perhaps related to http://scp.indiegames.us/mantis/view.php?id=1815?

**Comment by JohnAFernandez** [comment]
Well, it turns out that it was a different cause than I thought.  It's actually the Host settings.  Standalone defaults to Team Leader/Wing Leader, and it was *that* option which was buggy because it would disallow communication if you were a wing leader instead of enabling it!  Peer to peer defaults to another setting that I cannot remember.

See the pull request for that broken line.

**Comment by JohnAFernandez** [comment]
This got fixed!
