### ISSUE TITLE
Mainhall PA Sounds Need to STAHP

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2458]
2 bugs, possibly related.

1st, when the game is minimzed while you're in the mainhall the music will pause. PA sounds will continue to be selected and played endlessly in the background.

2nd, if you have a longer PA sound and switch to another campaign that has a different mainhall the first PA sound will continue to play until the end of the loop. Instead it should be stopped immediately.

**Comment by Goober5000** [comment]
Same bug.  Testing a fix now.

**Comment by Goober5000** [comment]
Ok, not quite the same bug.  Definitely related though.

**Comment by Goober5000** [comment]
Fixed in #2464.
