### ISSUE TITLE
Recent change in are-waypoints-done-delay evaluation before subject arrival

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2478]
On 20200610 and any earlier builds I've tried, if are-waypoints-done-delay is tested before a ship or wing is present in the mission it evaluates to CAN'T EVALUATE. On 20200615 it evaluates to ALWAYS FALSE, which can quite break missions made with the assumption of old behavior so easily that I assume it was not an intentional change.
Test case:
[a_sexptest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4783152/a_sexptest.zip)

On old builds this mission results in a passed directive in short order, and on the current one it's a failed directive in even shorter order.

**Comment by wookieejedi** [comment]
Just noting here that the two functions `sexp_are_waypoints_done_delay` and `sexp_are_waypoints_done` have not changed at all, so it appears to be something else. Any ideas @Goober5000?

**Comment by Goober5000** [comment]
It's possible that a bug slipped through, but these PRs are reviewed multiple times by myself, and at least once by one other person.

But the function in the current codebase is written as expected:
```
	if (ship_entry->status == ShipStatus::NOT_YET_PRESENT)
		return SEXP_CANT_EVAL;
```

I'll take a look at the test case.

**Comment by Goober5000** [comment]
Okay, it turns out this is simply due to the old sexp supporting ships and wings vs the new sexp supporting only ships.  I'll code up a fix.
