### ISSUE TITLE
Physics 'Whack' From Weapons Applying to Docked Parent Ships

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#2525]
Whack from weapons such as morning stars, shockwaves and beams will toss about small ships like an Isis. However, even when docked with a very large ship, like an Orion, both ships will whack with the same vigor if the Isis is whacked, resulting in the Orion wildly smashing any unfortunate ship in the vicinity. It's uh, pretty wack.

**Comment by Goober5000** [comment]
This bug has been known for a while.  See the `ship_apply_whack` function in shiphit.cpp.

The core problem is the need to calculate an inverse moment of inertia for the entire collection of docked ships.  Solve that problem and you've solved this bug.
