### ISSUE TITLE
Bug: Mission crashes debug build

### ISSUE THREAD

**Issue by nf33** [scp-fs2open/fs2open.github.com#2531]
[use_fast_debug_Mission_Crash.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4849494/use_fast_debug_Mission_Crash.zip)
[crash_mission1_.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4849234/crash_mission1_.zip)
Mission crashes debug build, scanning 2nd transport, the contents in the scan message crashes the game when set to <none> works when set to <wingman>.

I am using fastdebug on a clean version of knossis.  Also bugs out on other debug versions.

[Google drive link](https://drive.google.com/file/d/1p6hem37li-lG5WkRNFX082KEhnouQxFL/view?usp=sharing)

**Comment by Goober5000** [comment]
This was fixed by #2534.
