### ISSUE TITLE
Bug: Mission, Ravana doesn't jump in on is-cargo-known-delay.

### ISSUE THREAD

**Issue by nf33** [scp-fs2open/fs2open.github.com#2532]
Here is mission... scan the aper, the hidden Ravana (Exitor 1) has a short delay where it should jump in after the scan of the Aper, it is under the arrival cue on the ship properties.

[Exitor_doesn't_jump_in_missions.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4849855/Exitor_doesn.t_jump_in_missions.zip)

**Comment by Goober5000** [comment]
This is most likely due to the bug that was fixed in #2529.  Try the next nightly build, after this one, and see if it's fixed.  Or you could make your own test build by checking out the source code.

**Comment by Baezon** [comment]
Looks like you were right. Tested again, is-cargo-known-delay works as an arrival trigger on 6/30 properly.
