### ISSUE TITLE
FR: Allow Pilot/command text messages to fire before message audio is finished

### ISSUE THREAD

**Issue by nf33** [scp-fs2open/fs2open.github.com#2533]
So I've been having issues with audio timing and getting "the heads and text to line up as it were".  I was thinking of mixing all the conversation into one audio file, the problem becomes is that the next pilot/command text messages won't be played until after the audio.  

Could we get a message SEXP feature plays only one audio file, but cycles through text/pilot animations based on timers, aka then you only have to synch the visuals to the audio via timers.

Example, right now how events work on messages, is that message plays <From command or wingman> and audio and animated head plays, the issue is the animated head and text need to be divorced from audio, so they can be timed, allow blank messages (with no audio) to fire over an already playing previous message (that had audio) with timers.

For instance say 0 minutes to 2 minutes is pilot 1, then 2 to 4 is pilot 2, etc, that would go help instead of having to time multiple events, you only need one audio file and then time the talking heads to that one file.

That is a quick fix without having to fiddle with the sound system.

**Comment by Goober5000** [comment]
That is far from a quick fix.  You are asking for a large number of hacks to override core features of the messaging system.  I suggest you learn to work within the boundaries of the existing tools.

Alternatively, there are scripting functions that allow modifications of the HUD and special-purpose HUD guages.  You can use these to start and stop animated heads, but you would be responsible for the timing and sequencing.
