### ISSUE TITLE
controller selection

### ISSUE THREAD

**Issue by luca2125** [scp-fs2open/fs2open.github.com#2535]
Hi ,

I ask if is possible add another way to select the controller.

Actually to choose the controller must choose the Joystick index (CurrentJoystick=3) and GUID CurrentJoystickGUID:

File: Fs2_Open.ini

CurrentJoystick=3
CurrentJoystickGUID=0300000034120000FB0F000000000000

becouse I have different controllers, often when I connect my controller to other usb ports these values change.

So if you have different mods you need to update many times the file  Fs2_Open.ini of each mod.

A more easy solution can be add another optional parameter that override the previous:

CurrentJoystickName = "Sidewinder Force Feedback 2"

in this way you need the modify the value only the first time.

Do you think is a useful modification ?

**Comment by asarium** [comment]
Sorry but this is not a feature that is likely to be included in FSO. This is a thing that should be handled by the launcher which then passes the correct GUID and index to FSO via the config options you specified.

Having this in the FSO code would only make the joystick settings code more complicated. Maybe you can ask if such a feature could be included in Knossos. That should be in a much better position to determine if the same joystick has been plugged in in a different port using the mechanism you described.

**Comment by luca2125** [comment]
thank you for fast reply :)

About this issue report:

https://github.com/scp-fs2open/fs2open.github.com/issues/2417

can be take in consideration ?
