### ISSUE TITLE
Beam not firing on unknown targets when using beam-free on SJ Sathanas

### ISSUE THREAD

**Issue by nf33** [scp-fs2open/fs2open.github.com#2539]
Note the "unknown" cap ship fires on the sathanas but the sathanas does not fire back when it had it's AI explicitly ordered to.  It did fire one manual beam I forced in the event, but the beam-free-all is not working, even though the AI was given explicit commands to attack the colossus.  Not sure if it's just the Sathanas or it happens to all capital type ships.

[abc_mission.zip](https://github.com/scp-fs2open/fs2open.github.com/files/4863465/abc_mission.zip)

**Comment by Strygon** [comment]
Will investigate asap but I wanted to ask first. Did you check "All Teams at War" in the Mission Editor menu?
If so, did you also check the "beam freed by default" flag? From what I heard, the beam free sexp may act up sometimes.

**Comment by nf33** [comment]
Except you're not getting that Unknowns can fire on hostiles just fine, and the fact that you can manually add beams to fire on unknowns means firing beams works if you setup events to do it manually.  So given we have the source to the game, Unknown should really just be another team with default behavior of enemies just ignoring them.

Now you may ask why I was doing it to begin with, because you want the default behavior to not attack but you want it to respond.  The problem is Unknown is very useful for distinguishing groups of ships that have some sort of importance to the player because they are surrounded in purple.  Neutral ships are basically red and go into the 'hostile target group' when targeting.

So that's why I was using Unknown, it make life easier to know they aren't quite neutral or hostile, it marks them as not being a usual state.

**Comment by Goober5000** [comment]
"Given that we have the source to the game", we know exactly what the teams should be doing and we can confirm the documentation that Strygon found.  Unknown attacks Hostile, but Hostile does not attack Unknown.  The teams are working as intended.  This is not related to manually firing beams because manual firing has nothing to do with the team or IFF system.

If you want every team to attack every other team, you must select "All Teams At War" as Strygon suggested.

**Comment by nf33** [comment]
> "Given that we have the source to the game", we know exactly what the teams should be doing and we can confirm the documentation that Strygon found. Unknown attacks Hostile, but Hostile does not attack Unknown. The teams are working as intended. This is not related to manually firing beams because manual firing has nothing to do with the team or IFF system.
> 
> If you want every team to attack every other team, you must select "All Teams At War" as Strygon suggested.

Except I'm not using it widely enough to justify all teams at war, I'm using unknown just to mark items of interest in the targeting list, when target lists get massive it gets hard to what you want to find quickly.   Either way when scripted to attack the ships should attack, since when manually attacking one beam at a time it clearly works.  So it just didn't make any sense if you can get hostile to attack unknowns using one beam, but not beam-free.

**Comment by Goober5000** [comment]
As I told you, beam-free and manually firing beams are unrelated.  The default team behavior is what it is; it doesn't matter whether it makes sense to you or not.

If you want the teams to behave differently, learn how to mod iff_defs.tbl.
https://wiki.hard-light.net/index.php/Iff_defs.tbl

**Comment by Goober5000** [comment]
As I told you, beam-free and manually firing beams are unrelated.  The default team behavior is what it is; it doesn't matter whether it makes sense to you or not.

If you want the teams to behave differently, learn how to mod iff_defs.tbl.
https://wiki.hard-light.net/index.php/Iff_defs.tbl

**Comment by X3N0-Life-Form** [comment]
Following up on Goober's suggestion, my personal recommendation would be to add new IFFs depending on what you need to highlight (see sample IFF table below).

```
#IFFs

;; Every iff_defs.tbl must contain a Traitor entry.  Traitors attack	
;; one another (required by the dogfighting code) but it is up to you	
;; to decide who attacks the traitor or whom else the traitor attacks.	
$Traitor IFF: Traitor
   
;------------------------												
; Friendly																
;------------------------												
$IFF Name: Friendly														
$Color: ( 0, 255, 0 )													
$Attacks: ( "Hostile" "Neutral" "Traitor" )						
$Flags: ( "support allowed" )											
$Default Ship Flags: ( "cargo-known" )			

$IFF Name: Friendly Blue
$Color: ( 0, 0, 255 )													
$Attacks: ( "Hostile" "Neutral" "Traitor" )						
$Flags: ( "support allowed" )											
$Default Ship Flags: ( "cargo-known" )							
 
$IFF Name: Friendly Dark Blue
$Color: ( 0, 0, 150 )													
$Attacks: ( "Hostile" "Neutral" "Traitor" )						
$Flags: ( "support allowed" )											
$Default Ship Flags: ( "cargo-known" )

;------------------------												
; Hostile																
;------------------------												
$IFF Name: Hostile													
$Color: ( 255, 0, 0 )													
$Attacks: ( "Friendly" "Neutral" "Traitor" )						
+Sees Friendly As: ( 255, 0, 0 )										
+Sees Hostile As: ( 0, 255, 0 )

$IFF Name: Hostile Purple										
$Color: ( 255, 0, 255 )													
$Attacks: ( "Friendly" "Neutral" "Traitor" )						
+Sees Friendly As: ( 255, 0, 0 )										
+Sees Hostile As: ( 0, 255, 0 )

;------------------------												
; Neutral																
;------------------------												
$IFF Name: Neutral														
$Color: ( 255, 0, 0 )													
$Attacks: ( "Friendly" "Traitor" )									
+Sees Friendly As: ( 255, 0, 0 )										
+Sees Hostile As: ( 0, 255, 0 )											
+Sees Neutral As: ( 0, 255, 0 )											
  	
;------------------------												
; Unknown																
;------------------------												
$IFF Name: Unknown														
$Color: ( 255, 0, 255 )													
$Attacks: ( "Hostile" )												
+Sees Neutral As: ( 0, 255, 0 )											
+Sees Traitor As: ( 0, 255, 0 )											
$Flags: ( "exempt from all teams at war" )							

;------------------------												
; Traitor																
;------------------------												
$IFF Name: Traitor														
$Color: ( 255, 0, 0 )													
$Attacks: ( "Friendly" "Hostile" "Neutral" "Traitor" )			
+Sees Friendly As: ( 255, 0, 0 )										
 	
#End
```
