### ISSUE TITLE
Possible SEXP breakage in JAD mission

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2545]
In JAD 2.21, the mission "A Step Forward Into First Place" JAD221-04b has broken. After a race segment color coded enemies spawn. What is supposed to happen is that after you kill the green enemy events switch you to playing Delta 1.  In recent nightlies a few messages play after you destroy green but no switch happens. I have not ventured into the guts of the mission to try to isolate exactly what breaks but this seems like it could be related to the SEXP overhaul.

The mission works properly on 19.0 and the 20200610 nightly, but does not work on 0615 forward

**Comment by AxemP** [comment]
The `get-damage-caused` sexp seems to be the culprit.

https://cdn.discordapp.com/attachments/223511391531827200/729035617647984770/Annotation_2020-07-04_130607.png

`Delta 1 can't hurt it` event triggers, but not `But Holley Can!`, its a fairly straight forward chain, so likely that one.
