### ISSUE TITLE
Playback issue with voice files in CBrief (one page with voice, following page without)

### ISSUE THREAD

**Issue by Kerbrer** [scp-fs2open/fs2open.github.com#2549]
If a page has a voice file and is allowed to play before being interrupted by moving to the next page, which has no voice, then going back to the previous page, the first page's audio will continue for a split second where it left off before starting over.

For a good way to test this, the first mission of Road to Orum'pur's CBrief is an option. Once the rehashed FS1 briefing pages are past, the following pages do not have voice files.

**Comment by notimaginative** [comment]
I'm unable to reproduce this with a current nightly build. Is it still an issue?

**Comment by MjnMixael** [comment]
Tried reproducing this on the latest nightly with the following test mission and could not reproduce. Bug is knocking on 2.5 years old with no response from the creator and no way to reproduce. Recommend closing.
[Untitled.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10428371/Untitled.zip)
