### ISSUE TITLE
Another new SEXP bug.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2552]
This sexp is triggering far earlier than it ever used to. Either the AI is choosing to fire missiles at least 30 seconds sooner after all the sexp changes or one of these sexps isn't returning the correct amount. My guess is it has something to do the the ammo left percent sexps.

The mission works on the May 1 build, but sometime after that it stops. Not gonna lie, I'm getting tired of tracking these down and it's after midnight.
![imagebin](https://user-images.githubusercontent.com/7740469/86718465-ba788580-bfe8-11ea-8cda-7172e8d874a7.jpg)

**Comment by MjnMixael** [comment]
This is BtA: Mefistofele mission 2 (Shell Game), by the way. It's like all the way at the end of the mission. Super annoying to reproduce.

**Comment by Goober5000** [comment]
The `secondary-ammo-pct` sexp works as it should.  @streeeeeeeeeeeee is currently tracking down the date of the bug.

**Comment by MjnMixael** [comment]
The bug begins somewhere between June 15 and July 1.

**Comment by Goober5000** [comment]
Turns out the bug was in the mission, not the sexp. :)

The old version of the sexp returned 0% for ships that were not in mission.  The current mission returns NAN until the ships are actually present.
