### ISSUE TITLE
FR: toggle-asteroids sexp

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#2554]
I would find it useful to be able to toggle asteroid fields on/off for in-mission jumps. I know it generally works well enough to just jump your player and ships to an area far away from the asteroid field. However I have seen instances of AI deciding to make it a priority to fly 20k meters back to the asteroid field to shoot at asteroids. Being able to remove it from the mission would prevent that from occurring.

While my specific request is more to be able to turn asteroids off... I can forsee it being useful to also turn them on.

I suspect this sexp request may not be as simple as it seems.. so I'm open to suggestions on how to actually pull it off. The real goal is to stop the AI from even caring about asteroids that are so far away that you can't see them. So maybe there's a better idea on how to do that than toggling the field on/off.

**Comment by JohnAFernandez** [comment]
Having that freedom and being able to do other things with asteroids is probably something we should eventually tackle.  Probably no one has looked at that section of code in years since it works and is not high priority. I know I haven't. I think my eyes even glaze over if I see asteroid.cop
