### ISSUE TITLE
Using cheats to gain unlimited missile and energy count and repeating a mission leads to the unlimited cheat carrying over to new missions

### ISSUE THREAD

**Issue by Strygon** [scp-fs2open/fs2open.github.com#2582]
Using the ~w "Missile Count/Energy is always full" once or multiple times while repeating a mission may lead to the cheat carrying over to every mission you play from then on. Restarting the game will remove this, so it may be a memory issue.

Note: The missions in question so far where I've noticed this happening have mostly been in-progress missions I have been editing in FRED. The game was not closed between test runs.

EDIT: Does not require interference with FRED to be reproduced. It seems to have a higher chance of occurring when loading larger missions. I successfully reproduced it by applying the cheat in massivebattle1, then loading massivebattle2 without cheats.

Build where this was encountered: 17th July 2020

**Comment by Goober5000** [comment]
This bug has been around ever since FS1, actually.

**Comment by JohnAFernandez** [comment]
Oh, well, we can't have that....

**Comment by Goober5000** [comment]
Fixed by #2584
