### ISSUE TITLE
Saving in FRED changes dockpoint used

### ISSUE THREAD

**Issue by hypercast52** [scp-fs2open/fs2open.github.com#2606]
Ships have an inital status of being docked on the Reliant's (capship) 2nd dock point, saving either using Ctrl S or by menu moves the fighter to the first dockpoint.

https://prnt.sc/tpu1vk

https://prnt.sc/tpu27w

**Comment by hypercast52** [comment]
So did some further testing to see what happened if an AI occupied the first dock point while a player occupied the second, same issue. In fact doing so causes ships to merge. This doesn't seem to carry over to in game as the Crusader doesn't spawn. It also seems to outright "kick" the crusader off the dock point when Alpha 1 moves over. the same issue occurs exactly the same if the AI is in the second slot. It will kick the player off the first point and take over. pics below

https://prnt.sc/tq3tib
pre-save

https://prnt.sc/tq3uso
post save

https://prnt.sc/tq3wg2
crusader shown not attached to anything like it should be

https://prnt.sc/tq3yk0
post launch

https://prnt.sc/tq3z3f
note the lack of a friendly crusader in the area

**Comment by Goober5000** [comment]
I can't reproduce this bug.  What mod is this, and what are the exact steps you followed?

**Comment by JohnAFernandez** [comment]
We figured out what it was.  He had named two dock points the same on the Reliant.  Turns out nobody thought to check for this in Fred.  It was switching to the first dockpoint that matched.
