### ISSUE TITLE
Dumbfiring bombs

### ISSUE THREAD

**Issue by PremiumColt** [scp-fs2open/fs2open.github.com#2616]
I noticed this while playing The King's Gambit. Upon firing a bank equipped with Cyclops, I can dumbfire a second bank of bombs if they're equipped without having to achieve aspect lock. I've narrowed this issue down to starting on either the 26th or 27th of July nightly build (I've downloaded the 26th twice but FSO won't launch it).

Also not sure if related or not, but there's no "ping" sound when aspect lock has been achieved.

**Comment by Goober5000** [comment]
This sounds like #2207 is the culprit...
