### ISSUE TITLE
Proposal: Update DDSUtils to DX10/11

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#2633]
Our current implementation of DDS is using the headers defined in the standard for DX7. We could support additional block compression techniques and texture arrays if we were to update the current implementation to DX10/11.

**Comment by Goober5000** [comment]
What would updating the implementation entail, and what are the prerequisites?

**Comment by TRBlount** [comment]
The current implementation is based on the DX7 implementation, using the CFILE readers instead. The interface between `ddsutils` and the rest of the code, pretty much just BMPMan, would remain unchanged, the contents of the functions would need to be modified somewhat and the headers would also need to be changed to allow for the allocation of the DX10 header. The MS Docs have existing C++ implementations that people are free to use, we'd just need to modify them to use CFILE and be a bit safer across different compilers (MS only guarantees that the utils on the MS website work with VS 2013 and later).

**Comment by Goober5000** [comment]
Is DX = DirectX?  Why do we even still have that in the engine?  I thought we switched over to OpenGL.

**Comment by TRBlount** [comment]
We don't have DirectX. There are different versions of the DDS utilities corresponding to different versions of DirectX, and that is what I am referring to.
