### ISSUE TITLE
`current_target_is_locked` is not properly updated

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#2685]
The `current_target_is_locked` field of the `ai_info` struct is not properly updated.  This can be seen easily in the FSPort training mission btm-05, "Advanced Training #2".  The mission stalls after the "Notice the red indicator moving towards your target." message.  It is supposed to detect aspect lock via the `( special-check 0 )` sexp.  This checks `Player_ai->current_target_is_locked`.

This was noticed by MjnMixael on recent builds and is almost certainly due to the multilock merge.

**Comment by bangstk** [comment]
Looks like this broke again, it's not working anymore in Nightly 2020-10-14. Might have been sooner than that, but that's a very recent nightly that should have this commit

**Comment by Goober5000** [comment]
Calling @TRBlount

**Comment by PhantomHoover** [comment]
Resolved by #2830
