### ISSUE TITLE
FR: Nebula rendering enhancements & configurability

### ISSUE THREAD

**Issue by Durandal-Thoth** [scp-fs2open/fs2open.github.com#2689]
As per discussion with The_E, Goober5000, & Axem -

- [ ] 1. Ability to fade nebula poof bitmaps in and out when toggled via sexp. Again, you can add or remove the bitmaps, but they immediately appear and disappear which is quite jarring when you're trying to do a natural transition.

- [x] 2. Ability to use an RGB color pick for nebula background instead of the presets. This one is probably less important, but would make everyone's lives easier and give people more freedom in color design for their nebula missions. Incidentally this would also circumvent the need for .pcx files as a color palette for the background.

- [x] 3. Ability to configure transparency, scale, rotation, density, velocity, etc of different nebula poofs individually via nebula.tbl. Right now, nebula textures need to be created a very certain way and match the background color in order to avoid looking too janky when fading in and out at the edges of the screen (which shouldn't even really be necessary). Ability to control these parameters per bitmap would allow a wider variety of art styles to be employed. As an example, [this](https://cdn.discordapp.com/attachments/433363226105741315/748326665670754354/unknown.png) may look great as a still image, but current rendering means these high quality poofs pop in and out of existence in an unrealistic looking fashion.

**Comment by Baezon** [comment]
2. Partially implemented with a SEXP `nebula-change-fog-color` in #3319, actual UI support for a color picker should be a goal for qtFRED at least, though.

3. Implemented in #3507

**Comment by Goober5000** [comment]
1. Implemented in #5612
