### ISSUE TITLE
Bug:: QtFRED And SCP_String

### ISSUE THREAD

**Issue by TheForce172** [scp-fs2open/fs2open.github.com#2715]
I am getting this error when trying to run QtFRED from Knossos. It seems to be happening when trying to parse command lines.
![image](https://user-images.githubusercontent.com/2040992/92311585-37f05000-efb0-11ea-9199-7ff915dd6647.png)

and this similar error appers when trying to change the cargo of a ship in QtFred,
![image](https://user-images.githubusercontent.com/2040992/92311597-4f2f3d80-efb0-11ea-84e5-667f8084ca22.png)
I thought it was something wrong with the code I wrote but givein the fact it is happeng elsewehre I doubt it.
they both seem to be some sort of issue with handling/deallocation of scp_string as for the cargo one it happens when it is trying to tidy the string

**Comment by Goober5000** [comment]
Is this still an issue?

**Comment by TheForce172** [comment]
I actually worked out these were two separate issues, issues two is the string wrangling issues we've seen elsewhere which is an issue with the QT code itself being exceptionally fragile and not being able to handle any deviation from std::string. Issue one was actually old Knossos passing bad flags data to QtFred.

**Comment by Goober5000** [comment]
Okay.
