### ISSUE TITLE
Radar shows infinity symbol as asterisk

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#2721]
Guessing this is related to #2706.

![radar](https://user-images.githubusercontent.com/1878523/92531392-2c916480-f1fc-11ea-859b-0cc9d49f6f54.jpg)

**Comment by JohnAFernandez** [comment]
Now that I know what I'm looking for to make sure it works, I'll figure out what should change to properly remove this limit.
