### ISSUE TITLE
FS1 COOP UP Doomsday crashes on 20.1.X builds

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#2732]
This mission is working fine on 19.0.0 builds but crashes on every 20.1.X builds.

I tried to pinpoint the reason but i couldt find the reason, all i can tell is: Is not related to red alert, removing red alert does nothing, and this only happens on multi setting, if i set the mission back to single player it works.

[coopsm2-10a.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5204988/coopsm2-10a.zip)

**Comment by JohnAFernandez** [comment]
Ok.  Let me run it through a debugger.
