### ISSUE TITLE
FR: Sparkle Sparkle; beams that spawn particles

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2746]
You could make really cool effects if beams could spawn particles along their lengths, assuming the number of particles didn't become a performance issue.

I would like to be able to define different spawning for an event at beam activation, a continuous process while the beam is firing, and an event at beam shutdown.

Configurable properties I would want, settable independently for each of those three contexts:

Radial and linear velocity ranges, So you can make particles that race towards and away from the emitter, and outward from the beam or lingering in it's path

Distance range from beam center to spawn particles in, with both a minimum and maximum. I'd want to be able to spawn particles only in the center of the beam, or in a hollow tube around it, or anything in between

Density of particle spawning in terms of particles/meter, and for the continuous stage, particles/meter/second.

**Comment by EatThePath** [comment]
Subsequent thoughts: An additional wrinkle would be getting the particles to inherit the lateral motion of slash beams. The effect of this not happening could look plenty cool so if I could only have it one way I'd go without, but it seems worth mentioning if it turns out to be an easy to implement option.

**Comment by Goober5000** [comment]
This would require some annoying special-case code changes, but is pretty straightforward to do in scripting.  It would be much better to use a script for this feature.

The "flaming debris" script spawns particles on debris chunks, so you could use it as inspiration for spawning particles on beams.  Use the recently rewritten version of the script (which is still in 00_Testing and hasn't officially been released yet).  It uses modern hooks and API features whereas the legacy version of the script uses 10-year-old API functions that are rather inefficient.

For your purposes, the `On Beam Fire` and `On Beam Collision` hooks will be helpful, along with `gr.createParticle`.
