### ISSUE TITLE
Adjust play-sound-from-file and close-sound-from-file to specify that they need numeric variables

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#2758]
At the moment the two SEXPs do not specify what type of variable they need but the code needs a numeric variable and shows a warning if that is not the case.

To improve usability, that requirement should be added to the SEXP description.

**Comment by Goober5000** [comment]
Working on this.  Also going to patch the sexp_tree popup dialog and sexp syntax checking.
