### ISSUE TITLE
Only one swarm or corkscrew missile will track target

### ISSUE THREAD

**Issue by notimaginative** [scp-fs2open/fs2open.github.com#2767]
Equip Tornados or Hornets, lock onto a target and fire. Only one of the missiles will track the target with the rest just going off into the distance.

Confirmed to be the result of fixing #2724.

**Comment by Goober5000** [comment]
DahBlount can't catch a break. :P

**Comment by PhantomHoover** [comment]
I think it would be prudent to revert the problematic change for now. This bug is a lot more severe than the one it fixed.
