### ISSUE TITLE
Some localization requests for NTP

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#2786]
Heyya everybody,

during the development of [NTP](https://www.hard-light.net/forums/index.php?topic=96944.0) i found out, that it would be nice to have some additional features :).

1.) I would like to see that the $command sender entry in mission files is always set, even if the default command is used. Also it is missing a support for XSTR by default.
Right now i have the problem, that this line vanishs or the manually added XSTR string ids are deleted if i update a mission file.

2.) As i try to make Callsigns also translateable in some cases i would actually prefer that the change-callsign-SEXP works exactly like the change-alt-name-SEXP as this would make things much easier for a translation event that is applied right at mission start. Right now, Alt-Names are changeable at the mission start even the corresponding object is not in the mission. Callsigns however are not. They can only be changed after the object is in the mission.

3.) Translateable Jump Nodes. An enhancement of the Display Name feature. I would like to have a Jump Node where Display Name also works :). (Really, i changed Jump Node names much more often than i have ever changed wing names)

The following ones are more of "nice to have" than i would really need it for myself:
4.) Actually support for non-retail languages that can be activated via fs2open.ini. 
I tried to include Nikigori's Japanese Mod in NTP. But that failed as FSO does not recognize "Japanese" as a language at all, even i have string tables that begin with #Japanese and also used a "Japanese" language entry in fs2open.ini.
Is there actually any way to change that behaviour? 
Or have i to work with the default languages only, which would not be a big issue right now however, as languages like Japanese or Russian use their own font set anyway which are incompatible to German, French etc. So it would not be a big deal to use the strings of another language. 

4a.) To make them compatible to each other, the Fonts.tbl would need support to set language-specific font settings. So that the game is able to use different font settings for the different languages.

Greetings,

Novachen

**Comment by MjnMixael** [comment]
1 and 2 look to be duplicates from #1730 
3 is resolved by #5401
I think 4 is already working? 
4a wouldn't be too bad. I will look at that if the rest of 4 is already in place. Please advise

**Comment by MjnMixael** [comment]
Upon further investigation, 4a already exists. I think this ticket can be closed. I will do so later today if I do not here back.

**Comment by MjnMixael** [comment]
I'm way late on following through, but this looks to be all completed. Closing.
