### ISSUE TITLE
Bug: Hud has lost background color

### ISSUE THREAD

**Issue by bangstk** [scp-fs2open/fs2open.github.com#2811]
Hello;

Sometime between 3.8.0 Final and 19.0.0 the code responsible for drawing the HUD gauges transparency has changed, resulting in the loss of colored background for all gauges.

If I had to guess I think this only affects paletted .ANI gauges (e.g. all retail gauges), as they define their inner section with the color blue. This is probably being mapped to blank color rather than semi transparent dark color causing this issue.

I think this hurts readability of the HUD especially around nebulas and busy space backdrops, and of course looks pretty different from retail.

This affects the hud graphics from both FS1 and FS2 retail vps.

The effects are much more visible if you view these images on a dark background than on a white webpage:

3.8.0:
![fso_hud_3_8_0](https://user-images.githubusercontent.com/4380573/96362220-c56ba780-10f9-11eb-90e4-79f85e471842.png)

19.0.0:
![fso_hud_19_0_0](https://user-images.githubusercontent.com/4380573/96362222-c7ce0180-10f9-11eb-825e-584a54f70e2a.png)

**Comment by bangstk** [comment]
Also this affects the training messages. Normally they have a grey square behind them, now they have nothing but the text itself

**Comment by bangstk** [comment]
Just from a quick look at the code, I think the issue is in packunpack.cpp->line 158 and 259

`if (pix >= 15) {`
`bit_8 = 0;`

I think this should be 

`if (pix >= 15) {`
`bit_8 = 17;`

"pix 15" is the last palette index, which is the blue color I mentioned earlier. The code assumes this should wrap around back to color 0 (all black) but I think it should actually be color 1 (dark grey). Setting it to 17 makes it the same result as 
`bit_8` = (ubyte)(1 * 17);
which is the translation code for color index 1

In commit 72a797f73219f709a4617480bdf53c86c721491f this change was introduced, it looks like in the code that commit replaced it indeed mapped color index 15 to color 1 rather than color 0.

**Comment by wookieejedi** [comment]
Excellent detective work. Thanks for all your digging, do you have the setup to make a PR so this useful information can be formally reviewed?

**Comment by bangstk** [comment]
I got a build environment set up to test this and it indeed fixes the problem. I'll make a pull request soon.

I think the retail hud-transparency-decreasing-with-increased-gamma behavior would be better for a separate pull request some other time since it's a different issue & might have been removed intentionally. It also wouldn't be compatible with non-paletted HUD graphics without further work

**Comment by wookieejedi** [comment]
Excellent, thanks. If no one else beats me to it I'll take a look at it this evening.
