### ISSUE TITLE
Diaspora crashes after mission 3 debrief, unable to pack vertex buffer

### ISSUE THREAD

**Issue by Dowjin** [scp-fs2open/fs2open.github.com#2816]
From Diaspora latest release bundled with FSopen 3.6.13

Finished the special mission, mission 3 "Shadow Walking", upon finishing the debrief and clicking to continue it crashed and gave me the following error: "

Unable to pack vertex buffer for 'Col_BS_Sobek.pof'

ntdll.dll! NtWaitForSingleObject + 12 bytes
KERNELBASE.dll! WaitForSingleObject + 18 bytes
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>
fs2_open_Diaspora_R1.exe! <no symbol>

"

Breaking into debug froze it and then the task manager when I tried to just kill it.

Upon restarting the game and going to briefing, it picked back up with the briefing for mission 4.

**Comment by The-E** [comment]
3.6.13 is an ancient build. We do not accept bug reports for builds this old unless they can be reproduced using current release or nightly builds.
