### ISSUE TITLE
Bug: Multilock broke FS1 missile lock indicator animation

### ISSUE THREAD

**Issue by bangstk** [scp-fs2open/fs2open.github.com#2826]
This one is just another HUD cosmetic issue. The FS1 missile lock indicator (4 spinning triangles) are supposed to spin indefinitely when locked on, while in current nightlies it gets stuck on the last frame and sits there looking like this while flashing:

![fs1_lock_broke](https://user-images.githubusercontent.com/4380573/96989738-1ad9f700-14f4-11eb-896f-c4a4a8cb4544.PNG)

When multilock was added, it switched the lock animation code to a new function renderLockTrianglesNew in hudlock.cpp.

There is a variable "loop_locked_anim" that is set by whether the fs1 or fs2 hud is used. I think the new "time elapsed" code in renderLockTrianglesNew is causing this if statement to never be true:
`if(Lock_anim.time_elapsed < Lock_anim.total_time)`

Therefore it never conditionally calls hud_anim_render() with the loop parameter set to 1 so the animation stops on completion instead of looping even when "loop_locked_anim" is true

Also: in retail FS1 this indicator never blinks on and off either, this could be something also controlled by "loop_locked_anim" if there is interest in making it even more accurate to FS1

**Comment by Goober5000** [comment]
Did #2830 fix this issue also?

**Comment by bangstk** [comment]
Thanks, can confirm it is correct now!
