### ISSUE TITLE
Non-capships have very little to no debris

### ISSUE THREAD

**Issue by bangstk** [scp-fs2open/fs2open.github.com#2834]
Something I noticed while checking out those other HUD bugs I reported, ships like fighters, cargo, transports, etc. have practically no ship model debris anymore compared to retail/3.8.0, even on fairly empty training missions. 

It seems like the debris chunks are blowing up nearly immediately on spawning or very soon after. A good mission to compare is "The Place Of Chariots" by blowing up the herc coming at you and then blowing up some cargo and the Amazon freighter. They pretty much just have the explosion sprite and that's it.

I don't think this is caused by there being a lot of objects because even in the drone fighting in Training 2 or 3 I see that the drones just have the explosion sprite without the engine and front parts flying into space. Sometimes one piece might appear but then blows up less than half a second later, compared to retail and 3.8.0 when all pieces fly off forever.

Perhaps related to the dynamic debris/soft limit changes in #2649 and #2695? Something might be triggering the soft limit at all times regardless of how much debris there is. Capships don't seem to be affected, though I noticed capship debris was specifically exempted from these limits

This is observed with Nightly 20201025.

**Comment by Goober5000** [comment]
I suppose that's possible.  Can you test the nightly builds before and after those changes to confirm whether the bug appeared at that time?

**Comment by bangstk** [comment]
Thanks for looking at it, fighter explosions look way better now!
