### ISSUE TITLE
FR: Allow all mouse buttons to be used for controls

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#2844]
I use a Logitech M570 to play FreeSpace, which has the normal two buttons and scroll wheel, plus two extra buttons. In FreeSpace, I can bind the left and right mouse buttons as Button 1 and Button 2, as well as pressing the scroll wheel as Button 3, and they work perfectly. I can also bind scrolling the wheel up or down as Button 4 and Button 5, but I whatever I set these to, I never get an effect in game. I also can't bind the extra mouse buttons at all.

I'd very much like to use as many of the buttons on my mouse as I can. I remember much the same happening with retail copies of FS2.

**Comment by z64555** [comment]
This feature should already be in the engine, it should be able to support left, right, middle, the scrollwheel up and down, and two other buttons.  I've labeled it as a bug for now and will try to track down the issue.

**Comment by Svedalrain** [comment]
Correction: Scrolling up is Button 6, scrolling down is Button 7

**Comment by boogiebogus** [comment]
I can second this issue. I can only bind buttons 1, 2, and 3 - the others just don't work. Being able to use these would be really helpful for m&k gameplay.
