### ISSUE TITLE
FR: Sticky afterburners

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2867]
It'd be neat to have an option on afterburners such that once activated they don't turn off until fully depleted, and also can't be activated unless they're over a certain percentage of max change.

**Comment by z64555** [comment]
So, what, real-style afterburners which give you increased acceleration during their use and allow a higher top speed?

Making the afterburners "on" and "engage above X throttle" doesn't seem like a good control scheme to me,

**Comment by EatThePath** [comment]
What I'm thinking about would still be the same FS style afterburners engaged the same way, but they'd be more of an emergency button to displace hard all at once rather than something you tap a lot during dogfights. Which talking about it now might work best if you could change the other handling characteristics of the ship while active.

If I were to use this feature myself, I'd make burners that burn out in a couple seconds at most but give you much stronger effect than standard ones.
