### ISSUE TITLE
FR: -pilot command line flag

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2869]
When repeatedly relaunching a mod to test changes, the fewer clicks the better. Launching a mission from command line already gets a lot, which is good, but picking the pilot that way too would remove half the remaining ones at worst, and all of them at best.

Alternately one could have an option to always pick the last pilot again at launch and make the player click on the pilot room if they wanted to switch.

I haven't looked at the code but I would imagine one of these would be within my own coding reach if nobody else jumps on it or decides it'd be a bad feature, but if so it'll not be right away, so on the issue stack it goes.

**Comment by z64555** [comment]
IIRC, that's the only hiccup when doing testing on a specific mission.  You can have it auto-launch into the mission, bypassing the main menus, but you still need to select a player.

This feature should be straightforward to do.

**Comment by EatThePath** [comment]
the only other hiccup is if for some reason you have the wrong campaign selected from running some other mod last it'll give you the popup about that, but then it'll go straight to the mission after you do without sending you to campaign select. It'd be nice to have that popup be suppressed when you're launching a mission, but it can be fixed by just picking the right campaign anyway as far as I know, so it's a much smaller issue

**Comment by Svedalrain** [comment]
It looks like there's already a way to automatically select the last pilot. It seems to have be linked to some of the commandline flags for multiplayer. I presume adding an commandline option in cmdline.cpp that simply sets Cmdline_use_last_player = 1 will suffice.

See playermenu.cpp line 850 for the function that selects the last pilot.

**Comment by asarium** [comment]
There is already the `-benchmark_mode` option for this which skips the pilot selection. However, it quits the game after one mission is played so this may not be ideal for mod development.
