### ISSUE TITLE
#Command does not send any message

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#2887]
As reported in the [NTP release thread](https://www.hard-light.net/forums/index.php?topic=96944.msg1905231#msg1905231), some dialogues were missing, especially in SM1-03.
I found out, that this only happen with messages, that are send by "#Command".
I encountered this error also in SM1-04... but SM1-01 & SM1-02 aswell SM1-05 is working fine however. Thought it had a connection with the "Scramble Mission" flag as it only affected this kind of mission... but even after i disable the flag the messages did not appear.

First i thought i made an error in the development, but after even my workaround from previous translations did not work i dig deeper into this. This problem was not there in older builds!

I was able to pinpoint, that this bug was introduced with revision 1d471e2. So the build from 11th May 2020 (how unfortunate) is causing this.
EDIT:
To pinpoint that even further, the problem is the "$check communications for non-player ships:" flag for the ai_profiles. After i have deactivated it, it works. So it seems, that "#Command" is being recognized as an actual ship in some missions...

I can not exactly tell why the unaltered SM1-03 from the MediaVPs is working. Maybe the reason lies in the translation stuff i've introduced.

**Comment by Goober5000** [comment]
Is it all messages sent by `#Command`, or only certain messages?

**Comment by Goober5000** [comment]
I'm not really able to test the mod because of localization issues, but is it correct that `#Command` is being localized to `1718, "Placeholder"`?

**Comment by NovachenFS2** [comment]
> I'm not really able to test the mod because of localization issues, but is it correct that `#Command` is being localized to `1718, "Placeholder"`?

No, in the 0.2.1 release 1718 got a proper "#Command" string. And in 0.2.0 i used the $CommandSender function as i had activated the "Override #Command for event messages" flag. My first guess was, that it was caused by this.. together with the scramble mission flag. But no.

In the said mission it affected all messages by #Command. In other missions #Command worked properly, even translated.

**Comment by Goober5000** [comment]
The reason is that you need the `#` for Command messages.  So `#Placeholder` would be sent, but `Placeholder` would not be sent because there is no ship called Placeholder.

Yesterday I tested the first 60 seconds of SM1-04 from your mod, and #Command worked, but I was running in English.

**Comment by NovachenFS2** [comment]
> The reason is that you need the `#` for Command messages. So `#Placeholder` would be sent, but `Placeholder` would not be sent because there is no ship called Placeholder.
> 

I know. Actually the "Placeholder" should not be used, as i do not have activated the feature, that #default is used from the tstrings.tbl?
In this case the value from the mission file should be used?

But for 0.2.1 you will not encounter this error, as i have disabled the $check communications for non-player ships:" flag in general. It appears in 0.2.0.

**Comment by Goober5000** [comment]
Well I just tried your 0.2.0 on the latest build, in German, and it works:

![Clipboard01](https://user-images.githubusercontent.com/1878523/99148319-0bfae600-2655-11eb-9c9e-0cdd1bc6c52e.jpg)

**Comment by Goober5000** [comment]
It looks like the actual mission has the same problem: you have `Kommandozentrale` instead of `#Kommandozentrale`.

Nevertheless, the message still plays in 0.2.0, in German, using the latest build:

![Clipboard01](https://user-images.githubusercontent.com/1878523/99148584-9abc3280-2656-11eb-9bd3-2c35d9ba28b3.jpg)

**Comment by NovachenFS2** [comment]
> It looks like the actual mission has the same problem: you have `Kommandozentrale` instead of `#Kommandozentrale`.
> 
> Nevertheless, the message still plays in 0.2.0, in German, using the latest build:
> 
> ![Clipboard01](https://user-images.githubusercontent.com/1878523/99148584-9abc3280-2656-11eb-9bd3-2c35d9ba28b3.jpg)

It does not have a # beforehand, because this entry is translated via $CommandSender in the mission file, which is without #
Nevertheless, the Problem is most prominently in SM1-03. The whole dialogue between Command and Alpha 2 is missing there.

**Comment by Goober5000** [comment]
> It does not have a # beforehand, because this entry is translated via $CommandSender in the mission file and the Override #Command for event messages. In this case it is without the usage of a #-symbol

Command senders which are not ships should have the # symbol.  That is literally the purpose of the # symbol in message sources.

> Nevertheless, the Problem is most prominently in SM1-03. The whole dialogue between Command and Alpha 2 is missing there.

Ok, that helps.  The missing # symbol caused an invalid memory access which caused that part of the code to be skipped.  When I fix that, the Command messages are displayed.  See #2891.

However the # symbol should still be added because the message system may rely on the # symbol in unknown ways.

**Comment by NovachenFS2** [comment]
> Command senders which are not ships should have the # symbol. That is literally the purpose of the # symbol in message sources.
> 
> However the # symbol should still be added because the message system may rely on the # symbol in unknown ways.

If you create a mission and set a command sender in the mission specs, the result in the mission file was always $CommandSender <YourEntry> it never add a # there.
Alternatively the "Override #Command for event messages" is buggy as the # is not added in the code.

**Comment by Goober5000** [comment]
> If you create a mission and set a built-in command messages sender in the mission specs , the result in the mission file was always $CommandSender YourEntry. There was never a #.

It is up to the mission designer to use a regular name for a ship, or a #-symbol name for a special sender.  FRED will not automatically add the #.  FRED can't read the user's mind.

> Would that even work if you change that entry to "#Command"? I mean, if i use "Something#Other" as a command source, only "Something" would be displayed as a # already seems to be automatically used for the generic messages. Would a "#Command" not result into a "##Command" actually and so into a name, that is not displayed at all?

The game will follow the regular rules.  The # symbol at the beginning of the name means a special Command sender.  The # symbol in the middle of the name means characters that are truncated.  I think ##Command would not be displayed, but I have not tested it.
