### ISSUE TITLE
Silent CTD with certain combinations of ship-vanish and other SEXPs

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2912]
In the particular repro case, ship-vanish is called in an event before a team-wide alter-ship-flag happens. If the order is reversed, there is no crash. @JohnAFernandez indicates other similar combinations are likely possible.

Minimal repro mission attached. Should crash after 3 seconds.

[flag.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5577000/flag.zip)

**Comment by Goober5000** [comment]
Fixed by #2913.
