### ISSUE TITLE
Crash on a specific particle effect set up

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#2928]
This effect will cause a crash when used, it seems when deleting a weak particle pointer? It's quite deep in the particle code, so it's difficult for me to diagnose, so perhaps @asarium could shed some light on it. I'm *fairly* sure the effect has been set up properly/legally.

It is meant to spawn 3 invisible particles, which after a 1 second randomized delay, spawns another invisible particle, which then spawns two effects simultaenously. The middle man particle is required so that the two effects line up even despite the randomized delay, since if they are both given a random delay they will not necessarily trigger at the same time.

Test files attached.

[test-part.txt](https://github.com/scp-fs2open/fs2open.github.com/files/5600180/test-part.txt) (tbm)
[test-wep.txt](https://github.com/scp-fs2open/fs2open.github.com/files/5600187/test-wep.txt) (tbm)
[emptybitmap.txt](https://github.com/scp-fs2open/fs2open.github.com/files/5600192/emptybitmap.txt) (eff)
![emptybitmap_0000](https://user-images.githubusercontent.com/17305613/100302952-648d8580-2f69-11eb-9dea-01653ce4f73f.png) <- emptybitmap_0000.png

```
$Effect: HgnFlak
	$Type: Sphere
	+Filename: emptybitmap
	+Size: 1.0
	+Lifetime: 1.0
	+Velocity: 100
	+Number: (1 3)
	+Duration: Onetime
		+Trail Effect: $New Effect
		$Type: Cone
		+Filename: emptybitmap
		+Size: 1.0
		+Lifetime: 1.0
		+Deviation: 0.1
		+Velocity: (0)
		+Number: 1
		+Direction: Incoming
		+Duration: Always
		+Delay: (0.01 0.99)
		+Effects per second: 1.0
			+Trail Effect: $New Effect
			$Type: Composite
				+Child Effect: $New Effect
					$Type: Single
					+Filename: exp04
					+Size: 40.0
					+Lifetime: 6.5
					+Duration: Onetime
				+Child Effect: $New Effect
					$Type: Single
					+Filename: exp05
					+Size: 40.0
					+Lifetime: 0.5
					+Duration: Onetime

**Comment by asarium** [comment]
I used the supplied files but for me it appears to work as intended without crashing. I have AddressSanitizer enabled so I would assume that it would catch memory related issues.

You appear to have caught the crash in a debugger. Do you have a stacktrace of that?

**Comment by Baezon** [comment]
I'm uh not actually sure how to get a proper text stacktrace from a running MSVC process so I hope this screenshot will do.

![Untitled](https://user-images.githubusercontent.com/17305613/100398456-a1ff1b00-301c-11eb-8479-5716cc70bb23.png)

**Comment by asarium** [comment]
I opened a PR with something that might go wrong in that code but that is a very unlikely edge case. Maybe you could try it again with that branch?

Although my changes will just discard the trail in that case instead of crashing the engine.

FYI, you can also select all lines and then copy that via the usual Ctrl+C. That will create a text stack trace.

**Comment by Baezon** [comment]
Alas, still crashes, even with that check.

>	fs2_open_20_1_0_x64_AVX-DEBUG.exe!std::_Ref_count_base::_Decwref() Line 656	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!std::_Ptr_base<particle::particle>::_Decwref() Line 905	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!std::weak_ptr<particle::particle>::~weak_ptr<particle::particle>() Line 1643	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!std::weak_ptr<particle::particle>::operator=(const std::weak_ptr<particle::particle> & _Right) Line 1647	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!particle::SourceOrigin::moveToParticle(const std::weak_ptr<particle::particle> & weakParticlePtr) Line 129	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!particle::ParticleSourceWrapper::moveToParticle(const std::weak_ptr<particle::particle> & ptr) Line 68	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!particle::effects::GenericShapeEffect<particle::effects::ConeShape>::processSource(particle::ParticleSource * source) Line 129	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!particle::ParticleSource::process() Line 338	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!particle::ParticleManager::doFrame(float __formal) Line 188	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!game_simulation_frame() Line 3588	C++
 	fs2_open_20_1_0_x64_AVX-DEBUG.exe!game_frame(bool paused) Line 3947	C++

**Comment by asarium** [comment]
I just randomly managed to reproduce this bug while working on something else. At least the stack trace I got was very similar...
