### ISSUE TITLE
FRED comments, I beg you

### ISSUE THREAD

**Issue by GeneralBattuta** [scp-fs2open/fs2open.github.com#2930]
I'm doing some very complicated events and I just can't keep track of all the nested Whens and Wherefores.

It would be amazing to be able to enter short comments that you could see in the event window. Just lines of text that wouldn't be parsed by the mission as SEXPs. For example, like so

-WHEN
--true
--do nothing
The above event is a placeholder, use it later.
Below is the control event for Colossus turret ROF.
-WHEN
--is-ship-colossus(Colossus)
--set-turret-rof(99999999)

This would be HUGE for my short term progress.

**Comment by Baezon** [comment]
Duplicate issue of #2931 (despite the earlier number that one came first)
