### ISSUE TITLE
FR: Event comments

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2931]
Request from Battuta, relayed due to account issue
> I'm doing some very complicated events and I just can't keep track of all the nested Whens and Wherefores.
> 
> It would be amazing to be able to enter short comments that you could see in the event window. Just lines of text that wouldn't be parsed by the mission as SEXPs. For example, like so
> 
> -WHEN
> --true
> --do nothing
> The above event is a placeholder, use it later.
> Below is the control event for Colossus turret ROF.
> -WHEN
> --is-ship-colossus(Colossus)
> --set-turret-rof(99999999)
>
> This would be HUGE for my short term progress.

**Comment by naomimyselfandi** [comment]
So, one simple way to do this is to add some new SEXP operators - `comment`, `comment-number`, and `comment-boolean`, let's say, that all evaluate their first argument, and accept and ignore any number of string arguments. That doesn't require any major changes to FRED (actually, at least the latter two could be done using Lua SEXPs, but that'd be a kludge and a half) while still making it relatively easy to enter inline comments.

@GeneralBattuta, in the short term, I've been working around the same issue with `script-eval-block` and Lua comments, eg. `( script-eval-block "--[[this is a placeholder event" "use it later]]" )`.
