### ISSUE TITLE
Manage asteroid fields dynamically during a mission via SEXPs

### ISSUE THREAD

**Issue by LightblueMobius** [scp-fs2open/fs2open.github.com#2932]
**Asteroid Field** parameters are fixed and cannot be changed during a mission. This leads to a number of relevant drawbacks in mission design.

For instance, I may wish to trigger the _Inner Box_ and more aggressive asteroids under specific circumstances, yet the parameter managing that particular setting is fixed for the entire mission and cannot be edited. A similar limit affects asteroid speed, types, size and so on. All parameters are pre-determined in FRED and cannot change during the mission.

Another major drawback is experienced should the mission have stages _other_ than the one involving the asteroid field itself. One such scenario is a mission where we jump to an asteroid field, or jump out from it at some point. While setting various stages across huge distances in FRED somehow helps "hiding" the asteroid field, the problem isn't solved at all. Asteroid fields can be noticed and extra measures have to be implemented in order to make them untargetable (e.g., HUD radar range limits). Also, the game still treats them as a valid feature of the mission even when though they're no longer needed, so the engine may experience unnecessary slowdowns by loading asteroids which no longer serve a purpose in the mission itself.

For this reason, I think one or more SEXPs could be used to manage all these parameters dynamically during a mission, and eventually cause an asteroid field to be created from scratch or disappear when the mission no longer requires it.

**Comment by Goober5000** [comment]
Is this satisfied by #4857 and #4860?

**Comment by MjnMixael** [comment]
#4860 will almost certainly cover this. I don't think it'd look pretty to suddenly change the size of the inner or outer box parameters but it should work without issue. The game will probably instantly try to clear out asteroids within the inner box or if the outer box size is reduced. However if the outer box is increased, FSO will just fill it over time, iirc. I remember reading some code that tried to prevent spawning asteroids when the player is looking in that direction.
