### ISSUE TITLE
Particle Effects FR: Ability to offset location of spawn point/region from the source of the effect, as with pspew

### ISSUE THREAD

**Issue by Kestrellius** [scp-fs2open/fs2open.github.com#2936]
The $pspew functionality in weapons.tbl has an option (added in 3.6.14) to offset the spawn location of the particles from the projectile spawning them, using vector syntax. It would be very useful to have the same option for the particle effect system, on a per-effect basis. (This would allow nested effects to have different locations, despite being part of the same parent effect.)

**Comment by bryansee** [comment]
It would be like this.

[weapon pspew.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6144158/weapon.pspew.zip)

**Comment by The-E** [comment]
Like what? Posting a zip with two source files isn't useful, Bryan. If you want to contribute code, make a normal merge request.

**Comment by BMagnu** [comment]
This was implemented by #6264
