### ISSUE TITLE
Add a fourth argument to ai-disarm-ship which doesn't prevent other ships from performing a regular attack

### ISSUE THREAD

**Issue by LightblueMobius** [scp-fs2open/fs2open.github.com#2943]
Surprisingly, me and community member **Nyctaeus** found out that a single wing performing a "disarm" order against any enemy ship on a battlefield can lead **all** friendly ships to effectively ignore the target of said wing. It turns out this is due to the code interpreting the ai-disarm order as the _incipit_ of a capture operation, therefore a ship that is meant to be disarmed (and consequently captured) should not be destroyed. In our case, the target is a ship that must be destroyed, and a particular wing is deployed to weaken its defenses.

Although this was solved thanks to Battuta's input, which recommended a separate event forcing the affected ships to be unprotected several times per second, this AI behavior could be handled genuinely via a fourth argument to the **ai-disarm-ship** SEXP, instead of unprotect-ship.

_"Please note that this goal may call "protect-ship" on the target to prevent overzealous AI ships from destroying it in the process of disarming it.  If the ship must be destroyed later on, be sure to call an "unprotect-ship" sexp._

_Takes 2 arguments...
1: Name of ship whose turret subsystems should be destroyed
2: Goal priority (number between 0 and 200. Player orders have a priority of 90-100).
3 (optional): Whether to attack the target even if it is on the same team; defaults to false.
**4 (optional): Whether to apply a "protect ship" flag once the order is triggered; defaults to true."**_

**Comment by Goober5000** [comment]
Wing Commander Saga had this problem too.  It's a bit more complicated than that; not only is the ship protected, but any ship attacking it has its goal removed.  Their solution was to add `+Ignored on cripple by:` to all ship types.

**Comment by Goober5000** [comment]
This is handled by #5512.
