### ISSUE TITLE
The fireball limit is not that high and local subspace missiles behave badly when it is reached

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#2945]
Ran into this recently. Subspace portals are fireballs, only 200 fireballs are allowed at any time(MAX_FIREBALLS defined on line 32 of fireball\fireballs.cpp), and when that limit is reached it just stops creating new ones when asked. 

So, what happens if a local subspace missile(LSSM) is fired under these conditions? It just flies straight ahead until it times out, and then dies. Now if a LSSM tries to re-enter the mission space when there are no fireballs available it handles the situation much more gracefully, but the exiting behavior is pretty rough and also the most likely to be seen by the player.

You may ask, who is going to have more than 200 SSMs fired at once? To which I answer: this guy right here. But it's not a burning need, so I'd consider this a fairly low priority thing.

**Comment by JohnAFernandez** [comment]
This is fixed, wth
