### ISSUE TITLE
Warning/Error dialogs not clickable if FSO starts in full screen

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#2949]
The issue identified in #1886, and fixed in #2139, seems to be back.  Was SDL upgraded again?

**Comment by z64555** [comment]
Doesn't look like the libsdl subdir has been touched since #2139 so something else has changed.  Need to blame this on a revision somehow and that would require a reliable method of inducing all types of affected dialogs.

**Comment by z64555** [comment]
@Goober5000 Would you please outline exact steps to reproduce this?  I've been using both Knossos and MSVC, in fullscreen, fullscreen window, and using a modified player file .json to trigger an error popup, in each cases I'm able to click on the popup in Windows.

**Comment by Goober5000** [comment]
Well this is odd.  In the most recent builds, dialogs are perfectly clickable.  Maybe it got fixed. ¯\_(ツ)_/¯

**Comment by Goober5000** [comment]
Closing until I see it again.

**Comment by SelfGamer** [comment]
For me, even with the latest nightlies, this still occurs (OS is Windows 10)
As far as trying to reproduce this:
1. Don't have the -window or -fullscreen_window options.
2. Cause an Error
3. Lose focus on the FSO Window
Now the buttons are not clickable anymore. As long as, once the error happens, FSO keeps focus, the buttons will still be clickable. FSO losing focus _before_ the error pops up is similarly not an issue.
I suspect that this is because the Popup suspends the UI context in a way that it can't be given back focus, making buttons unclickable

**Comment by z64555** [comment]
hmmm, so, to lose focus on FSO window, maybe tab out to something else before the error triggers?

**Comment by SelfGamer** [comment]
If you tab out _before_ the error occurs, it will work fine.
Cause an error, tab out, and you can't click anymore.
_Some_ errors also cause this on their own, but not all (I've managed to get this to happen automatically with a script with a syntax error, causing an error during startup)

**Comment by z64555** [comment]
Hmmm. I'm still having trouble to consistently show this behavior.  I know I've had it happen in the past, which is in part why I've somewhat superstitious to always run in windowed or fullscreen_window while debugging, but I can't seem to find an error or warning dialog that'll constantly trigger this.

Could you perhaps attach a plr, .csg, or .fs2 file which would cause an error or warning?

**Comment by SelfGamer** [comment]
Attached is a tbm file (renamed to txt cause github: [tobreak-sct.txt](https://github.com/scp-fs2open/fs2open.github.com/files/5656376/tobreak-sct.txt) ) that causes an Error through Lua on startup. These kinds of errors occur early enough that the window does not get in focus, so buttons are not clickable either way.
However, an interesting discovery I made as well was that the knossos window position has an effect on this (how?!):
If knossos is on my main screen (where FSO also starts up), the issue occurs. If knossos is on the secondary screen, it does not.

**Comment by Goober5000** [comment]
Here is a file that will trigger a warning on ship parsing.
[buggy-shp.tbm.txt](https://github.com/scp-fs2open/fs2open.github.com/files/5656547/buggy-shp.tbm.txt)

**Comment by z64555** [comment]
Alright, thanks, looking into it

**Comment by z64555** [comment]
Linking the SDL post I made here for reference: [https://discourse.libsdl.org/t/sdl-showmessagebox-and-sdl-showsimplemessagebox-deadlocks-the-parent-window/28435](url)

**Comment by SelfGamer** [comment]
As an addendum: I've narrowed down the issue to it happening exactly then, when the knossos window would intersect the dialog box.
If they intersect even by a single pixel, knossos is in focus (which kills the dialog focus), if not, the dialog has focus.
