### ISSUE TITLE
Scripting FR: Keep Collision Overrides consistent for Ship-Ship and other collisions

### ISSUE THREAD

**Issue by SelfGamer** [scp-fs2open/fs2open.github.com#2953]
After testing and looking through the code, I notice that even with an Override for a Ship-Ship collision set, the physics will still get applied (only the damage + UI effects get overridden). This is inconsistent with how Ship-Weapon / Ship-Debris / Ship-Asteroid collision overrides work, as those will also disable relevant physics.
Is changing Ship-Ship overrides to work like the other overrides is the correct approach? I would prepare a PR then.
If not, what is the intended way of nullifying Ship-Ship collisions from lua?

**Comment by Goober5000** [comment]
Your PR looks like the correct thing to do.

**Comment by SelfGamer** [comment]
PR #2953 merged, issue fixed
