### ISSUE TITLE
FR: mission flag for preventing the protection that comes with disarm or disable orders

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#2968]
If any ship receives an order to disarm or disable a target, whether by sexp or from a player, that target becomes protected. The intent seems to be for any disable or disarm order to precede capturing the ship, and the protection prevents it from being killed by AI.

Mission designers often run into that protect, and I as a player used to in missions like Forced Entry, since the best way to remove the turrets from a ship is to order fighters to disarm it, whether or not the intent is to capture or kill it later.

The automatic protect is handy for missions involving capture. A mission flag to disable that protect would allow disarm and disable orders on ships for all other purposes without affecting retail missions.

**Comment by EatThePath** [comment]
Overlaps with #2943 though, though is broader in scope and proposes a different solution

**Comment by Baezon** [comment]
I think both would be decent approaches, since player orders will still be an issue otherwise.

**Comment by LightblueMobius** [comment]
#2943 mentions the "disarm" order only but "disable" has the exact same issue, apparently. Code-wise I have no idea what the best solution could be between an entirely new SEXP or additional arguments to existing SEXPs.

**Comment by Goober5000** [comment]
An ai-profiles flag makes the most sense, I think.  (You can have different profiles for different missions.)

However, the difficult part is not the flag, but finding all the places where disarm/disable targets are protected/ignored.

**Comment by wookieejedi** [comment]
There is now a way to set this for AI profiles, along with new orders if you do not want to set it via table, so I reckon this can be closed.

**Comment by Goober5000** [comment]
Yup, #5512 takes care of it.
