### ISSUE TITLE
FR: Add an optional scaling paramter to gr.drawMonochromeImage and gr.drawImage

### ISSUE THREAD

**Issue by SelfGamer** [scp-fs2open/fs2open.github.com#2995]
It would be nice to make it possible to draw images at other sizes than their native resolutions with the lua API.
An alternative to this would be to allow gr.loadTexture to resize the texture at loading time.

**Comment by Goober5000** [comment]
The `gr.drawImage` function does have the ability to draw at other sizes, but the `gr.drawMonochromeImage` function does not.  I looked into adding this capability several months ago, but the two functions use completely different graphics APIs, so the solution is not straightforward.

**Comment by SelfGamer** [comment]
Would it be feasible to implement texture resizing during loading?

**Comment by Goober5000** [comment]
I couldn't say.  I'm not a graphics coder.

**Comment by SelfGamer** [comment]
Alright, not actually nessecary it turns out. Currently solveable in lua, even if ugly:

```lua
local loadedTex = gr.loadTexture(textureName)
local x = loadedTex:getWidth() * scale
local y = loadedTex:getHeight() * scale
local renderTex = gr.createTexture(128, 128, TEXTURE_STATIC)
gr.setTarget(renderTex)
gr.drawImage(loadedTex, 64-x/2, 64-y/2, 64+x/2, 64+y/2)
gr.setTarget()
```
