### ISSUE TITLE
Scripting FR: Weapon shockwave information

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3005]
If reading weapon damage dynamicly in script, it needs to be known if the inner and/or outer radius of the weapon is set to get accurate numbers. Currently that's not accessible as far as I can see in the documentation. An isAreaWeapon bool function would also fill some of the needs, but I can imagine people wanting to know the actual radius

**Comment by Kiloku** [comment]
This was fixed in #3630 by exposing the radii of weapons
