### ISSUE TITLE
Accessing the player's target every frame in lua script causes Lua Error when restarting after death

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3007]
As the title says, I have a script that does things every frame based on the player's current target. When the player dies, I have safety checks in place that detects the player's target isn't valid on the last frame of the game state, so that's all good. But if the player hits "Quick Start Mission", on the first frame of the next game state `hv.Player` reports as a valid object of breed Ship, but trying to touch `hv.Player.Target` in any way, even to check if it exists, gets a `Lua Error: Could not find index 'Target' in type 'object'`. 

This happens if you quick start after dying. It does not if you restart without dying, or if you return to the mainhall after dying and then restart the mission.

I'm really not sure how to safety-check around this, and CTD on quickstart is a pretty painful flaw in this script. 

This seems like something @asarium might have insight into.

I built a repro script table. Just drop it in, die, and quickstart.
[restart-crash-sct.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5727813/restart-crash-sct.zip)

**Comment by Goober5000** [comment]
Crash confirmed.  I caught the error and looked through the call stack but I really can't see an obvious explanation.  On the frame of the crash, `Player_obj` is a valid object with a type of `OBJ_SHIP` and a correct reference to the correct ship.

This is just speculation, but could the Lua type hierarchy have been disconnected, so that the "object" doesn't realize it's also a "ship"?

**Comment by asarium** [comment]
Do we have a stack trace of the crash?

**Comment by Goober5000** [comment]
Do these help?
![err](https://user-images.githubusercontent.com/1878523/105641712-9466e580-5e53-11eb-880b-64979ee6c600.png)
[stack.txt](https://github.com/scp-fs2open/fs2open.github.com/files/5863056/stack.txt)

**Comment by asarium** [comment]
Does `Player_obj` change? The significant thing is probably that the hook is called from the loading callback and the player hook variable might still point to the "old" value from the previous mission.

**Comment by Goober5000** [comment]
`Player_obj` does point to the same address before and after the restart.  However that may not indicate a problem.  The `Objects` array doesn't move in memory, and since the mission is parsed identically it would not be surprising if the ship and object array indexes stayed the same.

**Comment by asarium** [comment]
The "Player" value in Lua is only updated in `game_frame` though so if we run into the loading callback hook then the value stored in Lua might still point to the old value in memory and cause inconsistencies that way.

**Comment by Goober5000** [comment]
Well, I'm not really sure how to test that.  That exceeds my expertise with the FSO Lua API.
