### ISSUE TITLE
Particle Effects FR: Ability to create particles with geometry

### ISSUE THREAD

**Issue by Kestrellius** [scp-fs2open/fs2open.github.com#3047]
I'd like to be able to generate particles which, rather than being simple sprites, can have arbitrary geometry. This would function much like 3D shockwaves do at present -- instead of specifying an animation file, you'd specify a .pof, and the .pof would have associated model data and an animated texture.

This would open up lots of interesting possibilities. The original impetus for this request, however, was weapons like the FSU Akheton, which leaves a trail of rings in its wake. These rings are meant to be three-dimensional objects and should not look the same from every angle, so if you see them from the side they look wrong. Being able to specify .pofs would handily solve this -- and do much more besides.

**Comment by asarium** [comment]
This is not really in the scope of the particle system since that is very specifically optimized towards rendering textured, rectangular geometry that is aligned to the screen. Throwing in arbitrary geometry would only make this system more complicated and slower.
