### ISSUE TITLE
Particle Effects FR: Greater control over random distributions for randomized parameters

### ISSUE THREAD

**Issue by Kestrellius** [scp-fs2open/fs2open.github.com#3051]
At present, it is only possible to use a uniform random range for most randomized fields in the particle table. It would be very useful if, instead, for each field, four parameters could be set: maximum, minimum, mean, and standard deviation.

This would effectively combine the functionality of uniform and normal ranges, and would allow much finer control over the way particle effects behave. (For example, I've often wanted to create impact effects that will usually create only a few sparks, but sometimes create many more, and found myself unable.)

The most relevant fields here are particle number and particle velocity, but size and lifetime would also be useful.

**Comment by BMagnu** [comment]
This was implemented by #6314
