### ISSUE TITLE
Scripting FR: Expose Persona

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3070]
The scripting API doesn't provide easy access to a ship's persona. Having access to it would provide two benefits: reading a fighter's persona makes it easier to send scripted messages, and being able to write to it allows ships to be given non-wingmate personae (eg. support ships).

**Comment by Goober5000** [comment]
Yeah this would be a good things to have.  Should be simple to implement too.
