### ISSUE TITLE
Submodel-destroyed visible all time in some models

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#3078]
![screen0764](https://user-images.githubusercontent.com/18072803/103466272-c1881280-4d43-11eb-92e7-2802a6acd863.png)
![screen0765](https://user-images.githubusercontent.com/18072803/103466277-c51b9980-4d43-11eb-90b8-c07cb291642b.png)
In this case Setekh, but I saw this on other models like Hecate, Rahu; from BP: Solaris, Erebus (turret debris), Katana, Narayana. Oddly enough, like Hecate, sometimes debris is visible in tech room and briefing popups but not in mission.

Bisected to this:
```
88c1d8a02a9062c394262aca3888e2debb15c22a is the first bad commit
commit 88c1d8a02a9062c394262aca3888e2debb15c22a
Author: Goober5000 <ipw47@mailbox.org>
Date:   Sat Dec 12 02:04:02 2020 -0500

    consolidate model instance code

 code/ai/aibig.cpp                     |   3 +-
 code/ai/aicode.cpp                    |   5 +-
 code/ai/aiturret.cpp                  |  13 +-
 code/decals/decals.cpp                |  11 +-
 code/hud/hudtarget.cpp                |   1 -
 code/menuui/techmenu.cpp              |  21 +-
 code/mission/missionparse.cpp         |   2 +-
 code/missionui/redalert.cpp           |   2 +-
 code/model/model.h                    |  53 ++---
 code/model/modelanim.cpp              |  54 ++---
 code/model/modelcollide.cpp           |  13 +-
 code/model/modelread.cpp              | 381 ++++++++++++----------------------
 code/model/modelrender.cpp            |  35 +---
 code/network/multi_obj.cpp            |  24 ++-
 code/network/multimsgs.cpp            |  16 +-
 code/object/collideshipship.cpp       |  10 +-
 code/parse/sexp.cpp                   |  40 ++--
 code/scripting/api/objs/subsystem.cpp |  10 +-
 code/ship/ship.cpp                    |  61 +++---
 code/ship/ship.h                      |   4 +-
 code/ship/shipfx.cpp                  |  31 +--
 code/ship/shiphit.cpp                 |   6 +-
 22 files changed, 352 insertions(+), 444 deletions(-)

```

**Comment by Goober5000** [comment]
Can you try bisecting again?  That commit doesn't appear to have anything to do with live debris.

**Comment by tomimaki** [comment]
Actually it is not debris, but submodel-destroyed visible all time. And I made mistake, copied commit from another bisection. :(

**Comment by Goober5000** [comment]
Ok.  I think I know how to fix this.  It's most likely another Volition bug that was uncovered due to the refactoring.

**Comment by tomimaki** [comment]
Hm, it fixed models in mission and F3 Lab, but not in tech room or briefing popup.
![screen0007](https://user-images.githubusercontent.com/18072803/103948067-70a85d80-5139-11eb-937c-f8da55524871.png)

**Comment by Goober5000** [comment]
I just checked the Setekh and both the tech room and briefing popup are fixed.  So the Rahu must be a different issue.  Can you point out exactly what is wrong?

**Comment by tomimaki** [comment]
https://youtu.be/e6m97YOg0l4
Check Rahu's hm... butt and hole on side and something like z-fighting .
And Cerberus, Watchdog, Alastor have some weird turret configuration. I thought it's the same bug because it showed after bisected commit.

**Comment by Goober5000** [comment]
That looks like some sort of graphics issue, not a submodel issue.  I would open another ticket for that.
