### ISSUE TITLE
Ships assigned in loadout respawn as default ships.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3101]
[2378.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5790350/2378.zip)
Migrated from Mantis 2378.

Created 2 wings Alpha and Beta with default ships all being Ulys. Set Beta waves to 5. Changed Beta to 4 different ships (random) in loadout screen. When they respawned they all respawned as Ulys not the assigned ship classes.

Mission uploaded. All you need to do is change Beta's ships to something else in the loadout screen, start the mission, press 1 and 2 to destroy the 2 ships, and watch the wrong ships warp in.

**Comment by JohnAFernandez** [comment]
Another flavor of this bug was already fixed..... The other thing is, multi doesn't support having more than 4 fighters in a player wing.  That's a longer term feature, which would take *a lot* of refactoring.

**Comment by MjnMixael** [comment]
I should note that this even affects single player.
