### ISSUE TITLE
FR: Replace-Texture SEXP

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3102]
What it says on the tin. A sexp that can be used to replace a specific texture just like can be done via tables or the ships dialog in FRED.

**Comment by Tnadz** [comment]
I second this initiative.  We've seen a few instances where a texture swap can make a mission incredibly dynamic.  Would love it if a SEXP master was able to work something out with this.

**Comment by wookieejedi** [comment]
Awesome work with @BMagnu's addition. Closing.
