### ISSUE TITLE
Issues with rendering Jump Nodes correctly.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3106]
This bug was created when an issue that caused FPS drops when rendering jump nodes was fixed. The root issue now is that jump nodes render hidden edge lines in their wireframe when they did not before. The easiest example is the FSPort jump node. The lines, some highlighted in red, in this screenshot show the issue even in FRED.
![image](https://user-images.githubusercontent.com/7740469/104107111-a7888b80-527f-11eb-8477-362b75ea360d.png)

This patch was uploaded to [Mantis 2396](http://scp.indiegames.us/mantis/view.php?id=2396) as a possible fix. Here is Valathil's comment on this patch.  

[vajumpnodes.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5791692/vajumpnodes.zip)

> Attached a patch that might speed up rendering by drawing the nodes with vertex arrays instead of seperate lines. Not a final version, might require some cleanup and additional parameters to not interfere with nohtl, just a quick test to see if its faster.

**Comment by Baezon** [comment]
Closing this for now since re-exporting the model makes the problem go away, even if the true cause could not be found.
