### ISSUE TITLE
Weapon glowpoints appear to stay in origin position if using external models

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3110]
Issue migrated from Mantis 2965.

If a ship shows external models for secondary weapons, and the models for those weapons have glowpoints, then the glowpoint effects will not be positioned correctly, instead acting as if the ship is at the mission origin.

I've attached a small test mod to show this error. It contains a modified stock model of the GTF Hercules - with secondary firing points moved to the outside of the model so that the missiles are easily visible to start with - as well as a table that enables external weapon models for the Hercules, and a mission containing both a player and AI Hercules to test with.Once in the mission, switching to external view and zooming out so that the mission origin (to the right and behind the player's starting position) is visible should show the missile glowpoints. They will remain there regardless of where either of the ships is located, but they still respond to their associated secondaries being fired (i.e. firing a secondary will cause the glowpoint to jump backwards and then move forwards slowly, as per reloading of external secondaries). It doesn't seem to matter whether it is the player's or the AI's ship that has the secondaries.MV_Assets from the Media VPs is required as that contains the secondary weapons with glowpoints.
[Externals_test.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5791861/Externals_test.zip)
![screen1554 - 28-11-2013 (arrow)](https://user-images.githubusercontent.com/7740469/104109172-ea9f2a80-5290-11eb-9d4f-79edcf3345bb.png)
![screen1553 - 28-11-2013 (arrow)](https://user-images.githubusercontent.com/7740469/104109175-ef63de80-5290-11eb-952f-dff5a2c92ab6.png)

**Comment by MjnMixael** [comment]
This is no longer on issue on 22.0

**Comment by EatThePath** [comment]
Thanks for updating us on it
