### ISSUE TITLE
FR: Vertical scroll bars for overly long F3 Lab lists.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3115]
As it is right now, if your weapons/ship list is too long, then the list in the F3 Lab will just go offscreen and you cannot access those assets. The solution is to add vertical scrollbars so we can scroll that list.

[This issue is migrated from Mantis.](http://scp.indiegames.us/mantis/view.php?id=2986) [There is also a forum thread regarding it.](https://github.com/scp-fs2open/fs2open.github.com/issues/2786)

**Comment by tomimaki** [comment]
[Some sort workaround](https://github.com/scp-fs2open/fs2open.github.com/pull/1917) for too long list were arrow keys, that could be used to switch to next entry, even if not visible on screen.
But it was lost after rewrite.

**Comment by MjnMixael** [comment]
This is fixed by imgui
