### ISSUE TITLE
Rahu's destroyed gas collector visible on current source in tech room and briefing popup even if it shouldn't

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#3123]
Before:
![screen0021](https://user-images.githubusercontent.com/18072803/104125372-9a8a9b80-5356-11eb-91e2-5fa052ae78bb.png)
After:
![screen0018](https://user-images.githubusercontent.com/18072803/104124812-12ef5d80-5353-11eb-81f9-667a9ab4c4d2.png)

```
88c1d8a02a9062c394262aca3888e2debb15c22a is the first bad commit
commit 88c1d8a02a9062c394262aca3888e2debb15c22a
Author: Goober5000 <ipw47@mailbox.org>
Date:   Sat Dec 12 02:04:02 2020 -0500

    consolidate model instance code

 code/ai/aibig.cpp                     |   3 +-
 code/ai/aicode.cpp                    |   5 +-
 code/ai/aiturret.cpp                  |  13 +-
 code/decals/decals.cpp                |  11 +-
 code/hud/hudtarget.cpp                |   1 -
 code/menuui/techmenu.cpp              |  21 +-
 code/mission/missionparse.cpp         |   2 +-
 code/missionui/redalert.cpp           |   2 +-
 code/model/model.h                    |  53 ++---
 code/model/modelanim.cpp              |  54 ++---
 code/model/modelcollide.cpp           |  13 +-
 code/model/modelread.cpp              | 381 ++++++++++++----------------------
 code/model/modelrender.cpp            |  35 +---
 code/network/multi_obj.cpp            |  24 ++-
 code/network/multimsgs.cpp            |  16 +-
 code/object/collideshipship.cpp       |  10 +-
 code/parse/sexp.cpp                   |  40 ++--
 code/scripting/api/objs/subsystem.cpp |  10 +-
 code/ship/ship.cpp                    |  61 +++---
 code/ship/ship.h                      |   4 +-
 code/ship/shipfx.cpp                  |  31 +--
 code/ship/shiphit.cpp                 |   6 +-
 22 files changed, 352 insertions(+), 444 deletions(-)
```

**Comment by asarium** [comment]
Could you add a screenshot of the "intended" behaviour? Would be good for reference when someone works on this.

**Comment by tomimaki** [comment]
Added. Possibly related are visible destroyed barrels on Watchdog, Cerberus and Alastor. But I'm not sure, still the same commit caused this.
Before:
![screen0022](https://user-images.githubusercontent.com/18072803/104125455-1be22e00-5357-11eb-8c56-a5373b759035.png)
After:
![screen0012](https://user-images.githubusercontent.com/18072803/104125460-1e448800-5357-11eb-8c57-a81516ef5c0a.png)

**Comment by Goober5000** [comment]
I have a hunch that fixing #3124 will fix this as well.

**Comment by Goober5000** [comment]
The barrels are fixed by #3137.  The Rahu's destroyed collector should be too, except I can't see it in either the before or after screenshot.

**Comment by Goober5000** [comment]
Should be fixed.

**Comment by Goober5000** [comment]
Ok, PR #3140 really fixes the Rahu collector.

**Comment by tomimaki** [comment]
I couldn't test it earlier but now I checked Rahu and other models. It looks good.
