### ISSUE TITLE
Allow scaling diffuse lighting or expand current lighting scaling to include it

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3128]
The scaling factors for directional lights are only applied to the specular component of the light. This is counterintuitive to me, if I'm scaling brightness I expect both to be changed.(edit: This comes largely from the labeling of the slider in the F3 lab and the naming of the variable in the code, on rechecking how the command line flags are set up it's made fairly explicit there. But it still feels like a very strange gap to be able to scale ambient and directional specular but not ambient diffuse) Changing this crudely is easy and I've already done it in a test build, I like the results and it aligns with what I expected, but I make this issue in the interest of finding out if such a change is at all desirable, if it has problems I haven't thought of, and what form it should take.

The crude change is just to copy the scaling that is applied to specular light in `gr_opengl_deferred_lighting_finish()`, at line 207 of `gropengldeferred.cpp`. Piece of cake. I assume however that since it was done that way there's a reason why only scaling the specular is desirable, and even if there wasn't, changing how everyone's lighting settings are handled with no way to reproduce their old settings exactly seems bad. 

The alternate ways that I can imagine are either a flag to apply the existing scale factor to both, or a flag to set a new separate scaling factor. I personally prefer the latter, but I tend towards expanding configuration options in general. 

Minimum light in normal FSO: 

![screen0777](https://user-images.githubusercontent.com/4766365/104141123-bc961500-537a-11eb-82f8-8459851397da.png)

Minimum light with my test change

![screen0788](https://user-images.githubusercontent.com/4766365/104141136-ccadf480-537a-11eb-8187-6f96518b83da.png)

**Comment by JohnAFernandez** [comment]
Not a graphics person, but personally, I think the second screenshot looks incredible.

**Comment by EatThePath** [comment]
Further reading and pondering makes me realize the same 'issue' applies to the weapon lighting tuners. A mod maker could presumably do all that tweaking themselves by editing all effects and level lights, but having a single scalar to make broad changes with can often be useful...

**Comment by EatThePath** [comment]
this has been implemented
