### ISSUE TITLE
Weapons/Ships FR: Optional rotation information for weapon external models.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3143]
As it says on the tin. Would need extra info defined in the ship pof on a per firepoint basis.
Clarifying edit:
I am requesting the ability to change the static orientation of weapon submodels for specific firepoints, so that you can have missile rack models mounted on the top, bottom, and side of a ship, for instance. An example of planned use: https://p3d.in/cLXd4

**Comment by Goober5000** [comment]
This is very vague.  What rotation information are you proposing, and how would it be used?

**Comment by EatThePath** [comment]
Essentially I want to be able to associate a uvec with a firepoint, to be used along with the standard vector being the fvec, so that external gun models can be mounted sideways, upside down, etc. My understanding is that there is no way to do this presently.

Could potentially be a table thing instead of a pof thing I suppose, and it'd be potentially nice to have a per firepoint flip flag too, while I'm at it.

Aeesar has talked about his own preferences for solving this same problem, which are very different and as I recall consist of having submodels in the pof for each weapon type and firepoint. I can see the merit in that system too, but even if we had it I'd advocate for augmenting the current external model system with this.

**Comment by Goober5000** [comment]
That would require removing some of the optimizations for that feature.  They currently use a lightweight rotation system that doesn't have some of the infrastructure of full-fledged rotating submodels.

**Comment by EatThePath** [comment]
Would a lack of those optimizations be likely to cause notable problems or loss of performance?

**Comment by Goober5000** [comment]
There would certainly be some degree of performance impact, but I couldn't estimate how much without profiling the code.  There would also be a non-trivial amount of code rewriting necessary.  In order to turn the lightweight system into the heavyweight system, there would need to be additional code infrastructure built.

In other words, it's not just optimization in terms of execution time, it's also optimization in terms of return on investment: incremental gain in feature vs. incremental cost in lines of code.

**Comment by EatThePath** [comment]
In case it's needed, https://p3d.in/cLXd4 provides some context for my request. No matter how you slice them, neither the primary or secondary models are going to work as designed without some rotation capability.

**Comment by Goober5000** [comment]
It's a neat-looking model, but how would the weapons rotate?  They all appear to be fixed in place.

**Comment by EatThePath** [comment]
They don't change rotation during play, but they don't share the same orientation between all of them either. The big missiles are mirrored from one aonther, the smaller missiles are all rotated around their centerpoint, and each of the eight primary firepoint models are rotated differently. Those hardpoints are not mono-weapon mounts either, there's at least four models that could be fitted to them, so even those models couldn't be baked into the fighter's mesh.

**Comment by EatThePath** [comment]
> 
> 
> That would require removing some of the optimizations for that feature. They currently use a lightweight rotation system that doesn't have some of the infrastructure of full-fledged rotating submodels.

I think the question I need to ask is this: Do you think the costs mean this change should never be made? Leaving aside the opportunity costs and if it seems important enough for you or anyone else to put it on the top of your list in the foreseeable future. And past that, is the approach I have in mind of reading an optional firepoint uvec that can be added to pofs the right way to go about it, or is there some other approach that would be better?

**Comment by EatThePath** [comment]
And to be absolutely clear since in rereading this discussion I realize this misunderstanding might have been present since the beginning: I am not requesting weapon models that can actively spin during play, though that would certainly be cool and having mounts attached to animated geo IS on my wish list, that's a separate request. I am simply requesting the ability to turn the external models to different static orientations.

**Comment by Goober5000** [comment]
> I am simply requesting the ability to turn the external models to different static orientations.

That's very easy, very simple, and avoids the whole other discussion.  Thanks for the clarification.

To briefly address the possibility of expanding the rotating weapon model code: I like to keep things as simple as possible.  The existing system addresses all the current uses (with the exception of the initial static orientation you mentioned) and making it a full-fledged rotation would add costs with very little benefit.

Fortunately now I can see that you aren't asking for full-fledged rotation.  A uvec would probably work, but what do you think about a degree offset instead?

**Comment by EatThePath** [comment]
I can't think offhand of any particular reason a rotation value would be notably better or worse, personally. Maybe it'd be somewhat ambiguous what the base position would be for weapons with normal vectors extremely far from straight ahead, maybe? That's something we plan on doing to at least some degree, as well, weapons that fire strongly off-axis. But even then the two options seem pretty equivalent

**Comment by Baezon** [comment]
Implemented in #3469
