### ISSUE TITLE
Graphical issue: Tube lights cut off abruptly at one end.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3146]
Now that tube lights are actually doing something besides acting like sphere lights at their origin some flaws in their implementation are coming to, ahem, light.

The beam tube light cuts off sharply at one end, and only one end, the 'far' end of the light, which is the firing point of a beam. Light extends as you would like past the impact point. The end cap light makes this flaw less visible but does not make it entirely invisible, under the right conditions it can stick out badly. 

![screen0864](https://user-images.githubusercontent.com/4766365/104772825-b1a40180-5739-11eb-81f7-c74798f80901.png)
It is visible here(Everything that isn't a tube light in this scene has been terminated for clarity) both at the very back of the Orion where the shivan beams cut off, and on the ear of the Hecate for the AAA beam.  From this I can also be pretty sure it's not a flat circular cut-off perpendicular to the end of the beam, at least to my eyes. (Edit: Or looking at the shivan beams again, maybe it is, and there's something screwy about the scaling of the very flickery lighting of the pulse beam that's throwing me off. It's possible, there's a lot of data transformation steps along the way giving chances to cross wires.) 

From grappling with the code in `deferred-f.sdr` that handles the light attenuation for tubes (line 55-78) I have a hunch that the nearest-point calculation goes screwy past the end of the beam, but I haven't been able to wring obvious flaws out of it yet.(Ed: The longer I think about this the more I think that's unlikely to be an issue, the proceedure there seems straightforward and sound enough.)

**Comment by EatThePath** [comment]
For the sake of covering the bases, this is a similar setup but with the tube endcap light turned back on, but not the muzzle glow.  It makes it less easily seen, but it's definitely still there.
![screen0870](https://user-images.githubusercontent.com/4766365/104775486-047fb800-573e-11eb-902d-4ae2dd258dda.png)

**Comment by asarium** [comment]
Yep, that is an artifact of the way tube lights are done. The endcap lights hide the issue a bit but is obviously not enough. The proper way to fix this is to augment the geometry rendered for the tube to include two half-spheres at either end.
That should then cover the lighting produced by the two ends of the tube.

**Comment by EatThePath** [comment]
> 
> 
> Yep, that is an artifact of the way tube lights are done. The endcap lights hide the issue a bit but is obviously not enough. The proper way to fix this is to augment the geometry rendered for the tube to include two half-spheres at either end.
> That should then cover the lighting produced by the two ends of the tube.

why then isn't there a similar effect on the other end? I'm quite confident in saying there's no sharp edge asspciated with beam impacts, either a stark one or one partially masked by an endcap light.

**Comment by EatThePath** [comment]
The past images aren't great for showing the fact that the impact side doesn't have this, as all the beams there are punching through. I think this one is, though. 
![screen0881](https://user-images.githubusercontent.com/4766365/104788680-7533ce00-5758-11eb-9dd1-e331598a1877.png)

Here's the wild thing I noticed while getting that shot though, 

![screen0879](https://user-images.githubusercontent.com/4766365/104788716-8a106180-5758-11eb-806f-dbd39919e029.png)
![screen0880](https://user-images.githubusercontent.com/4766365/104788718-8c72bb80-5758-11eb-850a-2361ae993f60.png)

If it's just the tube geo at work, then probably both and definitely at least one of these should be cut off very visibly past the point of impact, shouldn't it? But more than that both are defintely casting light behind the beams just fine and dandy. I don't know the rendering pipeline that well, but I don't know how else to interpert that than them working properly without the half-sphere additions.

Maybe the problem is actually that AAA beams are getting their light radius and scale values out of sync, I think that could produce something like effect. That is something I will look into.

**Comment by EatThePath** [comment]
Following some advice I once saw @The-E give I got RenderDoc and captured some frames to try to figure out what's going on. I still don't know what's going on, but I think I have some more precise questions. Rather than fill this issue with even more slow-loading images, I put them in a imgur album.

https://imgur.com/a/F334TwW

There are three frames there, I'll call them A, B and C in order. Each starts at an event before a particular tube light is drawn, and then goes the drawing of each component light element.

In frame A a beam is heading off to 30km. The cylindrical portion is drawn in accordance to the way they've been described as working, cut off sharply at the end. Then the 'end' sphere at the beam firing point is drawn over it, and finally the 'start' sphere is drawn somewhere presumably off screen.  Sensible enough.

In frame B a beam is drawn between two ships in frame. The cylindrical portion, when drawn, includes lighting clearly outside of the light's mesh. The end spheres then layer more light over it. The cylinder does not act as a hard boundary for the light's influence in this case

Frame C is similar to frame B, but with an engine change that sets the radius of the end spheres to infinitesimally small. I did this to eliminate the possibility that somehow they had anything to do with this, but as you can see the cylinder's light still gets pretty splash and the sphere lights can be confirmed to be crushed down to nothing.

I can't figure out a mental model that allows all these cases to coexist. If a lighting element is only in consideration when it is inside the light's geo, then B and C couldn't happen. If a light is always considered and only discarded based on the test in GetLightInfo, then A couldn't happen. If the end cap meshes are somehow associated with the tube light and their contents are subject to it's attenuation, A and C couldn't happen.

If this does all make sense but you don't have the time or inclination to walk me through how, then I suppose that's that. But as far as I can tell now it makes no sense to me and it's very frustrating.

**Comment by asarium** [comment]
The results are consistent with how deferred shading works.

The basic idea is that geometry is rendered that covers the _screen_ parts where the light may cast light. For every rasterized fragment of that geometry we then look up the position (and other shading parameters) of the fragment that was previously rendered there when the models were drawn.

The interesting part here is that as long as a fragment is covered by the geometry then it will be considered for lighting. In your example, the first scene has a tube light where the viewer is outside the geometry so it only covers about half of the screen. Lighting will only be computed for that half, the other half stays (erroneously) unlit.

The other two examples have the viewer inside the tube so the entire screen is covered by it or the outside of the tube is so close to the viewer that is still covers the entire screen. If you move the viewer to either side of the two ships you should start to see errors in the graphics output.

For a more in-depth explanation I would recommend this tutorial: https://learnopengl.com/Advanced-Lighting/Deferred-Shading
Some things in there are not exactly how FSO works but the general approach and architecture is the same.

**Comment by EatThePath** [comment]
To reiterate some discord conversation: That makes it all fall into place for me, and my current plan is to extend the cylinder mesh past each end by a light radius and eliminate the sphere caps. It'll have a small amount of wasted shading time at the edges and a little extra math to have the right light vector for attenuation calc, but it'd get rid of two extra lights and clear up this issue.

**Comment by EatThePath** [comment]
closed in favor of a full solution proposal in #3161 in the interests of clarity
