### ISSUE TITLE
Pain flashes do not fill screen at super high resolutions

### ISSUE THREAD

**Issue by JadedDragoon** [scp-fs2open/fs2open.github.com#3148]
![screen0018](https://user-images.githubusercontent.com/1294429/104828943-396e3680-5834-11eb-980c-ab8fcba20cd1.png)

As seen in the screenshot above, at resolutions above that of the pain-flash texture the image does not appear to scale.

Resolution is 1440p... full screen windowed. FSO 21.0 RC4

**Comment by z64555** [comment]
Need to look at how the pain flashes are implemented to determine if this is a code issue (bug) or an asset issue (not a bug)

**Comment by Kiloku** [comment]
From what I can tell, pain flashes call `gr_flash()`, which in turn calls `gr_flash_internal()` in `graphics\render.cpp`. There it creates a render material and passes it to `gr_render_primitives_2d_immediate()`. 
There's no reference to a texture file anywhere in that sequence. 

However, the screenshot is from BP, and the pain flash there looks different from how the regular pain flash looks (it shouldn't be vignetted, it just tints the whole screen red). BP has a painflash.png file that's 1920x1080. So I'd say this is probably not a bug.

**Comment by EatThePath** [comment]
I went into the BP mission files and confirmed Kiloku's findings. It's shown as part of that single mission using show-subtitle-image. I play at 1440 constantly and play BP with it, and in general pain flashes work fine. Mod flaw, not engine bug.

**Comment by The-E** [comment]
Yeah, this is a BP issue, not an engine one.
