### ISSUE TITLE
Warn in debug if beams have discarded damage factors

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3156]
Aside from the wiki and in-game testing, it can be difficult to catch that Armor, Shield, and Subsystem factors have no effect for beams by default. It would be useful for debug builds to display a warning if a beam has a tabled damage factor not equal to 1 while $Beams Use Damage Factors: in game_settings.tbl is not true.

However. the retail tables include the targeting laser, an unused fighter beam with 0 damage and non-1 damage factors. All other retail beams have all three damage factors set to 1. Perhaps the warning could be suppressed when using retail data, which could still add a warning to every mod that doesn't disable the targeting laser. Alternatively, the warning could be suppressed for beams with 0 damage, since those damage factors have no effect anyway.

**Comment by naomimyselfandi** [comment]
> Alternatively, the warning could be suppressed for beams with 0 damage, since those damage factors have no effect anyway.

For whatever it's worth, I think that's the best solution. It's the cleanest check, the easiest to explain (`// Avoid a warning for retail's Targeting Laser` or something to that effect), and _always_ avoids issuing a superfluous warning.
