### ISSUE TITLE
EFF without num frames causes CTD

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3157]
If you accidentally create an EFF that has no integer after frames: then FSO will crash to desktop when trying to load it. There will be no warning about what caused the crash. If possible, can we get debug to put a warning about this is the log before the crash?

To test, drop this eff in your retail\data\interface folder and load up the retail Aquitaine mainhall.

[2_mainwalk_0000.zip](https://github.com/scp-fs2open/fs2open.github.com/files/5832190/2_mainwalk_0000.zip)

**Comment by Strygon** [comment]
Having tried to make a fix for this issue, I've discovered that, currently, that is, in the most recent nightlies, the error will be caught by stuff_int and throw a "Expected an int, found..." error that will usually point you in the right direction.

**Comment by Goober5000** [comment]
I'd say the parsing strictness qualifies as a fix for this.
