### ISSUE TITLE
FR: Allow LUA to change active Campaign

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#3158]
Right now, lua can load an existing campaign file for a pilot. However, this only works if such a csg file exists, which is only the case if the campaign has been selected once before. I would like to have this extended as so lua can change the current active campaign of a pilot to any currently available campaign, even if this pilot has never loaded said campaign before.

**Comment by MjnMixael** [comment]
+1

**Comment by BMagnu** [comment]
Implemented by #3261
