### ISSUE TITLE
A plan to revise tube lights.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3161]
This is essentially a follow-up to #3146, but for various reasons it seems better to start a new one and close that. 

Tube lights have an ugly cut-off in certain circumstances. I want to fix them, and @TRBlount  asked me to detail my plan, so here we are.

To recap the current engine situation: When a beam is being fired, two `light` objects are created, a point light at the muzzle and a tube light running the length of the beam. The tube is primarily defined by a radius and two points. 

![image](https://user-images.githubusercontent.com/4766365/105557131-14187700-5cd1-11eb-9ea1-2d8b06257c32.png)

When the rendering functions handle the light, the tube light is translated into a cylindrical lighting volume and two spherical ones

![image](https://user-images.githubusercontent.com/4766365/105557217-44601580-5cd1-11eb-9f01-cd8b59db3604.png)

Lighting attenuation within the cylinder is done based on distance to the nearest point on the vector running along it's center. Since deferred lighting shades fragments if they visually overlap a light's volume in screen space, rather than if they are inside the volume in world-space, if the viewpoint is close enough to the center of the cylinder the full length of the cylinder's smooth falloff can often be rendered. If however we have a viewpoint like the example, then the sharp edge of the cylinder can be visible in the right lighting conditions.

![image](https://user-images.githubusercontent.com/4766365/105557077-fe0ab680-5cd0-11eb-9949-94290f1c3835.png)

My plan is to move the cylinder back along it's central vector by 1 radius and extend it by 2. Cylinder light volumes are a simple cylinder mesh one unit long with one face at the origin, so these operations should be quite simple. The shader has access to the radius, and when building the beam vector on which to find the nearest point it can repeat those operations in reverse. The end cap point volumes can be eliminated as redundant, but are left in the next illustration for demonstration purposes.

![image](https://user-images.githubusercontent.com/4766365/105557250-580b7c00-5cd1-11eb-9de1-41143530b48a.png)
 
The current attenuation math can already be seen to produce the right results if allowed to act. This should always allow that when appropriate, instead of just in select circumstances. It is essentially turning the light volume into a bounding cylinder for a whole capsule, rather than one component element of that capsule. 

Besides fixing the issue at hand, there are some visual side effects I expect. Removal of the doubling up should dim the lighting on both firer and target somewhat. In the case of the firing side this should be a return to 19.0 brightness before tube attenuation was fixed. If we wanted to be more efficient we could also have muzzle lights only be active when the tube light isn't active, as the tube covers a similar area, and then adjust the tube light brightness to compensate if necessary. 

(In fact tube lights have a moderately larger radius than muzzle lights, due to magic number multipliers in `gr_opengl_deferred_lighting_finish` to point and tube lights. The end cap point lights are an exception, as they get created separately using the larger tube light size multipliers.)

Overall I don't think any of these brightness changes will be that noticeable especially for people playing on default lighting settings. Personally I lean towards not removing the muzzle lights, as I think good things could come down the road from being able to configure muzzle and tube lights separately, and the few extra point lights from active beams are probably an insignificant concern next to the number that can be generated by rapid fire projectile weapons.

**Comment by Goober5000** [comment]
Resolved by #3167
