### ISSUE TITLE
FSO crashes with Mesa radeon drivers

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#317]
When trying to run a more demanding mod (e.g. WiH2) FSO crashes when entering the tech room and the following is printed to stderr:
```
EE ../../../../../../src/gallium/drivers/r600/r600_shader.c:158 r600_pipe_shader_create - translation from TGSI failed !
EE ../../../../../../src/gallium/drivers/r600/r600_state_common.c:784 r600_shader_select - Failed to build shader variant (type=1) -1
```
(The crash happens in an OpenGL draw call)

My best guess is that the main vertex or fragment shader is too complex for Mesa and needs to be simplified somehow. Using the proprietary AMD drivers works so it's probably not a limitation of my GPU.

**Comment by Echelon9** [comment]
What is the output when you run the below command? (seeing which version of Mesa 10.x or Git 11.0 you have):
```
glxinfo | grep "OpenGL"
```
A quick look around the Internet indicates it has been hit by a few other projects, so might need to be kicked up to the Mesa devs to fix.

You may also want to post somewhere the output from running fs2open with this environment variable `R600_DUMP_SHADERS=1`.

Another env variable that may provide more verbose logging of the exact register pressure (if that's the case here): `R600_DEBUG=hyperz,nosb`

**Comment by asarium** [comment]
I have switched back to the proprietary driver so I can't give you the exact version string but I was using a pretty recent Git 11.0 version.

I also found some issues that other projects had which were fixed by reducing the complexity of the shader (probably uses too many registers). Our main model shader is pretty massive and Mesa apparently isn't very good at optimizing for my card.

**Comment by logomancer** [comment]
Can confirm shader overflows are happening with Mesa/r600. I ran the game with LIBGL_DEBUG=1, entered the tech room, and got many instances of this:

```
EE r600_shader.c:2741 r600_shader_from_tgsi - GPR limit exceeded - shader requires 128 registers
EE r600_shader.c:161 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:815 r600_shader_select - Failed to build shader variant (type=1) -12
```

This renders the models invisible, aside from the cockpits and the nav lights, and the frame rate takes a significant hit (presumably, from CPU load trying to deal with the shaders). 

Disabling normal maps makes the problem go away in the tech room, but I encountered it again in a nebula mission in Freespace Blue, where a similar error occurred.

This was done on a debug build of master as of `ed2bbc3`, using the BPComplete and dependent mods, on an HD 6870.

r600 has a hard limit of 124 general-purpose registers per shader; if compiled shaders overflow this limit, the driver won't load the shader into the hardware to avoid locking up the card. I suspect that the issue will be resolved once the shaders are optimized.

**Comment by Echelon9** [comment]
Thanks for the extra debugging @logomancer.

It appears there are two potential resolutions here:
1. Simplify our shader source code, or
2. Assist the Mesa developers in improving the optimization passes.

We can of course consider making the changes for (1), but there is likely greater benefit from assisting the Mesa developers to improve optimization passes. One reason is that a number of our shaders are not wholly unique to our engine, e.g. the FXAA shader.

Thus, in order to progress (2) I've been considering whether we could have the fs2open engine shaders committed to `shader-db` ([see here](http://cgit.freedesktop.org/mesa/shader-db/tree/README)). It is a corpus of OpenGL GLSL shaders from applications, used by Mesa to verify optimizations.

I have patches, however the main question to be resolved is whether our license -- as it applies to the shader sources -- permits these to go in the public corpus of `shader-db`. There is a second private corpus that Intel holds.

**Comment by asarium** [comment]
One could probably argue that the shader code is separate from the current code base which means that the Volition licence clause doesn't apply to it. If that is true then the shaders would not be bound by the Volition licence and could be included in the shader database.

**Comment by chief1983** [comment]
Especially if the shaders are themselves unaware of what engine they are running on, then they should be able to be released under an MIT or whatever license by the author(s).

**Comment by SamuelCho** [comment]
So if we submit our shaders for optimization, would that still leave room for us to revise the shaders for additional features? Say after PBR goes in would we have to submit them again?

And if we take the simplification approach, can we just, say, remove shadowing? Or limit lighting to one directional light and one point light?

**Comment by logomancer** [comment]
@SamuelCho, `shader-db` is just a corpus to help Mesa optimize their shader compiler; it has little bearing on what any project does. In any case, getting PBR to work on Mesa would take more work on FSO's end; see #511.

**Comment by Echelon9** [comment]
Now that AMD's old proprietary driver stack (fglrx) on Linux is deprecated and will not be supported on Ubuntu 16.04+, we should revisit this.

@logomancer or @asarium can you please confirm if this bug is still present with either:
- Mesa-based radeonsi driver stack
- AMDGPU-PRO driver stack

**Comment by asarium** [comment]
Mesa generally doesn't support the shader we use so I can't test that. The AMDGPU-PRO driver stack only works with Ubuntu at the moment but I am using Fedora so I can't test that either.

**Comment by SamuelCho** [comment]
The Core changes are coming soon. The GLAD and TrueType changes put things into a temporary tailspin but things are getting stabilized slowly but surely.

**Comment by logomancer** [comment]
@Echelon9 Can't test at present, since I don't have a new enough video card. If the inventory gods smile upon me next week, I'll grab an RX 480 and take a look.

**Comment by Echelon9** [comment]
OK. May the inventory gods smile down upon you indeed @logomancer ...

**Comment by asarium** [comment]
This should be fixed by #844.

**Comment by Echelon9** [comment]
Can we get a confirmation of this fix from a Mesa r600 driver user?

It does not necessarily hold 1:1 that the OpenGL Core fixes in #844 would cause shader complexity to drop sufficiently for Mesa's internal TGSI intermediate representation to handle it. Perhaps, but not definitely.

**Comment by tomimaki** [comment]
Mesa r600 user here. With FXAA and shadows enabled I can play Universal Truth.
Some warnings in log but it works. :+1: 

```
  Initializing SDL video...
Initializing OpenGL graphics device at 1366x768 with 32-bit color...
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
Could not create OpenGL Context: Could not create GL context: GLXBadFBConfig
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
Could not create OpenGL Context: Could not create GL context: GLXBadFBConfig
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Actual SDL Video values    = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  OpenGL Vendor    : X.Org
  OpenGL Renderer  : Gallium 0.4 on AMD TURKS (DRM 2.43.0, LLVM 3.8.0)
  OpenGL Version   : 3.3 (Core Profile) Mesa 11.2.2

Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
Shader Variant Features:
Compiling new shader:
	Particle Effects
   Loading built-in default shader for: effect-v.sdr
   Loading built-in default shader for: effect-particle-f.sdr
   Loading built-in default shader for: effect-screen-g.sdr
Shader Variant Features:
	Geometry shader point-based particles
Compiling new shader:
	Distortion Effects
   Loading built-in default shader for: effect-distort-v.sdr
   Loading built-in default shader for: effect-distort-f.sdr
Shader Variant Features:
Compiling new shader:
	Deferred Lighting
   Loading built-in default shader for: deferred-v.sdr
   Loading built-in default shader for: deferred-f.sdr
WARNING: Failed to find uniform 'specFactor'.
Shader Variant Features:
Compiling new shader:
	Clear Deferred Lighting Buffer
   Loading built-in default shader for: deferred-clear-v.sdr
   Loading built-in default shader for: deferred-clear-f.sdr
Shader Variant Features:
Compiling passthrough shader...
Compiling new shader:
	Passthrough
   Loading built-in default shader for: passthrough-v.sdr
   Loading built-in default shader for: passthrough-f.sdr
Shader Variant Features:

Compiling passthrough shader...
Compiling new shader:
	Post Processing
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: post-f.sdr
WARNING: Failed to find uniform 'depth_tex'.
WARNING: Failed to find uniform 'timer'.
Shader Variant Features:
Compiling new shader:
	Bloom Brightpass
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: brightpass-f.sdr
Shader Variant Features:
Compiling new shader:
	Gaussian Blur
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: blur-f.sdr
WARNING: Failed to find uniform 'debug'.
Shader Variant Features:
	Horizontal blur pass
Compiling new shader:
	Gaussian Blur
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: blur-f.sdr
WARNING: Failed to find uniform 'debug'.
Shader Variant Features:
	Vertical blur pass
Compiling new shader:
	Bloom Compositing
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: bloom-comp-f.sdr
Shader Variant Features:
Compiling new shader:
	FXAA
   Loading built-in default shader for: fxaa-v.sdr
   Loading built-in default shader for: fxaa-f.sdr
Shader Variant Features:
Compiling new shader:
	FXAA Prepass
   Loading built-in default shader for: post-v.sdr
   Loading built-in default shader for: fxaapre-f.sdr
Shader Variant Features:
```

**Comment by asarium** [comment]
Thanks for testing this. Those warnings are nothing to be concerned about since FSO first tried to create an OpenGL 4.1 context which is not supported by your drivers.

**Comment by SamuelCho** [comment]
Nice, Glad to see my hard work paying off. :hammer:

**Comment by tomimaki** [comment]
Ah ok. 
After forcing mesa to cheat about OpenGL 4.1 some warnings disappeared.

```
  Initializing SDL video...
Initializing OpenGL graphics device at 1366x768 with 32-bit color...
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Requested SDL Pixel values = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  Actual SDL Video values    = R: 8, G: 8, B: 8, depth: 24, stencil: 8, double-buffer: 1, FSAA: 0
  OpenGL Vendor    : X.Org
  OpenGL Renderer  : Gallium 0.4 on AMD TURKS (DRM 2.43.0, LLVM 3.8.0)
  OpenGL Version   : 4.1 (Core Profile) Mesa 11.2.2
```

**Comment by Echelon9** [comment]
Fantastic. Great to see and well done @SamuelCho and @asarium.
