### ISSUE TITLE
Re-arming drone multiplayer bug

### ISSUE THREAD

**Issue by raspi** [scp-fs2open/fs2open.github.com#3170]
OS: Manjaro Linux
Version: release_21_0_0_RC5
Multiplayer coop, any retail mission or campaign as a client.
Host was running Windows 10 release_21_0_0_RC5
Knossos 0.14.2-dev+1f60d92 with MediaVPs 4.3

What happens:

I called rearming drone and the drone is somehow colliding constantly with the ship when it arrives, I can't use joystick to maneuver the ship (only slight movements possible) anymore. Ship's speed jumps to 200-300+. Setting speed doesn't do anything. Drone jumps around really fast. Fixed when someone destroys my ship and I respawn back to the game.

**Comment by JohnAFernandez** [comment]
OK.  This is not the first I've heard of this one.  I'm going to send you a special build that may help, because it has a fix that is not in master because of the RC cycle.

**Comment by JohnAFernandez** [comment]
Found the real cause of this.  Net_signature was shared between two different ships because of how it was calculated for wing members.
