### ISSUE TITLE
Cannot launch with a unicode Windows username

### ISSUE THREAD

**Issue by tmo7452** [scp-fs2open/fs2open.github.com#3173]
If the application is launched and the user folder contains unicode, they are presented with this error:
![image](https://user-images.githubusercontent.com/9245957/105918342-c322be80-6001-11eb-8ee0-77bfdb12df23.png)
This is due to poor logic in getPreferencesPath() within [osapi.cpp](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/osapi/osapi.cpp). It correctly handles SDL_GetPrefPath failing by offering to use the current directory, but does not do the same if the unicode check fails. I do not see any reference to the "portable mode" mentioned in the error.

If "portable mode" exists, it needs to be checked for. Otherwise, it should check if the current directory also contains unicode before failing.

**Comment by tmo7452** [comment]
Reported on behalf of this guy: https://old.reddit.com/r/freespace/comments/l5nrf6/fs_open_anywhere_else_than_appdata/

**Comment by pierreantoine-cheron** [comment]
@tmo7452 Hi I am this guy on reddit (_belgarath)
Do you think that changing the order of the Unicode and SDL_GetPrefPath check should be enough ?

**Comment by tmo7452** [comment]
> 
> 
> @tmo7452 Hi I am this guy on reddit (_belgarath)
> Do you think that changing the order of the Unicode and SDL_GetPrefPath check should be enough ?

No, to do this properly would require a little more than that, especially if you want it to have decent user feedback in this situation (instead of multiple warnings.) Something like:
```
if (isPortableMode()) {goto tryCurrentDirectory;} //TODO
trySDLPrefPath:
    preferencesPath = SDL_GetPrefPath(...);
    if (SDL_GetPrefPath failed)
        show warning
        goto tryCurrentDirectory
    if (preferencesPath contains unicode)
        show warning
        goto tryCurrentDirectory
    return preferencesPath
tryCurrentDirectory:
    preferencesPath = (full path to current directory, not just DIR_SEPARATOR_STR)
    if (preferencesPath contains unicode)
        show error
    return preferencesPath
```

Sure you do it another way to avoid `goto`, but I think this has a clear and clean flow.

**Comment by pierreantoine-cheron** [comment]
Just a quick question, the "#elif defined(WIN32)" thing , line 21 and checked for the unicode line 60, it it defined for all windows installations or only 32-bits versions ?

**Comment by pierreantoine-cheron** [comment]
@JohnAFernandez Why the "not a bug" label ? If it's not a bug how can I overcome this problem ?
Thank you.

**Comment by z64555** [comment]
> 
> 
> @JohnAFernandez Why the "not a bug" label ? If it's not a bug how can I overcome this problem ?
> Thank you.

Its how we distinguish issues that aren't a bug in the code, but is still a problem due to any number of reasons.  Since our issue tracker also contains feature requests, we need some way of distinguishing problems from features.

**Comment by pierreantoine-cheron** [comment]
@z64555 thank you very much for your explanations !
Can't wait to finally be able to play it !
