### ISSUE TITLE
FR: Sexp send-message-chain

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3185]
The same as send-message-list but with one additional argument.

Send-Message-Chain
--Event that, when true, will stop the chain from sending further messages
--Message sender
--Priority
--Message
--Delay
--Previous 4 arguments (not the event one) repeat indefinitely

**Comment by naomimyselfandi** [comment]
Should this stop when the event is _true_ or when the event is _not incomplete?_ The latter makes it easier to tie message chains to escort directives and the like.

**Comment by Goober5000** [comment]
You could make three variants - one for true, one for false, and one for incomplete.  Or you could make one sexp with an argument that lets you choose.

**Comment by naomimyselfandi** [comment]
I don't know how I feel about that. I can't help but feel like that'd be overkill - either convention is fine and complicating it would probably just make it _harder_ to use.

Actually, now that I've let it stew in the back of my brain for a while, I think I like Mjn's original take (waiting for true) better. "An event became true" is conceptually easier to parse than "an event hasn't completed", and it's really easy to write an event that becomes true whenever you need it to. So, nvm!

**Comment by Goober5000** [comment]
Fair enough.

**Comment by wookieejedi** [comment]
#3213 is merged, so closing this.
