### ISSUE TITLE
FR: mn.getMissionTimeMs()

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3210]
We have a scripting API (`mn.getMissionTime()`) to get the current time in seconds. We also have SEXP operators to get the current time in either seconds or milliseconds. We _don't_ have a scripting API to get the current time in milliseconds, and we should. I'm not married to the proposed name in the title.

If it's not unduly challenging to implement, a variant of `mn.waitAsync()` that waits for milliseconds would also be nice. `mn.waitAsyncMs()`, perhaps?

(Incidentally, the SEXP documentation for `mission-time-msecs` is outdated. We can enter chain delays in milliseconds, so the example usage is misleading.)

**Comment by Baezon** [comment]
FRED only deals in integers so having separate functions to deal with msecs when you need to be very specific makes sense. But the scripting API has no issue returning floats nor does lua have issues manipulating them, so I'm not sure I understand the need.

**Comment by wookieejedi** [comment]
Yeah, I'd agree with Asteroth. I regularly use floats in Async wait and the get mission time function.

**Comment by naomimyselfandi** [comment]
> FRED only deals in integers so having separate functions to deal with msecs when you need to be very specific makes sense. But the scripting API has no issue returning floats nor does lua have issues manipulating them, so I'm not sure I understand the need.

Well, I need millisecond precision. I'm currently calling out to `mission-time-msecs`, but it'd still be really nice to be able to get the time in milliseconds directly. If `mn.getMissionTime()` could return fractional seconds, that'd also work nicely (as long as it won't break backwards compatibility - I don't think it would, but I've been burned by Lua quirks too many times to say that with confidence).

**Comment by wookieejedi** [comment]
`mn.getMissionTime()` does return fractional seconds, if you print the `mn.getMissionTime()` every frame you can see the time change incrementally after the decimal point.

**Comment by Baezon** [comment]
The time functions return a floating point number, not an integer, unlike SEXPs. So instead of the SEXP to returning 2, 17, 121 etc the scripting functions return the time in the highest precision available to the engine i.e. 2.2177490, 17.99837507, 121.0379268. The SEXP milliseconds is in fact derived from these numbers by simply multiplying by 1000 and rounding to the nearest millisecond.

So the scripting functions in fact give you even greater precision than milliseconds, and you can work directly on their values with however specific fractions you require.

**Comment by Goober5000** [comment]
It would still be useful to get the time in milliseconds.  I think `mn.getMissionTimeMsecs` would be fine to add.

The strange thing is that `getMissionTime` returns a value in the `fix` format, directly, so I wouldn't expect it to be usable in its current form.  The code should be doing something like this:
```
			float mission_time = f2fl(Missiontime);
			int minutes = (int)(mission_time / 60);
			int seconds = (int)mission_time % 60;
``

**Comment by asarium** [comment]
There is special handling for `fix` values in place to convert them to a `float` for lua.

If you want the mission time in milliseconds then `mn.getMissionTime() * 1000` is the correct solution. No need for an additional engine API function.

**Comment by naomimyselfandi** [comment]
> The time functions return a floating point number, not an integer, unlike SEXPs. So instead of the SEXP to returning 2, 17, 121 etc the scripting functions return the time in the highest precision available to the engine i.e. 2.2177490, 17.99837507, 121.0379268. The SEXP milliseconds is in fact derived from these numbers by simply multiplying by 1000 and rounding to the nearest millisecond.
> 
> So the scripting functions in fact give you even greater precision than milliseconds, and you can work directly on their values with however specific fractions you require.

Oh, huh. And does the same apply to `mn.waitAsync()`? It'd be great to have that added to the documentation - it might seem obvious if you know how the internals work, but to someone who doesn't, it can easily be read as operating on seconds _as integers_ (like what lead to me posting this in the first place).

**Comment by asarium** [comment]
Lua actually does not know integers so fractional seconds is the "default" case for the language. Unless otherwise specified, all API functions taking number will handle fractional values just fine.
Since the original question was answered and is not relevant anymore, I will close this issue.
