### ISSUE TITLE
Destroyed submodels showing in FRED

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3212]
Lastest nightly, reported on Discord by JadedDragoon

For BP's UED Solaris and possibly other ships, destroyed submodels (hoping that's the term) are visible in FRED. Screenshot attached: the orange-black parts on the Solaris and Toutatis shouldn't be visible. The Lucifer is not relevant.
![OrangePartsBad](https://user-images.githubusercontent.com/73649993/107865200-1e421700-6e32-11eb-8a6b-a5750208242f.png)

Reminds me of #3123 and #3078.

**Comment by wookieejedi** [comment]
Can confirm.
