### ISSUE TITLE
FSPort 3.6.7's weapons.tbl has an error when parsed on nightly builds beginning with Feb 1 2021

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3215]
Here's a log: https://fsnebula.org/log/6029408cd42c7b84b2d7bf52

**Comment by Baezon** [comment]
Caused by bad table data.

**Comment by Goober5000** [comment]
It will be fixed as soon as possible.  There are several things that need to be done for the release.
