### ISSUE TITLE
FRED events cannot be deleted on nightlies starting Feb 11

### ISSUE THREAD

**Issue by Svedalrain** [scp-fs2open/fs2open.github.com#3216]
In the event editor, neither the delete button, the delete key, nor the delete item context menu option can delete an event.
Messages, sexps in events and arrival cues, and variables can be deleted.

Appears not to affect qtFRED, which #3191 didn't touch.

**Comment by wookieejedi** [comment]
Can confirm.

**Comment by Goober5000** [comment]
wut
