### ISSUE TITLE
Ship lookups in sexps are case sensitive

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#3221]
As part of the big "ship handling in sexps" rewrite, ship name lookups in sexps have inadvertently become case-sensitive. 
When ships get added to the registry, which at its core is a `SCP_unordered_map<SCP_string, int>`, they can only be retrieved when the exact name matches; in cases where missions were hand-edited, this can lead to lookups failing.

**Comment by Goober5000** [comment]
This is trickier than it looks.  Converting all of the keys to lowercase would be an ugly solution, which I would prefer to avoid.  On the other hand, `unordered_map` does not have a way to cleanly replace the equality function like `map` does with the comparison function.

**Comment by The-E** [comment]
Yeah, the cleanest way to do it would be to disallow direct access to the map and only access it through a single function that automatically ensures anything passed to it is lowercased.

**Comment by Goober5000** [comment]
I figured out how to replace the functions.  Draft PR posted.
