### ISSUE TITLE
Select weapon trail textures broken on recent nightlies

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3228]
Sometime between 21.0 and 20210211 at least one weapon trail in Warmachine stopped rendering properly. It can be seen on the public release build of Warmachine, v1.1.2. To reproduce I would suggest starting the tech room simulator mission trial by fire, it has relatively quick loading time and the default loadout carries the weapon in question(the Sarrisa) in your first bank.

This is what it should look like, and does on 21.0

![screen0030](https://user-images.githubusercontent.com/4766365/108429892-32a55b80-7206-11eb-956e-fc4cd70217f3.png)

And this is what the current builds make it look like

![screen0027](https://user-images.githubusercontent.com/4766365/108429936-3df88700-7206-11eb-9c86-232ddc6e63e8.png)

**Comment by EatThePath** [comment]
Today's nightly doesn't do this. Closing, will reopen if it comes back

**Comment by Goober5000** [comment]
I think it was fixed by #3291.

**Comment by Baezon** [comment]
#3255 I believe actually, I had forgotten to close this
