### ISSUE TITLE
FR: Expose simulated hull to scripting API

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3230]
Exactly what it says on the tin. We can read and write to the ship's actual hull, but interactions with the simulated hull have to go through `runSEXP`.

Admittedly, the use case for this is really narrow - you need to be either writing a script that interacts with a mission that uses sim-hits, or you need to be writing a generic utility script - but the latter case actually did come up in BTA.

**Comment by Goober5000** [comment]
Easily done.  PR forthcoming momentarily.

**Comment by wookieejedi** [comment]
#3234 was merged, so closing this.
