### ISSUE TITLE
FR: Enable $default keys$ in debriefings, recommendations

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3241]
There are some controls that are _very_ useful in very specific cases but aren't particularly well-known, like "Target my target's target". It'd be really nice to be able to mention these keys in debriefings and _especially_ in recommendations:

> [SPOILER REDACTED]. Make sure to prioritize threats appropriately. You can press $G$ to target a ship attacking your target, or $J$ to target your target's target. Both of these controls can be put to good use here.

**Comment by MjnMixael** [comment]
+1
