### ISSUE TITLE
Warn users about the current state of macOS support until known issues are fixed

### ISSUE THREAD

**Issue by ngld** [scp-fs2open/fs2open.github.com#3249]
Currently, you have to install Homebrew and their `freetype` package to launch FSO. The current nightlies are linked against `/usr/local/opt/freetype/lib/libfreetype.6.dylib` which only exists if you install libfreetype through Homebrew.

We should either bundle `libfreetype` the same way we bundle FFmpeg or at the very least warn users. A crash on launch isn't particularly helpful and most people don't run `otool -L` against FSO's binary to find out.

**Comment by chief1983** [comment]
I feel like I filed this already...

**Comment by ngld** [comment]
Ah, looks like it was closed (#2370). However, we haven't had a successful macOS nightly since that change so the latest FSO build on Knossos still has that issue...

**Comment by chief1983** [comment]
It's not the freetype though, Mac has just been broken in general for other reasons.  #2863 should have fixed freetype.  There is another ticket about ffmpeg issues.  We had a big gripe fest about how Apple is just crapping over the ability to keep making the game work by constantly breaking things on us.  I've been running out of energy to keep troubleshooting it myself and I spend more time on a Mac than a PC.

**Comment by ngld** [comment]
We just had someone on Discord who couldn't launch FSO on macOS. In the end, they only had to install Homebrew and libfreetype to fix their issue.

#2863 probably fixed the issue but that fix isn't available right now since we apparently don't have macOS nightlies.
The issue in #2875 is caused by Apple enforcing code signing in general (IIRC you can't even launch software that isn't signed on M1 Macs).

I'm not against stopping macOS support since I agree that it's a lot of work for little gain (especially with the depracation of OpenGL).
However, we should clearly communicate the current state of macOS support to users and at the very least add a warning with known issues to the FSO release thread and maybe the support forum.

**Comment by virusman** [comment]
What's the current state of macOS support?

**Comment by notimaginative** [comment]
Just to add, I've switch to a mac as my primary laptop and intend to improve macOS support in FSO as much as I'm able. It's going to take some time to get up to speed on things though. In particular I'm not yet familiar enough with things to successfully tackle the bigger build system issues (universal binary/libs), nor am I familiar enough with the ci setup to fix things there.

**Comment by notimaginative** [comment]
Unless there are bugs of which I am unaware I believe that all macOS issues have either been resolved, have a PR pending (BC7, signed libs), or require a complicated solution (rendering performance). And with Knossos.NET available as a proper Mac app, using FSO on a Mac is significantly easier than it was just a year ago.

As the original issue was resolved several stable releases ago (at least), I vote to just close this issue.

**Comment by Goober5000** [comment]
With the two Mac devs weighing in, and per @wookieejedi's comment on #6025, that's good enough for me.
