### ISSUE TITLE
Nebula poof rendering needs improvement

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#3250]
As documented by Durandal [here](https://www.youtube.com/watch?v=4boRXk2DWY4&t=2s) and [here](https://www.youtube.com/watch?v=gpxrsFG0-CM&feature=youtu.be), nebula poof rendering currently causes some bad issues with visual consistency, as poofs larger than retail will be faded out very quickly as they move across the scene.

The underlying reason are the nebula detail default settings. These set very low (by modern standards) values for when to start fading things out (see neb.cpp:169 and following).

These default values need to be adjusted. Ideally, they'd be made dynamic, taking as reference the actual size of the currently loaded poofs and the current screen aspect ratio.

Similarly, the default value for `break_alpha` can also be substantially lowered to further improve visual consistency.

see also https://github.com/scp-fs2open/fs2open.github.com/issues/2689

**Comment by z64555** [comment]
@Baezon I saw on discord you were messing around with nebula poofs along with fog.  Where you working towards this issue>

**Comment by Baezon** [comment]
Yes, while I am currently working on modder configuration for #2689, I've added my thoughts to The_E's PR #3266 addressing the aspects brought up in this issue.
