### ISSUE TITLE
Unable to compile master branch with MSVS

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#3254]
This ticket is largely for record keeping purposes as well as progress tracking.  Much discourse has been done on discord already, so this serves as something of a formalization.

Changes responsible by #3242 have caused the master branch to be unable to compile on local machines.  The issue slipped by due to the author not working on a machine with MSVS to do local tests, along with CI systems not catching the issue (they compile and build normally, for unknown reasons).

**Comment by Goober5000** [comment]
Confirmed fixed via #3251
