### ISSUE TITLE
POF animation enhancements

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#3288]
In addition to the changes described [here](https://www.hard-light.net/forums/index.php?topic=96055.0) and [here](https://github.com/scp-fs2open/fs2open.github.com/pull/2691), POF animation has its limitations; for example, animations stop abruptly when a subsystem gets destroyed, while turrets don't recoil when firing.

POF animation could be improved with interpolation, keyframe animation, morph target animation, bone-based animation and procedural animation.

**Comment by Goober5000** [comment]
Submodel translation is already in progress, which will allow barrel recoil.  Improvements to the animation system will allow modders another way to deal with subsystem destruction.

The practical aspects of this request are mostly covered by existing requests.  The pie-in-the-sky requests are not practical.
