### ISSUE TITLE
FRED: Add hotkey for "Edit Data"

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3289]
Having Ctrl-C/V/P working in the events editor is a _huge_ help, and there's one thing that'd make it even better - a hotkey for "Edit Data" (Ctrl-E, maybe?) Suppose you're setting up an `or` with several `is-destroyed-delay`s - you can set one up, copy it and add paste an appropriate number of times, and even select the nodes you need to edit all through they keyboard, but actually editing the ship names requires going through the right-click menu. With this hotkey, you wouldn't have to.

**Comment by Goober5000** [comment]
This should be straightforward.  The biggest question is whether the consensus is Ctrl-E or whether someone can make a good case for a different key.

**Comment by naomimyselfandi** [comment]
No strong preferences on what the key is! :)

Should this have the `good first issue` label?

**Comment by Goober5000** [comment]
Perhaps.  It "should" be as simple as matching the existing code and adapting it for the new function, but there may be unanticipated side effects.

That being said, from a glance at the code, and a test in FRED, this is already implemented!  Press the Space Bar.

**Comment by naomimyselfandi** [comment]
> That being said, from a glance at the code, and a test in FRED, this is already implemented! Press the Space Bar.

Today I learned! Well, in that case, this can probably just be closed... although it _is_ a useful feature, so it'd be kind of nice (for others!) to have it listed in the right-click menu like the other hotkeys.

**Comment by Goober5000** [comment]
Listing it in the right-click menu is definitely something I can do.
