### ISSUE TITLE
"Hidden" hotkey group doesn't hide ships from the F3 list

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3290]
If the player presses F3 in a mission, it brings up a list of all the ships in the mission and lets the player change their hotkeys. Setting a ship's hotkey as "Hidden" is supposed to hide it from this list, but it doesn't.

This is particularly problematic when a mission uses the modular construction kit - there's no way to stop all those props from cluttering up the list. (Admittedly, I'm not sure how many people even know about that function in the first place.)

(To avoid any ambiguity, this is _not_ the same as the ship lab, which is also bound to F3, but from the main hall.)

**Comment by Goober5000** [comment]
Bleh... I figured it out.  The "Hidden" hotkey does indeed hide the ship... but *only* for setting hotkeys before the mission starts.  After the mission starts, the ship appears in the hotkey listing as usual.

```
// if a ship's hotkey is the last hotkey on the list, then maybe make the hotkey -1 if
// we are now in mission.  Otherwise, skip this ship
if ( shipp->hotkey == MAX_KEYED_TARGETS ) {
	if ( !(Game_mode & GM_IN_MISSION) )
		continue;										// skip to next ship
	shipp->hotkey = -1;
}
```

I didn't even realize you could assign hotkeys before the mission starts, but apparently you can.  I just tried it.

**Comment by JohnAFernandez** [comment]
This would need require a small enhancement to add functionality.
