### ISSUE TITLE
Screen resolution check on startup?

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#3294]
Suppose your mod works only at 1920x1080 or higher (4K) screen resolutions. You want to restrict screen resolutions lower than the intended one. Whenever your current screen resolution is lower than what the mod requires, it will display an error message telling the user to change the screen resolution.

**Comment by Goober5000** [comment]
This was already solved cleverly by Axem in his JAD mod.  No code changes were necessary.
