### ISSUE TITLE
FRED: add data for variable paramaters behaving differently from replace data for same, causing error

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3298]
If you have a SEXP with an *optional* variable parameter and you use the event editor right click 'add data' option to populate the variable name, it adds only the variable name as a string rather than a proper variable reference. This causes an warning on save, and presumably breaks in game too. If you then use 'replace variable' it works properly, of course. It seems like since replace knows what to do with variable parameters, add could and should too.

**Comment by jg18** [comment]
I ran into this issue while working on PR #3398 (containers) with the new `map-has-data-item` SEXP.

However, I spent an hour or two digging through FRED's SEXP tree code and made no progress on fixing it. Maybe @Goober5000 has some ideas on what to do here?

**Comment by Goober5000** [comment]
This has been on my list of things to investigate for a while.  It's just a matter of narrowing down the branches and scrutinizing the code.  I had to implement shortcut keys using a similar approach.

I will take a look at it, but I can't predict when that will be.
