### ISSUE TITLE
FR: POF skeletal animation

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#3303]
POF could use skeletal animation where a sub-object is represented in two-parts: a mesh/skin and a hierarchical set of interconnected bones collectively forming the skeleton or rig, a virtual armature use to animate (pose and keyframe) the mesh. These bones could be animated by the same animation code.

The pincers of the SJ Sathanas mesh could benefit from this. As seen in one of the final cutscenes of FreeSpace 2, these pincers close and open. It would be nice to see them in-game with skeletal animation. In addition to these, multi-tentacled ships and even non-ship ones like human characters and monsters like Zolgear from Galaxian 3: Attack of the Zolgear could be possible.

It may be dependent on #2691.

**Comment by Goober5000** [comment]
Putting a mesh/skin on a model is not possible without support for a new model format.  And a new model format is highly unlikely for the reasons previously mentioned.
