### ISSUE TITLE
FRED: Message name and content remains unchanged when a message becomes un-focused in Event Editor.

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#3308]
In the FRED2 Event Editor (see eventeditor.cpp), a selected message and its contents will remain even after being unfocused following a right-click performed on any SEXP operator.
![Event Editor Screenshot Before (1)](https://user-images.githubusercontent.com/2004725/111677356-1b37ad80-885a-11eb-995b-13343b713873.png)
![Event Editor Screenshot After (1)](https://user-images.githubusercontent.com/2004725/111677365-1c68da80-885a-11eb-89e9-ff0eeaca3ed9.png)
![Event Editor Screenshot Before (2)](https://user-images.githubusercontent.com/2004725/111677366-1d017100-885a-11eb-8373-9ecf0e1f3d7a.png)
![Event Editor Screenshot After (2)](https://user-images.githubusercontent.com/2004725/111677367-1d9a0780-885a-11eb-93d1-019e46d155bc.png)
Anyone could attempt to edit that message must click on a message in the upper-left corner of the window. Otherwise, any changes committed to these will be lost whenever a message is selected.

The solution is that when any message gets de-selected, the name and content are blanked and grayed-out, preventing editing until a message is selected.

**Comment by Goober5000** [comment]
This is actually a really good bug report.
