### ISSUE TITLE
Assert creating weapon while out of objects

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3361]
I hit an assert on weapons.cpp:5926, which apparently trips if the weapon can't get a valid object number, which in turn appears to happen only if there are no object slots available. 

Filing on the general principle that assertions should never actually be hit.

**Comment by Goober5000** [comment]
Ok but I have a hunch there were a lot of objects present...

**Comment by EatThePath** [comment]
There certainly were. I'm just thinking maybe a descriptive warning or if you must error message could be more appropriate than an assert.

**Comment by Goober5000** [comment]
That's probably reasonable.  This could be changed to a `Verify`.

**Comment by Baezon** [comment]
Maybe for a ship, but for weapons this really doesn't need to be more than a print (which already happens). There's no need to be so noisy about something which is very likely not to cause any significant issues.
