### ISSUE TITLE
FR: FRED QoL Feature for Custom Hud Gauges

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3364]
I suspect this is not an easy request or it would have been done when the feature was added. But like Event comments and colors, you don't get if you don't ask.

I use a **lot** of custom gauges. I don't often remember the name of them exactly. So I always have to go open up the hud_gauges.tbl and search for the gauge I want to find the right name to use in any of the related hud gauges sexps. These sexps accept a string.

I would like to have FRED build a list of all gauges that I can select from for a SEXP, similar to the key-pressed sexp. This could be an indiscriminate list since some gauges are only defined for certain HUDs and FRED doesn't know which HUD is active. So just list everything found in hud_gauges.tbl. This would really simplify this whole process for the FREDer.

**Comment by Goober5000** [comment]
FRED already does this for some sexps - see `flash-hud-gauge` and `hud-set-retail-gauge-active`.  So it's just a matter of patching the sexps that use strings.  I assume these include the ones in the HUD submenu:

* `hud-set-custom-gauge-active`
* `hud-set-text`
* `hud-set-text-num`
* `hud-set-message`
* `hud-set-directive`
* `hud-set-frame`
* `hud-set-coords`
* `hud-set-color`

Any others?

**Comment by MjnMixael** [comment]
Those are the ones I'm aware. And just to make sure it's clear, I'm talking about custom gauges. Your example sexps list retail gauges only.

**Comment by Goober5000** [comment]
Right.  I should say that it's *conceptually* a very easy request.  It's not hard to make FRED collect a list of things and provide them as a dropdown menu.  As you say it's already done for retail gauges; this is just a matter of collecting the custom gauges.

**Comment by Goober5000** [comment]
Implemented in #3370
