### ISSUE TITLE
FRED wipes Team Loadout ships with 0 Var

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3365]
If you set a Teams Loadout ship (probably weapons, too but I didn't test that) amount available to equal a variable and that variable is set to 0, then on mission save FRED will remove that ship entirely from the Team Loadout section.

**Comment by MjnMixael** [comment]
Further information. It seems that FSO does not use the variable at all to set number of ships available despite that seeming to be an option in the Team Loadout dialog. What I'm trying to do is have a ship be 'unlocked' mod-wide (across campaign files) when the player performs certain actions. So in each mission we set the ship num available == @VARIABLE[0]. Then later we set that variable to +1. It's an Eternal variable. I can verify the variable is >0 in the player file, but missions ignore it when setting the Team Loadout.

**Comment by MjnMixael** [comment]
As it turns out, this doesn't seem to be related to variables at all. I have a particular few ships that FRED/FSO refused to allow in Team Loadout even though they are selectable in the Team Loadout menu. (Even if I confirm they are in the loadout list in the mission file via text editor, FSO does not show them in the menu.) Further testing required... I have not yet nailed down a cause.

**Comment by Karajorma** [comment]
I assume you've included the ship in the allowed ships list in the campaign file and then started/restarted the campaign. That little mistake has tripped me up a few times.

**Comment by MjnMixael** [comment]
Yeah I though of those things. However this is even occurring for single missions.

**Comment by MjnMixael** [comment]
This issue seems not to be related to variables. Still not sure of the cause. Closing this as none of the information will be helpful with the actual bug is found.
