### ISSUE TITLE
Ship told to attack itself. I was told to report it.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3366]
Got this while playing Shell Game in BtA's first demo. It happened during the sunspot portion of the mission, so there's EMP bursts every couple of seconds. The hostile ships (War wing) also have cluster missiles.

`Warning: War 1#b was told to attack itself! This may be an error in the mission file.  If that checks out, please report to a coder!
File: aicode.cpp
Line: 2383`

I double checked the mission file as instructed. The only ai orders given to War 1#b are to attack Mako#3.

**Comment by Baezon** [comment]
Does this happen consistently, or did it happen just the one time?

**Comment by MjnMixael** [comment]
I was testing a lot of things in this mission so I stopped keeping track, but I think it happened every single time in that mission during that particular section. If not every time then at least a majority of my tests got this error.

**Comment by JohnAFernandez** [comment]
Ok.  Then we should be able to track it down. I might be able to look at it tonight or tomorrow.

**Comment by JohnAFernandez** [comment]
Ok. I can't reproduce, but the problem in the code does *seem* pretty obvious.  It doesn't check that the ship is itself.  So I'll add a check and pass along a test build for you to try.
[test-build-targeting-self-in-emp.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6347568/test-build-targeting-self-in-emp.zip)

**Comment by Baezon** [comment]
https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/weapon/emp.cpp#L363

The code already takes into account team, so implicitly this will never return itself, so something else if definitely going on here.

**Comment by Goober5000** [comment]
With one exception... Traitors attack other traitors.  And here's the ship in question:
```
$Name: War 1#b		;! Object #85
$Class: GTB Zeus
$Team: Traitor
```

So there needs to be another check.

**Comment by Baezon** [comment]
Ahhh, I had not considered the ship might be traitor IFF.

**Comment by MjnMixael** [comment]
I played that mission sections 3 times using the previously attached DEBUG build (that was painful... I formally request Fast Debug next time) and did not get any warnings about the AI attacking itself.

**Comment by JohnAFernandez** [comment]
Thanks!
