### ISSUE TITLE
FR: Further expansion on LUA SEXPs types

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3381]
The end-goal here is once again FREDer QoL. I have a handful of lua sexps that accept custom data. I was thinking just how much easier it would be to have a pre-populated list in FRED of custom data similar to some retail sexps. Examples of where this would be useful...

- List of music files that can be played back
- Ship variants that can be set (I use a script that will automatically set turrets to certain weapons with a single sexp)
- Custom send message sexp could use a short list to create message priority (Low, Normal, High)

My idea is something like this where the function would get the data as a string, but in this way it would pre-populate acceptable strings in FRED...

For longer lists:
```
#LUA SEXPs
$Operator: dynamic-sexp
$Category: Change
$Subcategory: Scripted
etc....
Parameter:
  +Description: String
  +Type: Enum
  +Enum Name: String
#END

#ENUMS
$Enum: String
  +String
  +String
  +String
$Enum: String
  +String
  +String
  +String
Etc.....
#END
```

For shorter lists we could just do it right in the Parameter section:
```
#LUA SEXPs
$Operator: dynamic-sexp
$Category: Change
$Subcategory: Scripted
etc....
Parameter:
  +Description: String
  +Type: Enum
  +Enum: ( "High" "Normal" "Low" )
#END
```

A second semi related request would be the ability to list multiple types in a Parameter. Think SEXPs that can accept a Ship or Wing, or a Ship and a String (#Command for example in a messages based function).

```
$Parameter:
  +Description: The source of the message
  +Type: ship
  +Type: string ; eg. #Command
```

**Comment by Goober5000** [comment]
@asarium Can you comment on this?

I seem to recall that Axem requested something similar a few years ago, but that it was harder than it looked.  Though maybe that was filtering of an existing type, not specification of a list.

**Comment by asarium** [comment]
This would require a dynamic type system for the SEXPs to allow creating new types when we want to specify such a Enum value. When I looked at this when Axem asked for this it was not trivial to do that extension so nothing ever happened with that.
