### ISSUE TITLE
Bug/misfeature report: Handling of missing sounds needs to change.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3388]
It appears that if a sound is absent from the game files the engine will try to load it every time it could occur. This is an expensive operation and can cause performance loss if the sound is called frequently. Consequently, missing sounds should either be upgraded to a debug warning instead of a logprint, or the engine should remember failures and not try to reload bad sounds, or probably both.

Profiling a Solaris mission is showing me about 16% of CPU time is lost to trying to reload a single missing sound file, for context.

**Comment by notimaginative** [comment]
We could probably get away with using a placeholder sound. It's easy to create silence so if a file is missing or fails to load we could log it then load silence in it's place. The engine would load and play the "silence" rather than continuing to look for the missing file.

**Comment by Goober5000** [comment]
From @notimaginative on Discord:
> I didn't comment again on 3388 but I got a little worried about possible side effects when sounds would technically always load successfully. A permanent fail might be the least problematic solution, but I'm not sure what that would entail.

**Comment by Goober5000** [comment]
fixed in #3639
