### ISSUE TITLE
FR: Alternate table file organization option

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3391]
This is a bit out there, but I figured I ought to ask anyway. Like many of my FRs, while I would love it if someone else implements it, this is at least half an open chance for people to tell me if they'd have problems with the proposed changes in case I get motivated enough on the matter to implement it myself.

I, for reasons both aesthetic and practical, prefer to develop my mods as a large number of single-entry tbm files, or in some cases 2-5 closely related entries, rather than one monolithic table for everything. the problem is that throwing several dozen tables of mixed types into data/tables makes a brand new unpleasant mess, and the way that table types are distinguished means it's impractical to even sort these files and get them clustered by type.

This can be managed somewhere by making separate packages for each tbm type, but that's also a mess of it's own kind too. What I would like instead is to be able to make subfolders, data/tables/weapons and so forth, and just have the game assume any .tbm in those folders is of the appropriate type. Then I can stop worrying that I'm going to eventually stub my toe on some package load order headache, and I can get back the four characters in the filename that usually have to go to the table type suffix. In a 32 character string that gets a confining surprisingly fast.

**Comment by MageKing17** [comment]
Seems to be along the same lines as #449, except that was never merged (presumably because APNGs solved the same basic problem in a different way); I don't see there being an equivalent of APNGs for tables, though, and also I'm fairly certain this could be implemented in an even simpler fashion (since the subdirectory could be added at each `parse_modular_table()` call rather than needing to happen dynamically for, potentially, every EFF).

**Comment by notimaginative** [comment]
Currently working on something like this, but I don't think it's exactly what you're asking for. What I'm doing is a cosmetic change simply as an aid for data organization. So you could put weapon tables in `data/tables/weapons` but it doesn't just assume that the tables in there are for weapons, you would still need the `-wep.tbm`.

What I'm working on would allow for things like:
`data/models/terran/fighters/fighter01.pof`
`data/maps/terran/fighters/fighter01/fighter01-*.dds`
`data/effects/weapons/primary/shot01/shot01.eff`
`data/effects/weapons/primary/shot01/shot01*.dds`

It's purely organizational at the cfilesystem level, allowing those files to be found and loaded without requiring any additional code or mod changes. Tables, scripts, sounds, etc. would all work the same way too.

**Comment by wookieejedi** [comment]
Can likely close now that #4771 is merged?
