### ISSUE TITLE
Add Coverity badge to our README.md on Github

### ISSUE THREAD

**Issue by Echelon9** [scp-fs2open/fs2open.github.com#34]
Add the small boilerplate code provided by Coverity for our latest build status to a (future) README.md.

The boilerplate and example of the badge itself:
```
<a href="https://scan.coverity.com/projects/870">
  <img alt="Coverity Scan Build Status"
       src="https://scan.coverity.com/projects/870/badge.svg"/>
</a>
```
<a href="https://scan.coverity.com/projects/870"><img alt="Coverity Scan Build Status" src="https://scan.coverity.com/projects/870/badge.svg"/></a>

**Comment by niffiwan** [comment]
Done :smile:
