### ISSUE TITLE
Eternal Variables are not available to single missions

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3412]
I suspect this is currently by design, but I'm unsure. I have a situation where I'd like some kind of Eternal variable to be available mod wide, across campaigns, single missions, and any other situation that might arise.

My particular use-case is unlocking bonus ships mod-wide. This is the first of at least two hurdles I have run into.

**Comment by MjnMixael** [comment]
Still waiting on some kind of solution to this...

**Comment by Karajorma** [comment]
It definitely is by design and I'd be loathed to add yet another flag to SEXP variables to handle this. 

How about a mission specs "Allow Eternal Variables in techroom" flag?

**Comment by MjnMixael** [comment]
That would be excellent. Gets the job done without complicating variables further.

**Comment by MjnMixael** [comment]
Scripting now allows me to get around this in a new way so I no longer need this specific request.
