### ISSUE TITLE
A Ship's position in Ships.tbl determines availability in Team Loadout

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3413]
If a ship is in position > N, it will not be visible for selection in the Ship Select screen and FRED will remove it from the available ships list upon re-saving the file.

I say > N because in BtA 2.0 the position is 105, but in retail the position is 91. I don't use tbms to add ships in BtA, so I'm not sure why the number differs.

I have confirmed this with retail data, use the attached ships.tbl and mission file. There are two added Ulysses ships. GTF Ulysses Avail and GTF Ulysses UnAvail. Avail is in position 90 in the table while UnAvail is in 91. You will see in RC4 that Avail can be selected in the Ship Select screen while UnAvail cannot. If you edit the ships.tbl to move them up or down in the list, then they become either both available or both unavailable.

[AvailTest.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6429790/AvailTest.zip)

**Comment by Goober5000** [comment]
My first thought was that there was a limit of player-allowed ships, but that doesn't appear to be the case.  There are 26 ships with `player_ship` in that tbl until you get to the unavailable one.  26 isn't a nice round number, nor did I find 26 as a limit in a quick code search.

**Comment by MjnMixael** [comment]
BtA currently has 28 player flyable ships as long as they are all above position 105. So I, also, do not suspect a limit.

**Comment by Goober5000** [comment]
It's range-checking the ship class index against the weapon class limit.  Fix will be uploaded shortly; currently checking to see if that's the only issue.
