### ISSUE TITLE
Bug: XSTR variables not correctly displayed when ID > 9999

### ISSUE THREAD

**Issue by Achille44** [scp-fs2open/fs2open.github.com#3422]
In the following cases, XSTR variables are not displayed correctly on screen if ID > 9999:
- mission name in the tech room and in the briefing room
- $label in #Briefing section
- $MessageNew in #Messages section

The problem does not occur in the following cases:
- $Stage Text in #Command Briefing section
- $Display Name in #Objects section
- +Tech Description for ships and weapons
- +Description for weapons

(Tested on builds 21.2.0 and 21.3.0-20210506)

![20210508154412_1](https://user-images.githubusercontent.com/5891168/117541563-b9ebb980-b014-11eb-8919-08b187676fcf.jpg)

**Comment by Goober5000** [comment]
I didn't know some mods used that many strings.  Found and fixed.
