### ISSUE TITLE
Proposal: Rename Ai profiles.tbl

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3456]
The name is misleading and continues to trip up even people who have worked with the engine for years. I propose that a new name should be selected and treated as synonymous by the engine ~~similar to game_settings.tbl and mod.tbl~~. Documentation would be switched to the new name as much as possible. Changing over the internal variable and type names would probably be too much work to be done comprehensively, and too noisy, so I imagine that'd be left alone, but at least for the end users the purpose can be more clear that way.

I would name it mission_settings or perhaps gameplay_profiles or something, and there should be a new tbm suffix too of course.

**Comment by MageKing17** [comment]
> ...similar to game_settings.tbl and mod.tbl.

We, uh... don't actually ever attempt to parse a file named "mod.tbl".

**Comment by EatThePath** [comment]
> We, uh... don't actually ever attempt to parse a file named "mod.tbl".

It appears not! The wiki page reads as if that's an option, and I unwisely assumed.
