### ISSUE TITLE
New Random class trips assertions on bad user data

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3459]
The new `Random.cpp` has an assertion to ensure it's getting a valid range:

```cpp
int Random::next(int modulus)
{
	Assert(modulus > 0);
	return SCP_rng.next() % modulus;
}

int Random::next(int low, int high)
{
	const int range = high - low + 1;
	Assert(range > 0);
	return low + (SCP_rng.next() % range);
}
```

However, these functions can be called directly by SEXP operators such as `rand` and `rand-multiple`, so the assertions can be misleadingly tripped by user data.

On a semi-related note, it'd be really nice if `rand` and `rand-multiple` would issue warnings when their arguments are backwards. If the warnings include the arguments themselves, then it'll be so much easier to track them down.

**Comment by Goober5000** [comment]
This used to be silently converted to a zero-range, not asserted...
```
    // get diff - don't allow negative or zero
    diff = high - low;
    if (diff < 0)
        diff = 0;

    return (low + rand32() % (diff + 1));
```

**Comment by Goober5000** [comment]
@jg18 do you want to handle this one?

**Comment by jg18** [comment]
@Goober5000  Yeah I can take this up.

@naomimyselfandi Thanks for reporting this.

What should be the correct behavior in this situation, other than no Assertion failure? Should the function just return `0`?

**Comment by jg18** [comment]
Or, probably a better solution, FSO/FRED code that calls these functions should validate argument values first, or at least validate in cases that handle user data. The caller code should be defensive against invalid input.

Speaking of which:

>On a semi-related note, it'd be really nice if `rand` and `rand-multiple` would issue warnings when their arguments are backwards. If the warnings include the arguments themselves, then it'll be so much easier to track them down.

@naomimyselfandi  That sounds useful to me. Could you file a separate issue with your request? Thanks again for your help.

**Comment by naomimyselfandi** [comment]
> @naomimyselfandi That sounds useful to me. Could you file a separate issue with your request? Thanks again for your help.

I'm sorry, I didn't see this until now. Would you still like me to create this? (Feel free to shoot me a message on Discord; I'll see it faster that way!)

**Comment by jg18** [comment]
No problem, and no need to file another issue (changed my mind). PR #3464  with the fix, which should be merged soon, will include the extra warning you requested. Thanks for including it.

**Comment by jg18** [comment]
PR #3464 with the fix has been merged, so I am closing this issue as fixed.

@naomimyselfandi I added the warning you suggested, see [the diff](https://github.com/scp-fs2open/fs2open.github.com/commit/df1c518c3b1c5619f326cd5309492682082685a4) if you're curious.

Thanks again for the suggestion and for the detailed and well-researched report.
