### ISSUE TITLE
Communications menu unusable

### ISSUE THREAD

**Issue by sixtyfive** [scp-fs2open/fs2open.github.com#346]
Apparently I suffer from the issue described in http://www.hard-light.net/wiki/index.php/Fs2_open_on_Linux/I18n_and_Key_mapping_problems. Is using xmodmap to mess up one's keyboard mapping the only way to get a working comms menu under Linux or is there a saner way?

Note that I unbound keys 0 through 9, but that didn't make the numbers pressable in the comms menu. The problem seems to exist with 3.7.0 (Debian version) as well as a freshly compiled 3.7.3.

Perhaps it needs to be mentioned that my keyboard is a German one. Adding `-keyboard_layout quertz` doesn't change things.

**Comment by asarium** [comment]
Can you try using the `antipodes` branch? That branch uses SDL2 which is apparently better at handling different keyboard layouts than SDL 1.2 which is currently used in `master`. You will need to install the `libsdl2-dev` package to compile.

**Comment by sixtyfive** [comment]
Compiled; segfaults - see #345.

**Comment by sixtyfive** [comment]
Ah, forgot to say: the numbers *do* work in this branch, which is awesome! :+1:

**Comment by niffiwan** [comment]
I think this is resolved, if you think otherwise post a comment and it can be re-opened
