### ISSUE TITLE
Bug: single mission not visible if title is translated

### ISSUE THREAD

**Issue by Achille44** [scp-fs2open/fs2open.github.com#3471]
In non-english version, single missions with a title translated with tstrings.tbl/xxx-tlc.tbm are not visible in the tech room.

This bug does not affect campaign missions.

**Comment by Goober5000** [comment]
@NovachenFS2 are you able to test this?

**Comment by NovachenFS2** [comment]
@Goober5000 

Yes, i am.

And i can confirm that in a way.

That is what i have found out:
XSTR("Mission Name", -1) will show up the mission in every language. However by its original name of course, as no translation id was given.
XSTR("Mission Name", 0) or any other number make the mission not selectable in the Tech Room.

Due to my translation mod i tested some other string values. Even values that should not hit any lenght limit did not work. Only with XSTR("Mission Name", 4620) the mission reappeared again. However its title was not translateable.

**Comment by NovachenFS2** [comment]
So, i actually can confirm, that the mission is not visible in the Tech Room if a string id is given in the mission name, that is present in the tstrings.tbl/-tlc.tbm.

As far a value is present in the language-specific tstrings file, it is not visible.

**Comment by Goober5000** [comment]
Ok, then it sounds like it is working as designed.  If you have `XSTR("Mission Name", 25)` in your mission file, but in tstrings.tbl that entry is `25, "Press Alt-J"`, FSO will see that "Mission Name" and "Press Alt-J" do not match.  It will determine that the mission is not compatible with that mod, so it will not display it.

To make FSO display the mission, there must not be a conflict.  So you can use -1 or 4620 as you discovered.  If you want the name to be translated, you should make sure that the English string in both the mission and the tstrings.tbl is the same string.

**Comment by NovachenFS2** [comment]
With your given information i made another test. Well, actually it appeared in the Tech Room after i gave the string the same name in the `#German` section as in the mission file.

So we are talking about, that a translated string is called "incompatible" then. A string that could never match with the original one...

Maybe i was too inaccurate then.


A simpler example:

We have a mission with the name "Single Mission".
Let's say we give it a string id with 500, so it would be `XSTR("Single Mission", 500)` in the mission file.

So, in the `#default` section of an exclusive tstrings.tbl we add:
`500, "Single Mission"`

So, if you play on english, it works. As both entries are the same, like you wish.
But in any translation it will never match... 

In `#French` it is `500, "Unique Mission"` (regardless of whether this is the exact translation) and in `#German` it is `500, "Einzelmission"`

Both terms are different to the required `"Single Mission"` then.

**Comment by Goober5000** [comment]
If the mission has `XSTR("Single Mission", 500)` and the tstrings.tbl `#default` section has `500, "Single Mission"` then it should work, regardless of what language you use: English, German, French, etc.  Are you saying that it still does not work in this situation?

**Comment by Goober5000** [comment]
I looked at the code again.  The only condition for single missions being removed from the tech room is if the mission string and the  English string are different.  It should not matter what any other language uses.

"Different" includes spaces and capital/lowercase, so make sure those match.

**Comment by NovachenFS2** [comment]
> Are you saying that it still does not work in this situation?

Exactly. The mission is only visible, if there is also a `500, "Single Mission"` in the `#German` segment as well. If i use `500, "Einzelmission"` it is not visible and so no selectable.

I went through some previous builds and older MVPs for the matter.

All single missions from the GOTY edition are visible in the Tech Room simulator in the german language setting until the build from 2020-05-05. The Build from 6th May 2020 is the first one, where all missions disappear.

**Comment by Goober5000** [comment]
Can you upload a fso log for a debug run when the mission is not visible?

**Comment by NovachenFS2** [comment]
Here i go. That is the first build, where the missions are not shown.

[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/6629625/fs2_open.log)

**Comment by NovachenFS2** [comment]
> Well I see that it is indeed using German, but this is very strange. I will need to give you a custom build with more logging statements. Do you run 64-bit?

Yes.

**Comment by NovachenFS2** [comment]
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/6641846/fs2_open.log)

So a new log.
According to the log, that error does seem to affect the Multiplayer Missions aswell, which i did not check in any way.

**Comment by Goober5000** [comment]
Oh, this is interesting.  In some cases it's comparing an identical string both with and without an XSTR tag, so it's generating a false mismatch.  In another case it's comparing a string to an empty string.

Can you attach the mission and the tstrings that you tested it on?

**Comment by NovachenFS2** [comment]
[German GOTY.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6644573/German.GOTY.zip)

I only use original released files here. So that is everything from the German GOTY release. No custom files.

**Comment by Goober5000** [comment]
Okay, I tracked down the problem.  Switching between XSTR languages isn't as simple as changing the language index; the different section of the table needs to be parsed as well.  This will require a bit of thought to fix.

**Comment by Goober5000** [comment]
See if this build fixes the bug.
[fs2_open_21_3_0_x64_AVX2-FASTDBG.zip](https://github.com/scp-fs2open/fs2open.github.com/files/6646138/fs2_open_21_3_0_x64_AVX2-FASTDBG.zip)

**Comment by NovachenFS2** [comment]
> See if this build fixes the bug.

Seems so. Single Missions and Multiplayer Missions are visible and playable again.
