### ISSUE TITLE
Assert when exiting scripted menu then reloading mission

### ISSUE THREAD

**Issue by MatthTheGeek** [scp-fs2open/fs2open.github.com#3474]
Happens on debug build only. Tested on current (1.1.5) BP Complete with 21.3.0.20210603_22be402de

My assumption is parts of the missions are not unloaded properly because we exit the mission in an unexpected way.

Steps to reproduce: 
- Load BP1 mission bp-01-1.fs2. 
- From briefing, enter the database with the button on top right. 
- Exit with escape (not with the exit button), this brings you back to the mainhall.
- Load the same mission again.

```
ASSERTION: "(check == this || !check)" at jumpnode.cpp:251
 Jumpnode Jump Node 1 is being renamed to Delta Serpentis, but a jump node with that name already exists in the mission!


Assert: "(check == this || !check)"
File: jumpnode.cpp
Line: 251
Jumpnode Jump Node 1 is being renamed to Delta Serpentis, but a jump node with that name already exists in the mission!
```

**Comment by JohnAFernandez** [comment]
Thanks for the quick reproduction steps. I think I have a fix, but let's see what the other SCP members think.
