### ISSUE TITLE
Assert in F3 lab for select missiles

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3523]
```
ASSERTION: "team != -1" at object.cpp:1888
 Obj_team called for a object of type None with no team.
```
This can be tripped when viewing certain kinds of missiles, in particular the impulsive ray in Warmachine. I don't see myself digging beyond that in the immediate immediate near term, filing in case it's something really obvious someone can see and so I can remember and come back to investigate it later if not. Attaching that weapon's table file for the sake of more complete information.
[wm-m-vish-S-impray-wep.txt](https://github.com/scp-fs2open/fs2open.github.com/files/6681163/wm-m-vish-S-impray-wep.txt)

**Comment by MjnMixael** [comment]
New lab doesn't even let you select weapons. Not sure if that's planned to be added or not, but until then this seems no longer relevant.

**Comment by JohnAFernandez** [comment]
Agreed.  No longer an issue.  We can reopen or create a new issue if that changes.
