### ISSUE TITLE
[QtFRED] Ship Editor not saving edits correctly

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#3541]
I noticed earlier today while re-examining some of the QtFRED dialogs that the Ship Editor does not save information when closed.

As a quick test, you can open up QtFRED, modify the default Ulysses to be a different class, then attempt to close the dialog. The result is that the default ship is still a Ulysses instead of the new ship class.

**Comment by TheForce172** [comment]
This has been fixed and should be closed
