### ISSUE TITLE
Big bug: Empty turrets getting refilled on load

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3549]
Expectation: When 'none' is selected for a turret's banks in FRED, the turret will have no weapon and do nothing. That's how it works on 21.2.0.
Reality on 0703 nightly: When the mission is loaded by FSO or by FRED the empty banks are refilled with default weapons. FRED writes out the empty banks the first time but does not read them properly.

**Comment by jg18** [comment]
@EatThePath thanks for reporting this.

To help with repro/debugging/verifying, could you attach a minimal test mission (using only retail assets), please?

Thanks!

**Comment by Goober5000** [comment]
Looks like this is the same bug that's fixed by #3570.

**Comment by Goober5000** [comment]
Fix merged.
