### ISSUE TITLE
Command Briefing Scroll Buttons Disabled for TC

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#3550]
When we first added scroll buttons 19 year ago, we disabled them if there was not a custom background specified.  This is probably an incomplete check to maintain retail behavior.  If a Total Conversion simply replaces the original bitmaps but has a long Command Briefing, it will simply disable the scroll buttons without the modder having any idea why.  Better to have a check for retail before disabling.

See https://github.com/scp-fs2open/fs2open.github.com/blob/4ef212157a6c21fa61ff52d319163c9f6eea3446/code/missionui/missioncmdbrief.cpp

line 571

**Comment by Goober5000** [comment]
There isn't any way for the game to tell whether a background bitmap has the scroll buttons coded in or not.  The interface files are set up with the assumption that `CommandBrief-m` has no scroll buttons while `CommandBrief-mb` has buttons.  Similarly, `weaponloadout-m` does not have the "apply-to-wing" button and `weaponloadout-mb` has the button.

If a TC doesn't want to supply the extra set of files, then the only other thing I can suggest is to add a mod_table setting.
