### ISSUE TITLE
Briefing icon in ships.tbl is no longer applied when icon image is set to Unknown

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3575]
[Relevant xkcd.](https://xkcd.com/1172/)

[Commit 15901e4](https://github.com/scp-fs2open/fs2open.github.com/commit/15901e430ffe19edfe936a74f98718494bbaa45e) changed how ship classes with custom briefing icons are handled. It used to be that the custom icon was always used, no matter what. That commit changed it so some types of briefing icons will win out over the icon in ships.tbl.

While the new behavior is definitely more intuitive, we've actually been using the old behavior in the next chapter of _Between the Ashes_ - we wanted a ship to use its ships.tbl icon, but still show up as Unknown while clicked on. This change causes the Unknown icon to "win" over ships.tbl, which breaks the visuals of some of our briefings.

With that in mind, could this be controlled by a game\_settings.tbl flag or something? (More ambitiously, if briefing icons supported some form of alt name, that would also meet our use case.)

(There's a reason why creating a copy of the ship just for briefings is less practical than you might think, but I can't really get into it publicly.)

**Comment by JohnAFernandez** [comment]
@Goober5000

**Comment by Baezon** [comment]
What exactly is the situation here? If I'm understanding right, its a ship which has a class-specific briefing icon, but in the briefing this ship was specifically given a gas cloud (?) icon. Before, this would've used its class icon, but after the change it would use the gas cloud. If that's the case, why was this particular ship given a gas cloud icon at all?

**Comment by naomimyselfandi** [comment]
> 
> 
> What exactly is the situation here? If I'm understanding right, its a ship which has a class-specific briefing icon, but in the briefing this ship was specifically given a gas cloud (?) icon. Before, this would've used its class icon, but after the change it would use the gas cloud. If that's the case, why was this particular ship given a gas cloud icon at all?

The Unknown icon looks like a gas cloud, that's all. I'll edit the description to be more clear.

**Comment by Baezon** [comment]
The gas cloud *is* the proper icon for the unknown icon type though. Just to make sure I've got it straight, you have a ship, which you want to have a normal icon for, but when clicked on gives you the big question mark? It only has the Unknown icon, not to actually change the icon, but to change just the preview?

**Comment by Goober5000** [comment]
XKCD comic on point. :+1: 

The custom icon behavior broke a lot of old retail missions, so the current behavior needs to be the default.  But I can add a compensatory feature.

Can you elaborate on your alt name suggestion @naomimyselfandi ?  I'm not sure how that would help since icons are not the same thing as labels.

**Comment by naomimyselfandi** [comment]
> 
> 
> The gas cloud _is_ the proper icon for the unknown icon type though. Just to make sure I've got it straight, you have a ship, which you want to have a normal icon for, but when clicked on gives you the big question mark? It only has the Unknown icon, not to actually change the icon, but to change just the preview?

Yes, that's correct.

**Comment by naomimyselfandi** [comment]
> Can you elaborate on your alt name suggestion @naomimyselfandi ? I'm not sure how that would help since icons are not the same thing as labels.

Sure. It doesn't _directly_ help (which might be the source of confusion). When you click on an icon (and it isn't Unknown), it shows you the icon's class's model and name. If we could change that name, then that'd also satisfy this use case.

...although, as I was typing this up, I just realized that "Acts of Volition" in _Slaves of Chaos_ uses a planet icon to represent Lt. Sermak in the briefing, so it wouldn't actually satisfy it after all.

**Comment by Goober5000** [comment]
Implemented in #3576.
