### ISSUE TITLE
Script/SEXP FR: Control over lightning

### ISSUE THREAD

**Issue by X3N0-Life-Form** [scp-fs2open/fs2open.github.com#3583]
I've always thought it would be neat if modders could do things with the nebula lightning effect outside of nebula missions.

What I would like is to have some way to spawn a lightning bolt at will, ideally through scripting. It would allow for a number of cool things, from dramatic lightning strikes, to proper lightning guns, to **unlimited power!**.

From what I recall from glancing at some of the relevant code years ago, it *seemed* like exposing the lightning bolt creation function itself wouldn't be overly complicated, but that non-nebula missions would also need to be able to spawn lightning at all (see nebl_process() in neblightning.cpp for instance).

**Comment by MjnMixael** [comment]
+1
