### ISSUE TITLE
Particles FR: Ability to set spawn chance for particles below 50%

### ISSUE THREAD

**Issue by Kestrellius** [scp-fs2open/fs2open.github.com#3587]
At present, there is no way to make a particle effect that will spawn particles less than 50% of the time. This is because the lowest possible range for number of particles (other than just zero) is (0 1).

In various situations -- especially things like beam impacts, where the engine will fire off the particle effect every frame -- it would be useful to have a lower probability than this, e.g. an effect that will only successfully spawn a particle every one hundred times it's activated.

One conceptually simple way to implement this would be to allow the number parameter to parse negative numbers, but clamp negatives to zero once a number has been chosen. That is: say that you want a .25 chance of spawning a particle. You set the number of particles to (-2 1).

Then, the game randomly chooses a number: -2, -1, 0, or 1. But if -2 or -1 is chosen, they get clamped to 0. So the actual distribution is 0, 0, 0, 1. With a little bit of arithmetic, it would be easy enough to use this technique to generate a wide range of probabilities.

A more robust method of implementation would be a simple new parameter: spawn chance. It would default to 100, resulting in the existing behavior, but at, say 70, the effect would have a thirty percent chance to "fail" and not spawn any of its particles. (If the effect has a chance to spawn zero particles, then that would be something that happen after a "success" -- not factored into this calculation.)

(@EatThePath asked to be pinged in this FR.)

**Comment by talhydras** [comment]
Warmachine could take huge advantage of improved particle spawning functionality - we heavily use short duration beams, so having more precise control over spawning of particles would allow us to make more visually appealing impact fx as well as reduce unnecessary particle spawns.

**Comment by Kestrellius** [comment]
Feature has now been implemented by EatThePath.
