### ISSUE TITLE
FR: unclamp velocity inheritence.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3606]
Weapon velocity inheritance seems to be clamped between 0% and 100%. Values outside this range would be nonsense, but they might be fun nonsense.

**Comment by Baezon** [comment]
Are you sure it's capped? I seem to be able to use some pretty crazy values...

**Comment by EatThePath** [comment]
Looking at the code now it appears it's unclamped. I certainly remember hitting difficulties with trying to use over 100%, but maybe that was running into some other limitation. I'll have to look into it again in the future and try to pin down what's going on, but I'll close this and if I can find a test case for my issues again I'll bring it back up in whatever form is appropriate.
