### ISSUE TITLE
"Current target, any subsystem" multilock mode targets destroyed turrets

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3613]
This applies both to holding existing locks and creating new ones. Not sure if the same is true of non-turret subsystems. I have not historically used this mode that much, so I suspect this isn't a new flaw, but it doesn't seem like it's likely to be the intended functionality.

**Comment by Baezon** [comment]
I can't say for sure, but I was under the impression this was intentional. Multilock weapons target turrets not simply to destroy those subsystem but also to weight large ships as targets more heavily, and to always have a variety of locks on multiple positions on its hull. Which makes targeting even destroyed subsystems make more sense.

It should be noted that subsystems, destroyed or not, are the *only thing* multilock missiles aim for. By disabling locks on subsystems with 0 or less health, a ship with no visible healthy subsystems would be completely untargetable.

**Comment by BMagnu** [comment]
> a ship with no visible healthy subsystems would be completely untargetable.
That is true.

However, it could be argued, that any ship with _no_ alive subsystem (so, in most cases, no engines, no weapons, no turrets, etc) can be disregarded by the player.

> but also to weight large ships as targets more heavily

That is a very real point though.

Thinking about this, I am almost convinced this behaviour should be selectable by a -mod or -aip flag.
Opinions?

**Comment by EatThePath** [comment]
@Baezon Under "any target" I can see the weighting issue, potentially. Under "Current target, any subsystem" it's always going to be all on one target anyway. 

But the point about a fully stripped ship is a good one. Could it be made to pick up 0-health subs only when it runs out of non-0 ones?

**Comment by Baezon** [comment]
> However, it could be argued, that any ship with no alive subsystem (so, in most cases, no engines, no weapons, no turrets, etc) can be disregarded by the player.

While true, this would also apply to a ship which has no subsystems at all to begin with, although thats kind of a fundamental issue with always aiming for subsystems on large ships.

> Thinking about this, I am almost convinced this behaviour should be selectable by a -mod or -aip flag.

I would be in favor of a flag of some kind, although I'm not entirely sure what form exactly it would take/what the new behavior should be (if we want to resolve all the mentioned issues, anyway)

**Comment by BMagnu** [comment]
Yeah, it should probably be a flag.
Presumably just a weapon-info flag like "ml-ignore-dead-subsys" or something.
Then it's toggleable per weapon, and up to the modder to decide which factors are more important

**Comment by EatThePath** [comment]
yeah, per weapon would be my preference if it's going to be a configurable thing.

**Comment by EatThePath** [comment]
On the topic of if this is or is not a bug: I'll defer ultimately to the SCP's judgement in such things, but I'll make my case first.

First of all, it's hard for me to accept this is not-a-bug, because to my eyes the most obvious use case for this target mode is to strip the turrets off a ship and this behavior completely guts that. If a player uses a weapon designed that way, they need to know about it this, watch for the death of each turret beneath their weapon's hit effects, and then try to use the edge of their lock cone to 'scrape' the locks off the dead turrets while still keeping some live ones in their view. It's extremely awkward and artificial. 

Yeah, maybe someone out there could try to use this as a way to get cinematic volume of fire on a ship killer, and a flag to ennable that by letting you lock dead subsystems if there aren't enough live ones in view is a feature I support. But it seems backwards to not make the default behavior support that rather than fix it now before anyone makes a mod depending on that. 
Generally, ML weapons only break one rule, the single lock rule. Other missiles don't work this way, you don't keep targeting a Sathanas' dead beam cannon after bombing it, though I can construct some niche scenarios where someone might want to. This behavior shouldn't be inherent in this one targeting mode (or two? I know 'current target only' definitely doesn't do this.) If someone wants it, then it should be a per weapon flag that can be used on any locking weapon, not just here, and the current AIP flag solution makes that option messier and more confusing if someone wants to have both behaviors on the weapons in the same mission 

Strygon doesn't use `Current target, any subsystem` for any weapons in fcw, it doesn't appear that WoD does either on any of it's weapons. Maybe Axem or Spoon wanted it this way but they didn't use it, and it wouldn't have come up in testing because originally these missiles were only targeting turrets out of view until a bugfix this or last year, rather than turrets in view. If this was indeed the design, then IMO that design was a mistake and one FSO has the rare chance to correct before it becomes locked in by backwards compatability.

My opinion is admittedly rather biased. Two warmachine weapons are affected by this and I consider the current state unacceptable for them, so it kills the idea of actually finally pinning on a stable for us. I don't expect development to revolve around us, so if you don't find my reasons above compelling, so be it. But I guess in summary, to my mind an AIP-gated fix is just adding one more to the long list of 'make the game work like you thought it would' flags to maintain bug for bug compatibility for mods that as far as I know just don't exist.

**Comment by Baezon** [comment]
You make very fair points, and really not much more than backwards compatibility, even as recent as it is, makes me think that the new behavior should be opted-into, even if it makes more sense. Input from others would definitely be appreciated.

**Comment by Baezon** [comment]
Also, there is another rule ML missiles break, and that's, unless I'm mistaken, they are completely unable to lock the ship, and not its subsystems, for large ships. If dead subsystems are ignored I feel like this becomes a bigger issue, but I'm not sure the best way to resolve it.

**Comment by EatThePath** [comment]
> 
> 
> Also, there is another rule ML missiles break, and that's, unless I'm mistaken, they are completely unable to lock the ship, and not its subsystems, for large ships. If dead subsystems are ignored I feel like this becomes a bigger issue, but I'm not sure the best way to resolve it.

A rule I do wish was individually optional, but that's definitely a FR and but a bug.

I think the simplest and most general behavior would be that any ship without valid target-able subsystems gets the core ship targeted? It's a tricky edge case, and one I don't see an immediately appealing way to resolve in this context.

**Comment by JohnAFernandez** [comment]
I'm on the side of the flag being a workaround fix.  

Here's my thought on how to deal with the inability to lock on the large ship:

During the search through susbsystems to look for candidate locking targets, fill two separate variables, one with a live subsystems and one with a dead subsystem.  If no live subsystems are found, use the dead one, otherwise default to the live one that was found.

**Comment by EatThePath** [comment]
@JohnAFernandez could you elaborate on what you mean by

> I'm on the side of the flag being a workaround fix.

just for clarity sake? It feels like there's a few different ways to read it, is all.

In any case the fix you propose is the one I considered pushing for last night, at least in final effect, but it seemed like it'd have to be more elaborate of a system than was viable in this case. But after sleeping on it, and with how you describe the implementation, it seems like it actually shouldn't be unreasonable,  in the abstract anyway. I can imagine wanting optional features that modify it, but I would definitely find that an acceptable state for default behavior.
