### ISSUE TITLE
Escaped quotes in xstr cause freeze in parsing

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3627]
Tested in a few ship table fields. `\"` inside the string causes the parsing to get stuck on that file but never actually error.

**Comment by Goober5000** [comment]
The way to escape quotes in FSO strings is to use `$quote`, but this shouldn't cause problems.  I'll take a look.

**Comment by EatThePath** [comment]
Yeah, I wouldn't file if it just didn't work as an escape, but it appears to send the parsing into a loop and that's not great

**Comment by Goober5000** [comment]
I just figured out the cause.  Will have a PR up later.
