### ISSUE TITLE
FR: no_fred for weapons

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3643]
I have a lot, a LOT of weapons I will never ever want to assign to something in fred, generally submunittions but also upstream weapons I need to have in the files but only get in the way in fred list. A flag to hide them would be very, very helpful.

**Comment by Goober5000** [comment]
I have a plan for how to do this, thanks to #4919.

**Comment by Goober5000** [comment]
Implemented by 4927
