### ISSUE TITLE
Possibly misleading APNG load errors.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3644]
The attached thruster png in blue planet generates a warning in the debug log, I believe every time it is referenced: 
[thruster02-04.zip](https://github.com/scp-fs2open/fs2open.github.com/files/7117873/thruster02-04.zip)
the error is:
`Failed to load apng: (file thruster02-04.png) animation duration <= 0.0f, bad data?`
I also get that error with several recent png beam sections in warmachine, sections which I am fairly confident are actually loaded and displayed properly. I am not certain of what the thrusters are supposed to look like so I'm not sure but I haven't noticed any obvious problems with them.
If they're trying to load as APNG and then falling back when they don't, messages in the log to that effect would be good, because as-is it just looks like the texture is failing to load.

**Comment by z64555** [comment]
Needs a good look at to determine if its a bug or a not-a-bug for next RC.

**Comment by jg18** [comment]
Fixed with PR #3839. Thanks @EatThePath for reporting this issue.
