### ISSUE TITLE
Memory Management of stdlib containers

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#3680]
stdlib containers, such as std::vector, over-allocate space when adding new members with methods such as ::push().  This isn't a concern for most decently built PC's, but is a concern with low-end PC's and systems such as RasPi's that need to tightly manage their RAM.

The over-allocation is implementation dependent on at least the compiler side, and possibly also the architecture.  Memory alignment is also a concern, but we usually don't have a lot of control over it.  C++11 does provide a [::shrink_to_fit()](https://www.cplusplus.com/reference/vector/vector/shrink_to_fit/) method which should take care of the issue, but this method would have to be called at a specific time.  Too much of course would mean too much thrashing from moving the container around, and too little would mean wasted memory (which is probably a lesser concern than calling it too much).

Calling ::shrink_to_fit() would probably be best done on dynamic containers that are largely static in size during most of their use, such as a container that's been initialized at the start of a mission or game instance start and doesn't get any larger throughout that mission.

**Comment by The-E** [comment]
The big question I have here is.... Is this an actual problem we actually need to care about? Are the potential savings in memory allocation something that would actually make a noticeable difference?

To me, this asks for some real-world data. How much memory does the engine allocate for a run through a given mission or campaign, and how much of that is quote-unquote wasted on overallocated vectors?

Intuitively, I would say that this doesn't matter in the slightest. Whatever memory you can save by compacting the Ships list, for example, is certainly dwarfed by reducing the size of some commonly used texture, so this entire thing screams "useless microoptimization that will cause more trouble than the alternative"

**Comment by z64555** [comment]
Yeah, its something I thought I should bring up at the least.  It's not currently an issue and like you said, needs some real-world data before investigating further.
