### ISSUE TITLE
Prefetch particles used in Mission

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#3706]
Particles that can occur in a mission are loaded once they are needed the first time. This can introduce microstutters, due to the required access to the disk. While #3705 improves this already, there are still some microstutters remaining due to the actual access to the disk and loading of the file.
To avoid this, possible particles from weapons / ships / whatever should be prefetched before the mission like other resources.

**Comment by notimaginative** [comment]
Particles weren't paged in properly due to a code bug fixed by #3884. So that fix should solve this.
