### ISSUE TITLE
Windows 10 FSO crashes

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#371]
Lately, FSO has been crashing on a system level very abruptly on Windows 10 during gameplay on missions with large numbers of objects and ships. A blue screen of death (BSOD) appears with a DPC_WATCHDOG_VIOLATION message (though it may be IRQL_NOT_LESS_OR_EQUAL or others in some cases). A log file has not been logged while running on a debug build when a BSOD appears.
![2015-10-09 01 12 58](https://cloud.githubusercontent.com/assets/2004725/10374739/4bea94c2-6e27-11e5-8a8d-620828507130.jpg)

**Comment by niffiwan** [comment]
According to your forum posts, this issue has been acknowledged as a Windows 10 issue. There's nothing that FSO can do about this so I'm going to close this issue.
