### ISSUE TITLE
FSO crashes without an assertion

### ISSUE THREAD

**Issue by bryansee** [scp-fs2open/fs2open.github.com#372]
While running on FSO debug build, it sometimes crashes without displaying an assertion beforehand. The debug logs will display incomplete due to this. It has happened on FRED Open before.

**Comment by niffiwan** [comment]
This really isn't enough information to be able to investigate.  Can you please report what set of steps can be used to repeat this problem, as well as any error messages or screenshots?

**Comment by niffiwan** [comment]
If you can find some more detailed information, please reopen this issue.
