### ISSUE TITLE
Displayed Bank Angle has a Strange Range

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#3730]
(First reported by Strygon on Discord)

[Image 1](https://cdn.discordapp.com/attachments/223511391531827200/899087002157330462/unknown.png)
[Image 2](https://cdn.discordapp.com/attachments/223511391531827200/899087025741901854/unknown.png)

As shown, the Bank angle displayed has a strange range of -90 degrees to 270.  After a quick poking about I found a strange usage of `atanf()` inside of `atan2_safe()` within vecmat.cpp.  Discussion on Discord with DahBlount led me to suspect this is a workaround to C++98's buggy implementation of atan2 is causing the range error.

Modern versions of C++ should have an `atan2()` that works correctly when the inputs are at 0 or near epsilon of the floating point specification, meaning Volitions workaround shouldn't be needed anymore.

Note: the angles are correct, but not intuitively displayed for humans.

**Comment by Goober5000** [comment]
Here is the beginning of the discussion...
https://discord.com/channels/223511295431933953/223511391531827200/899086866970718250

It looks like all instances of `atan2_safe` can be changed to `atan2`.
