### ISSUE TITLE
Custom HUD gauge activation is retained when relaunching a mission

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3756]
When a player restarts a mission while custom HUD gauges have been activated, they remain activated as the mission restarts. This is counterintuitive and leads to very odd user experience.

**Comment by Goober5000** [comment]
Does this still occur?  I tried a MOTGW mission and its custom HUD gauge deactivated successfully.

**Comment by Goober5000** [comment]
Bump again.

**Comment by z64555** [comment]
Punting to 22.4 due to lack of feedback from reporter.

**Comment by Goober5000** [comment]
Closing since this appears to no longer be an issue.
