### ISSUE TITLE
set-subsystem-strength with <argument> causes a mission to fail to load

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3758]
On the latest nightly, I just got the following warning:

> Warning: Invalid ship name.
> 
> In sexpression: ( when-argument 
>    ( in-sequence 
>       "Redacted"
>    )
>    ( is-in-mission "&gt;argument&lt;" ) 
>    ( sabotage-subsystem 
>       "&gt;argument&lt;" 
>       "&gt;all engines&lt;" 
>       0 
>    )
>    ( set-subsystem-strength 
>       "&gt;argument&lt;" 
>       "Hull" 
>       ( rand-multiple 10 90 ) 
>    )
> [...]
> (Error appears to be: Hull)
> File: missionparse.cpp
> Line: 6117

The mission then failed to load.

"Hull" is, of course, the subsystem name, not the ship name, and the mission loads correctly on yesterday's nightly.

This is likely related to [commit 14123b1a04a44c9d7604bdeeb14c433b9c13a823](https://github.com/scp-fs2open/fs2open.github.com/commit/14123b1a04a44c9d7604bdeeb14c433b9c13a823).

**Comment by Goober5000** [comment]
Welp.  I'll take a look.
