### ISSUE TITLE
Multiple events with the same name don't cause a FRED warning

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#3766]
Exactly what it says on the tin. Accidentally giving multiple events the same name can lead to really confusing mission bugs and should trigger a warning in FRED.

**Comment by Karajorma** [comment]
You're probably going to need to set it to ignore the default name for events.

**Comment by Baezon** [comment]
Does actually cause it any issues? As I understand it, FSO itself doesn't need the names at all. I'm not sure FRED should warn for otherwise perfectly valid data, that is simply unideal organizationally for a FREDder.

**Comment by naomimyselfandi** [comment]
> Does actually cause it any issues? As I understand it, FSO itself doesn't need the names at all. I'm not sure FRED should warn for otherwise perfectly valid data, that is simply unideal organizationally for a FREDder.

Well, that depends on what you mean by "issues". The behavior of `is-event-true-delay` et al. is _probably_ still well-defined, but it's really counterintuitive. If a mission is complex enough for a FREDer to accidentally give two events the same name and not realize it, not knowing why `is-event-true-delay` is mysteriously returning the wrong result is... unpleasant.

**Comment by Baezon** [comment]
That's true, perhaps then it should warn if any SEXP which uses event names directly is used on events where the name is ambiguous?

**Comment by naomimyselfandi** [comment]
> That's true, perhaps then it should warn if any SEXP which uses event names directly is used on events where the name is ambiguous?

(I'm sorry, busy couple days, I missed this reply)

Sure, that makes sense and definitely accomplishes what I'm looking for. :)

**Comment by Goober5000** [comment]
I just thought of a simple way to do this.  PR incoming.
