### ISSUE TITLE
Possible Regression: Sentry Guns can no longer accept big ship weapons in FRED.

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#3768]
In Retail, The Mjolnir uses a beam with the "Big Ship" flag, while the Mjolnir itself has the "sentry gun" flag, before, it was possible to give the Mjolnir or (any other sentry gun) a "big ship" weapon in FRED, but now when opening the weapons window with a sentry gun selected in FRED's ship editor, the drop-box is blank, selecting it will show only small ship weapons, and (in the case of the Mjolnir) the default beam cannon is not shown and therefore unselectable. The mission must be edited in notepad to force the Mjolnir to use the correct weapon, or other any "big ship" weapons.

I'm fairly certain that this was not the previous behavior, and that it used to be possible to assign any (primary/beam) weapon to any (Primary/beam) turrets in FRED, (likewise for secondaries and missile turrets) It would be really useful if this functionality we restored assuming it previously existed, or if not, then at the very least, that Sentry guns be allowed to carry "big ship" weapons in FRED.

**Comment by Goober5000** [comment]
You might want to check your ship flags.  I just took a look at this and found the following:
1) The Mjolnir has the "cruiser" tag, both in retail and in the MediaVPs.
2) Loading "The King's Gambit" showed the Mjolnirs with both MjolnirBeam and MjolnirBeam#home as expected.
3) It's possible to switch the Mjolnir weapons from beams to lasers and back again.
4) It's not possible to assign a MjolnirBeam (or any other beam) to a small sentry gun such as the Alastor, but - as you inferred - the "sentry gun" object type is not a "big ship".

**Comment by Goober5000** [comment]
Closing since it's been a month.
