### ISSUE TITLE
Non retail sized head animations don't draw the background & border at the correct size

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#378]
This is easiest to see with the default head animations colour scheme (i.e. 8 bit palette) and a WoD EFF animation. _Probably_ not a big deal since the larger head headani's that I've seen in mods are always using full-colour head animations; this means the animations have no transparency and that makes the issue very hard to see.

**Comment by Yarn366** [comment]
What's happening is the black background's size is determined not by the animation size but by the "Animation Background Size" parameter (which defaults to 160x120) in hud_gauges.tbl. And the border is just a single HUD graphic, so its size can't simply be changed to fit the head animation.

I did make an SVN patch a year ago that address this, but it has yet to be committed. It works by scaling the animation to fill the area specified by "Animation Background Size" or "Animation Size" in hud_gauges.tbl. The Mantis report, along with the patch, can be found here:

http://scp.indiegames.us/mantis/view.php?id=3122

**Comment by MageKing17** [comment]
Could we get that in the form of a pull request?

**Comment by Yarn366** [comment]
Here it is: https://github.com/scp-fs2open/fs2open.github.com/pull/404

**Comment by MageKing17** [comment]
Awesome. I'll try to review it later.

**Comment by niffiwan** [comment]
Sorted; thanks @Yarn366
