### ISSUE TITLE
FR: Allow backwards dumb_rotation

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#3782]
currently, dumb rotation seems to be constrained both to the flat x, y and z axes, as well as only rotating clockwise around the axis.
At least the latter should be allowed by specifying a negative dumb_rotation_rate or similar

**Comment by Goober5000** [comment]
I'll roll the negative fix into my upcoming PR.  Might be able to roll the axis fix too; will check

**Comment by BMagnu** [comment]
NVM, seems to be some sort of issue with how I did it. I got it to work now...
