### ISSUE TITLE
On Frame Hook does not function when the "quit mission" pop up is displayed

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#3788]
This is was done on purpose in http://scp.indiegames.us/mantis/view.php?id=2446. Now I can't exactly say since the version of the script that was linked is undoubtedly no longer the current version, but this strikes me as being far more likely to be a problem with the script, *not* a problem with the engine.

"On Frame", in my opinion, should mean exactly that. Was a frame rendered? Here's your hook. It should not mean "Every frame except for certain arbitrary specific circumstances" unless it is impossible to do so in those circumstances. If a script is producing particles then it should be using the mission's frametime and not real frametime, which I can only speculate was the true cause of this bug.

I would really like to not introduce an 'On Frame Including The Quit Mission Pop Up' hook, and I highly disagree that all scripts should be forcibly disabled because some scripts were not designed with all the situations in mind. And importantly, I'm not aware of any other method to call scripts while this quit mission prompt is open.

**Comment by Goober5000** [comment]
Interesting conundrum.  I'll have to think about this.

I will say a few things:
1) I can't be certain that this script was ever used in a released mod.  I verified that it was never included in the MediaVPs - with the caveat that I can't check `MVPs 3.6.9_z` but I think this script postdates that.
2) The current MVP scripts should not be affected by this.
3) Pressing Pause triggers a state change, whereas pressing Escape does not, unfortunately.  Is there any way for a script to detect that the Escape dialog is active?

This could be a candidate for a game_settings.tbl flag.

**Comment by wookieejedi** [comment]
FotG uses a good number of scripts with `On Frame:`, where it is very useful that the escape stops the hook. It would be easy to adding in an extra conditional in the scripts to check if Escape was pressed, though as Goober mentioned I don't think such a check exists to call ATM.

A game table flag would also be a good option IMO, even if less granular.

**Comment by notimaginative** [comment]
Most popups don't process the game frame. The popup takes an image of the current screen, shows it as a bitmap, and draws the popup on top. It calls gr_flip() but is otherwise a closed loop (`while() { ... }`). There are other places in the code that call gr_flip() in such ways too (or used to be at least).

So running scripts in gr_flip() really isn't safe since it doesn't necessarily mean it's a game frame but a subprocess which puts everything else on hold. Some scripts could be safe to use there (io... and maybe that's it?) but most wouldn't.

**Comment by Baezon** [comment]
I mean I'll happily side-step the issue here if my selfish modding concerns can be satisfied, but I would like to simply draw some stuff to the screen while the pop-up is open. Any script-drawn graphics will persist during this time, but I have no idea how to detect and draw special graphics when this screen is opened and before it's too late.

**Comment by notimaginative** [comment]
Looking over the code real quick you've got two useful functions: `popup_active()` and `popup_running_state()`. The first will obviously indicate whether a popup is on screen and the second should return whether it's running a game state while the popup is active or if it's processing in a loop.

I don't know the scripting code enough to say how best to take advantage of those functions but I think what you want should be possible with a few minor tweaks. You'd just have to be careful not the break anything, like the fix (or workaround, honestly) for that mantis bug.

**Comment by asarium** [comment]
Thinking back to it, I agree that putting that _very_ special case in the `On Frame` hook wasn't the best solution for the problem. I am not sure if such a function already exists but as @notimaginative pointed out, `popup_active` would be sufficient to detect this situation from a script.

**Comment by Baezon** [comment]
Looks like it does. Many thanks.
