### ISSUE TITLE
Linux table load order still not fixed

### ISSUE THREAD

**Issue by the-maddin** [scp-fs2open/fs2open.github.com#3794]
PR #3734 does not fix the Solaris issue for me (which started the investigation of the bug addressed), namely the script tables are not loaded in inverse alphabetical order, as seen here: https://fsnebula.org/log/619c2f5ecd283f42c22001d9#True-425

_Originally posted by @the-maddin in https://github.com/scp-fs2open/fs2open.github.com/pull/3734#issuecomment-976023973_

**Comment by Goober5000** [comment]
paging @notimaginative

**Comment by the-maddin** [comment]
One moment, I might have made a mistake elsewhere

**Comment by Goober5000** [comment]
🤔

**Comment by the-maddin** [comment]
Just remembered I changed some things around in the Solaris data directory as a workaround, I'm retrying on a clean install

**Comment by the-maddin** [comment]
Sorry for the mess; the scripts are loading in the correct order now.
But there's a new bug since 21.4.0 in the visual novel script: Every text gets suffixed with (no wavefile for voice), but the voice plays correctly. I'll make a new issue with a log and this can be closed.

**Comment by Goober5000** [comment]
:+1:
