### ISSUE TITLE
Missing fs2_open_*-source-*.tar.gz in newer releases

### ISSUE THREAD

**Issue by sizeofvoid** [scp-fs2open/fs2open.github.com#3807]
Is this a conscious decision to stop providing source release tarballs? It would be helpful for package distributor if you could provide source-code-release tarballs like https://github.com/scp-fs2open/fs2open.github.com/releases/tag/release_19_0_0

Thanks in advance, Rafael

**Comment by z64555** [comment]
Hello, sorry for the late reply.

Currently our consensus is that we're dropping hosting tarballs and instead marking releases within the codebase with tags with each release and RC.  This of course may upset the workflow of those that used the tarballs, but as of to date, you're the only one who has spoken up about it.

**Comment by z64555** [comment]
Closing due to lack of feedback.
