### ISSUE TITLE
Recent tonemapper change causes fatal shader error on Linux

### ISSUE THREAD

**Issue by notimaginative** [scp-fs2open/fs2open.github.com#3821]
Changes from PR #3801 cause the tonemapper shader to fail to compile on Linux which results in a fatal error.

`0:113(27): error: initializer of const variable 'toeStrength' must be a constant expression`

The error is generated for lines 113-117 and appears to be due to `const` not being valid for a variable initialized by a uniform. Simply removing the `const` allows everything to work as normal. My GLSL knowledge is at least 10 years out of date however so there may be a more appropriate fix.

This *may* be a Linux driver bug but I have not confirmed that so far.

```  OpenGL Vendor    : Intel Open Source Technology Center
  OpenGL Renderer  : Mesa DRI Intel(R) HD Graphics 615 (KBL GT2)
  OpenGL Version   : 4.6 (Core Profile) Mesa 20.3.5

  Max texture units: 2 (32)
  Max client texture states: 2 (1)
  Max elements vertices: 3000
  Max elements indices: 3000
  Max texture size: 16384x16384
  Max render buffer size: 16384x16384
  Can use compressed textures: YES
  Texture compression available: YES
  Post-processing enabled: YES
  Using trilinear texture filter.
  OpenGL Shader Version: 4.60
  Max uniform block size: 65536
  Max uniform buffer bindings: 84
  Uniform buffer byte offset alignment: 32
```

**Comment by notimaginative** [comment]
@EatThePath You probably understand that change best.

**Comment by EatThePath** [comment]
> @EatThePath You probably understand that change best.

The changes you've tried sound sane as far as I know. Practically everything I know about shaders I learned from either blundering through FSO code or from SCP members after the first path failed me, anyway 😄

**Comment by wookieejedi** [comment]
Hmm maybe @The-E or @asarium might have some additional input?

**Comment by asarium** [comment]
I just looked at the shader and given that we officially need to support OpenGL 3.1, I don't think we can actually use global variables.

All those computations need to be moved into a function (maybe stored in a struct for easier passing around in the shader) to fix this properly.

**Comment by EatThePath** [comment]
This is crashing windows users too, it seems. I'm waiting for a test report from an effected user but I've got a fix ready to submit based on just axing the consts. Restructuring for opengl 3.1 support is something I could probably do this week but am not doing today.
