### ISSUE TITLE
`set-alpha-multiplier` does not affect glow maps

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#3822]
Seems like it probably should, but this is beyond me.

**Comment by Goober5000** [comment]
I'm bumping this to high priority since this is now needed for an active mod.

**Comment by Durandal-Thoth** [comment]
Attached test mission and associated assets for my use case. I'm looking for a sphere which the player can fly through, can fade in/out based on distance, and does not reflect light or receive shadows.

In addition, there are serious issues with parts of the sphere rendering differently, which at a glance appears to be based on where the directional light is coming from? I'm unsure, though.

While this doesn't affect the glowmaps, the glowmaps are also presently ignoring alpha, so for all I know the same issue may present itself.
[alpha-mult-test.zip](https://github.com/scp-fs2open/fs2open.github.com/files/12666504/alpha-mult-test.zip)
