### ISSUE TITLE
New animation code causes crashes in multi

### ISSUE THREAD

**Issue by notimaginative** [scp-fs2open/fs2open.github.com#3836]
I completely missed this in the original PR for the phase 2 animations, but when the animation packet is sent it uses `animationId` and `pmi`, both of which are only valid in the local instance. Neither index is necessarily present on a different client or the server and either causes the animation to do nothing or more than likely to just crash the server/client.

The packet should use the net signature of the object instead of the pmi and from that the proper local model instance can be retrieved (`multi_get_network_object()` followed by `object_get_model_instance()`). I'm not sure about the animation id however as I don't know the animation enough.

**Comment by notimaginative** [comment]
@BMagnu Hopefully you have some ideas on how to fix this. We'll need to disable the animation packet otherwise so that 22.0 isn't released with broken multi.

**Comment by BMagnu** [comment]
I can try to rework the animation ID to be equal on all clients as long as the tables used are identical.
And as for replacing the pmi with a network instance, is this sort of possible. It's possible for all things which have an object associated with it, but not stuff that has not. That will catch most animations, but when you'll eventually be able to animate other things, these wouldn't sync. But I guess that can't be helped.

**Comment by notimaginative** [comment]
Does the animation code work with non-models? Every model instance should be associated with an object as far as I know. I can't think of anything else off-hand which would be in sync over the network so if it doesn't have an object associated then it probably should just keep those animations local.

There isn't currently any way to indicate that tables are the same on different clients so it best to assume that they won't be. Is there any other way to identify an animation that could be used as a general lookup?

**Comment by BMagnu** [comment]
There are currently two non-object models I am intending to enable for animations.
One, the cockpit, should obviously stay local, the other, the skybox, not necessarily.

As for the tables, I'll be able to identify them by a hash of name + ship_index. I guess I'll just make it not do anything if that combination doesn't exist. And if it does, but is something different, tough luck.
Do I need to account for the possibility that the net signature doesn't yield a valid object? It's fine if it's a different type of ship, then it'll just not find and not play the animation. But a nullptr would be bad

**Comment by notimaginative** [comment]
`multi_get_network_object()` will return null if the object isn't found, which can and does happen, so plan for it. If it returns non-null then you can use `object_get_model_instance()` to get the pmi regardless of the object type (doesn't have to be a ship). That function will return -1 if the object doesn't have a model instance however, so take that into account also.

And a net signature of 0 is invalid so you could use that to indicate some special handling where the animation should not be associated with an object. You would just need to add some other way to indicate what the animation is and is for.

**Comment by BMagnu** [comment]
Alright. Should be doable in a few days. Hardest part will be to find the object pointer, since the animations only ever really touch pmi's, but I'll think of something.
