### ISSUE TITLE
Sphere-type particle effects are not quite uniform across the sphere

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#3840]
[test-wep.txt](https://github.com/scp-fs2open/fs2open.github.com/files/7759877/test-wep.txt)
[test-part.txt](https://github.com/scp-fs2open/fs2open.github.com/files/7759879/test-part.txt)

These cause subach bolts to explode into a bazillion particles in all directions, what should be uniformly randomly in all directions but this the result:
(viewed from the interior of the spherical shell of particles)
![screen0012](https://user-images.githubusercontent.com/17305613/147033059-7ff7420b-a32e-423d-a861-3de9f8b94582.png)
(directly behind looks the same)

Gonna call this low priority because this is subtle enough that you really need a lot of particles to even tell this is happening.

**Comment by jg18** [comment]
Fixed with PR #3841.
