### ISSUE TITLE
Support ship docking bug

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#3853]
As reported here:
https://www.hard-light.net/forums/index.php?topic=97956.0

> But, this weekend when I played thru Dunkerque, I noticed that if one of my wingmen asked for a reload, the Hygeia ship would just circle around the ship that made the request but would never actually dock with it. If I call in the Hygeia, it will happily dock with my ship and reload me, but when my wingmen ask - the Hygeia pilot is like, "Nope, not today!" This will go on for about a minute and then the requesting ship will eventually give up and go about its business, but if another wingman puts in a request the same thing will occur.
>
> Here's what I've discovered about this issue so far:
> 1) This only happens in FS2 - it does not happen in FS Port, Silent Threat, Destiny of Peace or any of the other mods in my meager collection.
> 2) This only happens with 21.4 - if I go back to 21.2, the Hygeia docks with the wingmen just fine during the missions.
> 3) I haven't tried ALL of the FS2 missions, so I don't know if this starts to happen after a specific point in the game or in any mission (or any FS2-based mod/mission, for that matter).
>
> I'll go back to some of the earlier missions in FS2 to see if the Hygeia avoids docking with wingmen in those missions too, but I also wanted to see if others here can duplicate this behavior. As a test, pick any FS2 mission (I first noticed this behavior in Dunkerque, so perhaps try that first), complete the mission, and hang around afterward and ask for a reload. Then see what happens when your wingmen ask for a reload and observe the Hygeia's behavior. Does it dock, or just circle around the requesting ship?

**Comment by tomimaki** [comment]
I think I saw this in Blue Planet. Support ship was flying around fighter, which was trying to point nose at support ship.

**Comment by naomimyselfandi** [comment]
The BTA team has seen this happen with models with an unusually long docking path, for whatever that's worth.

**Comment by z64555** [comment]
May be related to #3998

**Comment by Goober5000** [comment]
Thanks to some detective work by Renegade Paladin, the root cause has been identified.  Due to a bug dating from the introduction of `$ai path mode:` in 2011, it was not actually used until the bug was fixed in #3610.  Then, because the MediaVPs overrode the base-level profile, the `alt1` pathing mode was applied to every mod.

The next version of the MediaVPs will a) use their own `FSU MEDIAVPS` profile rather than overriding the base profile, and b) not use the `alt1` pathing mode.  Unfortunately, end users will not see the fix until the new version is released.
