### ISSUE TITLE
CFile cannot handle more than 65536 files.

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#3863]
Revision 251702511 from 2021-11-22 introduced a bug, that makes FSO unusable if you play with MVPs and mjnhalls.
Debug Build crashes right away.

Release Build is launchable, but the game crashes after i go into the campaign room for example.
2021-11-21 still works, but every build after that causes the error message and crash.

[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/7785892/fs2_open.log)

I hit the limit because of my 17k cache files. So after i deleted them it worked again. But earlier builds worked even with all the cache files in place. So there seems to be a limit now, that was not present before.

**Comment by tomimaki** [comment]
Are you sure about that commit? Because more likely #3734 caused problem.

**Comment by NovachenFS2** [comment]
It is the revision number. But i did not knew the commit number actually. So #3734 seems to be the right one.

**Comment by notimaginative** [comment]
The 65536 file limit has been in place for roughly 11 years, so it's nothing new. But there does appear to be a bug in that PR whereby files that used to be ignored, now aren't. It's a simple fix however so a PR for it should be available shortly.
