### ISSUE TITLE
Many hook condition combinations do not work

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#3874]
Things like `$Weapon class:` or `$Ship class:` listed before the hook itself. Many combinations are not supported, sometimes this is simple oversights, but others are more fundamental to how the system is handled. I don't really have the time to list and test all the combinations that would seem like they should work but don't, but here's a few examples:

On Weapon Created can't use weapon class conditions.

On Beam Collision's conditions apply to the *other* object in the collision, and so you can't condition on the beam's weapon class.

On Ship Collision, same thing, can't condition using any ship-related condition (ship name/class/type), unless the other object is a ship.

Overall, I've had an extremely poor success rate of attempting to use this system (and usually just do it manually in the script), if it were just one omission I'd be happy to fix it myself, but it's so common that I think it's clear this entire system needs a serious audit, or a complete refactor to actually work more generally.

**Comment by Goober5000** [comment]
By "this entire system" do you mean the scripting design, or just the conditions for running hooks?

I found the `ConditionsValid` function to be decently clear, but lacking in the hook combinations you mentioned.  It should be straightforward to add the conditions that need to be added.

**Comment by Baezon** [comment]
I mean the design of these script conditions. In some cases it's just matter of omissions which can be filled, but as I mentioned with Beam and Ship Collision, some of them aren't a simple matter of omission, the function doesn't even have access to the object(s) involved. It's because the condition system in general has these limitations, but they are completely opaque to the user that the system is so hard to use, in my opinion.

**Comment by Goober5000** [comment]
Wow, you're right, this is not designed very well.

I might be able to slightly untangle it in a way that would satisfy this issue.

**Comment by Goober5000** [comment]
Ok, the design is a little bit better than I first thought.  A bit rough around the edges, but fixable.  I'll have a PR in the next day or two.
