### ISSUE TITLE
Feature Request: Table-Defined Head ANI List to Override or Complement Default List

### ISSUE THREAD

**Issue by TheTrivialPsychic** [scp-fs2open/fs2open.github.com#3875]
Basically, I'd like the ability to define via table, either in a new table or as an add-on to the messages.tbl file (and tbm) what head anis I'd like to be available in FRED by default for a specific mod or total conversion.  I've been FREDding with TBP and I've found that there is an extensive list of head anis available, but as none of them are default you have to manually copy and paste the filename into FRED for each mission you want to use them in.  Thankfully, once you've manually added them into a mission they will continue to show up, but a pre-definable list would be useful, as well as the ability to force FRED to ignore the default heads that Freespace expects.

**Comment by MjnMixael** [comment]
2nd
