### ISSUE TITLE
Multi-Part Turrets and Wrong Initial Positions

### ISSUE THREAD

**Issue by TheTrivialPsychic** [scp-fs2open/fs2open.github.com#3876]
I've been working with TBP and a few of the ships have been displaying some incorrect default positions under current builds.  The odd thing is that in FRED, the lab and the techroom, they display properly.  The ships I've encountered this are Nova#guns and Nova#shadow.  These ships each feature 6 twin-barrel multi-part turrets on the top, 6 on the bottom, and 3 down each side.  The proper position for the dorsal and ventral turrets should be the forward 4 pairs facing level and forward, with the aft 2 pairs facing aft and level.  Unfortunately in-game, one whole side is facing aft, as is the opposite side on the ventral.

**Comment by BMagnu** [comment]
This stems from an issue with how the animation system calculates a few special values for turrets specifically.
This shouldn't be too hard to fix in a few days or so.

**Comment by TheTrivialPsychic** [comment]
Just as an addition to my observations, I also failed to note that all 3 of the dorsal and ventral turrets opposite the aft-facing set, are entirely fore-facing, when it should only be the front 2 of each set, but I doubt that changes anything form a fix perspective.
