### ISSUE TITLE
Broken Impact Effect (?) on current build (20220104)

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#3890]
I noticed broken Impact Effect (?) in some weapons on current build i.e. 20220104
![screen0805](https://user-images.githubusercontent.com/18072803/148105258-15e3850a-519c-470c-b527-1005134754fa.png)

**Comment by wookieejedi** [comment]
Hmm likely #3884.

**Comment by Baezon** [comment]
Is this just the MVPs? Have you only noticed this in a specific mission? And it's the impact effects, when a weapon hits something? Not the muzzle flash effect, when a weapon is a shot, it kind of looks like a muzzle flash effect there.

**Comment by tomimaki** [comment]
MVPS, some other mods like BP. I didn't see it in retail but didn't check too long.
It occurs when weapon hits something or weapon's time ended.

**Comment by wookieejedi** [comment]
Yep, I have an easily reproducible case.

**Comment by wookieejedi** [comment]
Looks like the reason is because the Impact Effect filename is an `.ani` file. Thus, preloading particles which use an ani file does not work ATM. Will inquire about a fix.

**Comment by wookieejedi** [comment]
Fix PR incoming

**Comment by tomimaki** [comment]
Tested 3893 and it works. Thanks :)
