### ISSUE TITLE
First weapon in weapons display is brightened

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#3894]
Visual thing only, doesn't affect gameplay.
![screen0084](https://user-images.githubusercontent.com/18072803/148248701-5dbf1823-5e00-434a-a0fb-ad1b5826590b.png)

![screen0083](https://user-images.githubusercontent.com/18072803/148248735-41e83b33-30a4-4490-99b0-8d03c0df7504.png)

First time it occured on 3 january nightly. Seems #3878 caused this.

**Comment by wookieejedi** [comment]
Noticed this too on FotG. I'll dig around to see what I can find.

**Comment by wookieejedi** [comment]
Also noticed it looks very odd with ships with only 1 primary weapon.
![HUD_bug](https://user-images.githubusercontent.com/14077810/148253121-94e79468-4b91-47d0-b9f9-e19985f8622a.jpg)

**Comment by wookieejedi** [comment]
PR made
