### ISSUE TITLE
No 3D Departure Warp for TBP

### ISSUE THREAD

**Issue by TheTrivialPsychic** [scp-fs2open/fs2open.github.com#3917]
I am unsure if this is a coding problem, or if the mechanics of the feature have changed and TBP is lagging behind.  In TBP, subspace warps (or 'Hyperspace jump points') use a different physical shape than FS does, in the form of an elongated cone.  Furthermore, when a ship arrives in the game area, it uses a blue effect, and an orange one when departing.  In the fireball.tbl, the "Jump in" is used in place of the standard warp, while the "knossos" space is used as the "jump out".  The Jump In effect uses the elongated cone for jumps, but for some reason the Jump Out effect doesn't.  It uses this wide, shallow cone shape for warps.  I have attempted to manually add the warp model line into the fireball table, and I've used the custom warpin/warpout parameters area in departure/arrival cues of a ship and have confirmed that the jump out or knossos effect will only use this default, wide-cone shape for exit warps.  This extends to sexp-generated exit warps as well.

**Comment by Goober5000** [comment]
I've reproduced this on my end.  I'll have a fix in a day or so.
