### ISSUE TITLE
qtFRED save only saves once

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#3920]
During debugging of some other features, I noticed that changing parts of the mission and hitting Ctrl+S did not write anything to disk except the first time qtFRED saved to that specific file. Save as still works, but hitting save after save as will also not write anything to disk a second time. 
I tried both changing options within a ship, as well as moving it, but that did not change the save behaviour.

**Comment by Goober5000** [comment]
Sounds like qtFRED is not checking the mission modification flag correctly.  Maybe @the-maddin can take a look?
