### ISSUE TITLE
Request: make default name of a changed preset be the base preset

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3930]
Currently if you have a pilot using a preset, make changes to that preset, and hit accept it prompts you to save a new preset and populates the name with the pilot's name. the majority of the time I just want to update the existing one, and it'd be nice if that flowed smoother

**Comment by z64555** [comment]
The controls bindings in the controls config menu are verified each time a new bind is added, thus checking the current bindings across all known presets and selects the preset that completely matches the current section.

It may be possible to save the name of the last preset that matched, and use that as save name of the new custom when attempting to save the new bindings.

**Comment by JohnAFernandez** [comment]
It should be very simple to accomplish this.
