### ISSUE TITLE
Proposal/RFC: Built in overide table directory

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3934]
To facilitate both modder tinkering and a move away from command line lighting flags, I would like to add a folder to the load order, a subfolder of the working directory named something like "final", "finaldata", "override" or similar. This would be loaded as a mod directory after all the mod flag directories. This is to ensure it is loaded after any mod. People have in the past used the data directory as a way to jury-rig changes into all mods they're playing, but that directory is in fact loaded before any mods, so that is failable. 

This is something I've been thinking about for a while and have a working prototype of, but it seems foundational enough that I'd like to give people a chance to weigh in on before I just fling in a PR. But the only ways I can think of to fix the mess that is the current lighting flags situation without likely community revolt depend on either this or launcher features.

**Comment by notimaginative** [comment]
My first instinct is that this is unnecessary and that's not how it works, but I might be confused as to what you're asking for. So let me put this out there and you can correct me if I misunderstood...

Given the mods `widgets,sprockets,things` it will first check in the user folder for `widgets`, then `sprockets`, then `things`, then '/`, loading any usable files, including "data" under each respective mod folder. Then will grab stuff from the game folder for the same mods. So if you put stuff in `<userdir>/widgets/data/tables` it would add to or override stuff for the `widgets` mod when it's specified. Same for `sprockets` and `things`. You can (and should) keep stuff out of the base `/data` folder and easily have overrides specific to mods in use.

Having an "override" or similar added as a root which is indexed after the mod folders would technically work the same way that just dumping stuff in "data" does. Using the "data" that's specific to each mod sounds to me more like what you want, but I'm not sure if that's my confusion over the request or yours over the file loading order.

**Comment by EatThePath** [comment]
Okay, correct me if I'm wrong, but... given mods W, S, and T, the game will index them in the order of userfiles for W,S,T, then game-dir files for W,S,T , then the actual root(R). But when actually loading it goes in the other direction, reading R,T,S,W. It has to for TBLs and TBMs to work, as each pass edits or augments the data set by the previous root. When I say "after" it is this second ordering I'm referring to. Indexed before, loaded after.

Now, using the userdata directories for mod specific overrides is better practice, but I don't think it's a realistic alternative. Insisting that sticking files in data is bad hasn't stopped users or even devs doing testing from using it for that, and a big reason why is that it isn't mod-specific. Let me provide two examples, one current and one hypothetical.

Current is the screencam script.  It's crude, it's crashy, but it's also pretty heavily used and everyone I know who uses it just sticks it in fs2/data. There's one or two other things people use similarly but that's probably the most common one. Copying those things to a new every time you use a new mod just isn't what people want, they want it available at all times. Screencam could be even more easily used and more stable if it loaded after, it usually blows up on mods that lack a terran species, and it could use a -sdf.tbm to guard against that if it wasn't being loaded before any mod tbls come in. This is still a danagerous and potentially destabilizing way load things, sure, but no more so than the alternative of just stapling a proper screencam mod over top of each of your mods.

Second, the lighting things I alluded to. I want to do away with the command line lighting flags because they're in my opinion very poorly suited to the way they're used by the community and accommodating both the existing ones and a better alternative is an unappealing prospect. Also, people who apply the same lighting adjustments to every mod have to depend on launchers making that convenient, and that's currently not really the case. As well, mods have to rely on the flag management of a launcher to set up lighting conditions that they like.  My desired solution is to move those settings into a table, as part of the lighting profiles system so that, when that system is done, mods can actually switch between different settings from mission to mission if they so choose. But also, to include a section for global adjustment settings. That, plus the override folder idea, would allow for instance a user who finds it hard to set a minimum ambient (or emissive if that's meaningfully different) that is applied to all mods period. It would also allow users to easily share adjustment tables with each other as files.

I don't think we can take the individual configuration that the flags currently apply away from users, and I don't think that they'd be happy with having to root around in userdata to copy files every time they play a new mod, or indeed every time they update an existing mod. If they use `/data/` as current community trends suggest they probably will, then mods can just reset those adjustment table values and deny the user the option, something which I think it would be better to make difficult.

To get back to the core proposal and off the lighting train, I get that this is in a way enabling bad practices, but I think it's a bad practice that is already in place and can't realistically be stopped unless the engine finds a new, non-human userbase. And given that, I think it's worthwhile to provide an option with the same convenience advantages to the user that is at least *slightly* less likely to go horribly wrong.

**Comment by notimaginative** [comment]
Riiight, okay, I see my confusion now. I always think about the indexing order and forget about `get_file_list()` order, which is reversed. I've done that enough that you'd think I would know better at this point.

I'd like to digest your comment a bit more before commenting again. But I see where your coming from now and it does make sense.

**Comment by EatThePath** [comment]
For illustrative purposes, this is my draft implementation of this proposal:  https://github.com/EatThePath/fs2open.github.com/tree/finaldata

**Comment by Goober5000** [comment]
Implemented in #4711
