### ISSUE TITLE
FR: A way to add glowpoints to ships without altering the POF

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3935]
Glowpoints.tbl gives the impression that it was intended to eventually include a way to add glowpoints via table and not in the POF. I could really use this option for a feature I'm working on in BtA.

Glowpoints require a position, a normal vector, a radius, a parent subobject, and a bitmap. Optional data includes Displacement Time, On Time, Off Time, LOD, and Type.

Glowpoints are also stored as N numbers of individual points in a bank. Ships can have multiple banks of points.

**Comment by BMagnu** [comment]
Implemented by #4713
