### ISSUE TITLE
Particles do not change visibility in the nebula

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#3952]
As shown in the attached screenshot, debris particles are visible in the nebula no matter how far away they are.  These particles are several km away, but they are still just as bright and sharply defined as they would appear at point-blank range.

![screen0088](https://user-images.githubusercontent.com/1878523/150669092-69f7c203-4b52-4047-b734-6874e2656f96.png)

**Comment by Baezon** [comment]
Whether this is actually a bug or not is arguable. Quite a lot of effects are visible by default, which I decided to merely expose as settings in game_settings.tbl (`$Particles affected by nebula visibility:` etc), since some mods due depend on these things being always visible.

**Comment by Goober5000** [comment]
Hmm, ok.  And in fact I remember reviewing that feature not too long ago.

All right, that works.  Closing ticket.
