### ISSUE TITLE
BUG: Ingame options interface not working properly.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#3955]
When you press F2 during a mission, clicking the volume sliders makes the slider start following your mouse movement constantly, but never actually sets the volume level. The only way to make them stop is to exit the options screen. That same screen works fine outside of gameplay.

Occurs on current master as of this issue, unsure when it started.

**Comment by wookieejedi** [comment]
Good find, @z64555 have any indication of what might be causing that?

**Comment by notimaginative** [comment]
Happens on a week old build too. And it's actually worse than just the sliders, it affects all ui elements. i.e., Turn briefing voice off, then on, and both options are highlighted. It also affects other in-mission menus beyond just settings.

**Comment by z64555** [comment]
Sounds like the mouse_up event isnt being detected by the slider handler.  Best hint I can give right now is to look in 'menuui/optionsmenu.cpp' to see how it detects mouse button release, then track down what all could interfere with it registering while inside a mission.

**Comment by notimaginative** [comment]
Ah, it's looks to be timestamp related. `ui/button.cpp` has a `m_press_linger` timestamp, and if I comment out the setting of that then it works. Any ideas @Goober5000?

**Comment by Goober5000** [comment]
Hmm.  Right now, time doesn't elapse in the options screen because it's paused.  I think retail just saved the old timestamp and backtracked to it when time restarted.  The same may need to be done here.

**Comment by wookieejedi** [comment]
Interesting, good to hear there's an outline for how to possibly fix it.

**Comment by z64555** [comment]
The UI system clock really should be independent of the mission clock 🤦

**Comment by Goober5000** [comment]
I have a fix for this now, but I want to test it a little bit before putting up a PR.
