### ISSUE TITLE
FR: Need a no-collide that AI will still consider a valid target

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3959]
BtA has need of a version of no-collide ship flag in FRED that can set a ship has having no collisions with other ships or weapons, but that the AI will still attack. The current implementation of the no-collide flag seems to also set Protect on the ship and the AI completely ignores it.

**Comment by wookieejedi** [comment]
Also took a look at the no collide option for ship protection. There is one line where it prevents AI from firing at no-collide ships. Unfortunately adding some kind of new flag would be non trivial, as the collide flag is used 39 locations. I would imagine that collisional groups could be used well for this purpose though?

**Comment by MjnMixael** [comment]
The idea here is holographic decoy fighters. So collision groups might prove difficult given they need to not collide with weapons of all kinds as well.

**Comment by wookieejedi** [comment]
Ah that makes sense. Hmm the cleanest way to do this then I can think of is adding a flag that `disable-protect-with-no-collide` (or something to that affect). It would then check that flag in the `aiturret.cpp` no-collide if section. I'd be interested to hear what other senior devs might think about that solution, as it's very specific (but the cleanest/most minimal).

**Comment by Baezon** [comment]
I would suspect that only that part in `aiturret.cpp` (and possibly also with fighters? i dont remeber) actually have to do with discarding no-collide targets. A new flag shouldn't be too bad, because most of those occurances should be dealing with the collision system itself. In either case, I definitely think a per-ship solution would be preferred here.

**Comment by MjnMixael** [comment]
Thank you for PR #4174 because it does what I need. I think alter-ship-flag sexp will work with this new flag but documentation will need to be added to the sexp?

**Comment by MjnMixael** [comment]
It does not show up in the alter-ship-flag sexp and it does not show up in the ship flags Misc section. In fact, it seems as though FRED is entirely unaware of this flag and removes it from ships if I add it manually via text editor.

**Comment by wookieejedi** [comment]
Looks like it was not added to `sexp.cpp`. I'll make a PR to add it in.

**Comment by wookieejedi** [comment]
Now merged. FYI since this is a rather niche flag, it's accessibly is only in the `alter-ship-flag` sexp

**Comment by MjnMixael** [comment]
That works for me. Thank you both.
