### ISSUE TITLE
Local SSMs have stopped working

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#396]
They worked OK on October 16 76b6f95, but don't on 27 Oct 2015 - Revision 3708f10

![Purdy](http://i.imgur.com/BOy92hv.png)

http://www.hard-light.net/forums/index.php?topic=90727.msg1800434#msg1800434

**Comment by niffiwan** [comment]
Looks like it was introduced by #385

**Comment by asarium** [comment]
The PR by @MageKing17 should fix this. Once it's confirmed fixed on the forums this issue can be closed.

**Comment by niffiwan** [comment]
Reported as fixed by FrikgFeek
