### ISSUE TITLE
$attach_thrusters: in the POF doesn't seem to work as expected

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3968]
I'm honestly not sure this ever worked, but it's clear what the model creator intended. Attached here is the Albanus freighter with scripted animations (using the new animation system). The POF specifies $attach_thrusters: on both the frontpods and readpods submodels. The thruster glows do not move with the submodels when animated.

Furthermore, when the front and rear pods are setup as actual subsystems then the thruster glows don't show at all.
[albanus.zip](https://github.com/scp-fs2open/fs2open.github.com/files/7953933/albanus.zip)

**Comment by wookieejedi** [comment]
Interesting... With FotG we use attach thrusters on our X-wing engines, which are subsystems and are children of animated wings (using the new animation system). Everything works as expected with that ship, but perhaps it works out for use since the engines themselves are not moving but rather their parent sub-models.

**Comment by wookieejedi** [comment]
Also, it seems the model does not specify an axis for the sub models, so try specifying one. I found out today that it needs to be specified to get glow points and eyepoints to attach.

**Comment by MjnMixael** [comment]
Good thought. I gave that a try, setting the submodels' rotation axis to X which didn't work. I then additionally tried again with a defined rotation axis while also setting them back up to be subsystems. But just as before that caused the thrusters to not be visible at all.

**Comment by MjnMixael** [comment]
Turns out this was an incomplete feature and this flag never worked. Since the flag is now being removed entirely, this can be closed.

**Comment by Baezon** [comment]
Gonna give this a shot since it shouldn't be incomplete, it should just work without any additional input.

**Comment by Baezon** [comment]
For what it's worth they *do* indeed need to be subsystems as you suspected, but I'm happy to report whatever was causing them to disappear in that case seems to have been fixed!
