### ISSUE TITLE
Assertion relating to animated submodels

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3985]
BtA has encountered this Assert 

Assert: "pm->submodel[submodel_num].movement_type == MOVEMENT_TYPE_ROT || pm->submodel[submodel_num].movement_type == MOVEMENT_TYPE_INTRINSIC"

The model in question has two animated submodels. They are doors that use animation type Rotation on docking-stage-2 to open and animation type Rotation on Docked to close. Looks like the Assert happened as the ship was going down, possibly while in the middle of docking or undocking. Relevant log is attached.

Animation details are here. And I verified that the submodels have no additional properties in the POF.

> $Name: bta_morgens_dock_s2
> $Type: docking-stage-2
> +Triggered By: 2
> $Segment Parallel:
> 	$Rotation:
> 		+Angle: 0,0,90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_L-a
> 	$Rotation:
> 		+Angle: 0,0,-90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_R-a
> +End Segment
> 
> $Name: bta_morgens_docked
> $Type: docked
> +Triggered By: 2
> $Segment Parallel:
> 	$Rotation:
> 		+Angle: 0,0,-90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_L-a
> 	$Rotation:
> 		+Angle: 0,0,90
> 		+Velocity: 0,0,40
> 		+Acceleration: 0,0,5
> 		+Submodel: Door_R-a
> +End Segment

[fs2_open (5).log](https://github.com/scp-fs2open/fs2open.github.com/files/7966423/fs2_open.5.log)

**Comment by chief1983** [comment]
Haha, FotG just found this yesterday I think.  Goober is looking into it, but fixing it will take a bit he said.  We implemented a workaround but not sure that will help your situation at the moment.

> Goober figured out that collisions do not work with nested submodels, but it looks like that will be an involved fix. Fortunately, though, I just flattened out the nested submodels in the X-wing and updated the animations to ensure s-foils still work properly.

**Comment by MjnMixael** [comment]
I'm not sure I fully understand your workaround. The doors here are parented only to detail0. I can't flatten that out any further, I don't think.

**Comment by chief1983** [comment]
Yeah I didn't really understand it either.  wookieejedi would be the one to talk to on Discord about it.

**Comment by wookieejedi** [comment]
Hmm that's odd that it triggered with the flat submodels...
