### ISSUE TITLE
Asserts & Crashes relating to Deleting Messages in FRED

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#3996]
When deleting a lot of messages I found that sometimes a message will trigger this Assertion

> ASSERTION: "strlen(new_name) < TOKEN_LENGTH" at sexp.cpp:29986
> 
> Assert: "strlen(new_name) < TOKEN_LENGTH"
> File: sexp.cpp
> Line: 29986

Sometimes it would fail completely and give me Debug Assertion Failed. Most often, however, I could delete the entire list of messages and once I press OK on the Events Editor window is when I get Debug Assertion Failed. I get that every time. I even tried clearing all messages but 1. That worked. No Assertion. Then going back and clearing the last one caused the Debug Assertion Failed.

![image](https://user-images.githubusercontent.com/7740469/151995890-96898604-c2e9-4a26-9ef1-80f0e32cdf21.png)
[fred2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/7979532/fred2_open.log)

**Comment by TheForce172** [comment]
I've traced this bug to this commit https://github.com/scp-fs2open/fs2open.github.com/commit/35094851f2a34eccaea3039089a853c6789dcbbd which seems to be causing overflow errors in multiple places but I cant quite work out how to fix it.

**Comment by Goober5000** [comment]
That's odd...

**Comment by Goober5000** [comment]
Thanks, that was enough to figure it out.
