### ISSUE TITLE
Act 2: Mission 10: A Flaming Sword Waypoint problem

### ISSUE THREAD

**Issue by Sissi-Herman** [scp-fs2open/fs2open.github.com#4008]
Found waypoint problem in Act 2: Mission 10: A Flaming Sword.
In this mission Lambdas 1, 2 and 3 have wrong or glitched out waypoints. They first fly to the center of the portal, then fly somewhere between 20k - 100k meters from the center of the portal to drop bombs and then try to fly back to the center to jump away. 
They can use almost 20-50 minutes just for flying around the space without any reason.

Problem is in version 21.4.1. In version 21.4.0 everything works fine.
No debug for this time. I downgraded back to 21.4.0.
Using Linux version.

**Comment by Sissi-Herman** [comment]
Huh? 

21.4.1. 
Released Nov 1, 2021
https://github.com/scp-fs2open/fs2open.github.com/releases/tag/release_21_4_1

**Comment by Baezon** [comment]
Oh right, the point release, I almost forgot about those. We'll take a look then, but you should try a recent nightly release as well. If you directly downloading them you can find them on the forums.

**Comment by z64555** [comment]
Please run a debug build of 21.4.1, then try running a debug build of a nightly, and give us the debug log of both.  Remember you'll have to copy or rename the debug of the first or it will be overwritten when you try to run the second.

**Comment by z64555** [comment]
@Sissi-Herman Were you able to get a debug log with this issue occurring, using 21.4.1?

**Comment by Sissi-Herman** [comment]
> @Sissi-Herman Were you able to get a debug log with this issue occurring, using 21.4.1 and a current nightly?

Sorry, I been away from home some days. I can't test yet.

**Comment by z64555** [comment]
Well, since you said it was on 21.4.1 and 21.4.0 did not have it, we'll close this issue for now.  Should you come across it again during versions later than 21.4.1 please re-open.
