### ISSUE TITLE
"not" sexp breaks subtly when used with arguments

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#4010]
Consider the following pseudo-event:
```
When-argument
Any-of
AND
 Destroyed-or-departed-delay
     Argument
 NOT
   Is cargo known delay
    Argument
   Modify variable
````
The intention is to modify the variable for each Argument with unknown cargo. However, `cargo-known-delay` can short-circuit, and when it does, this is inherited by `not`, breaking the intended behaviour.

**Comment by Goober5000** [comment]
Closing because this is a red herring; the true cause is in #4013.  See also the comments on #4011
