### ISSUE TITLE
FR: Attenuation values for $AmbientSnd

### ISSUE THREAD

**Issue by Kanangus** [scp-fs2open/fs2open.github.com#4021]
Would be extremely handy to provide an constant engine sound (note, NOT a flyby noise) to fired munitions. The current behavior which plays the sound effect at full volume regardless of distance from the munition for use cases such as warning beeps etc could be retained by omitting attenuation values from the table entry.

**Comment by Baezon** [comment]
Sounds like you want $AmbientSnd? $InFlightSnd is a HUD sound which is not meant to attenuate or be played for non-player weapons.

**Comment by Kanangus** [comment]
Didn't know that existed - is indeed what I need, but custom attenuation would be extremely useful here as well. For my use case the sound is dropping off at a much closer range than desired.

**Comment by Baezon** [comment]
The attenuation for all sounds can be adjusted in sounds.tbl/-snd.tbm
https://wiki.hard-light.net/index.php/Sounds.tbl#.2BAttenuation_Start:

**Comment by Kanangus** [comment]
Suppose this can be closed then. Still think it would be nice to be able to adjust attenuation on the fly rather than creating duplicates of the same sounds.tbl entry every time but that's probably more trouble than it's worth.

**Comment by Baezon** [comment]
You want to adjust it on the fly? What's your use case, I'm curious?
