### ISSUE TITLE
FR: Improve scan features

### ISSUE THREAD

**Issue by Kanangus** [scp-fs2open/fs2open.github.com#4027]
It's come to my attention that features for scanning in FSO are fairly limited, as we only have time per ship and range per ship class right now. Two new features that immediately come to mind that I have a use case for are as follows, but given how little attention scanning has apparently received, we may want to see if others have anything else to add.

1. Custom scan times per subsystem - this is almost a must. Right now, all subsystem scan times inherit the time of their parent ship, resulting in some scan times that are inordinately long, particularly on freighters and cruisers.

2. Scan speed multiplier per ship - this one is more of a personal request, but I think it would be very cool to specify a scan multiplier in the sensor subsystem of a player-flown ship which would allow certain ships eg stealth/recon fighters to scan targets more rapidly. This could even be made more modular so that "advanced avionics packages" or whatever could be equipped a la Tenebra which take up a weapon slot to boost scan speed.

**Comment by z64555** [comment]
Subsystem scan time could be based on subsystem max health, which then would act either as a modifier of the whole ship scan time or as a set rate (think like a damage system, but with sensors).

Scan speed multiplier would allow for scout/recon and police type roles for ships.  However the scan time of systems and ship does affect the mission difficulty.

**Comment by z64555** [comment]
Having the scan time linked with the subsystem max health would provide a consistant result vs. all ships, instead of requiring a scan time for every ship.

The goal here with linking to subsys health is to reduce the amount work a mod dev has to do in order to get a custom experiance.

**Comment by naomimyselfandi** [comment]
> Having the scan time linked with the subsystem max health would provide a consistent result vs. all ships, instead of requiring a scan time for every ship. The goal here with linking to subsys health is to reduce the amount work a mod dev has to do in order to get a custom experience.

It'd have weird consequences that mod developers probably wouldn't want, though. What if I want to help the player scan a Demon's engine subsystem? I'd have to make Demons easier to disable.
