### ISSUE TITLE
Add `ba.directiveText()`

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#4034]
Exactly what it says on the tin. `ba.directiveText("Press $Alt-J$")` would evaluate to "Press Alt-J" or "Press Shift-J" or whatever the player's mapped the control to, and so on, just like directive keypress text currently does.

**Comment by wookieejedi** [comment]
I like this idea. In thinking about it, it might be more versatile to have a ba.getControlString("Alt-J"), so that the function would return what the currently bound control string is for that key. That way it could be used in a multiple ways.

**Comment by wookieejedi** [comment]
After discussion on Discord: `ba.translateTokens()` would is planned function, and scripters will put `$$` around control keys that should be translated.
