### ISSUE TITLE
ControlConfigOverride in ccfg.tbl doesn't unbind defaults

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#4040]
When using the controlsconfigdefaults.tbl to set the default preset, key bindings can not be intentionally unbound, instead they retain their FS2 defaults.

Observed behavior:
`$Key Default: NONE` does nothing

Expected behavior:
`$Key Default: NONE` should unbind the given control

**Comment by Goober5000** [comment]
Closing as fixed
