### ISSUE TITLE
FR: New SEXP Skill-level-at-most

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4046]
The inverse of skill-level-at-least. Returns true if player is DIFFICULTY or lower.

**Comment by wookieejedi** [comment]
After some discussion on Discord, there's already a custom lua sexp that does this, so I can provide that if anyone else is interested.

**Comment by MjnMixael** [comment]
That or if someone really feels the need to do it engine side then I'd recommend copying the lua sexp functionality because it's better and more flexible. Return difficulty as a number 1-5. This request can be closed.
