### ISSUE TITLE
Sometimes the mouse gets stuck in the middle of the screen

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4073]
Almost certainly a controls-related problem.  This can happen in the main hall, but the most reliable way I've found to trigger it is to simply fly a mission and hit Pause or Escape.

And having said that, I can't reproduce it today.  Yesterday it reliably happened every time; today it isn't happening.

**Comment by z64555** [comment]
Punting to 22.2 since this can't be consistently repro'd.

**Comment by Goober5000** [comment]
I figured out a way to reliably reproduce this.  However it requires a dual-monitor setup.

1) Launch the game in windowed mode
2) When in the pilot select screen, drag the window over to the secondary monitor (the monitor other than the one it was launched on)
3) Launch a mission
4) When in the mission, hit Pause or Escape

**Comment by z64555** [comment]
Hrm, this may be an SDL issue.  I'll try to browse through the mouse API to see if there's any hints of a fix.

**Comment by z64555** [comment]
@Goober5000 When does the mouse get stuck in the center?  Is it within the game, or within the OS?  Does the game window have focus when the mouse gets stuck?

**Comment by Goober5000** [comment]
1) Only within the game.  Alt-Tabbing back to the OS allows the mouse to be used normally.
2) Yes.  The mouse is only "stuck" in the sense that the cursor is in the middle of the screen and won't move.  It is almost as if the mouse is still in "flight control mode", except the cursor isn't hidden, and the game is paused.

**Comment by z64555** [comment]
I've got a HDMI to Dsub adapter in the mail, should arrive sometime this week (6/22).  I'll be able to use an old monitor to test and debug locally once it arrives.

**Comment by Goober5000** [comment]
I can't reproduce it either.  I tried switching up the primary monitor and trying different resolutions.  It all worked.

**Comment by Goober5000** [comment]
Closing as fixed.
