### ISSUE TITLE
Custom Warp Size Parameters Ignored by Docked Objects

### ISSUE THREAD

**Issue by TheTrivialPsychic** [scp-fs2open/fs2open.github.com#4095]
I've been working with TBP, currently attempting to simulate the multiple-ships-through-one-warp-vortex effect seen in the Babylon 5 programs.  I manage to tag additional ships to jump alongside a larger warship or through a sexp-generated effect, by giving them a higher warping velocity, add zeroes for the sounds, and change the size of the effect to 0.01m.  This does the trick, but if the warping vessel has something (like cargo) docked to it, it will ignore the size figure and generate a standard vortex for the size of the object.  I've tried to give the docked object the same effect size figure, and also tried selecting the 'no warp effect' box, but it doesn't change anything.

**Comment by Goober5000** [comment]
It shouldn't ignore the size parameter if it's docked.  I'd call that a bug.

**Comment by Baezon** [comment]
Well, isn't that done specifically to compensate for the new dimensions of the docked assembly? If it always uses the size parameter you'll just have the opposite issue, A ship docked to something very large will have an unusually small warp (or may, anyway).

**Comment by Goober5000** [comment]
That's true...

My thinking was that, since warp parameters are assignable, the mission designer should take this into account.  But I can see both sides of this need.

Maybe the solution is to add a ship flag that controls whether the warp portal should be resized or not.

**Comment by TheTrivialPsychic** [comment]
Or simply require the mission designer to add the same data into the warping parameters for the docked object, and have the code accept it.

**Comment by TheTrivialPsychic** [comment]
Sorry.  It appears that I accidentally closed this.  My bad.

**Comment by Goober5000** [comment]
I'm in the process of addressing this and will have a PR up this evening.

**Comment by Goober5000** [comment]
This is not actually a bug; it can best be described as a missing feature.  I'll have a PR up soon (last evening was too optimistic) that will address this.

**Comment by z64555** [comment]
"missing feature" falls under "not a bug" too, lol

**Comment by Goober5000** [comment]
Wait, I didn't remove "not a bug".  Why did Github say I did?

**Comment by z64555** [comment]
heckn github gremlins. :trollface:
