### ISSUE TITLE
Multi cannot use timestamp() but uses it anyway

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#4099]
A minor issue.  Timestamp() is unreliable in multi because of a workaround to allow menus to work while the game is unpaused in multi (so that players do not de-sync).  All multi functions that use timestamp() should probably use Missiontime instead.  This would necessitate a multi bump.  The main consequence of this is that players would likely be unable to update their position to the server if the player is in a menu.

Should Missiontime be used or some other solution be found?

**Comment by z64555** [comment]
Gonna need a map of what all uses Missiontime and Timestamp first.

**Comment by JohnAFernandez** [comment]
The most affected things are in multi_obj.cpp .  The object update packet was using the timestamp as a way to track how far ahead or behind an incoming packet is to the local simulation.  There is maybe one other packet that uses it.

**Comment by Goober5000** [comment]
Yeah, Missiontime sounds plausible, but I too would want to see how exactly timestamp is used in the multi code first.

It might be possible to replace some timestamps with `UI_TIMESTAMP` which designed for user-experience things like blinking lights, and is not affected by time compression or pausing.

**Comment by notimaginative** [comment]
`UI_TIMESTAMP` is relative to the system timer, correct? That's what it looks like anyway. And if that's the case then the values are only useful to the local system. For multi it would have to be a time which could be relatively the same across systems, which was previously the timestamp.

And I think that `Missiontime` is directly based on the timestamp now so I'm assuming it's not going to give you different results than using `timestamp()` directly.

Goober can correct me on those two points if I'm off base and don't remember/understand the code correctly.

We may just need to bite the bullet and implement a timer sync internal to multi. Have a value that's sync'd during join and is incremented by the system timer, and perhaps re-sync'd every few minutes.

**Comment by Goober5000** [comment]
Missed the follow up earlier.  `UI_TIMESTAMP` doesn't pause and doesn't use time compression, but aside from that, both it and the regular timestamps use the system timer.

`Missiontime` is, indeed, directly based on the timestamp now.

Theoretically, a timer sync could be implemented by making timestamps dependent on the server when in multiplayer mode.  Either the server could set the value directly, or the server could add or subtract time if the clients got too different.

**Comment by notimaginative** [comment]
Sorry, not sure that I was really clear there. I meant that the value used by `UI_TIMESTAMP` appears relative to the start of the game, not the mission, so it's useless between different systems. Whatever time is used must be relative to a fixed point which is the same between server and client.

> Theoretically, a timer sync could be implemented by making timestamps dependent on the server when in multiplayer mode. Either the server could set the value directly, or the server could add or subtract time if the clients got too different.

I worry about manipulating timestamps since some things may break when the timestamp jumps around. I think it would be safer to have something separate for multi. Not a full timer setup though, basically just one value. It would be set by the server (just it's timer_get_milliseconds() value) when the client joins and the client would increment it every multi frame based on the delta of system time so that system performance isn't a factor. Factoring in lag should be pretty simple too.

That's just a guess though, I haven't really gone through the code and checked everywhere it needs to be used.

**Comment by JohnAFernandez** [comment]
So this issue is unfortunately all based on a misreading.  At first glance, where `game_do_state_common` calls `multi_maybe_do_frame`, it seems to disallow the call to `game_set_frametime` in `game_do_frame`, which would keep FSO from updating `Frametime` and `flFrametime`.  But `game_set_frametime` is called later in `game_do_state` within each of the individual states that are listed in `game_do_state_common`.  So everything ends up getting updated.

Now, I'm going to go work on finishing the interpolation upgrade which will just take the aggregated timestamp delta data already being sent by the server and figure out syncing with that.
