### ISSUE TITLE
FR: Discord Integrations should be optional

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#4113]
A discussion brought up by freijon on Discord prompted the case of making our Discord Rich Presence support into something optional.

I'm thinking at the least a commandline option should be added to opt-out (or opt-in) to using Discord RP, and a Cmake option should be added to allow the Discord RP libs to be excluded.

**Comment by freijon** [comment]
Maybe a short background explaination:
Most Linux distros are 'binary', meaning the packages they install are pre-compiled and the package maintainer decides which features to include. Same for the AppImage. Then there are 'source' based distros (they are a minority) where the end-user decides which features to include. They are presented with a list of features to include/exclude at build time. If we disable discord-rpc it means don't build the discord library and remove all calls to that library.
For the 'binary' distros or Mac OS / Windows which have the feature compiled in by default, it would certainly be nice to have a cmd line option to opt-out sharing this info online.

**Comment by Goober5000** [comment]
Implemented in #4711
