### ISSUE TITLE
Ship List Dialog causes CTD

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4115]
Clicking the ship list dialog button causes a CTD in FRED. Both release and debug builds. One time I got this message along with it. Using RC6.
![image](https://user-images.githubusercontent.com/7740469/160634216-777edbc8-dee7-4d3d-8e58-ce1f19b5d77e.png)

**Comment by wookieejedi** [comment]
Further investigation reveals it is likely due to number of IFFs in said modpack, which is > 10.
