### ISSUE TITLE
CTD when two models with animated submodels collide

### ISSUE THREAD

**Issue by Strygon** [scp-fs2open/fs2open.github.com#4119]
Basically, when experimenting with a squadron of mecha, which have a lot of moving parts, virtually any collision with eachother will result in an instant CTD.
This will NOT occur if the mecha in question his anything else, like a static ship.

[fs2_open_21_5_0_x64_AVX-FASTDBG_20220330_063314.zip](https://github.com/scp-fs2open/fs2open.github.com/files/8377770/fs2_open_21_5_0_x64_AVX-FASTDBG_20220330_063314.zip)

A clip of where this issue occurs.

https://user-images.githubusercontent.com/48550781/160769919-df536b51-a172-4594-a524-ccc26048244a.mp4

**Comment by BMagnu** [comment]
Turned out to be a bad model file.
