### ISSUE TITLE
Credits in credits.tbl and FSO lose whitespacing

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#4122]
Using 22.0.0 RC6. Images illustrate.
![screen0046](https://user-images.githubusercontent.com/47288956/161274496-25d19991-de08-4c28-b8d9-777e265bc725.png)
![screen0049](https://user-images.githubusercontent.com/47288956/161274511-d1be5078-9f08-466c-9c56-87fe08bf2bf0.png)

**Comment by Goober5000** [comment]
Looks like this was caused by #4071.  Zero-length strings are now returning zero for height as well as width.
