### ISSUE TITLE
[FR] Color coded Events in FRED should be able to be highlighted.

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4129]
A regular event, when clicked on gets highlighted in blue. This is pretty standard UI stuff. Color coded events do not get highlighted at all and it can be difficult to know which event you are on when you can't see it. Ideally the blue highlight should take precedent over the bg color when the event is selected. Both images below have an event selected.
![image](https://user-images.githubusercontent.com/7740469/161392743-76a8da5f-474e-4e55-b0ac-287e9e7dbee9.png)
![image](https://user-images.githubusercontent.com/7740469/161392761-539a14a2-44ba-47c1-846b-828ac335f33a.png)

**Comment by Goober5000** [comment]
Handled in #4135.  Had to balance tradeoffs between multiple users and I think 4135 achieves it.
