### ISSUE TITLE
Techroom doesn't take into account relative angle for barrels.

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#4137]
Barrels on models in Techroom aim straight up. This thing affects F3 Lab in way, if you check model first in techroom, then same model in F3 Lab, barrels are at wrong angle, but after restarting FSO, if you check model first in F3 Lab, then in Techroom, all is good.

**Comment by BMagnu** [comment]
And the techroom seems to also display destroyed submodels.
This is, in my guess, an issue with how the techroom is setting up and more importantly also cleaning up models, and less with how specifically initial angles are set to models

**Comment by Goober5000** [comment]
Initial angles were displayed in the tech room quite recently.  That's almost certainly due to recent changes for initial angle handling.

Destroyed submodels sounds like a separate problem though.

**Comment by wookieejedi** [comment]
Destroyed submodels showing up in the Techroom is fixes with #4138.
