### ISSUE TITLE
CTD with Empty Weapons in Mantle

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#4142]
From Discord:
`Mantle, mission 06, Gamma with no weapons, crash perfectly at 35 seconds in mission time`
`in this case, Gamma wing was Thots and he emptied both their single primary and secondary banks`
`Gamma is a hostile wing and the crash occurs when they get an ai-chase order for Alpha wing`

I was unable to reproduce this issue with a simple test case mission.

**Comment by JohnAFernandez** [comment]
Turned out to be a negative array access in `ai_code.cpp`.
