### ISSUE TITLE
[FR] Preloading of the subspace tunnel

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#4166]
(this is written from the experiences of both myself and naomimyselfandi)

When a mission switches from normal space into subspace, the initial load of the subspace tunnel can take long enough that it interferes with the scene transition. Preloading the tunnel seems like it would resolve the issue, but there doesn't seem to be any way to do that. Being able to preload skyboxes would be helpful for a similar reason.

Relatedly, starting a subspace mission also takes several seconds (in my case dozens of seconds) after I click "Commit", during which the subspace ambiance plays but I'm still looking at the briefing (it's fairly trippy). This also means that marking a mission as starting in subspace and immediately cancelling it isn't really a viable option, either.

I don't know how well our machines compare to the average FSO user, but Naomi gets 60 FPS during normal gameplay and I get about 40-ish, we don't have this problem with any assets other than the subspace tunnel.

**Comment by Goober5000** [comment]
Skyboxes are already preloaded - see `sexp_set_skybox_model_preload`.  Looks like the subspace tunnel is never preloaded though.

**Comment by DefCynodont** [comment]
huh, I was unaware there was a way to preload skyboxes, I changed the title.

**Comment by DefCynodont** [comment]
I saw the pull request :)  
I have a small Question: if the mission starts in subspace by default will it still preload? or will it require the use of the mission-set-subspace sexp?

**Comment by Goober5000** [comment]
If the mission starts in subspace by default, it will load the subspace assets before it starts.  This is what it has always done.  The new PR uses the same code - that's the main reason I was able to write it so quickly.
