### ISSUE TITLE
FRED should check for duplicate variable names and throw an error or warning

### ISSUE THREAD

**Issue by AdmiralNelsonFSO** [scp-fs2open/fs2open.github.com#4170]
I get the assertion:
ASSERTION: "get_index_sexp_variable_name(var_name) == -1" at sexp.cpp:4106

Assert: "get_index_sexp_variable_name(var_name) == -1"
File: sexp.cpp
Line: 4106

when opening an old mission in FRED debug.  Per EatThePath this assertion is the result of duplicate variable names present in the mission - which is indeed the case.  However, FRED should either not allow the mission to be saved, or throw a warning or error message when this happens.  Currently there is none displayed on save or in the error checker.

**Comment by z64555** [comment]
Do you have an example .fs2 that will reliably trigger the assert?

**Comment by AdmiralNelsonFSO** [comment]
[Exile01.zip](https://github.com/scp-fs2open/fs2open.github.com/files/8489565/Exile01.zip)
Here is one. Note the duplicate variable names.
