### ISSUE TITLE
Scripting regression in hudgauge 

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4171]
Axem's prompt-box script broke on the 20220207 nightly, bisecting a blue planet crash narrowed down to there. As a reproduction download blue planet and play Age of Aquarius, the prompt box is used immediately on the start of the first non-cutscene mission.

@Goober5000 #4003 looks like the most likely cause, but I'm not immediately sure of why. 

The error in question is
```
[Window Title]
Error!

[Content]
LUA ERROR: [string "proBox-sct.tbm - On Game Init"]:87: attempt to index a nil value

------------------------------------------------------------------

stack traceback:
	[C]: ?
	[string "proBox-sct.tbm - On Game Init"]:87: in function 'GetTextFromGauges'
	[string "proBox-sct.tbm - On Game Init"]:64: in function 'UpdateText'
	[string "proBox-sct.tbm - On Game Init"]:54: in function 'MakeList'
	[string "proBox-sct.tbm - On Game Init"]:198: in function 'proBoxOn'
	[string "String: proBoxOn()"]:1: in main chunk
------------------------------------------------------------------

------------------------------------------------------------------


[ This info is in the clipboard so you can paste it somewhere now ]


[Debug] [Continue] [Exit]
```
and the function in question, 
```

function PromptBox:GetTextFromGauges()
	
	local t = {}
	for i, v in pairs(self.Gauges) do
		local gauge = hu.getHUDGaugeHandle(v).Text
			if gauge:gsub("%s+", "") ~= "" and not self.Locked[i] then
				t[i] = ">> " .. gauge
			else
				t[i] = ""
			end
	end
	
	return t

end
``` 
The gauges are there in the files, and 20220205 displays them just fine.

**Comment by Goober5000** [comment]
The problem is that `hu.getHUDGaugeHandle(v)` is returning nullptr when it previously didn't.

I already tracked down the proximate cause, but now I want to figure out why it's doing that.

**Comment by z64555** [comment]
Presumably when empty its supposed to be `\0` instead of `nullptr`,  so it looks like an init or copy error.  One other thing is that a guage may have been std::move'd thus invalidating the data in the old position.

**Comment by Goober5000** [comment]
No, it's because different hud gauges are stored in different collections.  The implementation of that scripting function isn't checking the collection where that particular gauge was stored.
