### ISSUE TITLE
Large memory dump occurs when a debug build exits

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4185]
Steps to reproduce:
1) Compile and run a debug build ~~of FRED~~ in the Visual Studio debugger
2) Save a blank mission
3) Exit
4) The game will print an enormous memory dump to the debug log

It takes a long time for the memory dump to be printed - about a minute.  As far as I can determine, the dump occurs because a memory leak was detected.

EDIT: Turns out this happens in both FRED and FSO.

**Comment by jg18** [comment]
I can't reproduce this issue on latest master (`bb2bd3fc1`) in VS 2019 using a Debug build created from `fs2open` folder (as opposed to `FS2_Open.sln`).

After I save a blank mission, FRED exits about as quickly as usual.

**Comment by Goober5000** [comment]
I can reproduce it on latest master in VS 2019 using the solution generated by CMake.  I'm on Windows 11.

**Comment by Goober5000** [comment]
It doesn't happen in 22.0.  I'll run a git bisect later.

**Comment by Goober5000** [comment]
Git bisection shows 60c39c698a2da9cc84536580830e69659f1cb6d6 as the commit that introduced the memory leak.

**Comment by Goober5000** [comment]
Confirmed fixed by #4246
