### ISSUE TITLE
Chrome will not download from non-HTTPS URL's

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#4188]
Chrome, and likely several other browsers, will start to aggressively ignore URL's that are not HTTPS.  In the case of Chrome, it may, at most, open a tab and then immediately close it.

This is an issue for our scp.indiegames host which doesn't use the HTTPS secure protocol, so that will have to be updated in the near future.

**Comment by Goober5000** [comment]
This is being handled, but may not be ready in time for 23.0.

**Comment by Goober5000** [comment]
Server has been migrated and HTTPS support has been added.
