### ISSUE TITLE
FR: Localized nebulae

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#4193]
Currently, all FSO nebulae are whole-level.
It'd be really cool to have the ability to make nebulae that the player can actively fly into by themselves, as well as be observed from the outside.

While toggling the actual nebula rendering when the player enters a specific area is not too hard, making the boundary region look good as well as properly showing a cloud-like nebula from the outside is very difficult as of now.

**Comment by z64555** [comment]
Some solutions that I can think of involve 3D textures, animated particles, and actual modeled clouds.  This is definitely one of those things that need a reference to like Gaming Gems or something.

**Comment by Kanangus** [comment]
Freelancer is the best example I can think of for this, certainly the most iconic. The way Freelancer handled this was by deforming a spherical mesh and drawing billboards over it, fading the large billboards out as the player got close. Still looks pretty good today, but it's a little inflexible if you're trying to make any interesting shapes.

Might be interesting to see if more complex shapes could be pulled off here to emulate a more 3d nebula environment with wisps you could fly in/out of.
