### ISSUE TITLE
FR: Blacklisting problematic orders

### ISSUE THREAD

**Issue by naomimyselfandi** [scp-fs2open/fs2open.github.com#4196]
Sometimes, FSO will permit an order to be issued that directly contradicts the players' orders, or just doesn't make sense in the fiction of the mission (calling an attack on Arjuna 1 in "Enter the Dragon" comes to mind, or Beta wing in BTA's "Playing Pirate"). An SEXP operator to blacklist these orders would be useful.

Proposed API:
```
( set-order-allowed-for-target
   ( false )
   "Arjuna 1"
   "Destroy My Target"
   "Additional orders if desired"
)
```

Ideally, a wing or team could be passed instead of a ship. For example, a FREDer might disable "Capture My Target" orders for "<any hostile>", then enable them for a few specific ships.

**Comment by wookieejedi** [comment]
Apologies if I might be missing something, though what's the difference between this and `set-player-orders` sexp?

**Comment by wookieejedi** [comment]
Ah right, that makes sense. Thanks for clarifying!
