### ISSUE TITLE
Hudbrackets assert

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4214]
I have run into this four times now in the same mission. I'll potentially provide more debug info tomorrow because it's late.

I suspect this may be due to our script for drawing brackets around escort ships. I can provide the script if it helps. But other than that, the assert seems random. I can't tell any specific repeatable event that is causing it.

> Assert: "width > 0"
> File: hudbrackets.cpp
> Line: 60

**Comment by Baezon** [comment]
The assert is definitely a little more aggressive than it needs to be. It's simply indicating that the bracket it was asked to draw had zero (or less) area, that is, all the corners were in the same spot. The biggest obvious culprit for this is a `drawTargetingBrackets()` call without any padding (not necessarily an issue on its own), but on a weapon without a model (or possibly there was a strange issue with the model). 

Engine-side I'm just going to make this situation silently do nothing, but on your side I would possibly look at what kinds of objects are getting brackets, or adding just a smidge of padding.

**Comment by naomimyselfandi** [comment]
FYI, the script in question uses the default padding of five pixels, although it looks like it doesn't check whether the object is valid. I'll try that and see if anything changes.

**Comment by AdmiralNelsonFSO** [comment]
I noticed this same error in testing Exile FWIW, but missed noting the exact circumstance.  I don't think it runs any scripts that affect brackets.

**Comment by Baezon** [comment]
If the objects being bracketed have models, and especially if padding is being supplied then this really shouldn't be happening, and id be willing to investigate further if it can be replicated.

**Comment by EatThePath** [comment]
considering that no gameplay issues have been reported and the asserts are already removed, can we move this to at most low priority?

**Comment by Goober5000** [comment]
Done

**Comment by MjnMixael** [comment]
With the assert removed, I'm comfortable closing this completely unless @Baezon really does want to take time to look deeper.

**Comment by Baezon** [comment]
Well, there's not much to do without a reliable repro and there havent been any other reports so it's probably fine.
