### ISSUE TITLE
Enter/Esc keys and Close button don't work as they should in Add/Modify Container FRED dialog

### ISSUE THREAD

**Issue by jg18** [scp-fs2open/fs2open.github.com#4240]
Pressing the Enter key in FRED's Add/Modify Container dialog closes the dialog without saving changes.
Pressing the Esc key cancels without asking whether to save changes.

Proposed behavior:
* Pressing Enter should do nothing, since its meaning in that dialog is ambiguous.
* Pressing Esc should either do nothing or bring up a "Save changes?" dialog with Yes/No/Cancel buttons

**Comment by z64555** [comment]
Does the close button have a similar mechanic? If not, then the new behavior should apply to both Esc and the close button.

**Comment by Karajorma** [comment]
If the close button doesn't already bring up a "Save changes?" dialogue it definitely should. I agree that ESC should have the same behaviour.
