### ISSUE TITLE
New XSTR entries in hudreticle.cpp

### ISSUE THREAD

**Issue by Achille44** [scp-fs2open/fs2open.github.com#4259]
Please could you add new xstr entries instead of the following hardcoded texts located in hudreticle.cpp:
- Match_speed_icon = 'm' (lines 471, 481)
- "GLIDE" (lines 645, 656)
- "A/B" (line 587)

**Comment by NovachenFS2** [comment]
As i am looking through the code for my translation library where "Disable built-in translations" does not have any affect (i.e. in the ETS gauge), i found some additional strings, that are not translateable right now.
I think i can include yours as well during this process.
