### ISSUE TITLE
FIXME for AIM_GET_BEHIND

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4270]
There is an old FIXME related to the `AIM_GET_BEHIND` code:

```
// FIXME: got this from TBP and added it here to skip the Int3() but don't really want to handle it
// properly until after 3.6.7 just to avoid delaying release or breaking something - taylor
```

There is also a related @todo:
```
@todo Complete the AIM_GET_BEHIND option
```

**Comment by Baezon** [comment]
It doesn't look like that mode was ever implemented and is never set. I would vote in favor of returning the `Int3()` (or rather, an `Assertion()`), since there must've been some serious shenanigans to even get it in the first place.

**Comment by notimaginative** [comment]
I don't remember that at all. I believe that's a retail thing and not something we added, so technically I suppose the feature is already complete.

Obviously added that line to prevent hitting the default case there but I have no recollection of a "proper" fix for that. It may have just been to prevent getting there in the first place, having been triggered by some mod data that doesn't occur in retail. But without remembering how it got there, and short of reproducing the same scenario, I'm not sure what to do but just remove the FIXME.
