### ISSUE TITLE
"Free Look View" conflicts with thrust controls

### ISSUE THREAD

**Issue by daftmugi** [scp-fs2open/fs2open.github.com#4276]
When "free look view" is used while "reverse thrust" is held down, the throttle acts as if "reverse thrust" is not held down.

For example, hold "reverse thrust" to stop for rearming. While rearming and holding "reverse thrust", use "free look view" to look around, but the throttle will act as if "reverse thrust" is not held down (may go back to auto speed).

**Comment by z64555** [comment]
It appears that thrust controls are ignored when the camera is not locked.  Due to the nature of that portion of the code, I'll have to look at each possible case and edge case to see if its safe to allow thrust controls to function in freelook mode.
