### ISSUE TITLE
FR: FRED - infinite repeat/trigger count

### ISSUE THREAD

**Issue by MitoPL** [scp-fs2open/fs2open.github.com#4292]
As we already know, to have an event firing infinitely we need to put a massive number into the repeat count, or as some prefer, edit the mission file in a text editor and place the -1 value in there.

I am requesting a different method to handle this, for the sake of ease of use.

Variant 1: just let repeat count and possibly trigger count accept negative numbers, with any negative number being treated as infinity.
Variant 2: instead of variant 1, place a pair of checkboxes marked as "infinite" for both values, when marked the place for inserting a value being grayed out.
Variant 3: since this is usually used to have an event fire infinitely, often every frame, maybe instead let's have a "repeat every frame" or "evaluate every frame" checkbox (that when active would gray out all of the boxes - for repeat count, trigger count and interval time) and a "repeat infinitely" or "evaluate infinitely" checkbox (that when active would gray out repeat and trigger count boxes, but not interval time box).

**Comment by MjnMixael** [comment]
+1 for variant 1

**Comment by MitoPL** [comment]
I've also reminded myself that we could mix variants 1 and 3 - have the data boxes accept negative values for atypical use cases and also have the two "quick setup" checkboxes for ease of use. I think the latter would help introducing FRED for newbies - learning to set up an infinitely repeating event is currently one more step between an aspiring FREDer and a working mission, and it really isn't an obvious one, at least not as obvious as having an immediately visible checkbox that does exactly that, informing the user at the same time that yes, this is a possibility in this game engine.
Also I say that as a person with at least some basic experience with FRED, after jumping in to touch up a mission I couldn't really wrap my head around setting up said infinitely repeating event.

Besides, I feel that the approach of "just slap in an astronomically large repeat count and don't worry" is kind of... amateurish. Not to mention it begs for a situation where said repeat count wasn't astronomical enough and runs out in the middle of a mission, or even worse, that said thing happens to some players that have higher average FPS than the dev of said mission.

**Comment by wookieejedi** [comment]
Yeah, agreed that -1 in the counter would be a really nice solution.

**Comment by MjnMixael** [comment]
So it turns out this is already a feature as best I can tell in the code. Negative numbers for trigger and repeat mean to do it indefinitely. The only reason you can't put it in the Event Editor is because it only accepts ES_NUMBER. So this isn't a feature problem, it's an interface problem. I'm going to see if I can come up with a solution.
