### ISSUE TITLE
Reachable assert in ship_create 

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4297]
If you go into the lab in Solaris with a debug build and select the federation thunderbolt-class fighter( and presumably others), you will get an assert
 ```
ASSERTION: "strlen(shipp->ship_name) + strlen(suffix) < NAME_LENGTH - 1" at ship.cpp:9990

Assert: "strlen(shipp->ship_name) + strlen(suffix) < NAME_LENGTH - 1"
File: ship.cpp
Line: 9990
```
selecting this fighter in a non-debug build proceeds without incident.

**Comment by Goober5000** [comment]
This occurs because `Thunderbolt-class Interceptor 1` is 31 characters, which fits exactly in the buffer, but the Assert checks for 30 characters by mistake.
