### ISSUE TITLE
Unsafe code reachable through API reportedly valid ship and subsystem handles

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4315]
In the attached mod I've got a ship-handled keyed table of subsystem handles, and I drawTargetingBrackets for each subsystem during the on frame hook. Even though I check the validity of both the shiphandles and subhandles before calling it, by starting a new mission I can get access violations in, seemingly in multiple places depending on how the engine is feeling at the time.

To see it happen, use the attached scripts(includes axem's markbox), start a mission, then start a different mission. It should blow up one way or another.

Resetting the state table in the mission start hook is a perfectly effective way to avoid it, but it's a pretty unceremonious fail state that we should probably find a way to improve

**Comment by EatThePath** [comment]
It seems likely this is tied to #4329

**Comment by Goober5000** [comment]
> To see it happen, use the attached scripts

I don't see any attachments.  Were they removed?

**Comment by EatThePath** [comment]
> > To see it happen, use the attached scripts
> 
> I don't see any attachments. Were they removed?

No idea. I don't even remember what version of markbox or mission I was working with at the time I found this. I think the closure of #4329 makes closing this appropriate, fwiw, the 'start a mission, then start a different mission' repro step was a real hallmark of the problems there, and the missions where those problems were popping up are ones that I might have been adding markbox to.

**Comment by Goober5000** [comment]
Okey dokey.
