### ISSUE TITLE
Subsystem in table but not model causing logical errors in gameplay

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4329]
If a subsystem or turret is set up in the table but nothing matches in the ship, this does not always generate a strong warning (for turrets anyway), though it appears to be tied to the message `Ship _ has model_num _ but its subsystem  has model_num _, fixing...` in the log.

At first glance gameplay seems unaffected, but when the `$Fixed Turret Collisions:` is on AND you play more than one mission in a session(or possibly if ships of the effected classes enter after others are destroyed/depart) this results in all the submodels of a ship exploding off it as soon as any one of them takes any damage, and often badly screws up the collision of the ship.

**Comment by EatThePath** [comment]
@Baezon figured out, if I recall correctly, that the cause was table definitions for subsystems not in the model file.

While an asset bug it seems like one that should be practical to handle better in the engine

**Comment by Baezon** [comment]
This was turned into an error with #5591. Unsatisfying as far as a 'fix' goes, but should mean this can't happen anymore either way.
