### ISSUE TITLE
FSO Hangs up when joystick could not be found

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#4338]
Needs confirmation.

When FSO is provided a GUID or ID of a joystick that no longer exists for the CurrentJoystick, it hangs up.

**Comment by Kiloku** [comment]
I think this is only a Knossos issue. 

I tried setting an invalid GUID myself. When running the normal RC build from Knossos, it fails to run. Running the same binary file manually with the same command line settings, it runs fine. Knossos' status bar briefly says "FSO is Running" but it might be setting that status prematurely. 
I might be able to fix this in my fork of Knossos but I have no idea if my fork works on Windows.

**Comment by z64555** [comment]
Alright, confirmed this as a Knossos issue by using the debugger and a bogus GUID in the .ini.
