### ISSUE TITLE
22.2.0 RC1: Wingmen fire missiles from out of range in retail mission The Romans Blunder

### ISSUE THREAD

**Issue by Kiloku** [scp-fs2open/fs2open.github.com#4367]
In The Romans Blunder, after the Iceni jumps and the pilots chat/argue for a while, a group of Lokis and a pair of freighters arrive. 
As soon as they do, a number of the wingmen fire their Rockeye heatseekers from out of range, the missiles explode harmlessly long before impacting.  

I managed to reproduce this behavior with and without MVPS. I also compared with videos on youtube of people playing older versions of FS2, and couldn't see this behavior in any of them.

**Comment by Kiloku** [comment]
LSDNinja added on Discord:
"It happens on Surrender, Belisarius too. It’s like they get a target and just fire missiles regardless of how far away it is"

**Comment by MoerasGrizzly** [comment]
Yeah this seems to happen everywhere where fighters have heatseekers and see a target: They make the decision to fire before they see if they can actually hit the target.

**Comment by Kiloku** [comment]
My initial investigation and comparison with youtube videos was definitely flawed. I just re-ran the mission in Release 3.8.0 (from 2017), which is the oldest that will still run on my computer, and the behavior was also there.

**Comment by Goober5000** [comment]
As I recall, this has been the behavior ever since retail.  It's the reason the `Weapon Range:` field exists.  (The Rockeye does not have this field in its entry.)

**Comment by JohnAFernandez** [comment]
I am remembering it as retail behavior, too.  If we have a work around using `Weapon Range:` things like FS Blue can take advantage of it, but we can't touch the retail behavior.

**Comment by Kiloku** [comment]
I tested on the icculus.org version of FS2, which is as close as I can get to retail, and the behavior is there as well. Since there is a workaround that mods already use, I feel like this is a non-issue

**Comment by Goober5000** [comment]
Agreed
