### ISSUE TITLE
Removing an entry from the Tech Database through lua doesn't work if the flag is set to true in the table

### ISSUE THREAD

**Issue by Kiloku** [scp-fs2open/fs2open.github.com#4390]
`shipClass.InTechDatabase` (and others like weaponInfo) can be set by lua scripts. It succesfully changes the corresponding flag in the engine (such as `Ship::Info_Flags::In_tech_database`) to the new value. 
However, if the new value is `false` while the original value set in the table is `true`, then the entry will still show in the tech lab. 
This is because the code that fills the techroom list checks both `Ship::Info_Flags::In_tech_database` and `Ship::Info_Flags::Default_in_tech_database` (which is set by the table), adding the entry if *any* of the two flags are true for that ship. 

Since lua can't change `Ship::Info_Flags::Default_in_tech_database`, lua's `shipClass.InTechDatabase` is only useful for adding new entries, but not for removing default entries from the list. 

I believe this is not by design, but I wanted to ask before attempting to change it.

**Comment by Goober5000** [comment]
It's not by design.  I took a look at the use of the default flags and I'll have a PR up shortly.
