### ISSUE TITLE
Should ship classes with the same model but different subsystems work or not?

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#4408]
The table syntax perfectly allows modders to define two ship classes with the same model, but different subsystems (particularly different numbers of subsystems), and logically there's no obvious reason why this shouldn't work, where the model file's subsystems are 'available' to the ship class for usage in any combination or number consistent with the model file. Yet, functions like `ship_copy_subsystem_fixup()` seem to assert that classes which share a model must also share subsystems. 

I don't really understand that code very well, so I don't know if that system is just bugged and doesn't need to do that, or this is indeed a fundamental requirement that is completely unenforced or mentioned.

**Comment by MageKing17** [comment]
AIUI, `ship_copy_subsystem_fixup()` is copying *model* subsystems, not *ship* subsystems; it should be pretty safe to assume that two instances of the same model should have the same model subsystems.

**Comment by Baezon** [comment]
I can confirm that it is the `model_subsystem`s in `ship_info->subsystems` that can differ even if they share the same model that is causing this issue.

**Comment by Baezon** [comment]
Ok, well that's not great design, the warning was being suppressed because the `mprintf(("No subsystems found for model \"%s\".\n", model_get(model_num)->filename));` was happening earlier, which flags `ss_warning_shown`. I'm looking into that now, but I think that covers it.

**Comment by Baezon** [comment]
https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/ship/ship.cpp#L4026
>.>
Cool, because I didn't provide a $Closeup_pos: it manually calculated it from the model, by loading the model right then and there with NULL as the subsystem list (because it hasn't even been parsed yet), which triggers the 'No subsystems found...' mprintf, and suppresses the warning. Obviously, this behavior needs some clean up but the core issue is clear, table and model subsystems need to match no matter what.
