### ISSUE TITLE
22.2 RC2: Asteroids brackets display the players distance to their current target, instead of distance to the asteroid

### ISSUE THREAD

**Issue by Kiloku** [scp-fs2open/fs2open.github.com#4409]
This is split off from #4393. 
The brackets shown on-screen don't show the correct distance from the player to the asteroid. If the player has no target, the number used will be the last distance-to-target value that was displayed.

![image](https://user-images.githubusercontent.com/4577144/173827914-558bb6df-747e-4abb-9a5e-15aa16db99ba.png)
In the screenshot above, I am 555 away from the GVCv Asar, and this distance is also shown for the two asteroids on-screen. Notice that the asteroid off-screen indicator in the bottom-right has a different value, 597, which as far as I can tell is correct.

**Comment by JohnAFernandez** [comment]
Hopefully the check that I just added fixes this.
