### ISSUE TITLE
Skipping training causes crash in FSPort

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4412]
If the last mission in a campaign is a training mission, attempting to skip that mission using "skip training" will cause a crash.  This occurs on FSPort because the last mission is configured as a training mission.

Reported by Daft Mugi on Discord.

**Comment by daftmugi** [comment]
This is still crashing in 22.2.0 RC3.

**Comment by daftmugi** [comment]
After a little more testing, the debug build does not crash but the release build does crash.

After the crash, the output is `free(): invalid pointer`. This is on Linux.

**Comment by daftmugi** [comment]
Another note: This crashes in the mission simulator as well. Hope that helps with testing.

**Comment by Kiloku** [comment]
I have a core dump of this crash, but it's 576 Mb and I have no idea where I can upload it.

**Comment by Goober5000** [comment]
It crashes in Fast Debug, in the vm_free in this block of code in `mission_campaign_store_variables`:
```
	// handle variables that are saved on mission victory -------------------------------------
	if (mission_obj->variables != NULL) {
		vm_free( mission_obj->variables );
		mission_obj->variables = NULL;
	}
```
This is because it's referencing variables for a `Campaign.current_mission` that is -1.
