### ISSUE TITLE
No method available in LUA to clear mouse button downcount

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#4429]
Revealed by issue #4173, the `isMouseButtonDown` LUA method only checks if a mouse button is currently down.  It does not clear the downcounter, which is incremented on every mouse button event, and can lead to controls conflicts/overlays with the LUA scripts.

This also means that there's no method to service a singular mouse button event in LUA, meaning mission designers have to come up with their own solutions to implement a one-shot reaction event instead of continuously firing the event while the mouse button is down.

Old scripts, such as Axem's Lua Promptbox script, got around the issue by turning on/off the mouse to prevent the controls from collecting mouse events.  Now that the mouse is toggled between mouse mode and joystick mode, scripts for new mods will have to account for the possibility that both joy0 controls and mouse controls may be used/bound.

**Comment by z64555** [comment]
Some notes:
 * `mouse.h:mouse_down()` is mainly used outside of the mission playspace, AKA while within some menus that's outside of the normal gameplay.
 * `mouse.h:mouse_down_count()` is used exclusively within normal gameplay.
 * `mouse_down()` only checks if the quered button is down at the time of the check, not if it had gone down at any time before the check
 * `mouse_down_count()` checks if the queried button is down at the time of the check *or* if it had gone down at any time before the check.
 * `mouse_down_count()` clears the downcounter by default.

`mouse_down()` works within the context of the menus UI because execution more or less quickly loops over the checks continously in a single thread and code execution is tightly governed.

It doesn't work that well, if at all, within gameplay because gameplay has an aspect that menus does not: time.

The controls code has a very waterfall like schema which checks all controls to see if they had perhaps been activated since last frame.  The control checks then see what button/key they are bound to, and checks their downcounter.  If a control isn't checked for whatever reason, the downcounter remains untouched until its picked up by the control's handler.

`controlsconfig.h:CCI`'s have a new bool called `locked` which may be used to temporarily disable controls, which may be of some use for LUA scripts.

Since LUA scripts can run their own MenuUI within the gamespace, they're in a weird position where they need to be able to run a menu system and be able to emulate hardcoded control triggers.

**Comment by Goober5000** [comment]
See #4948, although I wrote that before reading the latest comment.  I left it in draft pending discussion.

**Comment by z64555** [comment]
Another observation,

 * The mousewheel is only managed in one of the two functions (`mouse_down()` and `mouse_down_count()`) because if it were done in both it would apply `mouse_decay()` twice in most, if not all, places that call `mouse_down_count()`

**Comment by Goober5000** [comment]
@z64555 should the mousewheel be included in this issue, or should another issue be opened for that?

**Comment by z64555** [comment]
Mousewheel should be its own issue.

**Comment by z64555** [comment]
Partially resolved by #4948
