### ISSUE TITLE
Sound volumes set via sexp carry over on mission quit

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#4468]
When "adjust-audio-volume" is used to change the relative volume of a sound type and the player exits the mission, the sound type will be at that volume at the main menu. 

For example, if the Effects volume is set to 0 and the player quits out, the menu sound effects remain muted.

**Comment by Goober5000** [comment]
I'm not able to reproduce this.  I created a SEXP that set the effects volume to 0, and my fighter's engines are muted as expected.  However when I quit to the main hall, the door sounds and intercom sounds play as usual.

**Comment by dariusbei** [comment]
Please find attached mission. It seems to happen when exiting the mission on player death screen
[soundtest.txt](https://github.com/scp-fs2open/fs2open.github.com/files/9053912/soundtest.txt)
.

**Comment by Goober5000** [comment]
Ok thanks, that definitely helped.
