### ISSUE TITLE
Red Alert hull and ammo values are carrying over incorrectly

### ISSUE THREAD

**Issue by Kiloku** [scp-fs2open/fs2open.github.com#4472]
This issue was identified in the Procyon Insurgency mod, where there is a string of four red alert missions. 

When the player finishes each mission, they'll start the next one with the lowest of `+Initial Hull:` and their hull at the end of the previous mission, however the expected behavior is to start with the highest of these values. 
@Goober5000 identified that the issue was caused by a combination of the [593be42e66](https://github.com/scp-fs2open/fs2open.github.com/commit/593be42e66) and [a04e83ab01](https://github.com/scp-fs2open/fs2open.github.com/commit/a04e83ab01) commits.

**Comment by Goober5000** [comment]
The correct behavior is to use exactly the saved hull value, disregarding whatever is the mission's initial hull.  Those commits are supposed to be range checks for valid hull values, but due to code rot they mutated into picking the lower of two valid values.

**Comment by Kiloku** [comment]
The report from the player said: 

> Also, at every stage of the Red Alert string it knocks 20% off my health.  I left the first stage at 100%.  I then started the second stage at 80%, fought nothing, and then started the third stage at 60% (it also replenished my missiles for some reason), so it's not behaving how Red Alert missions typically do.

**Comment by Goober5000** [comment]
Reopening so I can investigate the missile count.

**Comment by Goober5000** [comment]
The missile count worked as expected for me, so I'm calling this fixed unless someone can reproduce it again.
