### ISSUE TITLE
Fix ship class control flags to work on AI-controlled movement

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4484]
Follow-up to #4483.  There are several ship class flags that are supposed to affect how ships move even with normal movement, not maneuvers:
```
Ship::Info_Flags::Dont_bank_when_turning
Ship::Info_Flags::Dont_clamp_max_velocity
Ship::Info_Flags::Instantaneous_acceleration
```
So far I've only tested these with player ships, but they need to be updated to work with AI-controlled ships as well.

**Comment by Baezon** [comment]
I don't believe this is a regression, they never had the code to work for AI in general.

`Dont_bank_when_turning` works for AI in general, and should be good.

`Dont_clamp_max_velocity` allows players to rotationally accelerate indefinitely. If this is correct, which I suppose is reasonable, it shouldn't be difficult to fix for AI. 
Laterally for players, it does some odd things... You can exceed your max velocity by holding accelerate, but only depending on your current throttle setting. There might be some buggy behavior here I haven't bug much into. Either way, AI set their velocity by requesting % of thottle, which in many cases is `1.0`, for maximum speed, so even if uncapped, they won't really make use of it and it may fundamentally prevent them from 'taking advantage of this flag'. Dunno if this should be viewed as a problem per se.

`Instantaneous_acceleration` should work properly laterally as is. Rotationally, the fix should be fairly straightforward, simply an indefinite acceleration cap.

**Comment by Goober5000** [comment]
Asteroth and I discussed this, and since this would technically be adding new behavior, we'll tag it as Waiting for Stable and address it immediately after 23.0 is out.
