### ISSUE TITLE
Options subdir needs more documentation

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#4492]
Files within code\options need more documentation to clearly state what the API is for.  I stumbled across it when checking for fs2open.ini keys and found something that looks like custom keys could be made with the Options API, but I have no idea how its intended to be used at this point in time.

**Comment by MjnMixael** [comment]
I'm pretty certain these files control the API that makes in-game options available in the scripting Options (opt) library. See PR #4776 as an example. I don't think I follow it enough to be able to document the code, though.
