### ISSUE TITLE
AI code crash in Forced Entry (BP-10) and RC9 (hard to reproduce thus far)

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4522]
Assert: "(objp_hitter->type == OBJ_SHIP) || (objp_hitter->type == OBJ_WEAPON) || (objp_hitter->type == OBJ_ASTEROID) || (objp_hitter->type == OBJ_BEAM) || (objp_hitter->type == OBJ_DEBRIS)"
File: aicode.cpp
Line: 15591
The ai code is passing an invalid object type of 8 to a function when trying to decide how to respond to something hitting it.  This is a bug in the code, please report!

ntdll.dll! ZwWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
KERNEL32.DLL! BaseThreadInitThunk + 16 bytes
ntdll.dll! RtlUserThreadStart + 43 bytes

**Comment by MageKing17** [comment]
Object type 8 is `OBJ_GHOST`. Since the very next line of code is a comment saying `// lets not check hits by ghosts any further either`, it can safely be assumed that `objp_hitter` being a ghost is in fact a valid possibility, despite not being one of the types checked in the assertion. Then again, the assertion is quite new, having only been added in #4370. Presumably the correct solution is to simply throw a check for `OBJ_GHOST` into the assertion's condition, but I can barely follow AI code at the best of times.

**Comment by MoerasGrizzly** [comment]
Assert: "(objp_hitter->type == OBJ_SHIP) || (objp_hitter->type == OBJ_WEAPON) || (objp_hitter->type == OBJ_ASTEROID) || (objp_hitter->type == OBJ_BEAM) || (objp_hitter->type == OBJ_DEBRIS)"
File: aicode.cpp
Line: 15591
The ai code is passing an invalid object type of 8 to a function when trying to decide how to respond to something hitting it.  This is a bug in the code, please report!

ntdll.dll! ZwWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
KERNEL32.DLL! BaseThreadInitThunk + 16 bytes
ntdll.dll! RtlUserThreadStart + 43 bytes

[ This info is in the clipboard so you can paste it somewhere now ]


Use Debug to break into Debugger, Exit will close the application.

ntdll.dll! ZwWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_RC9_x64_AVX-FASTDBG.exe! <no symbol>
KERNEL32.DLL! BaseThreadInitThunk + 16 bytes
ntdll.dll! RtlUserThreadStart + 43 bytes

Got another one, BP2-03, RC9.

**Comment by EatThePath** [comment]
is there anything common about the situations where these occur?

If 8 is ghost I would expect it only happens when the player is dead?

**Comment by MoerasGrizzly** [comment]
I was being shot the fuck up every time it happened. Not sure if I would've died there.

**Comment by MoerasGrizzly** [comment]
Notably it doesn't reliablly happen if I get shot up. It does seem to only happen when I get absolutely railed.

**Comment by MoerasGrizzly** [comment]
Assert: "Objects[aip->target_objnum].type == OBJ_SHIP || Objects[aip->target_objnum].type == OBJ_WEAPON || Objects[aip->target_objnum].type == OBJ_DEBRIS || Objects[aip->target_objnum].type == OBJ_ASTEROID || Objects[aip->target_objnum].type == OBJ_WAYPOINT"
File: aicode.cpp
Line: 10027
This function just discovered that Gemini 2 has an invalid target object type of 0. This is bad. Please report!

ntdll.dll! NtWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
KERNEL32.DLL! BaseThreadInitThunk + 20 bytes
[...]
[ This info is in the clipboard so you can paste it somewhere now ]


Use Debug to break into Debugger, Exit will close the application.

ntdll.dll! NtWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
fs2_open_22_2_0_x64_AVX-FASTDBG.exe! <no symbol>
KERNEL32.DLL! BaseThreadInitThunk + 20 bytes
ntdll.dll! RtlUserThreadStart + 33 bytes

BP2-14, Pawns on a board of bone.
