### ISSUE TITLE
Lock animation counter not resetting

### ISSUE THREAD

**Issue by Yarn366** [scp-fs2open/fs2open.github.com#456]
When the player acquires aspect lock on a target, the animation lockspin.ani (assuming the default HUD is used) is plays where the lock triangle is located. The animation is supposed to play through once and blink at the last frame. However, starting with commit 8a728238390a14f4e98077d464128305f9948cb0, the first occurrence of this animation works fine, but subsequent occurrences only display the last frame. This continues to happen until the game is closed.

Part of the problem seems to be that the `Lock_anim.time_elapsed = 0.0f;` line was commented out in the aforementioned commit. However, that line can't simply be uncommented because that same commit made changes that removed `Lock_anim` as a global variable.

**Comment by Goober5000** [comment]
Whoops.  Let me see what I did wrong there.

**Comment by MageKing17** [comment]
At a glance, I'd say [hudlock.cpp:286](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/hud/hudlock.cpp#L286) is meant to do the same thing, but can't because if `current_target_is_locked` is false it probably means `lock_indicator_visible` is false, and `HudGaugeLock::render()` returns early in that case ([hudlock.cpp:222](https://github.com/scp-fs2open/fs2open.github.com/blob/master/code/hud/hudlock.cpp#L222)).

**Comment by Goober5000** [comment]
Yarn, are you sure that it was *that* commit when the problem started?  I remember now why I removed `Lock_anim` in that commit... it wasn't referenced anywhere else.

**Comment by Goober5000** [comment]
Have a look at #462.  Not sure of the best way to get a specific HUD gauge in a method that isn't a class method already.

**Comment by Yarn366** [comment]
It turns out that commit isn't the culprit. Rather, this problem was introduced after b1c2a85faabe9d2a248a8ffcf9d40ea7638eb7f8 and no later than 2e7dea0018d743d679f4b43ef15170006a939733. And the HUD overhaul was committed during that time, so go figure.

**Comment by SamuelCho** [comment]
I've seen this issue and Goober's pull request. I think his solution will work but I think another solution can be contained within the entirety of the HudGaugeLock class without modifying it externally. I noticed that the timer state is dependent on the lock state so I end up just using the if (Player_ai->current_target_is_locked) checkwithin the render() method. I just reset the lock timers if no target lock is ready to fire. https://github.com/scp-fs2open/fs2open.github.com/pull/479

I also noticed that we're missing a if(loop_locked_anim) check which basically the difference between FS1 and FS2 lock styles. Check https://github.com/scp-fs2open/fs2open.github.com/blob/1d2d2bce10b1c02d19261ee2888110bd028b9b84/code/hud/hudlock.cpp#L936 which is the original HUD code before I came in like a wrecking ball. Maybe that's the missing behavior you're talking about Yarn?

**Comment by Yarn366** [comment]
The lack of `if(loop_locked_anim)` looks like it would mess up only the FS1 animation, which appears to be working fine right now (it's animating continuously and not blinking). It's the FS2 one that's affected. So, no, that's not the behavior that I was referring to.

**Comment by Goober5000** [comment]
It looks like the missing `if(loop_locked_anim)` would only apply when the FS1 anim cycles back to t=0.  The majority of the time, it would be in the other if() block (in PR #479, lines 693-699) so it looks like the issue would only be noticeable sporadically.

**Comment by niffiwan** [comment]
Fixed by #479
