### ISSUE TITLE
FR: Setting dpi-awareness automatically for FSO

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#4588]
We still keep getting bug reports from people running FSO on screens that Windows considers to be high-dpi. When they do so, FSO (being unaware that scaling is applied) is unplayable, as the viewport we open gets scaled up and thus will exceed the screen bounds. There's official guidance from MS in this regard [here](https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process), which we should implement.

**Comment by JohnAFernandez** [comment]
I know it has FR in the title, but not having the "feature" leads to buggy behavior.
