### ISSUE TITLE
Models disappear in Twisted Infinities surface mission

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4637]
This bug affects the TI mission "Sneak and Destroy", MoonSurface.fs2.  It's not part of the main campaign but can be found in the tech room.

For most of the player perspectives, the surface is not rendered - and not only the surface, but the player ship as well.  This can be seen in the attached video:
https://user-images.githubusercontent.com/1878523/189500047-319858fc-80e4-4618-bb7d-918077bd34e4.mp4

The bug appeared sometime between 22.0 and 22.2.

**Comment by The-E** [comment]
Twisted Infinities uses a custom script to distribute and then render a bunch of rocks on the surface of that moon. When that script is disabled, everything renders normally; this indicates that the culprit is somewhere within the `gr.drawModelOOR` method.

**Comment by The-E** [comment]
Looking at the game in renderdoc reveals that the script is actually executed several times per frame. If we put in a manual guard against that (by checking in the script itself if it ran this frame), it works as intended; the true cause of this issue might be a combination of the script running more often than intended and some wonkiness involving `gr.drawModelOOR`.
