### ISSUE TITLE
Tips.tbl doesn't do key remapping

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4648]
In `player_tips_init()`, tips are parsed without doing any key remapping.  The string should be processed using `message_translate_tokens()`.

**Comment by maingotj** [comment]
Hi, I'm new to this project could I work on this?

**Comment by Goober5000** [comment]
> Hi, I'm new to this project could I work on this?

Certainly!

**Comment by kkruiliu** [comment]
Can you elaborate on what the problem is?  Why Tips.tbl need to do key mapping?

**Comment by kkruiliu** [comment]
Where the Tips.tbl located?

**Comment by kkruiliu** [comment]
> In `player_tips_init()`, tips are parsed without doing any key remapping. The string should be processed using `message_translate_tokens()`.
Hello! Where the Tips.tbl located?

**Comment by Goober5000** [comment]
> > In `player_tips_init()`, tips are parsed without doing any key remapping. The string should be processed using `message_translate_tokens()`.
> > Hello! Where is the Tips.tbl located?

It can be found in `root_fs2.vp`.  You'll need a VP viewer such as VPView32 to extract it.

**Comment by kkruiliu** [comment]
> > > In `player_tips_init()`, tips are parsed without doing any key remapping. The string should be processed using `message_translate_tokens()`.
> > > Hello! Where is the Tips.tbl located?
> 
> It can be found in `root_fs2.vp`. You'll need a VP viewer such as VPView32 to extract it.

Hello! I am a beginner at the project and I am trying to solve this bug. 
I tried to convert "message_translate_tokens(stuff_and_malloc_string(F_NAME, NULL))" into char* type and did "Player_tips[Num_player_tips++] = mychar*"; but it didn't work, some tips are missing and some are only showing key.  Is there any more information I need to know? What "message_translate_tokens" function exactly do?

**Comment by kkruiliu** [comment]
#4746

**Comment by kkruiliu** [comment]
#4746

**Comment by z64555** [comment]
`message_translate_tokens()` may be found in `.\code\mission\missiontraining.cpp`.  Its documentation is a little thin, so you may want to search the codebase for all usages of `message_translate_tokens()` to see how it is used.
