### ISSUE TITLE
Proposal: use Dear Imgui as a UI backend for the Lab and other dev/debug tools

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#4674]
Following a discussion in discord today, I took a closer look at [Dear ImGui](https://github.com/ocornut/imgui), and I think incorporating it makes a lot of sense for us.

But wait, I hear you ask: Don't we already have a new UI system being built by MjnMixael?
Yes, imaginary interlocutor, we do. But that system fulfills a fundamentally different purpose than what I am proposing here. For our main game interface, we want a highly skinnable system that can be easily "themed" according to a given mod's needs and wants. Using it for developer interfaces like the lab doesn't make much sense to me: We do want a reasonably fully-featured UI system there that we can easily extend as we add new features without having to rely on external data files.
Dear ImGui fills those needs (as can be seen by the many, many commercial games that incorporate it). Using it would solve a number of issues with wmcgui: finally we can have scrollable lists!

In a further step, we could also expand this into other areas: The mission profiling output, for example, is a prime candidate for this, as is the debug window.

**Comment by JohnAFernandez** [comment]
I just took a look and I think because their setup is so simplified, the code required to set up a dialog is miniscule. Take a look near the bottom of the page the E linked.

**Comment by Kiloku** [comment]
I love Dear ImGui and have a little bit of experience with it. I'm in favor!

**Comment by EatThePath** [comment]
I'd love to have imgui available for debug or stopgap/fallback interface stuff, what little I've used it elsewhere is great

**Comment by JohnAFernandez** [comment]
This was implemented!  Happy labing everyone!
