### ISSUE TITLE
Wing arrival info not cleared properly between missions (incorrect ships in waves)

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#4800]
When multiple missions are played in a single session, and two wings both share the same location in the wing list/index, and the wing in the subsequent mission has multiple waves- the ships in the 2nd wave will not be the correct ships, they are instead the ships used by the wing in the previously played mission.

Attached in this zip file are two test missions to demonstrate this.

[wingtestmissions.zip](https://github.com/scp-fs2open/fs2open.github.com/files/9815414/wingtestmissions.zip)

To replicate the error, simply play the 1st mission "RhoWingZodFighters" Then play "CancerWingIsAmazons" in a single test,
note that in the 2nd mission, the 2nd wave will not be the same ship class due to the bug.

**Comment by Goober5000** [comment]
I gave this a test run and I can't replicate the error.  Here are the steps I followed:
1. Launch a debug build using the latest code
2. Start mission A, observed Taurets, then quit
3. Start mission B, observed Amazons.
4. ~K'd all Amazons, waited for the second wave.
5. Second wave arrived and was Amazons.

**Comment by DefCynodont** [comment]
@Goober5000 it is the correct procedure, but make sure you are running both missions without exiting the game between them.

**Comment by Goober5000** [comment]
I didn't exit the game.  By "quit" I meant I quit the mission, not the game.
