### ISSUE TITLE
Assert/CTD at line 3782 in modelread.cpp on ship death

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4813]
The 10/22 nightly has this assert, the 10/21 nightly does not. In normal play, a CTD occurs.

In BtA2 if a ship is marked to Vaporize the assert is triggered. It does not happen when Vaporize is cleared. I was unable to reproduce this on retail with any BtA model, so there's some other mod setting also affecting. It's almost certainly related to @Goober5000 's debris changes last night.

**Comment by MjnMixael** [comment]
Ok, quick update. I can reproduce it on the public BtA, so that's good. Mission attached.

But also in this test mission the assert happens to both ships, whether they have vaporize or not.
[VaporizeAssert.zip](https://github.com/scp-fs2open/fs2open.github.com/files/9844700/VaporizeAssert.zip)

**Comment by Goober5000** [comment]
Huh, ok.  This was tested pretty thoroughly but something must have slipped through.  I'll take a look.

**Comment by Goober5000** [comment]
Well I am not able to reproduce this running that test mission under BtA - whether release or debug, or the 10/22 nightly or latest master.  It's possible this could be affected by a command-line option.  Could you upload your debug log?

**Comment by MjnMixael** [comment]
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/9847068/fs2_open.log)
Log attached. Seems this assert is going around, having also been reported in #SCP channel and the nightly thread on the forums.

**Comment by Goober5000** [comment]
Aha.  The crash only occurs when shadows are enabled.  I'll have a fix shortly.
