### ISSUE TITLE
FR: Additional player orders for transports and freighters

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#4819]
I would love to see additional player orders be added to the comm menu for transports and freighters using the already existing ai orders. This would open some wild posibilities.

i will list the ones that i think it will be usefull here:

1) Dock with my target (the same as "Capture my target" with the only difference this should work when the transport and target are on the same team) (aaaand it i think should also be avalible when the target is on a different, non hostile team example: Friendly<->Unknown).

2) Undock

3) Follow Me (ai-stay-near-ship "Player Ship")

4) Follow My Target (ai-stay-near-ship "Player target")

5) Stop (ai-stay-still)

**Comment by MjnMixael** [comment]
These are all possible to create now under the LuaAI feature set. Does require some scripting, but otherwise no code changes are required.

https://wiki.hard-light.net/index.php/Dynamic_SEXPs#.23Lua_AI

**Comment by BMagnu** [comment]
If it's just already existing AI orders, isn't modifying the objecttypes.tbl sufficient? You wouldn't even need to script the AI code yourself, though that is evidently a possibility as well

**Comment by Shivansps** [comment]
Ok thanks for the information
