### ISSUE TITLE
secondary lead indicators showing up in ship with no secondary weapons

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#4837]
HUD graphic for lead indicator has texture in frame 1 for dumbfire missiles and a blank texture for missile locks and primaries (frame 2 and 3 respectively).

Dumbfire missiles lead indicator is coming up in ships with an empty (ie. no weapon) secondary bank when it should probably be disabled instead.

Mod is also using +Lead Sight: for primary gun sights.

**Comment by Goober5000** [comment]
This could be related to #4411

**Comment by MjnMixael** [comment]
I tried to reproduce this by adding +Lead Sight: to my hud_gauges.tbl and then flying a ship empty secondary banks. I also tried a ship with no secondary banks. In both cases the dumbfire lead indicator was not drawn. Does this occur on the latest Solaris? Is there a good mission in that mod I could use to test?

**Comment by Kiloku** [comment]
If a repro is found, I'd like to test it as well, pleae.

**Comment by dariusbei** [comment]
Please find attached zip file to go into \slrs-interface\data\hud\
and the hud_gauges tbl for slrs-core\data\tables\

A good mission to test out would be any act 2 mission e.g. 21.fs2 in the most recent solaris public release on knossos

Reproduceable by choosing a comet gunship with e.g. stiletto secondary loadout
and then restarting the mission with a fighter with no secondary bank e.g. warden defender

You should see the dumbfire lead indicator show up for the warden defender

[slrslead_0000.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10097518/slrslead_0000.zip)
[hud_gauges.txt](https://github.com/scp-fs2open/fs2open.github.com/files/10097520/hud_gauges.txt)

**Comment by MjnMixael** [comment]
I tested this on the latest nightly exactly as described above and could not reproduce the issue. I got no secondary lead indicator while flying the warden defender.

**Comment by Goober5000** [comment]
@dariusbei can you try again on the latest nightly?

**Comment by dariusbei** [comment]
Yep it looks like the issue has been resolved with RC4 thanks.
