### ISSUE TITLE
Destroyed subobjects are not rendered

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#489]
Here is a screenshot showing the issue:
![subobject](https://cloud.githubusercontent.com/assets/1013983/11608324/6f227632-9b66-11e5-89bf-b3ed53b4e193.png)

**Comment by asarium** [comment]
This issue was first introduced in 64ad950a802f8bae62a67c54b0e95e6f6271554b.

**Comment by Goober5000** [comment]
@SamuelCho seems PR #486 had a bug in it.
