### ISSUE TITLE
hard crash in ai_goal_purge_invalid_goals

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4899]
> 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ai_goal_purge_invalid_goals(ai_goal * aigp, ai_goal * goal_list, ai_info * aip, int ai_wingnum) Line 534	C++
	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ai_goal_purge_all_invalid_goals(ai_goal * aigp) Line 568	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ai_mission_goal_achievable(int objnum, ai_goal * aigp) Line 1786	C++
 	[Inline Frame] fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!validate_mission_goals(int) Line 2082	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ai_process_mission_orders(int objnum, ai_info * aip) Line 2162	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ai_frame(int objnum) Line 14608	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ai_process(object * obj, int ai_index, float frametime) Line 14923	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ship_evaluate_ai(object * obj, float frametime) Line 9602	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!ship_process_pre(object * obj, float frametime) Line 9634	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!obj_move_all_pre(object * objp, float frametime) Line 1144	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!obj_move_all(float frametime) Line 1509	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!game_simulation_frame() Line 3640	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!game_frame(bool paused) Line 4045	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!game_do_state(int state) Line 6314	C++
 	[Inline Frame] fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!gameseq_process_events() Line 389	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!game_main(int argc, char * * argv) Line 6687	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!SDL_main(int argc, char * * argv) Line 7770	C++
 	fs2_open_22200_8_0_x64_AVX2-FASTDBG.exe!main_getcmdline(...) Line 177	C
 	[External Code]	

Encountered on universal truth on dev version of warmachine and almost but not quite master branch, haven't isolated a cleaner reproduction yet. However, the crash is reliable in tests so far, and reverting #4890 equally reliably resolves it.

**Comment by wookieejedi** [comment]
I'll make a revert PR tonight as a hotfix unless the situation changes.

**Comment by EatThePath** [comment]
was able to reproduce the crash on master and public warmachine, happens 10-20 seconds after the opening cutscene of wm-bpc-aoa-21x.fs2 with no player input needed. Was also able to reproduce the not-crash after the revert.

**Comment by Goober5000** [comment]
Started the mission and left it running until my fighter blew up at 1:25... no crash occurred.

**Comment by Goober5000** [comment]
This is on latest master (6255b9b154451d1f2aaf8be147fba054a5947e80) playing wm-bpc-aoa-21x.fs2.

**Comment by Goober5000** [comment]
Tried a few times; no crash.  The sound index crash did not recur either.

**Comment by EatThePath** [comment]
I've gone from being able to reproduce reliably to not being able to reproduce at all, so... harumph. no idea what's changed.
