### ISSUE TITLE
Subspace tunnel textures no longer animate

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#4909]
Likely the same issue as the other non-animating textures which was caused by the timestamp change. Note that handling this during mission-set-subspace preload will not be sufficient unless the parsing is smart enough to see when that sexp is called by lua scripts as is our case in BtA.

**Comment by Goober5000** [comment]
I tested latest master, and the following scenarios work:
1. starting in subspace
2. using the mission-set-subspace sexp
3. invoking the mission-set-subspace sexp via script-eval-block and mn.evaluateSEXP

Let me know if it still doesn't work after the next nightly is built.
