### ISSUE TITLE
ship list selection in FRED omits entries

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#4918]
#4833 introduced a bug where the last few ships loaded by FRED would not appear in the ship class dropdown list.  The number of ships not appearing is equal to the number of ships omitted from the list via the `no_fred` flag.  In their place, the dropdown displays extra copies of Waypoint or similar.

Fixing this bug while still allowing #4833 to work as designed is proving rather tricky.  ~~I have a fix in progress but it's not ready yet.~~

**Comment by JohnAFernandez** [comment]
Can you explain more about what's causing it?  I can't figure out what's causing it by looking at the code.

**Comment by Goober5000** [comment]
It's a very sneaky bug, but the essential root cause is that omitting entries in the ship class list will cause the highest `Ship_info` index[es] to exceed `ship_type_combo_box_size`.  This will then cause various parts of the FRED code to refer to the overflow entries (waypoints and jump nodes and player starts) rather than the last few ship classes.
