### ISSUE TITLE
Following up 4516

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4922]
Returning to this: The fix doesn't work fully. Although things like firerate appear to work correctly, stuff like afterburner usage is still affected by the scaling bug.
[ai.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10050936/ai.zip)
[ai2.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10050938/ai2.zip)

Steps to reproduce:
On FSBlue with a current nightly, try playing SM1-03 with AI1 and AI2, and notice how with the file included in AI2.zip, the AI reaches the Iceni much faster.

edit: on review of the submitted bugfix, it seems like several aspects that are affected by AI autoscaling have not been touched. I'm in particular worried about
$Afterburner Use Factor:
$Shockwave Evade Chances Per Second:
$Get Away Chance:
$Secondary Range Multiplier:

@EatThePath did a review of the AI's autoscaling a while back. I'll attach it here for your convenience:
[ai_autoscale_digging.txt](https://github.com/scp-fs2open/fs2open.github.com/files/10050994/ai_autoscale_digging.txt)

_Originally posted by @MoerasGrizzly in https://github.com/scp-fs2open/fs2open.github.com/issues/4516#issuecomment-1321269704_

**Comment by Goober5000** [comment]
Looks like there are several places in the code where autoscaling occurs without being labeled as autoscaling.
