### ISSUE TITLE
Player turrets produce no sound.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4930]
When a turret on a player ship fires, the player can not hear the launch sound.

This is especially noticable on capship command missions like BP's "The Blade Itself", but it also applies to any bomber mission (for example, try flying an Ursa during Slaying Ravana).

**Comment by X3N0-Life-Form** [comment]
The turret needs to have the flag "play fire sound for player".

**Comment by MoerasGrizzly** [comment]
> 

oops. I missed that, turns out it's hiding in the subsystem documentation on the wiki...
