### ISSUE TITLE
FR: API updates to account for subfolders.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#4939]
#4771 added subfolders and augmented the internal functions for finding files, however the luaAPI functions do not appear to have any awareness of this change. Updating or suplementing them would be very useful.

**Comment by notimaginative** [comment]
What's currently missing or not working?

I did look through the cfile parts of the luaAPI but didn't notice any need for changes beyond what I'd already made. The lua file loader was modified to allow for paths when requiring a script from another script, and path type determination was also modified for subfolder support. Those two changes were all that was needed to get the test data I had at the time to work.

Adding subfolders actually started with a request to make such a thing usable for scripts, so scripting was the first test of the new code. It passed all testes, though I admit those tests were quite basic compared to what you are likely to use.

**Comment by EatThePath** [comment]
To clarify the searcher and loader work fine, and the main lack I've encountered is in listFiles. I want to be able to restrict my search to a subfolder, but passing for instance `data/scripts/mods` as the directory seems to give me a list of all files in the scripts directory anyway, passing `data/scripts` and then for the pattern `mods/*.lua` complains that the pattern has to start with a *, and the list output doesn't contain any path information.

**Comment by notimaginative** [comment]
Okay, that's definitely something I missed. I'll update the filter check to allow it to include a path.

(ninja edit before submitting: lol, nope, didn't miss it. It's right there in my notes, I simply forgot to fix it 🤦 )

It should work with the second instance btw. So the subfolder path you want should be included with the filter as opposed to in the directory.

And the list output will only include path information if you specify a path or glob with the filter. If you specify a path like `mods/*.lua` then it should return files prefixed with the `mods/` path. If you are doing a straight glob (`*/*.lua`) then it would return files prefixed with and without paths, however they are found.

This behavior is for compatibility reasons.

**Comment by EatThePath** [comment]
> It should work with the second instance btw. So the subfolder path you want should be included with the filter as opposed to in the directory.

Is this to say that it should already work, or that is how it will work? If the former, `scripting/api/libs/cfile.cpp:76` gets in the way.
```cpp
	if (filter_str[0] != '*') {
		LuaError(L, "The filter \"%s\" is not valid! The first character must be a '*'.", filter);
		return ADE_RETURN_NIL;
	}
```

**Comment by notimaginative** [comment]
It's how it should already work. I was meant the update that filter check but forgot, according to my notes.

I've already made the needed changes, just need to test it and then I'll submit a PR.

```c++
	// allow subpath in filter, but it can't be the first part of the filter
	auto path_star_pos = filter_str.find("/*");
	if ((filter_str[0] != '*') && ((path_star_pos != SCP_string::npos) && (path_star_pos == 0))) {
		LuaError(L, "The filter \"%s\" is not valid! The first character must be a '*', or must follow a path.", filter);
		return ADE_RETURN_NIL;
	}
```

Are you aware of another other spots where things haven't been working?

**Comment by EatThePath** [comment]
so far that's the only snag I've found.  I'll probably be able to pull your pr and test it to see if there's any more speedbumps in my scheme

**Comment by notimaginative** [comment]
PR up. I also updated the description of `listFiles` to be more accurate.

Also went back through the rest of that code -- and my notes -- but didn't notice anything else that looked like it needed to be tweaked for subfolders.
