### ISSUE TITLE
Crash Loading Wings Of Dawn: VP Case sensitivity

### ISSUE THREAD

**Issue by TheForce172** [scp-fs2open/fs2open.github.com#4941]
Wings of Dawn crashes with the no web curser error despite it working on past nightles (unknown version probably from September).
Debug log shows no files are being loaded.
https://fsnebula.org/log/6383910d3c97ea8ae9ccee7b
**Steps To Reproduce:**
1. Install wings of dawn from Knossos
2. Modify config to use latest nightly
3. Try to play

**Most likely cause**
Having looked in the VP files this seems to be a case sensitivity issue caused by the recent subfolder update as in the retail VPs the folders are all lowercase but in WOD the folder names have capital letters.

**WOD**
![image](https://user-images.githubusercontent.com/2040992/204146936-8fccc0b3-8856-4c5c-994d-c1a6492db860.png)
**Retail**
![image](https://user-images.githubusercontent.com/2040992/204147162-1ef35141-8024-4345-aa49-d3c44982198b.png)

**Comment by notimaginative** [comment]
Yeah, this is definitely a bug in how VPs are indexed in the subfolder code. It's one of, if not the only, spot where a case sensitive check is used to compare directory names.

I'll do some quick testing and check for other problem areas shortly. A fix PR should be up soon-ish after that.
