### ISSUE TITLE
Feature Request: Per-Weapon convergences.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4947]
Heya

Seeing @MjnMixael implement per-weapon auto-aim had me thinking: What about per-weapon convergences? Would love to be able to, for example, have each weapon convergence at its maximum range.

**Comment by MjnMixael** [comment]
Convergence is quite a bit more complex in the code that auto-aim. It's gonna take much more research to make sure I fully understand what the code is doing and why. I started poking around to see what I could figure out, but with RC coming up it's going to be a while.

**Comment by MoerasGrizzly** [comment]
> 

No worries. I'm actually surprised it 's more complex.

**Comment by MjnMixael** [comment]
Auto-aim is really just a single value, an FOV and all the auto-aim stuff is done at the top of the code function. Convergence has distance, but also auto-convergence, auto-aim convergence, and I think another flag I can't recall off the top of my head. And the checks are spread throughout the code function and math calculations done in a few places with the distance setting.

Noting for myself. This is is `in_autoaim_fov` in ship.cpp.
