### ISSUE TITLE
Increase the maximum limit of messages in send-message-list

### ISSUE THREAD

**Issue by LightblueMobius** [scp-fs2open/fs2open.github.com#4968]
It turns out that this SEXP has its limit set to **30** messages per call (though it's worth noting that FRED doesn't specify it anywhere while the code itself does). If it's harmless, I recommend increasing it to at least **50**.

I also suggest to take a look at _send-message-chain_ as well and see it that SEXP has a comparable limit.

**Comment by Goober5000** [comment]
Implemented in #4963
