### ISSUE TITLE
Crash when Knossos explodes in A Flaming Sword

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#4970]
Crash only happens on current nightly i.e. 5/12
log: https://fsnebula.org/log/638e36c306a1b0806fccee97
mdmp file: 
[fs2_open_22_3_0_20221205_5bb869953_x64_SSE2-FASTDBG_20221205_181632.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10157808/fs2_open_22_3_0_20221205_5bb869953_x64_SSE2-FASTDBG_20221205_181632.zip)

**Comment by Goober5000** [comment]
Fixed by #4971.
