### ISSUE TITLE
Loading checkpoint on BP2-06 "Darkest Hour" on nightlies crashes the build. Works fine on FSO 22.2

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4990]
[As found by user DAK on discord.](https://discord.com/channels/223511295431933953/255067124836335616/1051107703726030858)

Assert is "Only ships can have subsystems!"
[fs2log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/10200337/fs2log.txt)

**Comment by Goober5000** [comment]
I haven't been able to reproduce this, but DAK will try again on the latest nightly in a few days.

**Comment by Goober5000** [comment]
Issue solved.  Fix will be PR'd in the next day.

**Comment by Goober5000** [comment]
Copying the explanation from Discord:
> 1) the Redoubtable is vanished, which clears it out of the mission and makes all ships that are targeting it pick a new target
> 2) Sagittarius 4, the player's current target, is vanished, which causes the player to auto-target a new ship
> 3) the player auto-targets Redoubtable, because even though it has been vanished, it is the *same frame* and therefore hasn't been cleaned up yet
> 4) the Redoubtable is cleaned up and the player finds himself targeting a phantom ship
