### ISSUE TITLE
BPC hard crashes when exiting database on current nightlies.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#4991]
Once again works fine on 22.2

Event log and crash dump provided.
[Log](https://fsnebula.org/log/6394a5988da9247990ccee5e)
[fs2_open_22_3_0_20221210_89ed5be8c_x64_SSE2-FASTDBG_20221210_152815.zip](https://github.com/scp-fs2open/fs2open.github.com/files/10200363/fs2_open_22_3_0_20221210_89ed5be8c_x64_SSE2-FASTDBG_20221210_152815.zip)

**Comment by Goober5000** [comment]
Easy to reproduce.  Fix will be up momentarily.
