### ISSUE TITLE
Allow Lua scripts to add to Lua Enums

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#5017]
Once #5011 is merged, there is a path to allowing scripts to add to the Lua Enums during parse. This would allow, for example, scripts that use complex config files to automatically add enum items so the modder doesn't have to remember to list those items in two different places.

This then could maybe allow dynamic lists such as ship subsystems for a ship previously set earlier in the sexp. I have a few ideas on how to make that work but will take some testing.

**Comment by EatThePath** [comment]
ah nice, I was probably going to ask for this at some point :)
