### ISSUE TITLE
FR: Allow multiple species assignments to messages.tbl - and also the option to never auto assign a persona

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5020]
wrt messages.tbl, there's some stuff that could make that table a bit less messy for BP in particular.
Specifically: The ability to assign a persona to multiple species, ergo:
Persona5
+Terran
+GTVA-TEI

Simms
+DoNotAssign

BP has:
Factions, rather then species, so some pilot personas make sense for multiple "species".
Several personas that are tied to a specific character. By default, these could get assigned to random pilots (FSBlue players may remember hearing Corey or Taylor during the FS2 campaign). Currently, BP has a workaround for that, but I'd rather just have a neat engine solution.

**Comment by Goober5000** [comment]
Implemented in #5104
