### ISSUE TITLE
Graphics initialization during parse?

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#5064]
PR #4969 caught my eye because it performs graphics operations during parsing, which is a code smell.  Furthermore, the game_settings.tbl and *-mod.tbms are parsed before `gr_init` is called, so graphics aren't even initialized at this point.

Looking at the code flow more closely, the only part of `gr_init_color` that depends on the graphics context is `gr_screen.signature`.  It just so happens that the default value of the signature field is 0, and the first `Gr_signature` value is *also* 0, so at least this is consistent.  Is there any risk that out-of-date signature values will cause problems for subsequent signatures?

Looking at other instances of `gr_init_color` throughout the code, there are a few that occur frequently (including one in `batching_add_line`) and a few others that occur only during ship/weapons table parsing, so this sort of split decision isn't limited to the mod table.

Wondering what more savvy graphics coders, such as @Baezon, @notimaginative, @TRBlount, and @EatThePath, have to say about this.

**Comment by Goober5000** [comment]
I did some more investigation on `Gr_signature` and found that in the current codebase, it is only called through `gr_init_sub`, from `gr_init`, which is itself only called once on startup.  In the original public source code release, `Gr_signature` is also updated in `gr8_set_gamma` and `gr_set_palette`, which do not exist in the current codebase.

This raises the question of whether `gr_screen.signature` can be removed entirely, or whether it should be kept in the event that some other graphics library may require it in the future.

**Comment by asarium** [comment]
As far as I know, `signature` is something that is still around from the software rendering version of the engine. None of the "modern" graphics APIs use or need that value as far as I know there is no reason to keep it around.
A long time ago I looked at removing that part but for some reason it was not possible at that point so maybe that has changed since then.

**Comment by The-E** [comment]
I'll take a look at this over the weekend, but my gut instinct says that this is something we can easily defer to the next release.
