### ISSUE TITLE
When lightshafts are disabled, there's no sunglare at all.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5089]
Doesn't matter if it's done through post-processing.tbl, command line, or via sexp.

When lightshafts are disabled in FSO 21.0 or lower, looking directly into the sun gives the same behaviour that has existed since retail FS2: The screen turns slightly brighter. From FSO 22.0 onwards however, disabling lightshafts also disables the "looking into sun" effect.

**Comment by MoerasGrizzly** [comment]
... Possibly? It definitely fits in there.

**Comment by Goober5000** [comment]
Reopening since this is distinct from supernovas, as I think I found the cause.
