### ISSUE TITLE
Switch to OpenGL Core Profile

### ISSUE THREAD

**Issue by logomancer** [scp-fs2open/fs2open.github.com#511]
Several issues surrounding Mesa have arisen over the past several months. Most of these stem from Mesa following the written OpenGL spec to the letter.

Mesa requires a `#version` directive at the head of each shader. Adding `#version 120` to the headers satisfies Mesa, but breaks shader compilation on AMD proprietary drivers (see #235).  Bumping up the version number (ex: `#version 140`) makes it compile on AMD proprietary drivers; however, because FSO is using the OpenGL Compatibility profile, Mesa caps itself to OpenGL 3.0 and GLSL 1.20, and thus the shaders are broken again. Finally, the latest PBR builds break Mesa by using `GL_ARB_shader_texture_lod` in its shaders, which requires GLSL 1.40 -- a version not available in OpenGL Compatibility profile in Mesa.

The long-term solution to these issues would be to switch the engine to use the OpenGL Core profile instead. This would allow the use of `#version` directives in all drivers and allow Mesa to use the advanced extensions which are fast becoming part of the engine. As AMD is planning to use Mesa as the centerpiece of its Linux driver architecture in the future, this switch will become more important in the coming months for Linux support.

**Comment by chief1983** [comment]
This has already been the long term goal I believe.  It would also greatly improve overall Mac support.

**Comment by asarium** [comment]
Using the OpenGL Core Profile is something that we want to do but we only have one member with OpenGL experience (@SamuelCho). We will also have to support two different code paths, one using the fixed-function pipeline (probably with an OpenGL 1 context) and one using the Core profile. That requires additional effort but we need it to support low-end systems or systems that don't support the extensions we need.

**Comment by Echelon9** [comment]
I agree this is an enhancement we should pursue; with the right resources available to actually make it happen (i.e. might take time).

**Comment by SamuelCho** [comment]
All I can say is that I'm working on it and it's definitely planned. I've done a lot of reworking how we interface with Freespace's graphics calls in my materials_progress branch. What should result is something cleaner and much more flexible which will make a Core transition much less unwieldy than if we were to attempt it now.

**Comment by asarium** [comment]
This has been resolved by #844.
