### ISSUE TITLE
Controlconfigdefaults warning using new `Bind` option in the table

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#5113]
Entry with using Keyboard type in `Controlconfigdefaults.tbl` such as this
```
    $Bind: TOGGLE_HUD_CONTRAST
        $Primary:
            $Controller: CID_KEYBOARD
            $Flags: NONE
            $Input: KEY_K
        $Category: SHIP_TAB
        $Has XStr: 611
```

Will cause a warning in debug builds:
```
controlconfigdefaults.tbl: Warning: Unknown flags passed to config item 104, ignoring: 
'NONE'
```

EDIT: Will be fixed by #5114.

**Comment by z64555** [comment]
`controlsconfigcommon.cpp::stuff_CCF()` isn't recognizing the "NONE" keyword passed to `$Flags:`

Working on a fix, PR should be ready shortly.
