### ISSUE TITLE
Primary weapon selection with "no primary linking" weapons is a bit awkward.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5124]
When you have a ship with two primary weapon banks, and in one bank have a weapon that can not be "primary linked", switching between those banks takes longer then it should.

As an example, take the UEF Ans... Ainsara..... Ansair... Stealth ship in BP2-21 (Her Finest Hour). By default this has an ammo pack and Sidhe equipped. However, if you want to switch between primary banks, it'll select the Sidhe twice before switching to the ammo pack. This seems to be because the game is switching between three states:
Primary bank 1
Primary bank 2
All Primary Banks

even though "All Primary Banks" is identical to having only Primary Bank 1 selected.

For the sake of convenience, It would be easier if the game would just skip that last stage and go straight back to primary bank 1.

**Comment by MjnMixael** [comment]
If you have a ship with three primary banks and only one has No Primary Linking, does it link fire the other two?

I'm thinking a simple check here would be if two more more banks can link, then do All Primary Banks... else skip back to Primary Bank 1.

**Comment by MoerasGrizzly** [comment]
> 

It does fire the other two yes (though for some reason, the lead indicator still treats the non-firing bank as having been selected).

I think the proposed check would work wonders already.

**Comment by MjnMixael** [comment]
The lead indicator stuff is a totally separate bug and from what kiloku is saying, it's not simple to fix. This, however might be. I haven't looked at the code yet but I will this weekend.
