### ISSUE TITLE
FR: "Always detonate at end of lifetime" flag for weapons.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5147]
atm the MVPs (and BP) use a table trick to let primary weapons "fizzle out" when they reach their max range.
By setting 
$Detonation Range: to the max range of the weapon
and
$lifetime: to something higher then it was so that it reaches $detonation range before the lifetime runs out.

However, this trick can cause some timing issues, as well as issues when the "weapons inherit weapon velocity" flag is also set.

Would propose a flag instead,  something like "terminal explosion" or what have you (i'm bad at names ok), that simply detonates the primary weapon when it reaches the end of its lifetime, like secondary weapons do.

**Comment by MoerasGrizzly** [comment]
Added in 23.2

**Comment by Goober5000** [comment]
Linking to #5528
