### ISSUE TITLE
It may be useful for SCPUI to know when FSO gets or loses focus

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#5164]
SCPUI scripts continue to run even if FSO has lost focus. In most cases this isn't an issue, but I have one where it does matter.

Seems like this may be simple to implement. Start with `gr_activate()` in 2d.cpp line 1694. Current plan is `ba.hasFocus` that returns true or false based on `gr_activate`.

**Comment by EatThePath** [comment]
If that's being exposed it might be a good idea to expose the status of the 'no unfocused pause' cmdline flag at the same time

**Comment by MjnMixael** [comment]
> If that's being exposed it might be a good idea to expose the status of the 'no unfocused pause' cmdline flag at the same time

Do you have an actual use case for that?
