### ISSUE TITLE
AI ignores missile flags in certain situations.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5166]
Behaviour observed both in RC6 and current nightly:

Launch FSBlue's SM2-02.
Notice that Scout 1 is getting Trebuchets fired at it. This should not happen due to the presence of the "Bomber+" flag.

Also, when playing that mission further, notice that the SB Taurvi's are launching cyclops bombs at fighter craft.

Notably, was not able to reproduce this bug on the MVP's SM2-02, making me suspect that the behaviour is tied to the "$smart secondary weapon selection:" flag.

**Comment by MageKing17** [comment]
Possibly related to #5151 (and #5153, and even #5156), which made it impossible for the AI to "unselect" a secondary weapon if none were valid for the current situation; presumably, the AI makes no such checks before *firing* secondaries.
