### ISSUE TITLE
New CTD without error message in 23.0.0 RC7 due to custom script

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#5172]
[16.txt](https://github.com/scp-fs2open/fs2open.github.com/files/10673615/16.txt)
Please see attached file, line 1808.
FREDing error in a mission using a custom script (WookieeJedi's movement script in Solaris) by duplicating a sexp script call causes a CTD without error message. 
Previously this was ignored. 
Not sure if crash is new engine behaviour or from newer versions of WookieeJedi's script.

Concern is not because of crash (which just needs conscientious FRED practice to avoid) but lack of error message.

Debug log https://fsnebula.org/log/63e216ff7b290af55dccee88
Custom script can be found for reference \Solaris-2.0.*\slrs-scripts\data\tables movements-sct.tbm & movements-sexp.tbm

**Comment by wookieejedi** [comment]
Thanks for the report, I'll investigate!
