### ISSUE TITLE
FSO allows mouse wheel to be bound, but does not recognize inputs when flying.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5206]
You can bind the scroll wheel to anything in FSO's controls, but trying to use that control doesn't do anything.
Steps to reproduce Bind scroll wheel to throttle up/throttle down or primary select forward/backward, and notice how the configuration screen recognizes your inputs, but your fighter does not.

**Comment by z64555** [comment]
Known issue, as of  #2848 or earlier.  Simply put, the engine doesn't know how to handle momentary trigger inputs that well for every control, and the issue is probably aggravated by having a higher frame-rate.

Hopefully it will be handled Soon(TM)
