### ISSUE TITLE
Without -fullscreen_window or -window after getting warning in F3 Lab imgui becomes unclickable

### ISSUE THREAD

**Issue by tomimaki** [scp-fs2open/fs2open.github.com#5216]
Current build.
Example: select debug build and retail. Go to F3 Lab and select Boadicea, then press continue on warning, then go back to game and try to select some other model or anything.

**Comment by z64555** [comment]
Unable to reproduce.  We have some new lab code done by The_E that may have fixed it as a side effect.  Please try again with 23.0 build or newer.

**Comment by tomimaki** [comment]
I still can reproduce it on 20230404 build.
But probably I know why you can't reproduce it. Try without -fullscreen_window.

**Comment by MjnMixael** [comment]
I actually just ran into this a couple days ago.

**Comment by tomimaki** [comment]
At least for me fixed between 24.0.2 and 24.2, so I close this.
