### ISSUE TITLE
FR: make per-mission "Player starts in chase view" a toggle instead?

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#5226]
FRED currently has a "Player starts in chase view" mission flag in the mission specs window, but for mods  with  
"$Player starts in third person/chase view by default: TRUE" 
in game_settings.tbl there's no similar function for player starting in first person/cockpit view.
Would it be possible to have the feature a toggle? Or implement a similar flag for first person?

![fred](https://user-images.githubusercontent.com/47288956/222699641-e0afd6df-a2a4-47aa-b97d-20f98205477a.JPG)

**Comment by Goober5000** [comment]
Yes, this should be as simple as changing the "No Debriefing" to "Toggle Debriefing" flag was.

**Comment by Goober5000** [comment]
Implemented in #5312
