### ISSUE TITLE
More XSTR entries

### ISSUE THREAD

**Issue by Achille44** [scp-fs2open/fs2open.github.com#5227]
Please could you replace the following hardcoded texts with XSTR entries?
- controlsconfigcommon.cpp (l.646): strcat_s(text, " or ");
- controlsconfigcommon.cpp (l.656): strcpy_s(text, "None");

I also found an harcoded text in the case of 'transfer-cargo' sexp: the cargo of the first ship becomes "Nothing" (hardcoded) after the transfer. I guess the required modification involves the function sexp_transfer_cargo (sexp.cpp) but I am not sure where exactly.

**Comment by Goober5000** [comment]
Can do.

**Comment by Goober5000** [comment]
Hmm.  As for the "nothing" cargo, this is hardcoded to always display the English "Nothing".  The code uses NOX, which means No-X, i.e. No XSTR.

**Comment by Goober5000** [comment]
I found a way around that though.  PR incoming.
