### ISSUE TITLE
FR: weapon flag for missiles/bombs to be unaffected by countermeasures

### ISSUE THREAD

**Issue by skdKitsune** [scp-fs2open/fs2open.github.com#5265]
Mainly for usage on bombs. 
It never felt right to me that bombs are affected by countermeasures, but it would be a great option to have in general.

**Comment by z64555** [comment]
From a technical standpoint, guided bombs are not much more than very slow moving missiles, so there's no reason a countermeasure should not attract bombs to it.

Gameplay, however... we've seen that the primary means of bomb interception is to send a fighter after it  or have the capships try to shoot down the bombs, making fighter-dropped countermeasures seem like a bad "lifehack" joke.

**Comment by skdKitsune** [comment]
True, I know. However there are some mods that use modified countermeasures (like the aurora flare in BP) and I've found out that you can just pop one of these in a skirmish with bombers and most if not all bombs in a nearby volley would just get redirected. 
It is niche ofc, but for me it just seems counter-intuitive that bombs are in any way impacted by cm's.
