### ISSUE TITLE
Feature Request: Allow for re-arm/re-pair to have new types of triggers

### ISSUE THREAD

**Issue by JohnAFernandez** [scp-fs2open/fs2open.github.com#5269]
Probably could be done via sexp, perhaps named `force-rearm` and `abort-rearm`, with parameters to set custom messages and set a specific start time.  The purpose of this is to allow mission designers and modders to give the player alternate rearm methods, like landing in a fighter bay, where the modder also wants to keep the normal hud gauges, sound effects, and message triggers.

I'll add that mission designers should be able to use it independently of dock status, to maximize usefulness.

This is specifically requested by Freespace Green, as part of his push to increase immersion.

**Comment by SerialMascot** [comment]
RE: built in support message. It might be complicated to include the message, which would obviously be tied to a specific ship, The unmodded default retail support message would also get in the way for a modder using this _not_ during docking. It should be fine to leave that out completely, and a message can be added in the editor if desired. Aside from the message, the other effects that take place during the repair sequence are the ones that are difficult to replicate with other actions.

**Comment by MjnMixael** [comment]
I have force-rearm working. I'm out for the weekend. Will do abort-rearm next week, then put up a PR.
