### ISSUE TITLE
g3_draw_sphere_ez isn't suitable for debugging

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#527]
I wanted to use this function to draw spheres for debugging purposes.  It would be nice to visually confirm that I'm getting coordinates to line up properly.  Unfortunately, the spheres aren't being displayed.

I posted the following test code and @DahBlount thinks it should work:

```
bool do_g3 = (G3_count < 1);

if (do_g3)
    g3_start_frame(1);

gr_set_color(128, 128, 128);
g3_draw_sphere_ez(&vmd_zero_vector, 50.0f);

if (do_g3)
    g3_end_frame();
```

(Note: if `g3_start_frame` and `g3_end_frame` are not included, the engine will crash with an Assert since `G3_count` is 0.)

Any ideas?

EDIT: I'll amend the issue.  The function works perfectly if it's added somewhere in the graphics render pipeline (e.g. if the waypoint render functions are uncommented in `obj_queue_render`) but it doesn't work if you just plop it in a random function using this test code.  So I'll amend this issue: how can this function be used for debugging?  Is there other wrapper code that could be used?  It looks like `g3_start_frame` and `g3_end_frame` are not sufficient.

**Comment by EatThePath** [comment]
Seems like the thing to do here would be to do like lights do, have a vector of debug spheres/other that is filled by a function called from regular gameplay, read during the graphics pipeline to build the spheres, the clear that vector to be refilled during the next frame. 

I'm assuming, anyway. I would need to poke more at it.

**Comment by Goober5000** [comment]
@Kiloku Do you have any insight into this issue based on your recent work with drawing lines in scripting?

**Comment by Goober5000** [comment]
Hang on, looks like #3769 satisfies this.

**Comment by EatThePath** [comment]
Small followup comment to that implementation : g3_draw_sphere_ez is kind of visually crap and there's a lot of room for improvement. I think the way debug spheres are implemented leaves room for that improvement if someone wants to come along at any point and replace the current drawing with something else
