### ISSUE TITLE
FR: Additional live-debris options.

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#5278]
Three hopefully minor requests: (in descending order of priority)

- [x] A table option to allow live-debris spawned by a destroyed subsystem to collide with the ship that the subsystem was a part of. 
(this please)

- [x] A game setting or mission setting to make Asteroids and Ship Debris / Live-Debris affected by weapon mass (IE: pushed by weapons)

- [x] A way to multiply (by percentage) the mass value of live-debris and/or ship debris. In the case of live-debris, it should be by-subsystem.

**Comment by Baezon** [comment]
Apparently, #1 is already a thing1

**Comment by MjnMixael** [comment]
This is complete, now, right?

**Comment by Baezon** [comment]
Yep! Forgot to close it.
