### ISSUE TITLE
FR: Force afterburn on AI orders 

### ISSUE THREAD

**Issue by Kanangus** [scp-fs2open/fs2open.github.com#5303]
As per discussion with Asteroth, this is a request for two additional arguments to AI orders.

The first arg is true/false bool for whether or not the AI uses afterburners to close distance to a target during an order, such as waypoints or destroy target.

The second is a defined radius around the target in which the AI should not use afterburners while executing the order.

This is a balance critical active mod request.

**Comment by Baezon** [comment]
Less keen on the whole 'defined radius' bit. The AI is going to have a lot of things to consider whether or not to continue afterburning. IMO, this should be specifically 'when closing the distance to your goal, afterburn as hard as possible'. "Closing the distance" can involve quite a bit of logic that would be best handled internally, it's a bit too 'micromanagey' of the AI.

**Comment by Kanangus** [comment]
> Less keen on the whole 'defined radius' bit. The AI is going to have a lot of things to consider whether or not to continue afterburning. IMO, this should be specifically 'when closing the distance to your goal, afterburn as hard as possible'. "Closing the distance" can involve quite a bit of logic that would be best handled internally, it's a bit too 'micromanagey' of the AI to try to explicitly give distances.
> 
> EDIT: And can could be simulated well enough, if the FREDder is really set on it, by simply giving the order again with or without the first flag.

This sounds good, wasn’t clear on the internals of AI goal code.
