### ISSUE TITLE
FR: better handling of "point to" feature for orientation editor in FRED

### ISSUE THREAD

**Issue by Kanangus** [scp-fs2open/fs2open.github.com#5356]
Current implementation of the "point to" feature requires the developer to needlessly check a box when simply selecting a ship in the Object: field should suffice. Object: field also requires developers to pick from a dropdown menu instead of typing in a name, this makes things extremely clunky in object-dense missions. Alternate solution would be a point-and-click selection method for determining the object the ship(s) should be oriented to.

**Comment by Goober5000** [comment]
Turns out that the dropdown doesn't support text input, and point-and-click isn't really workable, but the rest can be done
