### ISSUE TITLE
Location of arrrrwalktheplank ship spawn (Volition Bravos) influenced by prop ships.

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#5357]
In missions with very large ship props (e.g. "ships" with rotating pofs for use as moving backgrounds, such as the asteroid background in BTRL) the spawn location for Volition Bravos is set very far away from the player as seen in the picture.
![screen0161](https://user-images.githubusercontent.com/47288956/233374435-779901bd-f50d-4d60-9a21-8fedcb1fba80.jpg)

Reproduceable in Solaris, missions 1-3 & 5.fs2. Removing the prop background object (Astlayer.pof) makes VB warp in closer. 
In other missions, Volition Bravos appears as expected, near the player.

**Comment by MjnMixael** [comment]
I looked at this briefly. The cheat ship spawning function uses `prevent_spawning_collision()` from multi_respawn.cpp after originally setting it to a random position within 700m of the player. Hard to say why it moved the ship 245km before deciding it was safe to spawn...

That said, the comments in the code for calling in a cheat ship say it uses the same method as calling in a support ship. But that's not true as best I can tell. Calling in a support ship, found on line 8331 of missionparse.cpp does not use the collision check from multi_respawn.cpp and instead tries to spawn the ship in front of the player. Best I can tell it doesn't do any collision checks outside of a ray cast to see if there's anything between the spawn and the player.

**Comment by Goober5000** [comment]
I tried testing this with the latest code on Solaris 2.0.25, but I encountered a number of warnings culminating in an assert crash:
```
Assert: "handle >= 0"
File: bmpman.cpp
Line: 113
Invalid handle -1 passed to bm_get_slot!

ntdll.dll! NtWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! SCP_DumpStack + 382 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! dump_stacktrace + 61 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! os::dialogs::AssertMessage + 637 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! bm_get_slot + 60 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! bm_get_entry + 27 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! bm_get_info + 56 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! gr_aabitmap + 130 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! HudGauge::renderBitmap + 556 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! HudGauge::renderBitmap + 65 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! HudGaugeReticle::render + 1192 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! hud_render_gauges + 1194 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! hud_render_all + 16 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! game_render_hud + 112 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! game_frame + 1519 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! game_do_frame + 183 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! game_do_state + 410 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! gameseq_process_events + 250 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! game_main + 604 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! SDL_main + 359 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! main_getcmdline + 245 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! invoke_main + 50 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! __scrt_common_main_seh + 302 bytes
fs2_open_23_1_0_x64_AVX2-DEBUG.exe! __scrt_common_main + 14 bytes
[...]
```
It looks like this is caused by some missing HUD graphics.

**Comment by Goober5000** [comment]
That said, the actual *bug* appears to be caused by the spawn code not checking whether the object is no-collide.  The bounding box of AstLayer.pof is large enough to plausibly put the Volition Bravos that far away.
