### ISSUE TITLE
FRED Background Editor Warnings

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#5390]
I don't know where this bug is being created, but it's annoying and FRED needs to chill.

I have mission files made using the old background coordinate system. Newer FRED will convert those coordinates to a 0-359 setup. Bank is greyed out for suns. In some cases, converted Bank coordinates for suns can have a >359 value which FRED will warn about every time you click on something. But you can't change the value because the field is greyed out.

If bank is unused in the new coordinate system, then it should be zero'd automatically.

**Comment by Goober5000** [comment]
Can you provide an example background where this happens?  The math used in the angle conversion should prevent any angle from ever being >359, which implies that there may be a second, hidden bug here.

**Comment by Goober5000** [comment]
It turns out the good old FRED tutorial mission, Peter Drake's Shipyard, exhibits this error.  File attached.
[shipyard-completed.txt](https://github.com/scp-fs2open/fs2open.github.com/files/11748435/shipyard-completed.txt)
