### ISSUE TITLE
Nightmare speed docking between two Elysium transports

### ISSUE THREAD

**Issue by Vrets** [scp-fs2open/fs2open.github.com#5395]
Elysium transport (docker) docking with other Elysium transport (dockee) moves at "Nightmare speed" (~150 m/s). Docker will move at nightmare speed until reach start of apparent dock path with dockee ship.
[nightmareSpeedTransports.zip](https://github.com/scp-fs2open/fs2open.github.com/files/11413681/nightmareSpeedTransports.zip)

**Comment by Goober5000** [comment]
This was reported fixed on Discord by @Baezon:
> the 'nightmare speed' elysium docking was caused by its docking bay pointing to the wrong path
