### ISSUE TITLE
#Default Profile in lighting_profiles.tbl doesn't work in current (22-5-2023) nightly.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5416]
As per title.

To reproduce:
Load Knossos's BPC with latest nightly
note how lighting settings in the F3 lab (And indeed anywhere) are set to FSO's default rather then BP's lighting_profiles.tbl definition.

**Comment by EatThePath** [comment]
I have some ideas on how this is happening, should be able to work on it sometime today or tomorrow.
