### ISSUE TITLE
FR: hook for when comms menu is toggled

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#5420]
Wondering if it's possible to have a e.g. sexp be able to check if the comms menu is open. Got some ideas about getting better use out of the comms menu by using time compression to slow the game down for the player to set complicated wingman orders without worrying about gameplay.

**Comment by Goober5000** [comment]
The `hu.isCommMenuOpen()` function will check if the menu is open, but the hooks in #5425 will allow scripting functions to respond to opening and closing.

**Comment by Goober5000** [comment]
Implemented in #5425.
