### ISSUE TITLE
qtFRED does not correctly get custom hud gauges

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#5422]
suspect whoever added custom hud gauges as their own sexp a while back never bothered to update qtFRED

**Comment by Goober5000** [comment]
Are you referring to the sexp argument dropdown, or something else?

Looking at `get_listing_opf_builtin_hud_gauge` and `get_listing_opf_custom_hud_gauge`, the qtFRED versions don't have the latest deduplication code, but they still iterate through the proper gauge lists.

**Comment by Goober5000** [comment]
The description doesn't leave much to go on, but launching qtFRED shows that the sexp argument dropdown for hud gauges is indeed empty.

Investigation shows that this is not due to any sexp, but rather due to a missing part of qtFRED's initialization.  I'll have a PR up momentarily.
