### ISSUE TITLE
Add Timestamp Check to Friendly Wing Arrival Messages

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#5427]
Currently there is not timestamp check for sending Friendly Arrival Messages for Wings (though there is for Hostile Arrival Wings). So, if two or more wings arrive at the exact same time then multiple overlapping arrival message will be sent.

EDIT:
@naomimyselfandi has kindly stated she is interested in creating a fix for this issue, which is very appreciated!

**Comment by naomimyselfandi** [comment]
I don't believe this is a new issue, but rather that it was largely invisible until now. FotG has a somewhat unique relationship to arrival messages - it _doesn't_ use the standard wing names,  _does_ have voiced personae, and recently turned on the new flag that allows `Backup` messages to play.

(She/her, but thank you for not assuming!)
