### ISSUE TITLE
Strange lighting artefact. NVIDIA driver bug?

### ISSUE THREAD

**Issue by dariusbei** [scp-fs2open/fs2open.github.com#5430]
Illustrated with this video. https://www.youtube.com/watch?v=e5HpH2XuKSI&
Reproduceable with Solaris 2.2.0 on knossos, mission 15.fs2 in the Black Sun campaign.

First noticed when upgraded NVIDIA drivers. Artefacts seems to disappear with the February 2023 GeForce RTX 3070 drivers.
https://www.nvidia.com/en-gb/drivers/results/199863/

**Comment by The-E** [comment]
Yeah, this is the driver bug that we've been warning people about since it first appeared.
