### ISSUE TITLE
Inferno Alliance crash on mission loading screen

### ISSUE THREAD

**Issue by genafloo** [scp-fs2open/fs2open.github.com#5447]
Loading up the second mission of the campaign the game crashes on me.

as per usual the log is here:

https://fsnebula.org/log/647d503fd83e4820edb2e1c5

**Comment by Goober5000** [comment]
Confirmed.  The crash occurs while realigning the BSP tree for the INF_Antaeus model.

**Comment by genafloo** [comment]
any idea if there could be a possible fix to this? the mod and possibly others might be unplayable..

**Comment by Goober5000** [comment]
@Shivansps and @Baezon have been working on the problem.  You can see the results at #5450

**Comment by genafloo** [comment]
I'm quite new to github not really used to it- if possible could you guide me or let me know if its finished?

**Comment by Goober5000** [comment]
It's finished and merged.  The fix will be available in the next nightly build generated after the timestamp of my post.

**Comment by genafloo** [comment]
very much appreciated!
