### ISSUE TITLE
AI flies circles when ordered to attack subsystems in some cases when using `$improved subsystem attack pathing`

### ISSUE THREAD

**Issue by wookieejedi** [scp-fs2open/fs2open.github.com#5453]
When using `$improved subsystem attack pathing` there are documented cases of AI not attacking the subsystem and instead flying in circles. Examples from Discord copied below:

Example 1:
[https://youtube.com/watch?v=TYG5wxwneH0&feature=share9](url)
`4:45 I give gamma an order to take out a turret`
`4:56 you can see gamma flying randomly in circles`

Example 2:
[https://youtube.com/live/r9C7wucfd5I?feature=share9](url)
`2:42:30 Joe gives his wingmen the order to take out a weapons subsystem, the wingmen are also flying around in circles`

**Comment by dariusbei** [comment]
Please find attached example mission using Solaris 2.2.0
[AI_test_5453.txt](https://github.com/scp-fs2open/fs2open.github.com/files/11683381/AI_test_5453.txt)
