### ISSUE TITLE
Containers marked "Save on mission close" don't persist between missions

### ISSUE THREAD

**Issue by dilmahg** [scp-fs2open/fs2open.github.com#5458]
While developing a two mission campaign, I created a map container with a single key/value combination with persistence option set to "Save on mission close" in the first mission. This data is unavailable in the second mission, even after confirming identical container names and persistence settings. Confirmed that data is unavailable using an "is-container-empty" sexp in mission 2.

**Comment by jg18** [comment]
Thanks for filing this.

Does the issue occur with list containers?

Does the issue occur with containers marked "save on mission close" and/or "eternal"?

**Comment by jg18** [comment]
@dilmahg I'm having trouble reproducing this issue. See attached test campaign.

The messages that are sent in the second mission use the values from the first mission. I included a persistent variable as an experimental control.

[issue_5458.fc2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/11772396/issue_5458.fc2.txt)
[issue_5458_1.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/11772397/issue_5458_1.fs2.txt)
[issue_5458_2.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/11772398/issue_5458_2.fs2.txt)

**Comment by dilmahg** [comment]
Hey @jg18, I just had a look at those two and realised I forgot to mention a crucial detail - I was using the sexp "add-to-map" to add the first key/value combination to the map container in the first mission. I created the map container itself using the "Add/Modify Container" dialogue with the data type as "string" and key type as "string" too, but didn't give it any key/value combinations. 

Are you able to reproduce the issue using a sexp to add the key/value combination?

**Comment by dilmahg** [comment]
Okay, I fixed it @jg18! By changing the containers to "save on mission complete", it worked. If you're happy, I can add that little tidbit to the wiki so people learn from my mistakes?

**Comment by jg18** [comment]
Closing this issue as resolved. If someone finds a problem with container persistence in the future, please file a new issue instead of posting here, so that the discussions don't get mixed up. Thanks!

**Comment by jg18** [comment]
Oh, so there really *is* an issue here. "Save On Mission Complete" works as expected, but "Save On Mission Close" doesn't. Reopening with updated title.

**Comment by jg18** [comment]
Fixed with PR #5463.
