### ISSUE TITLE
FRED allows for saving missions with filenames that are too long

### ISSUE THREAD

**Issue by jg18** [scp-fs2open/fs2open.github.com#5459]
It seems that FRED doesn't check when saving a mission whether the mission file name is too long.

The maximum file name is 31 chars (`MAX_FILENAME_LEN` - 1) *including* the ".fs2" extension.

The result is a crash when opening the Campaign Editor, specifically in `get_mission_info()` in missionparse.cpp, in the call to `strcat_s()`.

IMO FRED should refuse to save a mission if the FREDder specifies a file name that is too long.

**Comment by Goober5000** [comment]
I'm not sure if it should refuse to save with a too-long message... but it should certainly not crash when accessing one.  I'll have a PR up shortly.

**Comment by Goober5000** [comment]
Turns out the file length is actually not a design restriction in this case.

**Comment by qazwsxal** [comment]
As mentioned on the linked PR, filenames longer than 32 chars can't be packed into VPs, so ideally there would be a warning on save about this limitation.

**Comment by Goober5000** [comment]
This has now been done on the linked PR.
