### ISSUE TITLE
Issue with Framebuffer Effects in Nebula

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#5460]
(example image attached)
![fbimage](https://github.com/scp-fs2open/fs2open.github.com/assets/86627340/149915f2-f4d2-400f-8208-c9766e30c56e)

As of all builds made within the past few months, setting the "framebuffer thrusters" and/or "framebuffer shockwaves" flags on will cause the distorted area to interfere with the nebula clouds, what's visible behind the effect ends up looking similar to how it would look if Post-processing was turned off in a nebula. IE: black effects at long distance. 

This occurs in the MVPs, but not Retail nebulae. as far As I can tell, there are no ill effects when on a non-nebula mission.

**Comment by TRBlount** [comment]
What hardware and drivers are you currently using? Recent Nvidia drivers have been causing problems and I wonder if this could be related.

**Comment by DefCynodont** [comment]
Nvidia GeForce GTX 950, 
Driver is 31.0.15.1694 (7/21/2022)
Windows 10

**Comment by DefCynodont** [comment]
Xenocartographer has just confirmed that the issue also occurs on her machine.
