### ISSUE TITLE
Bug(CTD):  adjusted AI class autoscale with a single autoscaling AI class

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#5474]
A minimal repro has not been constructed, but it appears that if the `use adjusted AI class autoscale` aip feature is on and all but one ai class has `$Autoscale by AI Class Index: NO` then a divide by zero exception can occur in `aicode.cpp:13118 in ai_manage_shield()`

**Comment by Goober5000** [comment]
Here is Woolie Wool's test table:
[ai.tbl.txt](https://github.com/scp-fs2open/fs2open.github.com/files/12065401/ai.tbl.txt)
