### ISSUE TITLE
subtle but concerning change in ship behavior.

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#5478]
In a mission with just me and a wing of bombers I use for testing something unrelated, the bombers always cruise around at low speed with occasional turns. I have confirmed with both 23.0 and 21.0 that this is consistent behavior. In latest nightlies, they just come to a stop immediately and park. 

Testing mission: [idle_test.zip](https://github.com/scp-fs2open/fs2open.github.com/files/11931588/idle_test.zip)

This seems like the kind of change that can have a lot of subtle ripple effects for old missions. I haven't bisected exactly when in this dev cycle it changed.

**Comment by Goober5000** [comment]
Bisection points to 41e338e8abcae1c212d36e3b9f8bff02247de8ef as the first bad commit, but that doesn't make sense...

**Comment by Goober5000** [comment]
Oh bleh, it was an inverted boolean check.  PR incoming...
