### ISSUE TITLE
FRED: Team Loadout Editor Issues/Bugs

### ISSUE THREAD

**Issue by LuytenKy** [scp-fs2open/fs2open.github.com#5494]
The first primary issue is that the FRED Team Loadout Editor has UI glitches that occur due to poorly formatted UI elements, primarily the checkboxes. Additionally, FRED randomly reassigns boxes that have already been unchecked.

The checkboxes are placed differently in the original version of FreeSpace, In such a way that they are spread apart from each other to avoid overlapping.

This is how it's displayed in the original.
![OG Loadout](https://github.com/scp-fs2open/fs2open.github.com/assets/135379429/517d6fd7-b0cb-4a51-b2da-179d539c61bb)

And this is how it's displayed in FSO, unchecking the boxes causes overlapping.
![FSO TeamLoadout](https://github.com/scp-fs2open/fs2open.github.com/assets/135379429/a46a4e45-8620-454c-93f4-7f5deffefafa)

A possible fix for this issue is to rearrange the checkboxes to avoid overlapping.

All versions of FreeSpace including the original have a bug in which the checkboxes are randomly rechecked after they have already been unchecked.

Note that the number of reassigned boxes may differ.

To recreate it, create a new FRED mission, go to the Team Loadout editor, uncheck all boxes, click Ok, reopen the Team Loadout editor, and you will see that some boxes will be reassigned again.

**Comment by Goober5000** [comment]
Hmm.  What FSO build are you using, and what operating system are you running on?  The checkboxes do not overlap for me running the latest nightly on Windows 11.

**Comment by Goober5000** [comment]
I've confirmed the random weapon selection bug though.

**Comment by Goober5000** [comment]
This is proving rather tricky to track down.  There are a lot of interlinked dependencies and spaghetti logic.  I'm going to focus on other tasks for the time being.

**Comment by LuytenKy** [comment]
> Hmm. What FSO build are you using, and what operating system are you running on? The checkboxes do not overlap for me running the latest nightly on Windows 11.

I'm using FSO 23.0.0, With Windows 10.

**Comment by Goober5000** [comment]
Well I may have figured this out while working on a different bugfix.

**Comment by Goober5000** [comment]
Fixed via #5817 and #5819
