### ISSUE TITLE
Detonate-on-death flag for weapons

### ISSUE THREAD

**Issue by Kestrellius** [scp-fs2open/fs2open.github.com#5521]
Weapons spawning their hit effects when they run out of life rather than just disappearing is pretty. This can be done using $Detonation Range.

However, setting the $Detonation Range to a value equal to the weapon's maximum range (such that it detonates during the same frame in which it dies) will cause the effect to only spawn sometimes, probably because the order in which weapon-killing and effect-spawning occur is nondeterministic. In order to get reliable behavior, one must increase the lifetime of the weapon slightly.

In complex table-stack situations, such as are common with the MediaVPs, this can result in unexpected overrides and bugs.

The best solution to this problem is a simple flag one can add to a weapon which causes it to always detonate when its life runs out.

**Comment by MoerasGrizzly** [comment]
I would love this feature.

**Comment by Goober5000** [comment]
Upon further investigation, this is actually not nondeterministic behavior: weapons *always* detonate when they reach the end of their lifetime... but only if they are secondary weapons.  The effects in question are all for primary weapons.
