### ISSUE TITLE
Bug: hud-set-coords lacks resolution scaling

### ISSUE THREAD

**Issue by Kanangus** [scp-fs2open/fs2open.github.com#5525]
hud-set-coords takes two numbers for the X and Y axis and is resolution-agnostic, meaning the sexp can presently only be set for one resolution.

Solutions here would be to switch to a scalar percentage system from screen center, or my preferred option is to allow fredders to set different offsets as they function presently for different resolutions, eg

Hud-Gauge-Name
Resolution 1
X
Y
Resolution 2
X
Y

Etc

**Comment by Goober5000** [comment]
The scaling system used for `show-subtitle` works pretty well, so I'll add a similar option for `hud-set-coords`.
