### ISSUE TITLE
Bug: Primary weapon linking edge cases

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5529]
[Testcase_2.zip](https://github.com/scp-fs2open/fs2open.github.com/files/12209380/Testcase_2.zip)

This is kinda hard to explain so here goes:
If you have a ship with one or two ammo weapons.
And one of those weapons can not be selected along with the others.
If that last weapon can no longer be selected, the player can also not link their two remaining primary weapons.

As an example, I've included a "test case" mission. It's designed to be run in Blue Planet Complete (the version that is on knossos).
To reproduce:
1) Shoot your primary weapons for a bit.
2) Use the supplied ammo pack
3) Swap your primary weapons a bunch of times and notice that they'll no longer link reliably.

Bug is present both in RC and last stable.

**Comment by Goober5000** [comment]
I confirmed this bug; it's fairly well contained inside `ship_select_next_primary`.  Fixing it would require a bit more than a simple change though; the function would need to be refactored.  This can be done, but probably not before the stable release.
