### ISSUE TITLE
FR: "Default Unavailable" flag for "player allowed" flagged weapons

### ISSUE THREAD

**Issue by Durandal-Thoth** [scp-fs2open/fs2open.github.com#5552]
All weapons flagged with "player allowed" are presently available by default in the loadout pool in FRED. More often than not this is a hindrance, especially earlier on in campaigns when most tech is unavailable, or when a weapon is used only once or twice in a campaign.

"player allowed" flagged weapons would check for the "default unavailable" flag, and if it is present, not default to available in the loadout pool.

**Comment by MjnMixael** [comment]
There seems to actually be precedent for this. Ships have "default_player_ship". So probably a "default_player_weapon" would be more inline with the other code. The inverse of what you asked for but same functionality.
