### ISSUE TITLE
RC8 and later: Ai wingmen refuse any order at all times

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5661]
Steps to reproduce:

1. Play a mission where you can order your wingmen
2. target a wingman - note how it has the "no orders" indicator - regardless of whatever order they were given in FRED.
3. order your wingman to guard you
4. notice how very briefly, "guard alpha 1" flashes before the craft resets to "no orders".

**Comment by wookieejedi** [comment]
Did some quick nightly testing before I had to run, looks like it only starts on yesterday's nightly 
https://www.hard-light.net/forums/index.php?topic=98972.0

**Comment by MoerasGrizzly** [comment]
https://github.com/scp-fs2open/fs2open.github.com/pull/5649
This is the only commit that touches ai code that could match the problem.

**Comment by Goober5000** [comment]
Ironically it looks like it was caused by #5658...
