### ISSUE TITLE
Virtual POF Weirdness

### ISSUE THREAD

**Issue by BMagnu** [scp-fs2open/fs2open.github.com#5672]
In very specific cirumstances, it seems possible that virtual POF can cause model glitches.
It seems to depend on the mission and what else is loaded, but I am not sure how, and it can basically create additional polygons it seems.
But it's comparably rare, as in, out of 10 missions I tried, two had these issues.

Basically, the ToDo is to trace the Add Submodel path in virtual pofs, and making sure that everything is memory safe and has no buffer overruns or anything.

**Comment by MjnMixael** [comment]
Any chance this was probably solved with #5984 ?

**Comment by BMagnu** [comment]
Good point.
It was indeed the last point of that PR,
> When replacing textures, it incremented the wrong poly count, causing potentially corrupted geometry and meshes

which ended up fixing this.
