### ISSUE TITLE
Not zipped AppImages

### ISSUE THREAD

**Issue by kenderipa** [scp-fs2open/fs2open.github.com#5682]
Hello,

short question. Could you please not zip the released AppImage? My AppImage manager cannot handle archive formats, and I'm not sure other managers can handle it.

Thanks in advance

**Comment by notimaginative** [comment]
The tarball produced for each release contains multiple AppImages, for the different build types. They aren't released individually.

Unless I misunderstand your question?

**Comment by kenderipa** [comment]
No you're not :) And I'm asking, if they could be released individually :)

**Comment by notimaginative** [comment]
Sorry, we can't really do that. Everything, from the build system to Knossos, assumes that every release is distributed as a single file. And since every release contains multiple files we have to do it as a zip/tarball.

**Comment by kenderipa** [comment]
Well, darn. Thanks for the reply.

**Comment by Goober5000** [comment]
Is there another way we might be able to solve this?  I'm not familiar with AppImage but surely most users have a way to accommodate the builds.

**Comment by notimaginative** [comment]
Yeah most Linux desktops include an archiving utility that could easily extract the tarball and give you the pair of AppImages. That or just using Knossos to deal with it all. But I'm assuming (perhaps incorrectly?) that in this instance there is some roadblock complicating the ability to do one or both of those things.

I've tried to think of a way to modify the CI setup to accommodate this but I believe the workarounds involved would be a bit too nasty and make the code much more difficult to manage.

**Comment by kenderipa** [comment]
The thing is, I'm using zap (https://github.com/srevinsaju/zap) as an AppImage manager. It easily downloads and integrates AppImage into the environment (makes executable, symlinks, icon, .desktop), but also lets update them easyly (if an rsync file is present, if not, one can easily remove the AppImange and download it again). It cannot, however, handle .zip archives. Of course, I can easily download the archived AppImages, extract them, remove the unneeded ones, make them executable, create a symlink, it's just that zap makes it all automatically.

**Comment by notimaginative** [comment]
Had a look at zap, which appears pretty nice for managing AppImages, but honestly that's really not a good way to deal with FSO. You often need multiple builds installed and even multiple types of builds installed (release and debug). It's just not a normal piece of software like zap is designed for.

What are you using to manage mods? Self install or something else?

Using something like Knossos.NET to manage your mods would also manage the builds for you, and is actually built specifically for that purpose. Knossos.NET is also a good candidate for being distributed as an AppImage once development on it stabilizes a bit.

**Comment by kenderipa** [comment]
I'm just starting with fs2open, so I'm not proficient enough for mods :)  Of course, I'll use something that makes sense for mod management in the end. However, you can install several build with zap, just select a different name for each build. And yes, I welcome the AppImage of Knossos, just don't zip it :)

**Comment by kenderipa** [comment]
Also please see https://docs.appimage.org/packaging-guide/distribution.html#do-not-put-appimages-into-other-archives

**Comment by notimaginative** [comment]
Ah, cool, didn't realize zap could install different builds! I'm actually going to have to try that thing out one of days.

I haven't worked out a better solution that having the FSO builds bundled together as they are unfortunately. Everything is just designed around it being that way. But if Knossos/Knossos.NET is used, which is really the preferred way to run the game, then that really doesn't matter since it does all of the work installing, upgrading, and managing the builds.

I have starting looking into an AppImage version of Knossos.NET however, and it will be using their recommendations for distribution and all. So on that front I believe everything will work as it should. It might be a while yet before official releases are available in AppImage format but some test AppImages of official releases should start showing up soon.

**Comment by kenderipa** [comment]
Sigh. All r8ght then, thanks for the discussion.

**Comment by kenderipa** [comment]
Should I keep the issue open? Do you need it as a reminder?
