### ISSUE TITLE
Latest builds crash with Debug Assertion Failed on Campaign Accept

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#5691]
Whenever `mission_campaign_free_list()` is run, the game now crashes with Debug Assertion Failed. #5679 looks suspect, but I'm not entirely sure.

**Comment by JohnAFernandez** [comment]
I think I see what happened.  Sorry about that.  Looks like the memory leak was a false positive and I should have checked the surrounding code more closely.

**Comment by JohnAFernandez** [comment]
Kind of disappointed with coverity, actually.  Both "memory leaks" are in fact false positives because vm_strdup also copies the pointer.
