### ISSUE TITLE
Bright top bar (window title bar?) in fullscreen occasionally

### ISSUE THREAD

**Issue by topas-rec** [scp-fs2open/fs2open.github.com#5695]
([Posted in the free space 2 forumsv previously](https://www.hard-light.net/forums/index.php?topic=98990.new) )

Hello everyone,

When I start Blue Planet or Freespace 2 (FSO) I sometimes have a bright vertical bar at the top of the game and the mouse click position is offset (vertical) for approximately the height of that bar.

It happens mostly from the first start on and requires 3-6 restarts of the game (sometimes more) to get rid of that bar.

I was able to take a screenshot and fetched a log, but I don't know how to further investigate this issue.

Does anybody know how to find the cause for this?
I use FSO 23.2.0 on arch Linux with Free space 2 installed from GOG.

Hard to see on white background of github page: a small white bar at the top
![Screenshot from 2023-10-17 08-41-08](https://github.com/scp-fs2open/fs2open.github.com/assets/20391449/d39611bb-c72a-46f1-8506-f930cf47519b)
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/13052399/fs2_open.log)

**Comment by JohnAFernandez** [comment]
Have you tried running in windowed mode (or fullscreen window)?  I have seen some minor issues in regular fullscreen before.  There's probably some small mistakes in how we use SDL

**Comment by topas-rec** [comment]
`Windowed` mode looks like fullscreen when the issue is present, except that it has window decorations (X - close button), rounded corners of the title bar and a proper title text in the window title bar:
![Screenshot from 2023-11-03 09-48-58 (windowed)](https://github.com/scp-fs2open/fs2open.github.com/assets/20391449/b122b220-dc4e-4261-85ac-1443331ca2b0)


`Borderless` or `maximized window` works without problems regarding the top bar issue, but has another problem: I use Gnome and I often hit the sticky corner when I use freespace20pen in this mode. That seems normal, since it is a maximized window - so no real issue - but not ideal as a workaround.
![Screenshot from 2023-11-03 09-51-42 (borderless - maximized window)](https://github.com/scp-fs2open/fs2open.github.com/assets/20391449/3f12ab4f-5e7c-4a6f-aafb-6a222f6a0327)

**Comment by topas-rec** [comment]
I found this issue in the SDL version of xonotic on the same system, too.
It doesn't happen that often, but it was there one or two times.

**Comment by topas-rec** [comment]
The issue seems gone.
I thought the reason is that I switched to `{lib32}-vulkan-radeon` from `{lib32}-amdvlk` ([according to the arch wiki](https://wiki.archlinux.org/title/Vulkan#Installation)). Reverting this doesn't reproduce the issue. So it might be something else. Since arch linux uses a rolling release model, an update might be the reason.

Since noone else is reporting this - I think the real reason doesn't matter.

As long as I cannot reproduce this - I'll close it. Let's hope it doesn't come back.
