### ISSUE TITLE
change-soundtrack sexp doesn't work when no music is defined in mission specs.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5705]
Issue does not occur in FSO 23.0. Does occur in 23.2 stable.
Steps to reproduce:
Open mission bp2-05 with FSO 23.2
notice a distinct lack of music.

When a soundtrack is enabled in music specifications, the sexp works as normal. Even when a completely different soundtrack is selected (I selected "Joshua"), the mission starts out with the correct music.

The bug seems to occur whenever change-soundtrack is called. If a mission starts silent or starts with a "play-sound-from-file" and then later calls a soundtrack, it also won't work.

**Comment by Goober5000** [comment]
Hmm.  This is a case of finding the right way to thread the needle for the bugfix.

**Comment by MoerasGrizzly** [comment]
> Hmm. This is a case of finding the right way to thread the needle for the bugfix.

I'm quite curious why change-soundtrack needed changing at all. Was the "Trampling all over the timing" such a big deal?

**Comment by Goober5000** [comment]
> > Hmm. This is a case of finding the right way to thread the needle for the bugfix.
> 
> I'm quite curious why change-soundtrack needed changing at all. Was the timing change such a big deal?

The bug that motivated the bugfix was encountered in a Scroll mission.  There is a default soundtrack, but under certain circumstances the soundtrack is changed.  This caused the music to start immediately instead of after the customary delay, and was somewhat jarring.
