### ISSUE TITLE
Wingmen anis are not rendered properly with current nightly.

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#5710]
![screen0002](https://github.com/scp-fs2open/fs2open.github.com/assets/9599230/f85cb700-2374-40a4-a1fd-9f98e54d4d39)
![screen0003](https://github.com/scp-fs2open/fs2open.github.com/assets/9599230/b70ab766-a851-46c0-920a-6125e07d69e4)
![screen0004](https://github.com/scp-fs2open/fs2open.github.com/assets/9599230/2fdaa180-a438-4980-b540-756c683d703e)

Seems to occur with the MVP's and BP's modified hud but not the retail FS2 one.

**Comment by Goober5000** [comment]
Interesting that it occurs with more than one HUD.  I have seen it in Vasudan Imperium too.

@BMagnu knows about this issue and has some ideas on what might be causing it.
