### ISSUE TITLE
BUG: 'Timestamp_Since' called with invallid Timestamp

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#5725]
I have a mission where I repeatedly get 'Assert: "stamp.isValid() && !stamp.isNever()"' We have ruled out any suspect scripts already, and it no SEXPs are firing when this happens, nor does it always happen every time, but when it does it's always in the same place in the mission.

A Log is attached.
[fs2_open.log](https://github.com/scp-fs2open/fs2open.github.com/files/13193782/fs2_open.log)

Any help would be appreciated.

**Comment by Goober5000** [comment]
Unfortunately the FastDebug log doesn't have a meaningful stack trace.  Are you able to generate a log from a regular Debug build?

**Comment by MjnMixael** [comment]
Relevant stack trace

Assert: "stamp.isValid() && !stamp.isNever()"
File: timer.cpp
Line: 354
timestamp_since was called with an invalid timestamp!

ntdll.dll! NtWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! dump_stacktrace + 283 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! os::dialogs::AssertMessage + 839 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! timestamp_since + 74 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! training_check_objectives + 164 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_simulation_frame + 1704 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_frame + 2187 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_do_state + 1635 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_main + 1059 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! SDL_main + 343 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! main_getcmdline + 245 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! invoke_main + 50 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! __scrt_common_main_seh + 302 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! __scrt_common_main + 14 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! WinMainCRTStartup + 14 bytes
KERNEL32.DLL! BaseThreadInitThunk + 29 bytes
ntdll.dll! RtlUserThreadStart + 40 bytes

[ This info is in the clipboard so you can paste it somewhere now ]


Use Debug to break into Debugger, Exit will close the application.

ntdll.dll! NtWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! dump_stacktrace + 283 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! os::dialogs::Error + 116 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! os::dialogs::AssertMessage + 1244 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! timestamp_since + 74 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! training_check_objectives + 164 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_simulation_frame + 1704 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_frame + 2187 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_do_state + 1635 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! game_main + 1059 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! SDL_main + 343 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! main_getcmdline + 245 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! invoke_main + 50 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! __scrt_common_main_seh + 302 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! __scrt_common_main + 14 bytes
fs2_open_23_3_0_x64_AVX2-FASTDBG.exe! WinMainCRTStartup + 14 bytes
KERNEL32.DLL! BaseThreadInitThunk + 29 bytes
ntdll.dll! RtlUserThreadStart + 40 bytes

**Comment by MjnMixael** [comment]
I dunno why Def made the sexps like this, but this is the event that triggered the assert this time around.
![image](https://github.com/scp-fs2open/fs2open.github.com/assets/7740469/962b2b3a-e393-487a-b88a-fe79f53a3a8f)

**Comment by Goober5000** [comment]
Hmm.  I wonder if this is related to the old `born_on_date` bug:
https://scp.indiegames.us/mantis/view.php?id=930

**Comment by Goober5000** [comment]
I have an idea for a fix, but I'll need to do some testing.

**Comment by Goober5000** [comment]
Fixed via #5747
