### ISSUE TITLE
Please rebreak $dumb_rotate rotation time

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#573]
https://github.com/scp-fs2open/fs2open.github.com/pull/560

Goober says he fixed a "significant bug" with $dumb_rotate, but modders have been using this feature for years (BtRL, Blue Planet, JAD, a few others I think too) and now with that fix, anything that had used it before for slow and subtle movements, are now spinning faster than a centrifuge working on uranium.

Could perhaps this be reverted and a new option, something like $dumb_rotate_sec be added so if someone wanted it in seconds, they could do it that way?

**Comment by Goober5000** [comment]
Well, phooey.  If mods already rely on the broken behavior, then you're absolutely right, it needs to be restored.  (A shame this wasn't caught before the feature was originally introduced.)

The bug itself will still need to be addressed.  I think I'll introduce new POF properties called $rotate_time and $rotate_rate, and their $dumb_ equivalents, to remove the ambiguity.

**Comment by asarium** [comment]
So instead of delaying the 3.7.4 release even more could the old behavior just be restored? The fixed options can be added at a later time.

**Comment by Goober5000** [comment]
There are also people who also rely on the fixed option.  I will have time this weekend to fix this.

**Comment by asarium** [comment]
Ok, if you have the time to fix this soon then it shouldn't be a problem.

**Comment by Goober5000** [comment]
PR opened.  I'll catch Axem on IRC tomorrow and send him a test build.

**Comment by asarium** [comment]
This was fixed in #580.
