### ISSUE TITLE
Translated Command Sender is not sending messages

### ISSUE THREAD

**Issue by NovachenFS2** [scp-fs2open/fs2open.github.com#5749]
Heyya,

in my effort to make a small update for my translation library after 18 months (time flies), i found out, that Command does not send messages in every mission in every build after 22.2.0 RC4 in every non-english translation.

After doing some research, I found out that #4440 seems to introduced a problem that $Command Sender: with a XSTR is to be recognized by the game as an invalid message source in foreign languages and thus will not play. As the debug build from 2022-06-26  is giving me following error that confirms that.

> WARNING: "Invalid message source 'Kommandozentrale'.  Unable to send message." at sexp.cpp:13356

In the mission files i am using a $Command Sender: XSTR("Command", 2046), entry, that ensures that all kind of command messages are properly send by 'Kommandozentrale' in the german translation. But the same error appears in the French translation with 'Commandement' aswell, of course.

**Comment by Goober5000** [comment]
Could you send me a mission that demonstrates this bug?  You can PM me on HLP or Discord if you want to.

**Comment by NovachenFS2** [comment]
Well, surprisingly i had problems to reproduce this bug in a new clear mission to show this error, as the messages were send by 'Command' everytime 🤔. 

But i sorted this out. Actually the problem affects event messages only, IF you use the 'Override #Command in event messages' flag.

Because during my test i could confirm, that generic command messages like "Deploying support ship now. Please stand by." actually do not have issues. They are always properly send by 'Kommandozentrale'.

I created a small mod based on retail data for this with one mission that send one event message by command. There is no error in english language, but this message does not appear if you change the language to german.

[cmdmsg.zip](https://github.com/scp-fs2open/fs2open.github.com/files/13249174/cmdmsg.zip)

**Comment by Goober5000** [comment]
Thanks.  The bug was not caused by #4440, but that change exposed a bug that had been previously hidden.  I figured out how to fix it and a PR will be up shortly.

Also my Discord ID is the same as my Github username. :)
