### ISSUE TITLE
Sticky Support Ship

### ISSUE THREAD

**Issue by TheForce172** [scp-fs2open/fs2open.github.com#5759]
Seeing [this](https://github.com/scp-fs2open/fs2open.github.com/issues/3853) or a similar bug can be consistently reproduced on final mission of Frontline 2335 FSO Version : 23.3.0-20231102

After calling support ship support ship docks and does support fine but then the Reload complete message plays twice, your ships location seems to jump and the support ship wont let go.

Telling the support ship to jumps out jumps you out and ends the mission.
Abort rearm does nothing.

Debug log : https://fsnebula.org/log/6544cf0c2250e58fbcded79e
Video https://youtu.be/Wz0GY4affYA (Bug at 0.45)

Not happening on 23.3.0-20231030, So most likely caused by #5611

**Comment by MjnMixael** [comment]
I'm betting my #5611 PR is the cause. But I'm out for 5 days or so. Someone else will have to take a look.
