### ISSUE TITLE
FR: integrating a function similar to Wookieejedi's wingman-gauge script

### ISSUE THREAD

**Issue by skdKitsune** [scp-fs2open/fs2open.github.com#5872]
Would be great to have an in-engine function to clear the wingman-gauge of wings and set new wings displayed in the gauge via sexp.

A sexp that would automatically clear completely departed or destroyed wings (no pending reinforcements) from the gauge to make room for new wings would also be very handy.

**Comment by Goober5000** [comment]
To make sure I understand the request, you want the ability to change the wings displayed on the squadron gauge on-the-fly, right?  Basically to change the "Squadron wing names" in the Custom Wing Names dialog during the mission?

**Comment by skdKitsune** [comment]
> To make sure I understand the request, you want the ability to change the wings displayed on the squadron gauge on-the-fly, right? Basically to change the "Squadron wing names" in the Custom Wing Names dialog during the mission?

Pretty much.
A good example would be the FS2 retail mission "Love the Treason...", where you start off with a filled wingman gauge, but all of them end up self-destructing. Clearing these wings out of the gauge and adding "Skull Alpha", "Skull Beta", etc to the gauge via sexp would be handy.

**Comment by Goober5000** [comment]
Implemented in #6451.
