### ISSUE TITLE
(VR) Aspect lock is too fast

### ISSUE THREAD

**Issue by Kerbrer** [scp-fs2open/fs2open.github.com#5882]
While having my missiles and bombs acquire lock at twice the speed they normally would is kind of nice, I fear it kind of trivializes everything just a bit.

**Comment by BMagnu** [comment]
This probably has to do with certain things being ticked in the GUI loop.
I thought I'd caught all of these when I divided the HUD frametime in half for VR mode (which fixed too-fast headani's for example), but it seems that did not affect everything
