### ISSUE TITLE
FR: Loadscreen fiction overlay

### ISSUE THREAD

**Issue by Durandal-Thoth** [scp-fs2open/fs2open.github.com#5897]
This is a request for an overlay graphic/textbox which can pull an entry for a mission defined in a list. Lists would be stored in the fiction folder in txt format and could contain any number of entries, of which the game will pick one on random at mission load. 

For anyone not seeing what I'm envisioning here, Attack on Titan comes to mind - technical readouts and bits of lore would be provided in a splash at a midway break during an episode. This will allow writers a good delivery system for supplementary lore which may otherwise be missed, or provide additional context for a mission. For players, it gives them something to read instead of a just a splashscreen and a loading bar to stare at.

**Comment by Durandal-Thoth** [comment]
It seems this already exists in the form of Axem's lua-loadscreen. I suppose it's worth leaving this FR up in case anyone has any desire to migrate that system from script to proper code, but it can be considered a very low priority.

**Comment by Goober5000** [comment]
Yeah this would be better handled by lua-loadscreen or something similar.  Alternatively, it might be possible with SCPUI.

Adding something like the fiction viewer would require some very specialized code for a very unusual situation.  And where one modder might want a fiction viewer, another modder might prefer an animation.

**Comment by Goober5000** [comment]
Closing as this is not suitable for implementation in code.  There are already two ways to do this via scripting.
