### ISSUE TITLE
FR: subsystem scanning that doesn't say "cargo"

### ISSUE THREAD

**Issue by jlberman** [scp-fs2open/fs2open.github.com#5922]
Currently, when a subsystem has a specific cargo assigned to it, on scan it's hardcoded to print "cargo: CARGONAME".

Request an option to not print "cargo".

**Comment by Baezon** [comment]
The text *can* be modified via strings.tbl, specifically `84, "cargo: %s"`, but this will change the text across the entire mod. I assume you were looking for something more specific to the ship/subsystem in question?

**Comment by jlberman** [comment]
Correct, I want it to just print one time.

**Comment by jlberman** [comment]
![screen0090](https://github.com/scp-fs2open/fs2open.github.com/assets/16578032/9a8b12a3-ca96-40ee-bb28-6ee2b96f43d5)
![screen0091](https://github.com/scp-fs2open/fs2open.github.com/assets/16578032/c50de736-96bc-4531-9b7f-95007c7b8ee8)

**Comment by Baezon** [comment]
For what it's worth, by overriding the string, you could still get the same effect, provided you remembered to write `cargo: ...` as the cargo for other examples which you still want to work the normal way.

**Comment by Goober5000** [comment]
There is an existing option to change what is printed; if the cargo is prefaced with a #, the string will say "passengers: ..." instead of "cargo: ...".

But if you want to remove the "cargo: " altogether, that would require some additional work.

**Comment by jlberman** [comment]
Yes, I'm looking to remove the "cargo" string entirely.

**Comment by Baezon** [comment]
Did you want to try the strings.tbl method...? I can help you with it.

**Comment by jlberman** [comment]
Nah, I can go without it for now - the strings.tbl method would break a
whole lot of other stuff in my mod, and I don't want to redo everything
from scratch.
