### ISSUE TITLE
Fred regression: FS2 save format and fixed-angles-in-mission-files flag

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#5980]
In 23.2.1 and the 20240202 nightly, selecting the FS2 Retail save format will throw frequent warning messages about the incompatibility of the fixed-angles-in-mission-files flag and the retail save format. This can be seen even on a blank new mission. The message can be triggered by many things, including but not limited to opening a file, closing the backgrounds editor, and saving the file. 

Various other edits can trigger the warning, and while i haven't isolated a cause it sometimes seems to get caught in a loop of throwing the warning in response to any and all input, including trying to close FRED. Force-killing the program seems the only escape.

The checkbox for the corrected angles format is on and turning it off is not preserved. My hunch is that this flag defaults to on without any special handling in the retail save format mode, but having any background flags enabled trips this warning, and so anything that triggers mission validation causes this.

Presumably related, opening and re-saving a retail mission, with fs2 compatibility on, seems to unavoidably scramble the background bitmaps, which seems less than ideal.

**Comment by Goober5000** [comment]
There are three separate issues here: the repeated message box, the checkbox persistence, and the save behavior.  The first one looks straightforward: the box pops up every time the mission is saved, including autosave, and for every background; so I'll just add a check to only display it once.

When you say "with fs2 compatibility on" do you mean with the retail save format selected?

**Comment by EatThePath** [comment]
> When you say "with fs2 compatibility on" do you mean with the retail save format selected?

That's correct.

**Comment by Goober5000** [comment]
Turns out the checkbox problem was an emergent bug: the persistence worked fine, but FRED cleared *all* blank backgrounds, then added a new one -- which defaulted to having the flag checked.  I'll fix that too.

Will investigate scrambling later.

**Comment by Goober5000** [comment]
Oh, the scrambling is simply because FRED is saving the backgrounds in the corrected format but without the corrected flag (hence the warning "The sun and bitmap angles will be loaded differently by previous versions").  It should be possible to re-scramble the angles though.
