### ISSUE TITLE
Containers do not return the proper numbers in eval_num

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#6029]
Test mission:
[TestEscort.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/14518847/TestEscort.fs2.txt)

There is a string-to-number map containing ships and their escort priorities.  The mission attempts to add each using `add-remove-escort`.  However, the `eval_num` function does not correctly evaluate the container, causing the value to be interpreted as an unknown string (OP_NOT_AN_OP) that evaluates to 0.

**Comment by jg18** [comment]
Fixed with PR #6031.
