### ISSUE TITLE
FR: bad-rearm-time sexp

### ISSUE THREAD

**Issue by Durandal-Thoth** [scp-fs2open/fs2open.github.com#6037]
Fairly straightforward, no equivalent for good-rearm-time exists.

bad-rearm-time would allow a support ship to be in-mission and allow the player to rearm while preventing the AI from rearming for the duration it is active.

In addition I'd strongly suggest allowing the ships affected by good-rearm-time and bad-rearm-time to be explicitly specified. Right now, it affects all ships on a team, which could be made a lot more granular.

**Comment by Goober5000** [comment]
bad-rearm-time has been implemented by #6069

**Comment by JohnAFernandez** [comment]
Closing since it is implemented.
