### ISSUE TITLE
Force Player Minimum Speed

### ISSUE THREAD

**Issue by AndrewofDoom** [scp-fs2open/fs2open.github.com#604]
I had posted a similar issue a long time ago (Mantis: http://scp.indiegames.us/mantis/view.php?id=2675) with relations to my old SHMUPSpace mod, which I did find a workaround (thanks 2d games). Now I need this forced speed again on players but this is a 3d mod. It's supposed to be like that old game called Stellar Assault except a spiritual successor to it instead of a fan made sequel.

**Comment by niffiwan** [comment]
note to self; have a look at ```read_keyboard_controls()``` in code/playerman/playercontrol.cpp; at the end of the stuff dealing with all the throttle settings consider an override that sets speed to a minimum value.  Probably set both of these; 1st will be some value specified by the modder

     Player->ci.forward_cruise_percent = 33.3f;
     override_analog_throttle = 1;

**Comment by niffiwan** [comment]
note to self MKII:
Add "+Player Minimum Speed:" to ships.tbl

**Comment by niffiwan** [comment]
Writing parts of the code has raised a few more questions.

1) Do you want the minimum speed to apply to x/y (up/down,left/right) velocities? I'm intending to use the same table format as $Max Velocity:, but if you don't need minimum x/y values I'll just ignore the other two values in the table _for now_, and only set the minimum for z.

2) Does your mod intend to have player pilot-able glide enabled ships?  Currently it interacts weirdly with glide; you always have forward thrust even though you're "gliding", which means you're never really gliding properly, you're kinda "skating" around. However, if glide worked as normal then I figure the player can bypass the speed restriction with creative use of glide. i.e. glide backwards, near the place you want to stop, disable glide, then wait until your forward thrust cancels your momentum, then enable glide again, and you should be nearly stopped.

**Comment by MageKing17** [comment]
With regards to your second point, you could make it only thrust forward if the magnitude of the player's velocity is too small (like inverted decay for being over the maximum speed).

**Comment by AndrewofDoom** [comment]
2) No it doesn't have any form of gliding at all.

**Comment by niffiwan** [comment]
eeeeeeeehxhellent; I can be lazy then :)

**Comment by niffiwan** [comment]
I didn't need to be too lazy.  Give these executables a go & let me know if they work as expected
http://www.mediafire.com/download/wlc88e5ee2njije/fso_player_min_speed.7z

You need to add this to your tables:
```
$Name:                          GTF Perseus
+nocreate
$Player Minimum Velocity:		0.0, 0.0, 40.0
```

It immediately follows ```$Max Velocity:```

(code is here: https://github.com/niffiwan/fs2open.github.com/commit/5a5cd7f626af7b236962676dd0f061014d9d4af7)

**Comment by AndrewofDoom** [comment]
I'm here to confirm that his code does work as intended on my side.

**Comment by niffiwan** [comment]
committed via #615
