### ISSUE TITLE
Discord doesn't display what you are playing on newer nightlies

### ISSUE THREAD

**Issue by PremiumColt** [scp-fs2open/fs2open.github.com#6048]
I've noticed that from the FSO.24.1.0-20240228 build onwards, Discord does not display what mod/campaign you are playing. The FSO.24.1.0-20240227 nightly and prior ones do display it.

To reproduce, enable "Share your activity with others" in Discord's User Settings>Activity Privacy and launch FSO with FSO 24.1.0-20240228 or newer (I also tested this with FSO 24.1.0-20240306, FSO 24.1.0-20240315 and FSO 24.1.0-20240316).

**Comment by MjnMixael** [comment]
A toggle for that was added to the new F3 Options menu. Mainhall -> Options -> Press F3. Make sure the option is turned on.

**Comment by PremiumColt** [comment]
Ahh okay. Got it running. Thanks for the quick reply,

**Comment by Goober5000** [comment]
Closing as resolved 👍
