### ISSUE TITLE
Using -nointeractive, -mission and -benchmark still shows "campaign not found" message

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#6051]
This error still displays if the last pilot campaign is not present with the current files, what is pointless because you cant really do anything about it.  Maybe"-nointeractive" should make this message not to be displayed?

**Comment by Goober5000** [comment]
Can you elaborate on this?  What is the use case?  And what is the actual "campaign not found" message that is displayed?

**Comment by Shivansps** [comment]
This one
![image](https://github.com/scp-fs2open/fs2open.github.com/assets/2444336/f62c24c8-c317-496c-98e1-c541eb4dc706)

But i just realised this message is removed on 24.0.0 completely, i just realised this. Or at least it not longer shows as 24.0.0 seems to auto switch active cp if the active one is missing.

So i think you can close this if that removal was intentional.

**Comment by Goober5000** [comment]
Yes, the campaign fallback behavior was changed in #5910:

>  If the player's current campaign cannot be found, the code now automatically falls back to the mod's default campaign or the first campaign in the campaign list. To avoid problems, this only happens when the game is started for the first time or when the player chooses a new pilot; in all other cases there is no fallback from the current campaign, whether or not it can be found.

**Comment by Shivansps** [comment]
ill say that change is good enoght to avoid this problem.
