### ISSUE TITLE
Show Insignia checkbox in the F3 Lab does nothing

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#6062]
The insignia checkbox neither disables or enables insignia. While I'm at it, it'd be nice to be able to select particular insignia in order to test-view them like team colors

**Comment by JohnAFernandez** [comment]
My graphics amateur perspective on this is that there doesn't seem to be a way to turn off insignia rendering in general. It needs a toggle first.  I think I see it though, because it's turned off when none of the textures are supposed to be rendered.
