### ISSUE TITLE
FR: Settings for movie subtitles

### ISSUE THREAD

**Issue by Achille44** [scp-fs2open/fs2open.github.com#6064]
In some cases, the movie subtitles (.srt files) are difficult to read on screen due to the colors/brightness of the video.
It would be nice to have a way to customize how the subtitles are displayed (at least the possibility to change the color of the text and the coordinates where the text appears).
Maybe these settings could be added to game_settings.tbl (same as "$Movie subtitle font")?

**Comment by Goober5000** [comment]
Dark Visor will be taking a look at this.

**Comment by Goober5000** [comment]
Implemented in #6116
