### ISSUE TITLE
Add $On Subsystem Destroyed action to scripting.tbl

### ISSUE THREAD

**Issue by AndrewofDoom** [scp-fs2open/fs2open.github.com#610]
The name itself should be self explanatory. It should have only one value, that is the reference to the subsystem destroyed.

**Comment by AndrewofDoom** [comment]
Made an update. The second value is redundant since you can call getParent() on the subsystem reference.

This is important since currently there is no easy way to check if a subsystem is destroyed outside of polling every ship for every subsystem it has on it, which can easily chew performance with a O(n^2). This along with problem #605 would mean I would have make a graph for each ship I make, hurting performance even more.

**Comment by ln-zookeeper** [comment]
I think the fact that the subsystem handle is not derived from object means that the hook variable referring to the subsystem probably needs to be a string, rather than a direct handle to the subsystem. That shouldn't be a problem though.

So, assuming the above is correct, the hook variables should be Ship (ship handle) and Subsystem (string).

**Comment by AndrewofDoom** [comment]
Does it though? The subsystem handle has the ability to get its parent subsystem. But, hey what do I know?

If anything, the way you have it would be more consistent with the rest of the ship related actions.

**Comment by MageKing17** [comment]
Subsystems are obviously valid Lua objects, but they're not "objects" in FSO (like ships/weapons/what have you), which is relevant to trying to use them as hook variables; `SetHookObject()` and `SetHookObjects()`, as the names suggest, only work on `object` instances.

It might, however, be possible to use `SetHookVar("Subsystem", "o", l_Subsystem.Set(ship_subsys_h(valid_object_pointer, valid_subsystem)))`; this basically just calls `ade_set_args()`, and the ship indexer for retrieving subsystem objects uses `l_Subsystem.Set()` in exactly that way.

**Comment by AndrewofDoom** [comment]
Now that I think of it, I think I'm in favor of Zookeeper's idea since it would probably let me use with a $Ship or $Ship Class conditional hook.

**Comment by Goober5000** [comment]
Implemented in #2037.
