### ISSUE TITLE
Cubemap related debug assert

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#611]
If you're running a debug build and you don't have the 3d hardware textures option at max, then the game will throw this assertion:

Assert: !resize
File: gropengltexture.cpp
Line: 659

If you have the 3d hardware textures at max this won't happen. To reproduce this you just need to turn that setting down and go into the tech room or the f3 lab and select a ship.

**Comment by niffiwan** [comment]
Also see this Mantis issue: http://scp.indiegames.us/mantis/view.php?id=3098
