### ISSUE TITLE
Mission file not visible in tech room -> mission simulator

### ISSUE THREAD

**Issue by topas-rec** [scp-fs2open/fs2open.github.com#6158]
Hey everyone,

I made a mission (`.fs2` file) I would like to test it.
Since I am on linux [I cannot easily run Freespace from FRED](https://github.com/scp-fs2open/fs2open.github.com/issues/6155).
That's why I want to use the mission simulator in the tech room after starting Freespace manually.

I created a mod in Knossos.NET and placed the mission file in the mod folder under `data/missions`.
When I launch that mod in single player through Knossos I cannot see the file / mission in the mission simulator.

As a test I moved my mission file to another mods (GOTY Mission Pack) mission folder and started that mod.
There the file is shown and can be played.

It seems my mod setup is the reason here.
Can someone help me what could be the cause?

I am running out of ideas after
* testing another existing mod (GOTY Mission Pack - already mentioned above)
* comparing my `mod.json` with the one from the working mod (differences, yes, but I don't see a difference which could cause this)
* comparing the debug logs of mine and the working mods (differences, yes, but I don't see a difference which could cause this)
* making my mod as plain as possible - only FSO as a dependency
* creating an additionally mod from scratch and placed the mission in there
* inserting my mission file in `filelist` entry in the `mod.json` (doesn't make sense somehow as it should be automatically discovered - at least that's what I read everywhere)

It could also be a Knossos issue with creating mods. If that is the case then close this and I'll ask for help there.

**Comment by ngld** [comment]
> I created a mod in Knossos.NET and placed the mission file in the mod folder under data/missions.

If you're working on a mod (as opposed to installing a published mod), each package has its own folder. Make sure you've created a package for your mod, that it is selected and then click the `Open Folder` button in Knossos.NET. That should open the package folder which contains an empty `data` folder. Move your `missions` folder inside that folder and try again.

If that still doesn't fix the issue, use the `Debug` button in Knossos.NET to launch the FSO Debug build, wait for FSO to load, close it and then upload your `fs2_open.log` through Knossos.NET's Debug tab. That should give you a link you can post here.

**Comment by topas-rec** [comment]
That works. Great. Thank you.

Is there a guide that mentions this?
I found the [Tutorial - How to make a mod from scratch](https://wiki.hard-light.net/index.php/Tutorial_-_How_to_make_a_mod_from_scratch) which is from 2022 at the time of writing and that I've read before. It mentions to put ship files in the packages data folder - I could have get the information from there, but missed it.

> [...] create a folder named "data" inside the package (which we named root here). This is where we will start adding files [...]

**Comment by ngld** [comment]
[This guide](https://docs.google.com/document/d/1oHq1YRc1eXbCgW-NqqKo1-6N_myfZzoBdwZuP16XImA/edit?pli=1) is very complete and detailed but it was written for an older Knossos version which means that the screenshots no longer match but the overall concepts have remained the same.
