### ISSUE TITLE
FR: Allow Multiple Gamepads/Joysticks

### ISSUE THREAD

**Issue by mikeloeven** [scp-fs2open/fs2open.github.com#623]
Recently i got a new HOTAS stick and was dying to try it out with FS2 Open however it seems that there is a major flaw in the game that prevents you from mapping controls from more than one Gamepad type device. Considering that a lot of HOTAS sticks are two separate devices the game needs to be updated to allow it to map inputs from more than one Gamepad device.

**Comment by niffiwan** [comment]
This is a known issue. SDL2.0 is planned to be merged post 3.7.4, this will migrate the Windows platform to SDL and provide the framework that'll allow FSO to recognise multiple controllers.  More work will probably be required after that point to actually get them integrated/working.

**Comment by mikeloeven** [comment]
I didn't see any other issues when i searched is there another bug tracker associated with the project

**Comment by niffiwan** [comment]
yeah; we have a [mantis instance] (http://scp.indiegames.us/mantis/my_view_page.php). Not sure if that particular issue has been reported in there or not.

**Comment by MageKing17** [comment]
I'm unaware of a corresponding Mantis issue (and I just did some fruitless searching for one); it's more of a well-known engine limitation (dating back to retail) than an issue with FSO. That being said, it *is* a known issue, and it's expected to be taken care of some time post-3.7.4.

**Comment by mikeloeven** [comment]
Ahh i see though back when i actually played FS2 for the first time my joystick was serial and hotas devices were several thousand a pop XD

**Comment by JohnAFernandez** [comment]
Having to push this to 21.4 as this is a feature.

**Comment by z64555** [comment]
Deferring to 21.6, due to Controls5 deferment.

**Comment by z64555** [comment]
Controls5 is in pending smoothing out the rest of corners.  Expect in 22.0
