### ISSUE TITLE
`NextFireTimestamp` does not return mission time

### ISSUE THREAD

**Issue by Baezon** [scp-fs2open/fs2open.github.com#6256]
`NextFireTimestamp` on subsystems is documented as
```
 number NextFireTimestamp = number
    The next time the turret may attempt to fire
    Value: Mission time (seconds) or -1 on error
```
But the return is instead the amount of real time passed as seconds since the start of the program. This obviously quite difficult to work with. I don't know if it's always been this way, or if any other timestamp script values are affected...

**Comment by Goober5000** [comment]
Looks like the function hasn't changed since its addition in b7716621a8, so it never would have worked.

**Comment by Baezon** [comment]
I can believe it. I would tentatively propose few ever used this value and of those that did, a number that goes up with time is good enough.
