### ISSUE TITLE
Crash when saving control config.

### ISSUE THREAD

**Issue by Alcom1** [scp-fs2open/fs2open.github.com#6273]
Crash occurs immediately after saving a control config in the "Control Config" menu.

Before the crash, there were other issues with saving the control config.

- Could not overwrite existing config by saving it under the same name.

- Deleted existing config, but still go the "cannot overwrite" message when saving under the same name again.

Log : https://fsnebula.org/log/66a53c2c25fe9a7d2f0010be

Crash dump: [fs2_open_24_0_2_x64_AVX-FASTDBG_20240727_182701.zip](https://github.com/user-attachments/files/16401209/fs2_open_24_0_2_x64_AVX-FASTDBG_20240727_182701.zip)

**Comment by z64555** [comment]
Do you get the same error when running vanilla FSO?  I suspect it may be something on SCPUI's side.

**Comment by wookieejedi** [comment]
Same, I also concur it's likely SCPUI

**Comment by JohnAFernandez** [comment]
Here is the stack trace from the minidump.  It does seem to be SCPUI related.  

![Screenshot 2024-08-09 203232](https://github.com/user-attachments/assets/170b40b0-c1b1-4372-b127-872775210765)

I can't really understand the code fully, but based on this, I'm guessing something caused SCPUI to use up too much stack space?

![Screenshot 2024-08-09 203826](https://github.com/user-attachments/assets/05adfdca-fd0c-4187-b61d-3057aeab63bf)

**Comment by wookieejedi** [comment]
This is indeed an SCPUI bug, and a fix has been pushed to SCPUI master here: [https://github.com/MjnMixael/SCPUI/issues/13](url)

This can likely be closed as completed

**Comment by MjnMixael** [comment]
Additionally it is now fixed in the next SCPUI version. So it can be doubly closed.

**Comment by BMagnu** [comment]
Right, if it's fixed in SCPUI, closing this issue
