### ISSUE TITLE
FR: Make mission volume levels at mission start smarter

### ISSUE THREAD

**Issue by MjnMixael** [scp-fs2open/fs2open.github.com#6291]
It'd be great if we could get the audio volumes to match any volume changes set via sexp at mission start. The reason is that, for example, if you want to start your mission with an and audio fade-in, you'd set the audio to 0 with a sexp on the first mission frame. However, that sexp doesn't actually run until the second frame and this causes the mission to start with an audible pop as the game plays 1 frame of audio and then cuts the volume as instructed by the sexp.

I have two ideas to address this:

1: Add to the mission post_process code that checks for the audio sexps and pre-sets the game volume to match. I'm not exactly sure if there's a good way to detect events that run on the first event-available frame, but if so, this might be the simplest approach.

2: Systemize the whole thing. Create some kind of way to mark certain sexps as pre-run sexps. Specifically add code to run these before frame 0. This could open all kinds of cans of worms.

3: Add to Mission Specs (or some other menu where it may make sense) volume sliders for the three volume controls. These sliders would be the 'default mission volumes' and would be set before the first in-mission frame. Overridable by SEXPs, of course. I'm not really in favor of adding a whole UI setup and code for this, but it's a fallback if option 1 or 2 is not really viable.

**Comment by TRBlount** [comment]
Could you post an example?  Event music is not supposed to start until 1 second after the player is in-mission, as set in `event_music_set_start_delay()`.  This should be more than enough time for any sexps to set the initial volume.

**Comment by MjnMixael** [comment]
This is more for effects, not music
