### ISSUE TITLE
Lag-pursuit option for aspect-seeking missiles

### ISSUE THREAD

**Issue by Goober5000** [scp-fs2open/fs2open.github.com#6309]
Fusion mentioned that aspect-seeking missiles fly lead-pursuit in FS2 but lag-pursuit in FS1.  For greater fidelity, FSPort would like the option to switch to lag-pursuit for certain missions.  The mission "The Hammer and the Anvil" is much harder in FSPort than in FS1 and this could be one reason why.

This should be configurable via an ai_profiles flag so that different missions can use different pursuit techniques.

**Comment by Baezon** [comment]
Would it not be sufficient to simply have a interceptor variant for use in that mission? Not sure I'm a fan of just having ai profiles arbitrarily modify a single weapon value when existing methods can do the same thing without much hassle.

**Comment by Goober5000** [comment]
That sounds like it would be fine.

**Comment by naomimyselfandi** [comment]
Isn't this [already configurable](https://wiki.hard-light.net/index.php/Weapons.tbl#.2BTarget_Lead_Scaler:)?

**Comment by EatThePath** [comment]
I think the default steering behavior for heat seekers and aspect seekers is different, which probably makes that logic sensible.

From what I can tell with a little googling, what I had been thinking of as 'lag pursuit' seems to be more accurately termed 'pure pursuit', that is simply flying directly towards the target's current position. Actual lag pursuit looks to be a more complicated thing where you turn wider than your target to better catch them after the turn. That was all in dogfighting stuff, maybe it's different in missile contexts. Regardless I imagine lag pursuit in our context has been used to mean the pure pursuit concept, which should be a scalar of 0.

A negative scalar looks like it should be viable, I don't see it getting sanitized anywhere and it could lead to interesting behavior, but probably not FS1 mimicking behavior.

**Comment by Goober5000** [comment]
Gotcha.  Makes sense.  Woolie Wool ran some tests and reported that a value of 0.0 seems to reproduce the FS1 behavior well.

Thanks all for your help.  I'll close this as complete.
