### ISSUE TITLE
RC1 errors upon reading mv_effects-snd.tbm

### ISSUE THREAD

**Issue by MoerasGrizzly** [scp-fs2open/fs2open.github.com#6326]
Error: mv_effects-snd.tbm(line 26):
Error: Missing required token: [$Name:]. Found [(0.97 1.02)] instead.

File: parselo.cpp
Line: 319

ntdll.dll! NtWaitForSingleObject + 20 bytes
KERNELBASE.dll! WaitForSingleObjectEx + 142 bytes
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
fs2_open_24_2_0_RC1_x64_AVX.exe! <no symbol>
KERNEL32.DLL! BaseThreadInitThunk + 29 bytes
ntdll.dll! RtlUserThreadStart + 40 bytes

The line it chokes on appears to be the ["Pitch"](https://wiki.hard-light.net/index.php/Sounds.tbl#.2BPitch:_2) value.

**Comment by wookieejedi** [comment]
Fixed by #6325
