### ISSUE TITLE
Potential performance regression in 24.2 cycle

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#6344]
On discord LuytenKy has reported significant framerate drops between the July 21 and August 18 nighties. I believe this is the gap where nighties were off, so user bisection is difficult.
Reportedly large dogfights, especially coinciding with weapons firing, are the source of the drop. They pointed to La Ruota Della Fortuna in FSPort as an example, where they observed solid 60fps before and dips down to 20 after. Reportedly retail missions can also show impacts.
Their log files show a Radeon RX 6400, which from what I can tell ought to be decently modern and capable. Personally, I'd prefer this get pinned down before the 24.2 final version.
On the suggested missions my primary computer(with an Nvidia GPU) run well enough on the current builds I don't think I can get anything useful out of comparing before and after. I can't promise any timeline about standing my testbox back up and doing more useful tests on my end.
I have noticed that the logs for another issue, at https://discord.com/channels/223511295431933953/223511391531827200/1278737609417429022, they have deferred lighting off. I have no clue if that was an attempt to troubleshoot on their part, and I didn't use it in my tests.
There's a decent spread of possibly impactful merges in the nightlies gap. Building and sending them more steps to bisect with would also be likely productive.

**Comment by Goober5000** [comment]
I've generated the nightly builds that were missing between July 21 and August 18, so hopefully bisection will be more tractable.
