### ISSUE TITLE
Unwanted new warnings on retail sound syntax with non-int names 

### ISSUE THREAD

**Issue by EatThePath** [scp-fs2open/fs2open.github.com#6354]
This has had some various discussion on discord but seems like it needs a tracking issue:

In the recent sound changes (#6112, #6286) checks were added that include a warning for sounds that use retail sound syntax and end up in vector indexes which aren't equal to their name. This does not account for the possibility that these sounds currently allow non-integer names, which won't ever match their index.

Arguably, allowing these names in the first place was an oversight or mistake. It appears it became possible in mid 2012 (e541cf0180453c3452d4ea53ea66db03c441cd58, pre-gethub), as a side effect of adding the newer syntax. However, I would argue to the contrary on a few grounds:
1: Restoring this restriction after 12 years, even in a soft warning form, feels capricious to a modder, especially when it has to be explained with implementation-specific technical details of the sound code and it's history.
2: String names in the retail syntax is useful to a modder! if you don't need any of the capabilities of the newer syntax then the retail one makes a very compact way to list out sounds. Also especially when updating older mods or trying to bring together aspects of two mods, or dealing with a deep mod stack, adding non-numeric characters is a far more reliable way of preventing accidental sound definition collisions.

It'd be one thing if the current method was the only viable way to address the issues so far, but I am dubious of that. As far as I can figure it should be sufficient to have any pure-integer names displace any named strings in their matching index, and ensure no named sounds are placed in reserved slots to begin with. Alternatively, it would probably be more robust to move entirely to a hash map, but that's an overhaul that is likely to be a huge amount of work.

This late in an overdue RC cycle I think one possibility to consider is reverting these sound patches temporarily and revisiting the issues that prompted them in the next version. As far as I understand the relevant issues are relatively minor and could be largely sidestepped by asking the MVPs add empty sounds in the ballistic rearm reserved indexes before the new named sounds are defined, or having affected mods include a retail-derived sounds.tbl or a loaded-pre-mvps tbm that adds those sounds. This is very much not an ideal solution but this sound overhaul as-implemented worries me and I'm not personally confident we've shaken it out properly or will be able to do so before a stable.

That's my two cents of course. As I am not currently devoting large portions of time to SCP, either coding or review, I don't feel it's my place to make a bigger stink about by nebulous and subjective concerns than I already have done, but still wanted to have them 'on the record' as it were.

**Comment by Goober5000** [comment]
Looking at the sound code, there is an assumption that sounds defined in the retail style will have numeric IDs.  When numeric IDs are added, they need to match their indexes.  That's the reason for the warning.

It's already the case that named sounds parsed in the new style can be placed into any available index, whose index does not need to match the name; so it should be simple to also allow this for named sounds parsed in the retail style.

**Comment by EatThePath** [comment]
to the edit: That seems like it's not possible, or at least must be new to the recent revisions? Warmachine has 30 sounds that are triggering this warning, and I'm pretty sure I'd have noticed if that many sounds didn't work.

**Comment by Goober5000** [comment]
Okay, I see what Warmachine is doing.  I was so used to reading retail-style sounds in a certain way that I mentally inserted a numeric index where it was "supposed to be" even though the lines didn't actually have them.

Anyway, the style that Warmachine is using should be entirely valid.  It should be straightforward to fix the warning check to accommodate it.
