### ISSUE TITLE
Bug: a malformed XSTR checker in FRED

### ISSUE THREAD

**Issue by jlberman** [scp-fs2open/fs2open.github.com#6374]
When a malformed XSTR is in a briefing (for instance), it throws an error that shows "Alpha 1 is not present" in a mission, and the error checker doesn't point to the correct issue, which is that the XSTR is malformed.  Just to give an example, I deliberately set up a malformed XSTR in line 86...

![image](https://github.com/user-attachments/assets/4acba5c2-8937-484b-b9dc-de872b340f24)

...but the FRED error message points to line 404 of the mission.

![image](https://github.com/user-attachments/assets/be4b4e6a-2fb6-40cf-a8ee-39d790b7451c)

**Comment by Goober5000** [comment]
The XSTR warning did fire, but only in a debug build.  But both @jlberman and I think there's a case to be made for displaying this warning in release, so I'll make a PR.
