### ISSUE TITLE
removal of the Fighter/Bomber ship type in recent nightlies can cause some missions to fail to load.

### ISSUE THREAD

**Issue by DefCynodont** [scp-fs2open/fs2open.github.com#6388]
BtA currently has a mission that uses/used the Fighter/Bomber ship type in an `is-ship-type` SEXP. While we are aware the type never worked correctly, it's removal has caused the mission to **abort loading** on the new nightly builds, as there is no fallback or failsafe. It's entirely possible other missions in other released campaigns could get the same error or errors. I'd like to suggest that some kind of safeguard be put in place for backwards compatibility.  

Thank you for your time. 👍

**Comment by Goober5000** [comment]
Indeed.  The "fighter/bomber" type is used in a couple other missions as well, including one of the missions in the Game of the Year edition of FS2.

In the course of testing #6367 I verified that the "fighter/bomber" type does not appear in the ship tables of any mod (with the exception of The Babylon Project, but that mod defines its own "fighter/bomber" type).  But that SEXP definitely throws a wrench into things.

**Comment by Goober5000** [comment]
Resolved in #6390, for now

**Comment by Goober5000** [comment]
Fixed properly in #6393
