### ISSUE TITLE
Bug: Unequippable weapons for specific banks showing as equippable.

### ISSUE THREAD

**Issue by jlberman** [scp-fs2open/fs2open.github.com#6398]
In ships.tbl, there's only one weapon that can be equipped in the first bank of this ship.  

![image](https://github.com/user-attachments/assets/ba76b588-9f46-46e6-8f94-b16f029118b6)

Click that bank in the weapon loadout room, and the loadout room shows that you can equip those weapons in that bank.

![image](https://github.com/user-attachments/assets/6d2355a0-cc3b-4eb2-bb01-619f10c28a27)

But when you try to drag an invalid weapon into that bank, it gives you an error.

![screen0249](https://github.com/user-attachments/assets/437ab16c-49dc-43e7-8ba4-6da72e1d1fd5)

It should grey out invalid banks in the UI when you can't load a particular weapon into a particular bank.

Note to @Goober5000 : This can be replicated in Inferno M14.

**Comment by EatThePath** [comment]
Unless this situation plays out differently in a past version of FSO, I think this is not really a bug. If memory serves, outside of some bomb slots retail doesn't do a lot with having different compatibility for different banks, so the UI just isn't designed to react like that. 
I'm willing to be wrong if you can point to a scenario where it does re-actively grey out weapons based on bank selection, or did in a past version.

**Comment by jlberman** [comment]
Oh, OK. So this is really a feature request, then?

**Comment by EatThePath** [comment]
> Oh, OK. So this is really a feature request, then?

Yes, probably. Though I think it's also a feature mods can probably implement with Lua these days, too.

**Comment by MjnMixael** [comment]
This does work in SCPUI out of the box.

**Comment by wookieejedi** [comment]
Interesting, if manually created icons are used instead (such as eff image sequences for the icons) then they properly show as greyed out. I wonder if this feature just never made it over to the generated icons feature?

**Comment by Goober5000** [comment]
Hmm.  It's entirely possible that updates were made to one part of the UI but not another part.  There have been many updates over the years, and it's not uncommon for an upgrade in one part of the code to miss a very similar case elsewhere in the code.

**Comment by jlberman** [comment]
Yeah, because in retail it does grey out those things.
