### ISSUE TITLE
Allow Different Ambient Sounds for Mainhalls.

### ISSUE THREAD

**Issue by UndyingNephalim** [scp-fs2open/fs2open.github.com#6421]
Currently all mainhalls are locked using the same ambient background sound effect:

if (play_ambient_loop) {
    Main_hall_ambient_loop = snd_play_looping(gamesnd_get_interface_sound(InterfaceSounds::MAIN_HALL_AMBIENT));
}

Being able to specific a different sound for custom mainhalls would be an excellent feature.

**Comment by Goober5000** [comment]
Implemented by #6423
