### ISSUE TITLE
Placing more than 31 characters on Cargo Name soft-lock Fred2

### ISSUE THREAD

**Issue by Shivansps** [scp-fs2open/fs2open.github.com#6427]
Right now if you open Fred2, put more than 31 characters on a cargo name and close the ship window with the "x" this ends in a situation where you can only close Fred2 via task manager, there is no way to get out of that.

**Comment by Goober5000** [comment]
The situation here is an "Enter no more than 31 characters" dialog repeating endlessly.  Something is not configured correctly with MFC data validation.  The character length is being checked, but the dialog is trapped in a loop that doesn't let the user fix it.
