### ISSUE TITLE
Initial Rotation Broken in Ship Lab

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#643]
In the F3 Ship Lab, the 'Initial Rotation' feature commonly used for turrets does not behave as it did before the build http://www.hard-light.net/forums/index.php?topic=91116.0.  This includes being broken in the 3.7.4 release.

Test Case:  Load Diaspora using 3.7.4 or a nightly on/after Dec 3, and view the Bolitho in the Ship Lab.  The Initial Rotation box should be checked in Render Options, but the turrets are not aligned to their initial rotation.  3.7.2 and nightlies from Dec 1 or earlier will show the correct behavior by comparison, as does viewing the Bolitho in the tech room with any build.

**Comment by SamuelCho** [comment]
Might be a side effect of my changes to move model rendering to the polymodel_instance system.

**Comment by chief1983** [comment]
I learned some more about this one.  Even though the arms of the Faustus (MediaVPs 2014) don't rotate, the shadows do move along the hull as if they are rotating.  It's pretty strange to see.  In 3.7.2 the glow points were stuck in the air during rotation, not sure I even see the glow points in the F3 lab now (3.7.4).  Only seen these things in the ship lab so figured I'd mention them here too.

**Comment by asarium** [comment]
I found an inconsistency in the lab code about how `Lab_selected_object` was handled. The variable was passed to the render info of the normal render pass but not to the shadow render pass so it's probable that there is something wrong with how the model instances are being handled.

**Comment by chief1983** [comment]
Sweet tats, been hoping someone might have an idea on this eventually.  I noticed one more thing.  If you check Show Destroyed Subsystems, the subsystems that would be gone when destroyed (say, a radar dish) don't disappear, but their shadows do.

**Comment by asarium** [comment]
It looks like there is a mitmatch between how the submodel instance data is handled. The lab code assumes that it uses its own subsystem data structures but if you set the object number parameter on the render info it uses the information in the specified object.

I think using the object information is correct in this case since it is cleaner to handle it that way.

**Comment by asarium** [comment]
If I remove the object number from both `render_info` calls the initial rotation works again but I'm not sure if that's a good solution. The damaged model checkbox also doesn't seem to do anything.

**Comment by asarium** [comment]
After a bit of looking at the code, it seems like it was deliberately designed to not use the model instance code. I made sure that the object number isn't set anywhere while rendering the object and that fixes this issue.

**Comment by chief1983** [comment]
https://youtu.be/QbhOd6WM31g

Initial rotation is working!  And destroyed subsystems are fixed too.  However, there's a couple issues I mentioned previously in this ticket still present, we can open a new ticket for those or reopen this one, doesn't matter to me.  The lab still starts off showing you the tail end of the ship though, not a big deal but still a regression.  More significantly though, is the lights on the Faustus' submodel.  Watch them sit still when I animate the ship's subsystems.  Apparently my earlier comment said that glowpoint behavior was there in 3.7.2.  So these are probably separate issues themselves.

**Comment by asarium** [comment]
Could you make separate issues for those two bugs? It would make tracking them easier.
