### ISSUE TITLE
PBR/HDR: Drawing monochrome images causes them to go black

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#650]
![monochromeimage](https://cloud.githubusercontent.com/assets/6625164/16711177/c8de50c2-4612-11e6-98ee-cd2a3d126390.png)

I draw that health gauge with gr.drawMonochromeImage and in the top (in 3.7.4) it draws as expected. In the PBR/HDR builds, it draws them black. I don't think this is a lua specific thing since custom $Radar Image 2D images in the ship table will draw as black too.

Here's a test mod that displays the behavior (though its hard to see that black health bar against black space :p)
https://drive.google.com/file/d/0B_q0tkX7VcSaRmhhVVo4UFJiakE/view?usp=sharing

**Comment by DahBlount** [comment]
I believe this is fixed by Pull Request #659.

**Comment by AxemP** [comment]
Just something to note, -no_glsl makes the monochrome images work correctly.

**Comment by SamuelCho** [comment]
This should be fixed now as of https://github.com/scp-fs2open/fs2open.github.com/pull/668
