### ISSUE TITLE
PBR/HDR: Weird team color glow behavior

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#651]
![screen0657](https://cloud.githubusercontent.com/assets/6625164/16711186/7782ba14-4613-11e6-9042-d44c3d29036b.jpg)

The modded Cain has team color glows that seem to glow through the really long weapon trails being fired by the player.

![screen0659](https://cloud.githubusercontent.com/assets/6625164/16711198/cab8324a-4613-11e6-87ea-51a9b6847fcf.jpg)

And here the glows seem to go teal when it fires a red beam. It only happens at the end of the beam.

None of this happens if I disable the team glows for the ship in the table.

Here's a test mod that displays the behavior:
https://drive.google.com/file/d/0B_q0tkX7VcSaRmhhVVo4UFJiakE/view?usp=sharing

**Comment by asarium** [comment]
I did some debugging with APITrace and according to that, the parts of the model that have team-glows have a negative green value in the texture. I don't know if that's intentional or if that might cause issues.
