### ISSUE TITLE
PBR/HDR: 'FS1 Ship Select' ship effect in-mission doesn't display correctly

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#653]
The select effect in the weapons load out is fine, but in mission it doesn't look like its doing the effect right.

It's hard to see in pictures exactly, but he attached mission will show the problem. Press 1 to trigger the effect on the invisible Fenris. (Rename to .fs2 of course)

[effecttest.txt](https://github.com/scp-fs2open/fs2open.github.com/files/356069/effecttest.txt)

**Comment by asarium** [comment]
I have done some investigating here and I have confirmed that something it going wrong with the FS1 effect. I checked the timer values that are passed to the shaders and they seem to be working so it's not an issue with how these values are handled.

I checked the shaders and a first looked hasn't revealed anything that may explain why the effect works in the ship select room but not in-mission.
