### ISSUE TITLE
Scene render targets in nebula missions broken following nohtl removal

### ISSUE THREAD

**Issue by SamuelCho** [scp-fs2open/fs2open.github.com#657]
Nebula missions (specifically tested Mystery of the Trinity) seem to render the scene to a tiny box in the corner of the screen. I narrowed it down to https://github.com/scp-fs2open/fs2open.github.com/pull/641/commits/70529dbd5a2e64c188675fbec086c5e7d5fa05ea. The commit before it seems to be fine https://github.com/scp-fs2open/fs2open.github.com/commit/a43bb9ad371379ddb44e925f4ac229dab5121473.

![nebula_broke](https://cloud.githubusercontent.com/assets/426809/16793275/965d927e-4884-11e6-91d6-98ccd3530467.png)

**Comment by The-E** [comment]
Issue could be here: https://github.com/scp-fs2open/fs2open.github.com/pull/641/commits/70529dbd5a2e64c188675fbec086c5e7d5fa05ea#diff-fc0f9877a190d9d20c7d0c1d3e607bdcL354

That if conditional should never be hit.
