### ISSUE TITLE
Build fails with CMake: missing EnableExtraCompilerWarnings

### ISSUE THREAD

**Issue by rtoijala** [scp-fs2open/fs2open.github.com#700]
Build fails with the new CMake system.
It seems to be missing the file ```EnableExtraCompilerWarnings```.
Since this is my first time really using CMake, I might just be doing it wrong.

Steps:
1. ```mkdir build```
2. ```cd build```
3. ```cmake ../```

CMake 3.6.1
GCC 6.1.1
Arch Linux x64

CMake output and logfile are attached:

[output.txt](https://github.com/scp-fs2open/fs2open.github.com/files/388835/output.txt)
[CMakeOutput.txt](https://github.com/scp-fs2open/fs2open.github.com/files/388840/CMakeOutput.txt)

**Comment by MageKing17** [comment]
You need to download the submodules.

> Before you do anything, make sure you have updated your git submodules, either by running `git submodule update --init --recursive` or by clong the repository with the `--recursive` flag.

**Comment by rtoijala** [comment]
Thanks, works now.
Just to satiate my curiosity, in which file are those directions included?

**Comment by MageKing17** [comment]
I was quoting @asarium's [forum post](http://www.hard-light.net/forums/index.php?topic=92318.0) made when the CMake PR was merged (the very first reply to which, interestingly enough, was somebody else having the exact same problem).

**Comment by chief1983** [comment]
It was also the first thing I ran into and reported on IRC before the merge :P

**Comment by rtoijala** [comment]
Right, it seems my searching skills are lacking. I have yet to understand that development is also discussed on hard-light.

**Comment by MageKing17** [comment]
With PR #704 it should now be slightly more obvious when this is the problem.

**Comment by chief1983** [comment]
I think what he was hinting at earlier though, is maybe the Readme or something would help to have a not about checking out the submodules.  I noticed it isn't mentioned yet at least.

**Comment by rtoijala** [comment]
Yes, I did notice that it was not mentioned...
Also, while checking the files in the root directory for instructions, I also noticed that the following files are quite out of date:

`INSTALL`
- mentions Freespace2.dsw which according to google is for Visual C++ 6
- mentions ./configure and autoconf/automake for Linux

`NEWS` exists only for autoconf compatibility

`ChangeLog` was last updated 2013

`COPYING` might want to link to [https://github.com/scp-fs2open/fs2open.github.com/wiki/Licensing](the Licensing wiki page)

`FS2OpenSCPReadMe.doc`
- was last updated 2003
- links to Bugzilla on http://fs2source.warpcore.org/ that has since disappeared

`AUTHORS` also links to http://fs2source.warpcore.org/

When I first started looking for instructions for contributing, these were quite confusing and irritating. However, since I am an infrequent and novice contributor, I don't see it as my place to try to change them.

**Comment by MageKing17** [comment]
You're quite right about all of those files being wildly out of date; actually, could you make a new issue for them to help us remember? The last time I pointed out `AUTHORS` was out of date we updated [the in-game credits for 3.7.2](https://github.com/scp-fs2open/fs2open.github.com/commit/e0e3cffab67ebb9d554bd52065269a5e823c249c), but `AUTHORS` remained unchanged.
