### ISSUE TITLE
Documentation files in top folder are out of date

### ISSUE THREAD

**Issue by rtoijala** [scp-fs2open/fs2open.github.com#711]
Follow-up on my [comment](https://github.com/scp-fs2open/fs2open.github.com/issues/700#issuecomment-236377624) from Issue #700.

`INSTALL`
- mentions Freespace2.dsw which according to google is for Visual C++ 6
- mentions ./configure and autoconf/automake for Linux

`NEWS` exists only for autoconf compatibility

`ChangeLog` was last updated 2013

`COPYING` might want to link to https://github.com/scp-fs2open/fs2open.github.com/wiki/Licensing

`FS2OpenSCPReadMe.doc`
- was last updated 2003
- links to Bugzilla on http://fs2source.warpcore.org/ that has since disappeared

`AUTHORS` also links to http://fs2source.warpcore.org/

I suggest getting rid of `INSTALL`, `NEWS`, `ChangeLog` and `FS2OpenSCPReadMe.doc`, updating `AUTHORS` and adding a link to the wiki page to `COPYING`.

Also, `Readme.md` could use better or more complete building instructions.

**Comment by chief1983** [comment]
For the readme, specifically explaining that there are required submodules (`git submodule update --init --recursive`) would be a good start.  Just mentioning that here as a reminder.

**Comment by Kiloku** [comment]
Does anyone know if removing the `NEWS` file still causes problems with autoconf/automake?

**Comment by Goober5000** [comment]
That looks to be the case:

https://stackoverflow.com/questions/21773003/error-in-automake

https://www.sourceware.org/autobook/autobook/autobook_25.html#Generated-Output-Files

**Comment by niffiwan** [comment]
I'm pretty sure we don't use autoconf/automake anymore, it's all cmake. And while on Linux by default that'll create Makefiles for use with make, that's not autoconf/automake.

Or in other words, try deleting NEWS, then compile from scratch w/ cmake and it'll probably work just fine.

**Comment by Kiloku** [comment]
The above PR doesn't deal with the Build instructions part. I intend to look into that this weekend.

**Comment by Goober5000** [comment]
Addressed by #2156 and #2171.
