### ISSUE TITLE
Nebula mission sprites aren't rendering correctly.

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#712]
Mission that take place in a nebula still don't have visible gaseous sprites under PBR.

**Comment by SamuelCho** [comment]
What gaseous sprites are you talking about?

**Comment by DahBlount** [comment]
The nebula "poofs", literally PoofColorNum.dds (PoofGreen01.dds for exmaple) in the MVPs effects VP.

**Comment by SamuelCho** [comment]
Do they show up when you turn post processing off?

**Comment by DahBlount** [comment]
Yes. I took some screenshots and did some image analysis. The sprites are actually there, but they're so faint, it's nearly impossible to see them without some heavy contrast.

**Comment by SamuelCho** [comment]
Going from gamma to linear color space is likely killing the contrast. I don't know if I have a way to fix this.

**Comment by DahBlount** [comment]
Yeah, the dds files themselves are pretty dark. Increasing their brightness makes them pop out in nearly the same way as pre-pbr builds.

**Comment by SamuelCho** [comment]
Hmm, i'll see if I can apply a slight color boost to the poofs to compensate for the gamma correction.

**Comment by DahBlount** [comment]
Alright, if it helps you can compare the graphics between the MVPs 2014 and 3.6.12. The 3.6.12 graphics render just fine in PBR/HDR.

**Comment by DahBlount** [comment]
Did a PR for this ever get made?

**Comment by asarium** [comment]
@TRBlount I opened a PR which boost the colors of the sprites a bit. IMO it looks similar to how it was before but that factor can need to be adjusted if it doesn't look right.
