### ISSUE TITLE
Thrusters are visible through models

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#736]
I have no idea why this happens and it also doesn't seem like an error that always happens because more people would have noticed that by now:
![master](https://cloud.githubusercontent.com/assets/1013983/17366134/df375924-5989-11e6-8ddb-a140049bbbbd.png)

The error already occurs in 3.7.4 final so it wasn't caused by PBR:
![3_7_4_final](https://cloud.githubusercontent.com/assets/1013983/17366113/c6b1a102-5989-11e6-88ff-ef006616d1bd.png)

**Comment by asarium** [comment]
After further investigation, this appears to be caused by the "Disable deferred rendering" option. Enabling that options fixes the issues.

**Comment by The-E** [comment]
If I had to guess, this is due to the no deferred render path not setting the depth buffer correctly. This should be testable by disabling soft particles, if that fixes the issue, then that's where the issue is.

**Comment by SamuelCho** [comment]
When deferred rendering is on, we check the position gbuffer to check depth for particles. If it isn't on, we use the depth buffer. Does this problem persist before the TrueType merge? If not, a function could have been erroneously replaced by the GLAD changes.

**Comment by The-E** [comment]
Given that it happens on 3.7.4 as per the op, I think we can strike Ttf and GLAD from the list of suspects.

**Comment by SamuelCho** [comment]
My bad. I haven't had much sleep these past couple of weeks.

**Comment by MageKing17** [comment]
A similar problem (thruster glows, but not the entire thruster effect, being visible through the sides of ships) has been around since even before the deferred renderer was merged (and, last time I noticed it, was still a problem even with the PBR renderer).

**Comment by SamuelCho** [comment]
That's because thruster glows are spherically attentuated like explosions. I may have to switch them to linear attenuation.

**Comment by SamuelCho** [comment]
I can't seem to reproduce this bug. Has anybody been able to get the same results?

**Comment by MageKing17** [comment]
I am also unable to reproduce with deferred rendering off *or* on, either on current master or 3.7.4 Final.

Although I was testing in the F3 lab rather than in a mission. Does the problem only occur in a mission?

**Comment by asarium** [comment]
The F3 does not have the same issue. In mission the issue still exists.

**Comment by The-E** [comment]
Well, I can't reproduce this specific issue either. I can, however, get this effect pretty reliably:

https://i.imgur.com/pLCVxm8.jpg
https://i.imgur.com/FMTkdJi.png

**Comment by asarium** [comment]
Another thing I notices is that there is a weird pattern where the thrusters are drawn correctly. Here is a picture of that:
![thruster_bug](https://cloud.githubusercontent.com/assets/1013983/17672090/be85f510-631a-11e6-8beb-7d81cec42f05.png)

That pattern is present along the the entire way from the top left corner to the bottom right corner so it might be a driver bug.

**Comment by SamuelCho** [comment]
What Radeon driver are you using by the way?

**Comment by asarium** [comment]
I am currently using 16.4.2 but I also tried it with the most recent driver version where the same issue appeared as well.

**Comment by chief1983** [comment]
In current master, I am seeing some odd thruster behavior in the ship lab with Post processing enabled, that goes away when I disabled it.  The thrusters are longer and appear to bleed through places they shouldn't when it is enabled.  Not sure if related to this issue but when I saw the behavior this one popped into my head.

**Comment by SamuelCho** [comment]
Yeah, that's due to the limitation of spherical attentuated particles. I plan on having those attentuate linearly.

**Comment by Goober5000** [comment]
The funny thing is that this bug used to happen all the time in retail FS1, but it was fixed in retail FS2.

**Comment by asarium** [comment]
I can no longer reproduce this bug but I now have a new GPU. This may have been a driver/hardware issue or it may have been fixed by #1186 which cleans up up a few oddities with framebuffer and depth buffer handling.

Anyway, this can be closed now.
