### ISSUE TITLE
Coverity seems to have stopped treating Assertions as halting.

### ISSUE THREAD

**Issue by MageKing17** [scp-fs2open/fs2open.github.com#740]
The most egregious example would seem to be Defect 1320551, which claims there's a negative array access immediately below an assertion that guarantees the index will be positive (rather than just checking for `-1`, which most of the similar negative-read defects have):

```c++
Assertion(wi >= 0, "Trying to validate non-existant weapon '%s'; get a coder!\n", it->c_str());
wip = &Weapon_info[wi];
```
> CID 1320551 (#<i></i>1 of 2): Negative array index read (NEGATIVE_RETURNS)
> **negative_returns:** Using variable **`wi`** as an index to array **`Weapon_info`**.

**Comment by MageKing17** [comment]
There may be some further issues with Coverity itself because I see at least one Defect (1317157) which complains "You might be using variable `x_axis` before verifying that it is >= 0" when the line this appears above *is* the comparison `x_axis >= 0`, and another Defect (1297190) that appears to be checking an impossible situation (it goes from "3. Condition `msg_mode == 3`, taking false branch." to "5. Condition `msg_mode == 3`, taking true branch." without any code that could change `msg_mode` in between).

**Comment by asarium** [comment]
The coverity modelling file and the source code are out of sync. I don't know how coverity handles it but the modeling file uses `WinAssert` which is marked as a kill path. Maybe there is a problem with the mismatching definitions.

**Comment by niffiwan** [comment]
Should have pasted in the IRC conversation:

````
I suspect SDL2 is what messed up coverity the most, the older *nix based code was far more eager to just "exit(1)" from stuff, whereas the new SDL2 stuff is more like windows & pops up dialog boxes with the "debug" options
pretty sure that extra debug option is what makes coverity think that they aren't killpaths anymore, because in theory you can return now from Error & continue execution
````

I think this also applies to assertions, somehow. Either way, I'm intending to update the modeling file to remove as many false positives as possible.

**Comment by niffiwan** [comment]
#754 should fix this issue (well, it's already fixed, that PR just commits the relevant changes to master)

Coverity defect 1317157 seems like a false positive to me as well... and in fact the latest Coverity snapshot now agrees (and has marked the issue as absent)
