### ISSUE TITLE
*nix standalone doesn't write terminal output anymore

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#757]
Starting the cli standalone used to provide some initial feedback in the terminal, and then tell you where to find future output.  Now, there is no terminal feedback at all.  In addition, in the event of segfaults, debug assertions, etc, it will attempt to pop up a window dialog, even in a headless environment.  This has been leading to hangs for me on some platforms that have to be terminated from another session.  @asarium mentioned in IRC that we might need to ensure the standalone runs in non-interactive mode to help with this.

**Comment by chief1983** [comment]
I can't get test the -noninteractive mode as a fix for this since standalones currently won't run on any platform I have that uses the webui one.

**Comment by chief1983** [comment]
Ok, I am not really sure if noninteractive mode is working or not.  When I run a standalone I still don't see any terminal output.  No dialogs either though now, just nothing.  I used to see this though.
```
cliffgordon@cliffmbp:/Applications/Freespace2  $ ./FS2_Open\ 3.7.4\ \(debug\).app/Contents/MacOS/FS2_Open\ 3.7.4\ \(debug\) -standalone
outwnd not initialized yet...  
Standalone running
Future debug output directed to: /Users/cliffgordon/Library/FS2_Open/data/fs2_standalone.log
```
It'd tell you once the standalone loading had completed, and shortly after you should see it in FS2NetD (if enabled) or on your LAN game scan results.

**Comment by asarium** [comment]
Is it writing anything to the log file? The current situation is more or less by design since that is how it's done on all platforms.

**Comment by chief1983** [comment]
It looks to be writing things now.  I think we could tentatively close this and if I see another dialog window I'll just have to reopen I guess :P
