### ISSUE TITLE
Scripting: gr.setLineWidth() isn't working correctly

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#765]
What it says, I always get a line of 1 pixel wide no matter what I try to set it too.

This script demonstrates the problem on the main hall.

http://pastebin.com/8YhGMAPz

Seems to have broken between the Aug 1 and Aug 2 nightlies (maybe TTF merge related?)

**Comment by asarium** [comment]
@AxemP Could you check if #766 fixed your issue?

**Comment by asarium** [comment]
In my tests the test script worked fine with the changes so I am going to close this. Feel free to reopen this if the issue hasn't been fixed for you.
