### ISSUE TITLE
std::lock_guard<std::mutex> Creates infinite loop in memory.cpp

### ISSUE THREAD

**Issue by z64555** [scp-fs2open/fs2open.github.com#768]
When using MSVS 2013, this issue occurs on commits after the introduction of the memory tracking stuff.

The block does not occur when commenting out the two lines that have std::lock_guard.

**Comment by asarium** [comment]
The stacktrace @z64555 provided on IRC shows that locking a mutex somehow allocates memory. There is no way to provide a special memory allocation function to fix that so the "best" solution is to simply disable the locking for MSVC 2013 and earlier.
