### ISSUE TITLE
obj_set_flags needs to be audited

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#802]
Objects are currently doing a bit of their own thing when it comes to flags. Some flags can be set and removed by manipulating the flags variable directly, others (Like OF_COLLIDES, for example) require extra processing to set up. 

This, I feel, is not a good thing. It is not immediately apparent when obj_set_flags needs to be used (For the record, any alteration of OF_COLLIDES, OF_NOT_IN_COLL, OF_COULD_BE_PLAYER requires a pass through obj_set_flags). My personal instinct is to remove those flags and turn them into member variables that can only be manipulated through getter/setter methods in the object class. Thoughts?

**Comment by JohnAFernandez** [comment]
Can be closed because object flags have been changed to a flagset now.
