### ISSUE TITLE
SDL joystick GUIDs are not unique

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#813]
When I added the joystick GUID code I assumed that the GUID returned by SDL would be unique to that joystick so it could be used for identifying it. However, that is not the case. Apparently the joystick only identifies the type and not the instance of the joystick so if there are two devices of the same type they can not be used properly.

One possible solution would be to also use the device index (the one used with `SDL_JoystickOpen`) and use that as an additional identifier if there are multiple joysticks with the same GUID. However, this index is not constant and can change if the joysticks are plugged into a different USB port. Alternatively, there is a instance ID which is supplied by SDL. I don't know if this changes when devices are plugged in somewhere else.

Since the new input code will support multiple joysticks we need a way to reliably identify those so the mappings stay the same. I need more data in order to determine how this issue should be solved correctly. I'll add some code to FSO that collects this data which may help me solve the problem.

**Comment by chief1983** [comment]
I don't even think the OS considers a joystick the same device when plugged into a new Port.  I think windows still reinstalls the drivers for each new port.  I think if people shuffle their joysticks from port to port then we may have to require them to live with re-assigning them.

**Comment by asarium** [comment]
I read that DirectInput has some sort of mechanism that allows to uniquely identify a device even if it was plugged into a different port. I don't think we have access to the necessary information to properly identify devices across platform so I guess we'll have to live with this limitation for now.

**Comment by Goober5000** [comment]
The immediate issue was addressed, and this seems more like a good thing to be aware of rather than an active issue, so I'll close it.
