### ISSUE TITLE
Wrong version in Mac nightly Info.plist

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#830]
This was noticed in the nightlies, but is probably an issue with any Mac build from master currently.  The InfoPlist.strings file placed deep in the .app, in Contents\Resources\English.lproj\, still claims to be version 3.7.3.

**Comment by asarium** [comment]
That could be solved by configuring the file with the version set in the CMake config similarly to how it's already done with Windows.
