### ISSUE TITLE
Mac nightly builds won't run

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#836]
Swifty asked me to see if I was having troubles with the current Mac nightly builds, and he's right, they don't seem to run now.  Even selecting one in wxLauncher causes an error dialog about the app not being compatible with the system.  I believe locally made builds are still running so this may be some sort of build portability issue.  I am running OS X 10.11 and the CI server seems to be building them with the 10.9 SDK, not sure if that should cause an issue or not.

**Comment by Echelon9** [comment]
I compared the CMake-derived master build with an older 3.7.3 build I had around. I've deliberately ignored changed in binary files:
```
$ diff -rqu FS2_Open\ 3.7.3\ \(debug\).app fs2_open_3_7_5_x64-DEBUG.app/ | sed '/Binary\ files\ /d'
Only in FS2_Open 3.7.3 (debug).app/Contents/Frameworks: SDL.framework
Only in fs2_open_3_7_5_x64-DEBUG.app/Contents/Frameworks: SDL2.framework
Files FS2_Open 3.7.3 (debug).app/Contents/Info.plist and fs2_open_3_7_5_x64-DEBUG.app/Contents/Info.plist differ
Only in FS2_Open 3.7.3 (debug).app/Contents/MacOS: FS2_Open 3.7.3 (debug)
Only in fs2_open_3_7_5_x64-DEBUG.app/Contents/MacOS: fs2_open_3_7_5_x64-DEBUG
Files FS2_Open 3.7.3 (debug).app/Contents/Resources/English.lproj/InfoPlist.strings and fs2_open_3_7_5_x64-DEBUG.app/Contents/Resources/English.lproj/InfoPlist.strings differ
$ diff -u FS2_Open\ 3.7.3\ \(debug\).app/Contents/Info.plist fs2_open_3_7_5_x64-DEBUG.app/Contents/Info.plist 
--- FS2_Open 3.7.3 (debug).app/Contents/Info.plist	2015-11-06 07:49:20.000000000 -0500
+++ fs2_open_3_7_5_x64-DEBUG.app/Contents/Info.plist	2016-08-17 21:55:49.000000000 -0400
@@ -3,11 +3,9 @@
 <plist version="1.0">
 <dict>
 	<key>BuildMachineOSBuild</key>
-	<string>15B42</string>
+	<string>15G31</string>
 	<key>CFBundleDevelopmentRegion</key>
 	<string>English</string>
-	<key>CFBundleExecutable</key>
-	<string>FS2_Open 3.7.3 (debug)</string>
 	<key>CFBundleIconFile</key>
 	<string>FS2_Open</string>
 	<key>CFBundleInfoDictionaryVersion</key>
@@ -23,28 +21,30 @@
 		<string>MacOSX</string>
 	</array>
 	<key>CFBundleVersion</key>
-	<string>3.7.3</string>
+	<string></string>
 	<key>DTCompiler</key>
 	<string>com.apple.compilers.llvm.clang.1_0</string>
 	<key>DTPlatformBuild</key>
-	<string>7B91b</string>
+	<string>7D175</string>
 	<key>DTPlatformVersion</key>
 	<string>GM</string>
 	<key>DTSDKBuild</key>
-	<string>15A278</string>
+	<string>15E60</string>
 	<key>DTSDKName</key>
 	<string>macosx10.11</string>
 	<key>DTXcode</key>
-	<string>0710</string>
+	<string>0730</string>
 	<key>DTXcodeBuild</key>
-	<string>7B91b</string>
+	<string>7D175</string>
 	<key>LSApplicationCategoryType</key>
 	<string>public.app-category.games</string>
 	<key>LSMinimumSystemVersion</key>
-	<string>10.7</string>
+	<string></string>
 	<key>NSMainNibFile</key>
 	<string>MainMenu</string>
 	<key>NSPrincipalClass</key>
 	<string>NSApplication</string>
+	<key>SDL_FILESYSTEM_BASE_DIR_TYPE</key>
+	<string>parent</string>
 </dict>
 </plist>
```

I haven't verified this as a causal element, but a blank `LSMinimumSystemVersion` looks problematic if the build is moved between OS versions.

**Comment by chief1983** [comment]
Yeah, before I got to the bottom of your message, that line had already jumped out to me as well.  I was wondering if it could be in the binary though, possibly something an inspection of its linking configuration might reveal, but that looks like a better place to start.  I'm trying to narrow down if my own builds run though, not sure why Swifty would be having trouble running his builds as he reported.

**Comment by chief1983** [comment]
And as I had feared, my builds work until I remove the build directory.  Something is keeping them from completely detaching from their original compilation environment.

**Comment by chief1983** [comment]
otool output from a build I just made:
```
cliffmbp:Freespace2 cliffgordon$ otool -L fs2_open_3_7_5_x64.app/Contents/MacOS/fs2_open_3_7_5_x64 
fs2_open_3_7_5_x64.app/Contents/MacOS/fs2_open_3_7_5_x64:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/Ogg.framework/Ogg (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/Theora.framework/Theora (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/Vorbis.framework/Vorbis (compatibility version 1.0.0, current version 1.0.0)
	@rpath/SDL2.framework/Versions/A/SDL2 (compatibility version 1.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```
otool output from 3.7.4 official release:
```
cliffmbp:Freespace2 cliffgordon$ otool -L FS2_Open\ 3.7.4.app/Contents/MacOS/FS2_Open\ 3.7.4
FS2_Open 3.7.4.app/Contents/MacOS/FS2_Open 3.7.4:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/GLUT.framework/Versions/A/GLUT (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/SDL.framework/Versions/A/SDL (compatibility version 1.0.0, current version 12.4.0)
	@executable_path/../Frameworks/Ogg.framework/Ogg (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/Vorbis.framework/Vorbis (compatibility version 1.0.0, current version 1.0.0)
	@executable_path/../Frameworks/Theora.framework/Theora (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1258.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1404.46.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
```

There's quite a few more linked to the 3.7.4 build, although none of those have to do with the build environment so they may just not be needed anymore.  As I mentioned, my builds worked fine locally, until I deleted the contents of the cmake build folder, upon which I get errors about the program not working on my OS.

**Comment by Echelon9** [comment]
It's the linking to/with something inside SDL2.Framework.

Before and after changing the name on my CMake build director (so it couldn't be found):
```
$ ./fs2_open_3_7_5_x64-DEBUG.app/Contents/MacOS/fs2_open_3_7_5_x64-DEBUG 
FSO is running in legacy config mode. Please either update your launcher or copy the configuration and pilot files to '/Users/xxx/Library/Application Support/HardLightProductions/FreeSpaceOpen/' for better future compatibility.
Segmentation fault: 11
#
# Rename build/ folder
#
$ ./fs2_open_3_7_5_x64-DEBUG.app/Contents/MacOS/fs2_open_3_7_5_x64-DEBUG 
dyld: Library not loaded: @rpath/SDL2.framework/Versions/A/SDL2
  Referenced from: /Applications/Freespace 2 Open/./fs2_open_3_7_5_x64-DEBUG.app/Contents/MacOS/fs2_open_3_7_5_x64-DEBUG
  Reason: image not found
Trace/BPT trap: 5
```

As you mention the SDL.Framework was also linked by reference to @rpath, but it's somehow related to SDL2.Framework.

**Comment by chief1983** [comment]
I just noticed something else peculiar about the Framework setup in use now.  None of the items inside of it are symlinks.  The Frameworks embedded in the app used to have a large number of symlinks inside the different framework packages, now they all seem to be actual files.

**Comment by chief1983** [comment]
After digging, this comes from a reported issue with cmake's copy_directory and copy commands following symlinks, and providing no alternative not to do so, at least when the issue was closed on Mantis.  I will see if the issue exists and was followed up on their new bug tracker.  They talked about implementing a proper 'cp' command as an alternative.

**Comment by chief1983** [comment]
I don't see an easy way to fix it, other than replacing the use of the cmake command to do the copying with a platform specific command.  Since it's within a check for the APPLE platform, I don't believe doing so would be an issue.

**Comment by asarium** [comment]
@chief1983 Yes, it should not be a problem to use the standard `cp` for copying the frameworks.

**Comment by chief1983** [comment]
I tried modifying the copy_directory commands to just use `cp` instead, but it doesn't seem to have an effect.  In fact, in the generated xcode project, I can't even find the custom command that does the Framework copying at all, either in Xcode or with just plain grep.

**Comment by chief1983** [comment]
I manually overwrote the Frameworks in the assembled app with the ones in the Frameworks.tgz, it doesn't help get past this SDL2 error when I remove the build directory.  So while that still probably needs to be addressed, it isn't helping the problem.

**Comment by chief1983** [comment]
Builds are not portable because the rpath is not set in the binary.  You can see in the long output of `otool -L` that it is not set.  Been trying to set it to @loader_path/../Frameworks (or something like that, just like older binaries have set) using my limited CMake skills but the resulting path keeps being expanded in the resulting binary to be a complete path that only exists on my system.  That won't be much use for making it portable.  So, could use some help figuring out how to get a non-expanded path stored in that binary's rpath value.

We also still need to figure out how to fix the framework copy mechanism to something that can copy symlinks correctly.  I could not seem to figure that out either, I can't even find any reference to copying libs in the resulting xcode project.

**Comment by chief1983** [comment]
This should all be addressed as soon as 955 is merged.

**Comment by chief1983** [comment]
And fixed.
