### ISSUE TITLE
Massive spaz out of Sobek ship in Diaspora mission The Strike

### ISSUE THREAD

**Issue by SamuelCho** [scp-fs2open/fs2open.github.com#84]
I was trying to reproduce chief1983's bug report involving my faster IBX changes in Diaspora. This other bug just came out of left field while testing.

When playing mission "The Strike", the  enemy Basestar jumps in and the Sobek starts literally freaking out. Sorry if I can't write this issue with a more specificity but this GIF will probably explain the issue better: http://i.imgur.com/WZUhAJQ.gif

This does not happen on a 3.7.2 build so I suspect a recent commit may have caused this issue.

**Comment by niffiwan** [comment]
I can confirm seeing this issue with Diaspora on Linux as well but haven't had the time to isolate the commit that introduced the issue. I suspect that Vipers are getting stuck in the launch tubes, or are remaining docked to the Sobek which is what is causing the crazy dance.  The issue seem to start occurring when the 3rd and 4th friendly wings arrive.

**Comment by niffiwan** [comment]
Issue seems to have been introduced by 83b59fb76c1c60bb10777be49f9089b64d4c9ac4. I can also confirm that Blue & Yellow Vipers are remaining in their launch tubes after they spawn i.e. they never launch.  I suspect they're docked to the Theseus and their manoeuvring is causing the odd behaviour.

**Comment by niffiwan** [comment]
After looking at the mission file, I think random-multiple-of has been borked.  Red 2 and Blue 1 launch successfully, none of Red 3-4, Blue 2-4 and Yellow 1-4 launch, they all remain in their tubes. I didn't wait around until Green arrived. 
Refer to Events:
  +Name: Launch Red
  +Name: Launch Vipers

**Comment by MageKing17** [comment]
Whoops. I successfully made sure to keep track of when the random argument had been located, but forgot to save that node anywhere, so they'd just use the... last available argument? Shouldn't that result in Red 4 launching, not Red 2? Oh well, I'll just fix the logic and see if that fixes it.

**Comment by MageKing17** [comment]
Okay, so I tried it with a corrected random-multiple-of and Red 2 was still the only one that launched and I got swatted by a rapdily-spinning Sobek, so I think I need to do some stepping through with a debugger here.

**Comment by niffiwan** [comment]
Resolved by 9ef7aa2432b2ea14cf8b28e7049ad6d15742ee9b
