### ISSUE TITLE
Default to new config location

### ISSUE THREAD

**Issue by rtoijala** [scp-fs2open/fs2open.github.com#858]
For new users (meaning no config whatsoever in either the old or the new location) FSO complains that they should move to the new location (for me: `~/.local/share/HardLightProductions/FreeSpaceOpen/`), but creates all files in the old location (for me: `~/.fs2_open`).

The directory for the new location is created but stays empty.

New users should probably default to the new location, not the legacy location.

Workaround: simply start the game and move the files.
Or: before starting, run 

```
mkdir -p ~/.local/share/HardLightProductions/FreeSpaceOpen
touch ~/.local/share/HardLightProductions/FreeSpaceOpen/fs2_open.ini
```

**Comment by asarium** [comment]
One solution could be to check if the old folder exists and if it doesn't then the new location is used by default.

**Comment by MageKing17** [comment]
I believe the current logic checks whether `fs2_open.ini` can be found in the new location, and if it can't then FSO enables legacy mode. Simply adding a check to that conditional to see whether it exists in the old location should take care of that problem... except for the fact that on Windows, there *is* no old config location, so something slightly more complicated needs to happen there.
