### ISSUE TITLE
Unrecognized command line parameter -debug_window

### ISSUE THREAD

**Issue by rtoijala** [scp-fs2open/fs2open.github.com#862]
wxLauncher shows `-debug_window` as a possible cmdline flag.
However, starting FSO with `-debug_window` results in a message box with the text
`Unrecognized command line parameter -debug_window`.

`-debug_window` is only ever mentioned on one line in `cmdline.cpp` in the `exe_params` array.

**Comment by asarium** [comment]
That option has been removed but apparently I missed removing it from `exe_params`.
