### ISSUE TITLE
OpenGL debug contexts crashes depending on platform?

### ISSUE THREAD

**Issue by SamuelCho** [scp-fs2open/fs2open.github.com#879]
I don't know if it's because I'm on a Windows machine or because I have a Radeon R9 280, but if I have an OpenGL error and the debug context tries to report it, I get a crash. 

I narrowed it down to how void debug_callback() is declared. I notice that if void __stecall debug_callback() is declared instead of the standard __cdecl, we don't get the crash. To test, just noodle with a shader, maybe the passthrough, and remove a semi-colon to force a compilation error. Again, I've seen people report shader errors even with the debug context enabled so I'm wondering what the difference in target platforms are.

**Comment by asarium** [comment]
Damn, the callback must be declared with the `APIENTRY` calling convention. I also have been seeing some weird crashes but I never could track it down. I'll submit a PR.
