### ISSUE TITLE
Weirdness in the ship lab when bloom_intensity is 0

### ISSUE THREAD

**Issue by The-E** [scp-fs2open/fs2open.github.com#889]
I haven't tested this in mission yet, but here's a bit of weirdness:
When you are in the lab looking at a model and use the n key to reduce bloom intensity to 0, strange things occur. It looks like whatever is being rendered is getting rendered accumulatively, leading to an eventual white-out where the model used to be.

**Comment by SamuelCho** [comment]
That sounds awesome.

**Comment by The-E** [comment]
It actually kinda is. Still though, not exactly intended behaviour :)

**Comment by MageKing17** [comment]
Screenshot DahBlount took of 0 bloom intensity:
![Screenshot](http://puu.sh/qNzcE/cc033fe871.png)

**Comment by The-E** [comment]
I should add that this behaviour is also present in #844. A fix can therefore wait for (or be done as part of) that PR.

**Comment by SamuelCho** [comment]
It looks like when bloom intensity is zero, the bloom pass function doesn't even run. Looks to be a simple fix but it'll probably happen until after the OpenGL Core PR gets merged.
