### ISSUE TITLE
Nano VG consuming too much frametime in game_render_frame()

### ISSUE THREAD

**Issue by SamuelCho** [scp-fs2open/fs2open.github.com#898]
I've been doing some profiling and noticed a huge 6 millisecond spike in the rendering code. I tracked it down to stars_draw(). Specifically tracked it down to stars_draw_stars() calling gr_aaline which uses the Nano VG drawing library. I tested before and after my OpenGL Core commits and stars_draw() take up 6 ms in both cases. That's not a trivial number, considering building shadow maps and rendering the g-buffers takes around 6 ms on a busy scene on this same machine. 

This [reflects the concerns I had when I argued against integrating NanoVG into the engine](https://github.com/scp-fs2open/fs2open.github.com/pull/692#issuecomment-235689656). I was assured that there were no performance drawbacks but that's clearly not the case here. I think we should limit NanoVG's use to the HUD pass and make stars_draw_stars() use traditional OpenGL line drawing until we can figure out how to reduce NanoVG's overhead.

**Comment by SamuelCho** [comment]
Did some more testing. stars_draw() consumes 1.5 ms on my machine on the commit before the NanoVG commit.

**Comment by asarium** [comment]
Does it consume 6 ms of CPU or GPU time? If there is a major performance problem in the library then we could fix it and also submit the patch to upstream.

**Comment by asarium** [comment]
I just ran FSO through the VS profiler and I can see that nvgEndFrame is called an absurd amount of times which is incredibly inefficient. We could probably improve that a bit by using the standard GL_LINES but I'll first try to improve the rendering performance by using the path renderer directly.

**Comment by asarium** [comment]
I think I fixed the issue, please test if this branch improves the situation: https://github.com/asarium/fs2open.github.com/tree/fix/starNVGRendering
I have seen drastic profile result improvements with these changes.

**Comment by SamuelCho** [comment]
Yeah this runs a lot better.
