### ISSUE TITLE
Controls keep getting reset at runtime

### ISSUE THREAD

**Issue by TRBlount** [scp-fs2open/fs2open.github.com#899]
FSO keeps resetting my controls every time I run the exe.

**Comment by MageKing17** [comment]
Did you turn on JSON pilotfile output, by chance?

**Comment by DahBlount** [comment]
No, I did not.

**Comment by rtoijala** [comment]
This is probably linked to #913.

**Comment by asarium** [comment]
@DahBlount Is this issue still present after #913 has been merged?

**Comment by DahBlount** [comment]
I believe so.

**Comment by chief1983** [comment]
Still an issue?  I haven't had an issue saving my axis settings and having that get reset, I don't think.

**Comment by z64555** [comment]
@TRBlount poke

**Comment by Goober5000** [comment]
Closing
