### ISSUE TITLE
Some PBR textures don't render env reflections and non-PBR textures only render the F3 Lab nebula environment

### ISSUE THREAD

**Issue by DahBlount** [scp-fs2open/fs2open.github.com#900]
I was examining some issues I noticed last night under master and found that certain ships with -reflect maps don't render environment reflections at all while those with -shine only reflect the nebulas you see in the F3 lab.

**Comment by asarium** [comment]
@DahBlount Is this related to #1030? Could you check if that also fixed this issue?

**Comment by DahBlount** [comment]
I believe #1030 fixed reflectance maps not rendering env reflections, but the issue with the F3 Lab cubemap being used always is still present.

**Comment by SamuelCho** [comment]
Can you elaborate on this a bit more? Did you say that the F3 cubemap is only used when -shine maps are being used? But this doesn't happen if -reflect maps are used?

**Comment by DahBlount** [comment]
No. Regardless of using a shine or reflectance map, the F3 lab cube map is used in missions. I believe someone also reported that after running a mission and returning to the F3 lab, the cube map is swapped to the cube map that should've been rendered in the mission.

**Comment by DahBlount** [comment]
Here's an image album Axem made that demonstrates the wrong cubemap being used in some pictures:
http://imgur.com/a/By13c

**Comment by DahBlount** [comment]
Here's a picture showing both -reflect and -shine at max gloss/env:
![](https://ibin.co/38MR9i44MiPL.jpg)

**Comment by AxemP** [comment]
I made a test mod. :)

https://drive.google.com/file/d/0B_q0tkX7VcSadk1oQXc1QWFIT3c/view?usp=sharing

**Comment by SamuelCho** [comment]
ty for the test mod. it helped a lot.
