### ISSUE TITLE
glPushDebugGroupKHR causing crashes

### ISSUE THREAD

**Issue by SamuelCho** [scp-fs2open/fs2open.github.com#902]
Every time the game enters the tech room, lab, or briefing screen, I'm getting a crash from this function. glPushDebugGroup seems to work okay though?

**Comment by SamuelCho** [comment]
Ah crap, I accidentally committed glPushDebugGroup replacing glPushDebugGroupKHR in PR https://github.com/scp-fs2open/fs2open.github.com/pull/904. I hope that's okay @asarium. If it's not, feel free to change it back.

**Comment by asarium** [comment]
The spec says that both names should be valid so it's not a problem.

**Comment by SamuelCho** [comment]
Okay, I'll close this issue then.
