### ISSUE TITLE
FRED2 unable to create OpenGL context

### ISSUE THREAD

**Issue by SamuelCho** [scp-fs2open/fs2open.github.com#905]
Since the OpenGL Core migration it looks like our poor buddy FRED can't start up again. I tracked it down to MFCOpenGLContext::createOpenGLContext() where the method prematurely halts as soon as it learns that we're asking for a Core context. Thing is, is this check needed? WGL creates a compatibility OGL context regardless of what you do unless you do a dizzying dance with WGL extensions. And it seems like we don't even do anything else with the const os::OpenGLContextAttributes& ctx parameter that's passed into this method. I got rid of that "return nullptr" and FRED works fine after that.

**Comment by MageKing17** [comment]
Given that Windows drivers don't usually have problems with Compatibility profiles and non-Windows systems can't run FRED anyway, that sounds reasonable to me (as long as wxFRED doesn't have a similar problem, which I wouldn't expect).

**Comment by asarium** [comment]
wxFRED has issues since it's not limited to Windows but that can be handled in that implementation. I tested FRED with the OGL Core changes before the new viewport management code merge and it worked fine with the compatibility profile.

**Comment by SamuelCho** [comment]
Well it certainly did before but something changed during or after the Core migration changes that's preventing MFCOpenGLContext::createOpenGLContext() from creating a valid context. Does FRED work on latest master on your end?

**Comment by asarium** [comment]
The check is the problem here. I added it since the code is not able to actually create a Core context. That was written before you created your PR and I forgot to test and change it when I did the merge. You should be able to safely delete the check.

**Comment by asarium** [comment]
This has been resolved by #916.
