### ISSUE TITLE
Use Uniform blocks instead of uniform variables

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#910]
I want to discuss the advantages and disadvantages of using uniform blocks instead of standard uniforms for passing data to the shaders. This does not mean that is must happen but instead I want to have an open discussion about if and how it could be implemented.

I had some good experiences with uniform blocks in a testing project where it allowed me to decouple the rendering backend from the code that is using the rendering functions since the rendering backend only gets a uniform buffer handle for the data instead of somehow getting that data down to the rendering functions. It also allows to but data that is often changed together into the same buffer and change it at the same time.
Uniform buffers are also the way shader data is passed to the shaders in Vulkan but that's just a minor point here since we are not in a position to consider adding Vulkan support yet.

The disadvantages I currently see are that it's harder to properly optimize this concept since the drivers are usually pretty good at figuring out when the updated uniform data needs to be sent to the GPU. There is also the issue that the buffer data needs to be properly aligned before the GPU can use it. I have developed a helper class for that but it makes uniform block usage a little bit more complicated. There are probably other issues I haven't encountered yet so I would like your opinion on that.

What do you think? Especially @SamuelCho since you probably already have experience with passing data to the GPU this way.

**Comment by SamuelCho** [comment]
We can just start off by having uniform buffers handle relatively static
data that don't have much variance between draws. We could probably store
shadow view and projection matrices, shadow cascade distances, and all 256
lights in a per-scene uniform buffer. That way you just need a single
glBufferData before a series of draws get sent like I do with the batch
transform texture buffer object. The light data in the uniform buffer can
be indexed using a simple uniform array that's given per-draw.

We can get fancier If you want uniform buffers to handle all uniform data.
Maybe we have two block binding points. One of the block bindings is for
the static draw data described above. The second block binding is for
dynamic draw data. The uniform struct layout of our dynamic draw data
encompasses all possible uniform data inputs of the shader regardless of
what the current #define flags are for the current shader variant. And then
we update a shared dynamic buffer object per-draw using glBufferSubData,
offseting into it like we do for the immediate vertex buffer I implemented
for the OpenGL Core changes. We point glBindBufferRange to that offset
before the draw and we're ready to make the draw call.

I'd just say start us off with the per-scene uniform buffer for now. It'll
be quicker to prototype and test. Then we'll look into per-draw stuff once
we get a good handle on things.

**Comment by asarium** [comment]
Thank you for your input. One of the things I am actively investigating right now is turning some of the shader `#defines` into uniforms which will mean that there will be less shader switches. I'll make sure that any major changes to the shader system is as compatible as possible with uniform buffers.

**Comment by SamuelCho** [comment]
Are you still working on this? I've been thinking about this lately and I think I want to take a stab at it myself.

**Comment by asarium** [comment]
I have been doing some research and also made a few code changes but nothing substantial. Here is the current code which has some cleanup and a new gr_ function for binding a uniform buffer: https://github.com/asarium/fs2open.github.com/tree/ogl/uniformBlocks

**Comment by SamuelCho** [comment]
So I've been doing some uniform buffer tests. I ended up trying two methods. One was the immediate method. The other was the batch method. I started off using your code but then decided to just start from scratch once I realized how picky OpenGL was going to be about byte offsets and alignments in the buffer.

I sadly haven't seen any performance improvement from using them. Both had no dramatic or perceptive difference in time spent drawing compared to the explicit uniform method. If there is still draw call overhead to minimize, I don't think uniforms are the issue here.

The code is available [here](https://github.com/SamuelCho/fs2open.github.com/commits/uniform_buffers). The code is sloppy and messy since my objective was to just get something working. The batch method of uniform buffers is enabled in commit https://github.com/SamuelCho/fs2open.github.com/commit/2b84abe4815ddee38024acfdefab9f10992c80a1 while the immediate method is enabled in commit https://github.com/SamuelCho/fs2open.github.com/commit/fcd0e27665d5814975b31d203bd42933b8444f32. I moved lighting into the uniform buffer as well in a later commit after getting the gist of how arrays are arranged in a uniform buffer in std140. Still didn't really do anything.

**Comment by asarium** [comment]
I'll try to get it to run with the Mesa drivers. You probably used the Nvidia drivers which are probably very good at optimizing the old style uniform updates but uniform buffers should be better for less optimized drivers like Mesa so the changes may improve performance with that driver.

**Comment by SamuelCho** [comment]
I actually have an AMD card but you make a very good point.

**Comment by asarium** [comment]
I tested the changes under Linux and is looks like they actually make the game a little bit slower: ![Performance graph](https://cloud.githubusercontent.com/assets/1013983/18948302/d2fe253c-8636-11e6-9fce-ed341df4826d.png)

I tested the branch you linked to but as far as I can tell, that uses the immediate buffer solution which is probably not ideal. Could you reenable the batched method since that should, in theory, work a lot better.

**Comment by SamuelCho** [comment]
I don't have access to git at work so the most you can do at the moment is try https://github.com/SamuelCho/fs2open.github.com/commit/2b84abe4815ddee38024acfdefab9f10992c80a1

It doesn't have the light uniforms converted into the uniform buffer but maybe you'll get better perf regardless. If you do get better performance even with the uniform buffers, then that would be pretty promising. So maybe it won't hurt to try it out in the meantime until I get a chance to revert stuff.

**Comment by asarium** [comment]
Alright, I'll try that.

**Comment by SamuelCho** [comment]
The latest commit of that branch has uniform buffer batching with lighting data moved into the uniform buffer. See how that works out for you.

**Comment by asarium** [comment]
Here are the new results:
![figure_1](https://cloud.githubusercontent.com/assets/1013983/18985941/cafed948-86fa-11e6-9af1-d865fa838845.png)

The differences are a bit erratic but I think overall it's not an improvement. There were a lot of graphical glitches where submodels were missing or in the wrong position so I guess that the transformations are somehow screwed up. That may explain the erratic behavior so I'll look into fixing those issues.

**Comment by asarium** [comment]
I am finished implementing this and the changes are available in [a branch of my fork](https://github.com/asarium/fs2open.github.com/tree/opengl/modelUniformBuffers).

Unfortunately, the performance improvements are not significant so there might still be room for improvement somewhere but this is certainly a good start.

It depends on a few changes that I would like to merge separately so those changes will be submitted in individual PRs.

**Comment by asarium** [comment]
I just did another test without shadows which moves the bottleneck from the GPU to the CPU which is where my changes should show the most impact:
![performance graph](https://user-images.githubusercontent.com/1013983/29562403-6edbe7f6-8739-11e7-835d-dbe5eedbe075.png)

In areas where FSO is CPU limited there is ~1ms of improvement so these changes definitely improve performance.

**Comment by SamuelCho** [comment]
This looks promising. I wonder if the performance gain is only noticeable with shadows off because the shadow map rendering phase doesn't use many uniforms.

**Comment by asarium** [comment]
When I profiled the code with and without shadows I noticed that rendering the shadow map takes very long compared to the normal scene draw (understandable since it draw the entire scene effectively four times).

The results above were collected on an RX 480 on Linux so the performance differences may vary on Nvidia hardware.
