### ISSUE TITLE
Credits slideshow crossfade broken

### ISSUE THREAD

**Issue by rtoijala** [scp-fs2open/fs2open.github.com#914]
The credits slideshow is supposed to display each image for 8 seconds followed by a cross-fade of 1 second to the next image. Currently, however, the previous image does not disappear after the one second. This can be seen particularly well with the image containing a human (Bosch?), since he has a distinctive shape. This also leads to colors from previous images leaking into images that are supposed to be black and white.

Example image:
![2016-08-30-113021_1600x900_scrot](https://cloud.githubusercontent.com/assets/1586926/18082249/a3cf2114-6ea6-11e6-850b-bc30535f7549.png)
This is the retail file `data/interface/2_crim01.pcx`, which is originally black and white. The blue and red have leaked over from `data/interface/2_crim08.pcx`, which was the previous image.

**Comment by AxemP** [comment]
The root problem also appears to affect the drawImage scripting function. Drawing images draws them additively without using the image's alpha value or the one specified by the function parameters.
