### ISSUE TITLE
FRED isn't remembering recently opened files

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#940]
The recently opened files list under the file menu isn't being retained through the program closing and being opened again.

Pretty easy to reproduce, open some files, see how that list populates, close fred, reopen and see how that list is empty again.

**Comment by AxemP** [comment]
Yes it does.

**Comment by MageKing17** [comment]
We aren't still trying to save or load FRED's INI file to the Windows folder, are we?

**Comment by asarium** [comment]
It uses `WriteProfileInt` but the documentation doesn't say anything about where that information is written.
