### ISSUE TITLE
Standalone will not run

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#941]
The standalone won't actually run anymore.  No crash, seg faults, etc.  Even when compiled with ASan or run under GDB, there's really no information.  Just that it exited with code 01.  This occurs on Linux (gcc) and FreeBSD (clang), both tested with debug builds.  I had to comment out the newdelete.cpp on FreeBSD as current master as of this posting leads to a segmentation fault otherwise.  This is the same as the proposed fix for the alignment issues on Mac.  Suspect it is related to clang as that is one of the main common items between the two platforms, but that's outside the scope of this issue.

On windows, it crashes with the error in the below comment.

**Comment by chief1983** [comment]
This may have something to do with it though.  Windows is broken too.
```
Assert: "!Is_standalone"
File: cursor.cpp
Line: 184
Cursors can't be loaded in standalone mode!

ntdll.dll! ZwWaitForSingleObject + 12 bytes
KERNELBASE.dll! WaitForSingleObject + 18 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! SCP_DumpStack + 347 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! dump_stacktrace + 87 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! os::dialogs::AssertMessage + 770 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! io::mouse::CursorManager::loadCursor + 64 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! gr_init + 1514 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! game_init + 913 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! game_main + 391 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! actual_main + 203 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! SDL_main + 16 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! main_utf8 + 21 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! WinMain + 151 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! invoke_main + 30 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! __scrt_common_main_seh + 336 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! __scrt_common_main + 13 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! WinMainCRTStartup + 8 bytes
KERNEL32.DLL! BaseThreadInitThunk + 36 bytes
ntdll.dll! RtlUnicodeStringToInteger + 595 bytes
ntdll.dll! RtlUnicodeStringToInteger + 542 bytes
fs2_open_3_7_5_AVX-DEBUG.exe! invoke_main + 31 bytes
```

**Comment by chief1983** [comment]
Ok, it is a different issue on *nix I think.  Just checked the debug log (should have already I guess), and saw some interesting things.  When run on the command line with -standalone, the log has "Passed cmdline options:  <none>".  At the bottom of the log, I see this:

```
Initializing SDL video...
Error: Couldn't init SDL video: No available video device
File: SDLGraphicsOperations.cpp
Line: 142
```

I don't really have any idea why it wouldn't see the command line options.  Tried adding on -noninteractive too, to no effect.

**Comment by asarium** [comment]
I though I had fixed that cursor issue at some point but apparently I didn't. The "!Is_standalone" assertion is wrong anyway so I'll have to figure out how to properly handle that situation in the cursor code. Simply removing that code also doesn't work since that causes an ASan error.

The other issue is an oversight by me since the SDL video system is always initialized even if we are in standalone mode where it isn't actually needed.

**Comment by asarium** [comment]
@chief1983 A few changes have been merged into master to address this. Please check if the changes have fixed your issue.

**Comment by chief1983** [comment]
Just realized that the graphics init fix might not have even been necessary, I was looking in fs2_open.log and not fs2_standalone.log.

**Comment by chief1983** [comment]
Linux and Mac both run now as well.  If the cursor issue is verified as fixed on Windows then this is good to close.

**Comment by chief1983** [comment]
Everything looks good now, started a one player dogfight and jumped out, no hiccups, can close this now.
