### ISSUE TITLE
Weird memory allocation related crash in FRED

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#945]
Semi-recently FRED has started to crash mysteriously without any sort of direct cause. They tend to happen after about an hour of FRED being open.

I got this error when trying to trap it in a debug build, but no symbols, I don't know if this is exactly related or not but it came up after I was moving a sun around in the background editor.
![clipboard01](https://cloud.githubusercontent.com/assets/6625164/18322749/df5ccc82-74f9-11e6-9490-55c08497512f.png)

This is visual studio after compiling my own debug build. I had just been doing typical FRED things (putting down ships, deleting ships, opening closing dialogs, adding a few sexps). Eventually what caused the unhandled exception was just using the top toolbar, changin the movement constraints from Y to XZ or going from Rotate to Select and Move (I forget which one exactly)
![clipboard02](https://cloud.githubusercontent.com/assets/6625164/18322805/2ef158da-74fa-11e6-8d5b-c1783f7f9907.png)

(And FYI the value of size was 318897559)

This is pretty tough for reproduce since it seems to just randomly happen after like an hour of running FRED without any real idea what's causing it.

**Comment by SamuelCho** [comment]
Looks like the new geometry batcher isn't releasing memory in FRED. Definitely would have overlooked this if it weren't for this report so ty.
