### ISSUE TITLE
Alpha blend filter type behavior has changed

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#961]
As @AxemP and I discovered while fixing #958, the alpha blend filter type was apparently broken for a long time but was fixed by @SamuelCho in the materials system merge.

The default lua opacity type was `GR_ALPHABLEND_NONE` but the bitmap drawing function behaved like normal alpha blending was applied. The rest of the code is probably also affected by this and may need to be reviewed. The bug only affects the `alpha` parameter for `gr_set_bitmap` so most the the code should be fine but if that alpha parameter is used then bitmap rendering may be broken.

**Comment by SamuelCho** [comment]
material_determine_blend_mode already accounts for this. It returns src*alpha + dest*(one minus alpha) even if we say we don't want blending.

**Comment by asarium** [comment]
The original version of `material_set_interface` used `material_determine_blend_mode` but I replaced that with `ALPHA_BLEND_ALPHA_BLEND_ALPHA` since an image without an alpha channel always disabled alpha blending which caused the credits issues.

**Comment by SamuelCho** [comment]
Hmm, I'll have to dig up how opengl_setup_render_states handled the interface flag then to double check.

**Comment by chief1983** [comment]
Did anyone confirm that this was fixed by #1104?

**Comment by Goober5000** [comment]
Pinging @asarium for a fix check...

**Comment by asarium** [comment]
The default opacity type is `GR_ALPHABLEND_FILTER` now so I guess this has been more or less fixed. Since there were no bug reports about broken scripts with 3.8 we can safely assume that this shouldn't matter too much.
