### ISSUE TITLE
gr.hasViewmode() not working correctly

### ISSUE THREAD

**Issue by AxemP** [scp-fs2open/fs2open.github.com#965]
gr.hasViewmode(VM_INTERNAL) should return true when in the cockpit view (and does with 3.7.4) but after around August 18, it no longer does. Instead VM_EXTERNAL_CAMERA_LOCKED is true when we're inside the player's ship. Bit flag problems maybe?

Here's a script that tracks which view modes are active.
http://pastebin.com/17TmpedV

**Comment by asarium** [comment]
This was probably caused by the viewmode changes made by @z64555. Those changes introduced an incompatibility with scripts since `CAMERA_LOCKED` is now also true when in the cockpit.

**Comment by niffiwan** [comment]
As suspected, seems to have been introduced by 9bce334c65fa2ad7aba7ab5655616721ca2ac7fb

**Comment by z64555** [comment]
Oh lovely. Uh. I'll try to get around to looking at lua's implementation. I'd prefer to go with the new convention set by 1e40f71 since in my opinion it's more logical and flexible.

**Comment by z64555** [comment]
I [made a branch](https://github.com/z64555/fs2open.github.com/tree/fix/issue_965) to address this issue.
