### ISSUE TITLE
Segfault on Final FS2 Mission

### ISSUE THREAD

**Issue by megatog615** [scp-fs2open/fs2open.github.com#971]
The engine seems to segfault on the final mission of FS2, just before the loading screen appears. I have tested all the way back to 3.7.4 and still have the same issue.

[backtrace.txt](https://github.com/scp-fs2open/fs2open.github.com/files/471254/backtrace.txt)
[fs2_open.log.txt](https://github.com/scp-fs2open/fs2open.github.com/files/471257/fs2_open.log.txt)

**Comment by niffiwan** [comment]
I loaded & entered the final mission OK on 3d5682a. Just compiling the latest master now; in the meantime could you try removing the pbr_mvps mod? And if it still crashes, could you try to reproduce with no mods loaded, i.e. using retail assets only. Thanks

**Comment by megatog615** [comment]
Disabling pbr_mvps still crashes, but seems to load fine with no mod activated.

**Comment by asarium** [comment]
> WARNING: "Invalid model number -1 requested. Please post the call stack where an SCP coder can see it. " at modelread.cpp:3175

There should be a callstack attached to that dialog, please post it here (or break into the debugger and post that callstack).

**Comment by megatog615** [comment]
Debug dialog won't transfer to clipboard so I screenshotted it instead.
![2016-09-14-143533_961x562_scrot](https://cloud.githubusercontent.com/assets/3255620/18524959/b235fbf4-7a88-11e6-8024-0ed42b57cb1b.png)

**Comment by asarium** [comment]
I tried reproducing the segfault on my system (Fedora 24) but the mission loads fine for me. It might be a corrupted file so please check if the MediaVP files have the correct checksums. The MediaVP 2014 release thread has MD5 sums of the VPs which you can use to validate your files.

**Comment by megatog615** [comment]
I md5sum'd all of them and they all check out.
2646219d1d67250adc4bcf4ceaa0176f  MV_Advanced.vp
f38badfdc5e3af3bacb356809a8ad8a6  MV_A-Glows.vp
bb65f1e147c3417a86dd5464f268feb5  MV_Assets.vp
67ef346aba6a38e60e3517306d0dedca  MV_CB_ANI_1.vp
b25264ca441b654bc147c1e7da574eea  MV_CB_ANI_2.vp
cd3fef0af8308087f619d0e19cf4b620  MV_Effects.vp
121300bbe229d0373cd731a37b205b3a  MV_Music.vp
45b22fb976ada8c8eceb96592b940d33  MV_RadarIcons.vp
c7729dea15e7b23de1936cd79e5a036c  MV_Root.vp

Even if it was a corrupt file, why should that segfault? Shouldn't it throw a warning and continue, ignoring the data file?

**Comment by SamuelCho** [comment]
Was the mission loaded from the tech room or via the briefing screen?

**Comment by niffiwan** [comment]
My test was from the techroom

**Comment by megatog615** [comment]
I loaded the mission at the briefing screen. It crashes immediately after I click the commit button.

**Comment by SamuelCho** [comment]
Can you try loading the mission from the techroom? Go to the mission simulator, press the Ctrl+Shift+S keys and load "Exodus"

**Comment by niffiwan** [comment]
Shouldn't it be "Apocalypse" for the last mission? sm3-10?

**Comment by megatog615** [comment]
Yes, it's Apocalypse. It segfaults if I run it from the mission simulator.

**Comment by tomimaki** [comment]
```
TBM  =>  Starting parse of 'anuket-shp.tbm' ...
```
Clean up data folder where you placed anuket. Version 1.0 gave the same warning and crash. 1.1 is ok.

**Comment by megatog615** [comment]
That did it.

**Comment by asarium** [comment]
Where can I find the 1.0 version of that mod? Wrong data should never cause a segfault and I would like to fix that.

**Comment by tomimaki** [comment]
Broken model is [here](https://drive.google.com/open?id=0B1zW3qtCeqSuOV9PQUFjWXpFS3M).

**Comment by asarium** [comment]
I was able to extract it without problems but for some reason FSO doesn't see the files in the mod. I'll debug that once I am finished with my other project.

**Comment by asarium** [comment]
I tried the linked mod and there is a warning that is directly linked to the crash so there is nothing that needs to be changed here so I'll close this issue.
