### ISSUE TITLE
Investigate what's needed for a 64-bit TrackIR dll

### ISSUE THREAD

**Issue by chief1983** [scp-fs2open/fs2open.github.com#974]
With nightlies now only being 64-bit, users no longer have the ability to test builds with TrackIR without requesting or compiling 32-bit builds.  The DLL released years ago is still just a solution for 32-bit builds.  Need to identify what options we have to go about getting a new 64-bit DLL created.  In a perfect world, @SamuelCho would still have the assets used to create the 32-bit DLL and creating a 64-bit one would be trivial.  If not, we will probably need someone willing to go through the process of validating a new DLL with NaturalPoint again, or at least getting the SDK and building a new DLL.

**Comment by SamuelCho** [comment]
the FS2TrackIR project should be on our SCP FTP, wherever it is, if we even still have it. I also have the project available on my machine if anyone needs it.

**Comment by chief1983** [comment]
I think we just learned that a lot of things on the ftp were lost in the indiegames server move about a year ago.  I think goober mentioned user folders being in that.  Getting the project from you is probably our best option at this point.

**Comment by SamuelCho** [comment]
Okay some real quick digging in my gmail, I have a copy of the modifications portej05 made to SCPTrackIR. I can forward the e-mail to anyone who needs it.

**Comment by chief1983** [comment]
You can send it to chief1983@yahoo.com and I can make sure it gets back to a place where the SCP team can access it as needed.

**Comment by chief1983** [comment]
Ok, I have uploaded the email history and attachments relating to TrackIR DLL development to the SCP Indiegames server.  So it won't disappear any time soon I hope.  I will take a look at it and if I need help I'll seek it out.  This can be closed for now, thanks @SamuelCho.

**Comment by asarium** [comment]
Has there been any progress towards building a 64-bit DLL?

**Comment by chief1983** [comment]
I haven't made any with it yet, been working on other stuff.

**Comment by asarium** [comment]
I compiled a 64-bit version of the TrackIR DLL with the required changes and apparently it is not working with 64-bit builds. To improve usability, I will submit a minor change so that FSO searches for the DLL with a `64` suffix if FSO is using a 64-bit build.
