### ISSUE TITLE
Laser bitmaps visible through geometry

### ISSUE THREAD

**Issue by asarium** [scp-fs2open/fs2open.github.com#976]
When playing the first campaign mission of Diaspora R1 the flak projectiles are visible while sitting in the launch tube:
![seethrough](https://cloud.githubusercontent.com/assets/1013983/18592015/4ac7098c-7c35-11e6-9d21-f4985aebac52.png)

I'm not sure when this started happening and why I haven't noticed it with any other mods. So far only Diaspora seems to be affected. I'll try to find the commit that introduced this bug.

**Comment by SamuelCho** [comment]
Do you still see thrusters appearing through ship geometry? This could be related to that.

**Comment by asarium** [comment]
This happened even if deferred lighting was enabled which fixed the thruster issue for me. I'll take a look at the thrusters when I run Diaspora next time.

**Comment by asarium** [comment]
There is some kind of problem with how the depth buffers are handled. Specifically, it seems like the scene is rendered into the wrong depth buffer if a cockpit is in use. If I diable the calls to `gr_opengl_post_process_save_zbuffer` everything works fine (except that there is no cockpit) which shows that there is something wrong with that part of the code.

**Comment by asarium** [comment]
When I always set `Scene_depth_texture` as the depth texture of the scene framebuffer in `gr_opengl_scene_texture_begin` everything works fine.

**Comment by asarium** [comment]
I think I found the root cause. `opengl_post_lightshafts` does reset the depth buffer to the right texture but it does that on the bloom framebuffer because that's the framebuffer that is currently bound. That means that all depth rendering actually happens on the cockpit depth texture which explains why this bug happens.

I'm currently adding a system to our GL_State that handles a stack of currently "bound" framebuffer so that we can return to the previous framebuffer when blooming is done without having to explicitly save to which framebuffer we need to return.
