### ISSUE TITLE
AppImage builds have extra stuff in them

### ISSUE THREAD

**Issue by IssMneur** [scp-fs2open/fs2open.github.com#985]
I was just checking out the nightly builds for Linux and noticed that it appears that FASTDBG AppImage includes a copy of the release AppImage as well as a copy of the Release binary.  I looked at [August 8th](http://www.hard-light.net/forums/index.php?topic=92370.0) and [September 26th](http://www.hard-light.net/forums/index.php?topic=92580.0) nightlies.

**Comment by asarium** [comment]
Damn, that's right. AppImage takes everything from the install directory which will also include the previous builds in the nightly environment.
