### ISSUE TITLE
Travis/Coverity integration broken

### ISSUE THREAD

**Issue by niffiwan** [scp-fs2open/fs2open.github.com#992]
The changes to `.travis.yml` (only) in commit f266583a47448a8f7c7e6e3b392d0ccde8a11247 seems to have broken Travis building for Coverity.

Here's the Travis log with the changes to `.travis.yml` reverted:
https://travis-ci.org/scp-fs2open/fs2open.github.com/jobs/164218477

Here's the log from prior to reverting the changes:
https://travis-ci.org/scp-fs2open/fs2open.github.com/jobs/163971367

What are those .travis.yml changes for? The doco I'm reading [here](https://docs.travis-ci.com/user/installing-dependencies/) (& [here](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix)) seems to suggest they're required to run on container based infrastructure, but doesn't mention putting them into the build matrix? 

If we really need the changes, then I guess I could go spelunking through the [travis](https://github.com/travis-ci/travis-worker) [codebase](https://github.com/travis-ci/travis-build) to see what happening (or rather than learning ruby, let laziness takeover & just log an [issue](https://github.com/travis-ci/travis-ci/issues) :D )

**Comment by chief1983** [comment]
We may not need them, but how did it only now cause breakage?  We were trying to fix the memory profiling code on some Unix platforms or compilers, forget what specifically was broken.  But we've removed that now I think didn't we?

**Comment by asarium** [comment]
The changes are required for making Travis compile with more recent versions of GCC and clang. Since the code that required those compiler versions was removed as part of the memory allocator removal they aren't needed anymore but IMO it's better to compile with a more recent version of GCC anyway since the one we used before had a few issues with C++11.

**Comment by niffiwan** [comment]
@chief1983 it only caused breakage now because the last time I triggered a Coverity build was 2nd September

@asarium do you have a link to the doco for the new method of specifying the compiler version to be used?

**Comment by asarium** [comment]
The new compiler version is enabled by setting `CC` and `CXX` to the respective commands: https://github.com/scp-fs2open/fs2open.github.com/blob/master/.travis.yml#L59

**Comment by niffiwan** [comment]
Ah cool, I got that, but I was wondering where that config was documented by Travis. I mean, how did you  know those settings were valid in the 1st place? (incidentally, the [travis YMAL lint website](https://lint.travis-ci.org/) doesn't like our current .travis.yml file... but it also doesn't seem to like the apt directive in "global" addons)

**Comment by asarium** [comment]
It's not a travis specific configuration. CMake uses `CC` and `CXX` for determining which compiler should be used.

**Comment by asarium** [comment]
@niffiwan Are there any updates for this?

**Comment by niffiwan** [comment]
sorry, no updates. I didn't get around to logging the issue with Travis CI. I suspect that the matrix being empty is why Coverity doesn't trigger, but I haven't due through their code to confirm.

**Comment by Goober5000** [comment]
Old, and overcome by events.

**Comment by niffiwan** [comment]
I'd like to clarify - is the position that we don't want Coverity static code analysis performed on FSO? If so the relevant coverity config should be removed.

**Comment by Goober5000** [comment]
I think we do; but my understanding is that Travis is not working well these days, making the point moot.

Also this issue hadn't been updated in 2.5 years, so I wondered if anyone still cared about it.

**Comment by asarium** [comment]
Travis is still working well so far. I wanted to check out the new GitHub Actions stuff though so maybe we won't need it at some point.

**Comment by z64555** [comment]
Closing, since Travis/Coverity has been removed from our CI tools
